### ISSUE TITLE
Site Support Request for katsomo.fi

### ISSUE THREAD

**Issue by Jiriss** [ytdl-org/youtube-dl#10543]
I would like support for katsomo.fi videos. The videos are required Silverlight plugin and are difficult play a non-Windows platform. This are a few examples for videos:

http://www.katsomo.fi/#!/jakso/33001005/studio55-fi/658521/jukka-kuoppamaki-tekee-yha-lauluja-vaikka-lentokoneessa
http://www.katsomo.fi/#!/jakso/33001017/uutislahetykset/646807/kymmenen-uutiset

07.10.2016:

Do you give some estimations when youtube-dl could support for this finnish TV channel?
As said, it's difficult to play videos from katsomo.fi on non-Windows platform therefore youtube-dl would be very useful.
Unfortunately some videos require login credentials.
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.03_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.03**
### Before submitting an _issue_ make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
A geo-restricted and DRM'ed example: http://www.katsomo.fi/#!/jakso/33006076/suomen-surkein-kuski/718972/sarja-alkaa

**Comment by Tsutsukakushi** [comment]
@yan12125 Most videos are geo-restricted but not all.

**Comment by jv84** [comment]
Here's instructions for Katsomo API: https://ultrahack.org/files/Katsomo-23625753-300816-1435-2.pdf

**Comment by Emgalai** [comment]
It should be noted that Katsomo no longer requires Silverlight (or any other add-on). But Katsomo now requires free registration.

**Comment by jv84** [comment]
@Emgalai It is noted on issue #12212 already a year ago.

**Comment by kobolttti** [comment]
Found out that youtube-dl does work for some content from Katsomo using the mpd URL, for example:
$ youtube-dl "https://mtvdashvod.akamaized.net/video/playout/ismvol1/2018-02-13/Kymmenen_Uutiset(876941_ISMUSPWV).ism/Kymmenen_Uutiset(876941_ISMUSPWV).mpd"

However, some content fails, for example:
$ youtube-dl "https://mtvdashvodcloud-a.akamaized.net/video/won/ismvol1/2018-02-06/Ina__3_porno(873979_ISMUSPWV).ism/Ina__3_porno(873979_ISMUSPWV).mpd" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://mtvdashvodcloud-a.akamaized.net/video/won/ismvol1/2018-02-06/Ina__3_porno(873979_ISMUSPWV).ism/Ina__3_porno(873979_ISMUSPWV).mpd', u'--verbose']
[debug] Encodings: locale ISO-8859-15, fs ISO-8859-15, out ISO-8859-15, pref ISO-8859-15
[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Ina__3_porno(873979_ISMUSPWV): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Ina__3_porno(873979_ISMUSPWV): Downloading webpage
[generic] Ina__3_porno(873979_ISMUSPWV): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2240, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1071, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is this due to login requirement? Files attached:
[Kymmenen_Uutiset(876941_ISMUSPWV).zip](https://github.com/rg3/youtube-dl/files/1814842/Kymmenen_Uutiset.876941_ISMUSPWV.zip)
[Ina__3_porno(873979_ISMUSPWV).zip](https://github.com/rg3/youtube-dl/files/1814843/Ina__3_porno.873979_ISMUSPWV.zip)

**Comment by jv84** [comment]
@kobolttti Usually on Katsomo, only news clips can be watched without logging in. If the login method is not supported, then that latter case can't obviously be tested (without some loophole).

Having a way to extract the mpd URL automatically would be a good start anyway. :smile:

**Comment by kobolttti** [comment]
Extracting the mpd URL:

- The very last integer on a Katsomo URL is the ID of the clip. For example for "https://www.katsomo.fi/sarja/seitseman-uutiset-33001008002/perjantai-15-6-klo-1900-917987" the ID is 917987.
- GET https://api.katsomo.fi/api/web/asset/917987/play?protocol=MPD
- Responce has the mpd URL as whole

Dirty proof/test:
$ youtube-dl `curl -s "https://api.katsomo.fi/api/web/asset/917987/play?protocol=MPD" | grep url | sed 's#<url>\(.*mpd\).*#\1#'`
[generic] Seitsem_n_Uutiset(917987_ISMUSPWV): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Seitsem_n_Uutiset(917987_ISMUSPWV): Downloading webpage
[generic] Seitsem_n_Uutiset(917987_ISMUSPWV): Extracting information
[dashsegments] Total fragments: 972
... (downloading)


If the clip requires login then GET for api.katsomo.fi will fail with reply:
$ curl -s "https://api.katsomo.fi/api/web/asset/885332/play?protocol=MPD"
"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error><code id="1044">SESSION_NOT_AUTHENTICATED</code><description>User is not authenticated</description><reference>xxxxxxxxxxxxxx</reference></error"

Authentication is based on cookies. Following POST is used for authentication:
curl "https://api.katsomo.fi/api/authentication/user/login" -H "Accept: application/json" --data "username=PUTEMAILHERE&password=PUTPASSWORDHERE&rememberMe=true" -c cookies.txt

When successful this will reply {"response":{"code":"AUTHENTICATION_OK","description":"Authentication successful","reference":"xxxxxxxxxxxxx","userId":nnnnnn}} - and the curl parameter -c will save the authentication cookies to cookies.txt.

Now the previously "SESSION_NOT_AUTHENTICATED" failed GET to api.katsomo.fi will work when the cookies are passed with the GET:
$ curl -s "https://api.katsomo.fi/api/web/asset/885332/play?protocol=MPD" -b cookies.txt | grep url | sed 's#<url>\(.*mpd\).*#\1#'
https://mtvdashvodcloud-a.akamaized.net/video/won/ismvol1/2018-03-07/Ina__3_porno(885332_ISMUSPWV).ism/Ina__3_porno(885332_ISMUSPWV).mpd


However, I'm still unable to get youtube-dl to download the clip even I pass the cookie.txt:
$ youtube-dl --cookies cookies.txt "https://mtvdashvodcloud-a.akamaized.net/video/won/ismvol1/2018-03-07/Ina__3_porno(885332_ISMUSPWV).ism/Ina__3_porno(885332_ISMUSPWV).mpd" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'https://mtvdashvodcloud-a.akamaized.net/video/won/ismvol1/2018-03-07/Ina__3_porno(885332_ISMUSPWV).ism/Ina__3_porno(885332_ISMUSPWV).mpd', u'-v']
[debug] Encodings: locale ISO-8859-15, fs ISO-8859-15, out ISO-8859-15, pref ISO-8859-15
[debug] youtube-dl version 2018.06.14
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Ina__3_porno(885332_ISMUSPWV): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Ina__3_porno(885332_ISMUSPWV): Downloading webpage
[generic] Ina__3_porno(885332_ISMUSPWV): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2330, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1190, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This also seems to remove the cookies from the jar:
$ cat cookies.txt
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.


What am I missing here?
