### ISSUE TITLE
Vimeo on demand extraction broken

### ISSUE THREAD

**Issue by LGH** [ytdl-org/youtube-dl#10624]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.11.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
» youtube-dl --verbose  --username 'xyz@xyz.com' --password 'abc123' https://vimeo.com/watchlater
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://vimeo.com/watchlater']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo:watchlater] Logging in
[vimeo:watchlater] watchlater: Downloading page 1
[download] Downloading playlist: Watch Later
[vimeo:watchlater] playlist Watch Later: Downloading 1 videos
[download] Downloading video 1 of 1
[vimeo] Logging in
[vimeo] 126682985: Downloading webpage
[vimeo] 126682985: Extracting information
ERROR: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/hakan/python/envs/yt-dl-env/lib/python2.7/site-packages/youtube_dl/extractor/vimeo.py", line 462, in _real_extract
    flags=re.DOTALL)
  File "/Users/hakan/python/envs/yt-dl-env/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/hakan/python/envs/yt-dl-env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/Users/hakan/python/envs/yt-dl-env/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/hakan/python/envs/yt-dl-env/lib/python2.7/site-packages/youtube_dl/extractor/vimeo.py", line 476, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

---
### Description of your _issue_, suggested solution and other information

It appears Vimeo extraction is broken. For downloading on demand videos, no URLs appears to work: /watchlater, /ondemand/purchases, /ondemand/{videoid}. This affects current version 2016.09.11.1 as well as the previous I tested with, 2016.09.08. I have tested on Mac OSX with the Homebrew distribution of youtube-dl, from a Mac OSX virtualenv with youtube-dl installed using pip, and finally in a Linux virtualenv - result is the same in all three cases.

**Comment by dstftw** [comment]
>If work on your *issue* required an account credentials please provide them

**Comment by dstftw** [comment]
It may possibly work after d002e919863c910e52c623ee544e93fe41af4665.

**Comment by rfourquet** [comment]
I'm getting a similar error ("Unable to extract info section") with the following site, which doesn't require any login/account: `https://www.eckharttollekurs.net/einfuehrungskurs-lektion-3/`

**Comment by Mineroboter** [comment]
Problem is still there. For example output of `$ youtube-dl -v https://www.claus-von-wagner.de/tv/anstalt/20140204-revolution`

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio/best', '--embed-thumbnail', '-i', 'https://www.claus-von-wagner.de/tv/anstalt/20140204-revolution', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.7 (CPython) - Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 20140204-revolution: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 20140204-revolution: Downloading webpage
[generic] 20140204-revolution: Extracting information
[download] Downloading playlist: video
[generic] playlist video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 292929605: Downloading webpage
[vimeo] 292929605: Extracting information
ERROR: Unable to extract info section (caused by RegexNotFoundError('Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/vimeo.py", line 528, in _real_extract
    'vimeo clip page config')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract vimeo clip page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/vimeo.py", line 547, in _real_extract
    flags=re.DOTALL)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/vimeo.py", line 528, in _real_extract
    'vimeo clip page config')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract vimeo clip page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/vimeo.py", line 547, in _real_extract
    flags=re.DOTALL)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/vimeo.py", line 561, in _real_extract
    cause=e)
youtube_dl.utils.ExtractorError: Unable to extract info section (caused by RegexNotFoundError('Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Finished downloading playlist: video

**Comment by remitamine** [comment]
> [debug] youtube-dl version 2018.09.10

@Mineroboter you're using an outdated version.

**Comment by dirkf** [comment]
>https://vimeo.com/ondemand/luter/280331656

Working now with no login.
