### ISSUE TITLE
update script fails

### ISSUE THREAD

**Issue by 5shekel** [ytdl-org/youtube-dl#1138]
encountered this on windows 7 64bit.
ehwn i start the update machcnism for the .exe version 
the update script will try to pause for 5 seconds using
`ping 127.0.0.1 -n 5 -w 1000  1>NUL`
but this will stop and not continue after batch file initiation. 
i am left with this files.

```
youtube-dl.exe
youtube-dl.exe.new
youtube-dl-updater.bat
```

what i usually do is manually edit the batch to remove the pin command and run it again.

**Comment by mohammedp010** [comment]
Is any one working on this?

**Comment by dirkf** [comment]
No, for many reasons:

1. the report is ten years old and should have been closed
2. the report didn't show enough context to be progressed
3. the update code is different, so the report probably no longer applies
4. even if it did, currently there's no point, since the update (`-U`) option doesn't supply a useful version (#31585).
