### ISSUE TITLE
[twitch.tv] Download All Clips

### ISSUE THREAD

**Issue by Mioni** [ytdl-org/youtube-dl#12297]
Could I do that? Put the link of the user and he can download all the clips? put 1 and 1 makes me tired. :)

**Comment by goggle** [comment]
```
youtube-dl https://www.twitch.tv/<username>/videos/all
```
does that.

**Comment by Mioni** [comment]
Videos ok but clips? 
https://www.twitch.tv/goldglove/clips

**Comment by goggle** [comment]
This does not seem to be supported in the sense you want to use it, probably because it has a slider on the top of the page, where you can choose which clips should be shown on the page (trending, top last 30 days, etc.), but this slider does not change the URL of the page. So it is not clear, which clips should should be extracted since youtube-dl works URL-dependent.

**Comment by Felk** [comment]
The information is encoded into the url by now, e.g. `https://www.twitch.tv/USERNAME/clips?filter=clips&range=all`, but youtube-dl doesn't seem to find the videos

**Comment by EpicLPer** [comment]
Why was this closed?

**Comment by llacb47** [comment]
It was fixed in the referenced commit.

**Comment by EpicLPer** [comment]
Yeah, just now noticed sorry :) Still had an older version of yt-dl and didn't work, that's why I was suddenly confused.
