### ISSUE TITLE
write-kodi-descrition option request

### ISSUE THREAD

**Issue by f1egmatik** [ytdl-org/youtube-dl#13588]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your *issue*, suggested solution and other information

Thank you very much, youtube-dl authors, for this great app! I am ask you create new --write-kodi-description option (additionally to --write-description). If this new option is enabled, yt-dl writes all available info about single video to [%filename.nfo](http://kodi.wiki/view/NFO_files/TV_episodes) and (if downloads playlist) as much as possible info about playlist to [tvshow.nfo](http://kodi.wiki/view/NFO_files/TV_shows). 
So Kodi will take correct (!) descriptions from local (!) drive while scanning. 
Could you make it?

**Comment by JimKillock** [comment]
This would be _really_ useful.It would be very helpful to know from the team here how much work it is to create it also.

**Comment by dirkf** [comment]
Use `--write-info-json` to generate a filename`.info.json` file and a tool such as _jq_ to extract from it whatever metadata you want to put into a Kodi .nfo file, in whatever format that is.

**Comment by dirkf** [comment]
Simply invoke the tool in a `--exec ...` option.

Generally, it's better to have separate tools for specific tasks that can be combined as needed, even though yt-dl arguably violates that paradigm.

If an integrated solution were desired, ytdl-nfo uses the same licence as yt-dl so it would be possible to subsume it, or **better**, for Kodi to subsume it. For yt-dl there would be some small changes to match coding conventions.

**Comment by JamesClarke7283** [comment]
> 

Thanks i will put the comand in once i am done, the .nfo is trivial but the coverting of the thumbnail file name, i want to do it without running lots of commands. And so it depends on what thumbnail file extention was used. I just need to get that via the TEMPLATE format but its not listed.

Also programmatically i am sure this can be done easily  as a third party tool as well if they use the above tool to do it.
https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site=

But a command might be simple enough.

**Comment by JamesClarke7283** [comment]
If you want the thumbnails to work in Kodi as well, this is the cleanest one ive been able to do which preserves the formats used
```bash
THUMB_EXT=webp youtube-dl --write-subs --write-thumbnail --write-info-json -o "%(title)s.%(ext)s" --convert-sub srt  \
--exec after_move:'mv "%(title)s.$THUMB_EXT" "%(title)s-thumb.$THUMB_EXT"' \
--exec after_move:'ytdl-nfo "%(title)s.info.json"' https://www.youtube.com/watch?v=Ojr6hWdNQUk
```
Hardcoding it is the only clean solution, but if the thumb nail formats change then you need to adjust it.

The "thumbnail" attribute, gives the full external URL to the thumbnail. If someone has a way to extract just the ".webp" at the end of this, let me know
Example is this one:
"https://i.ytimg.com/vi_webp/Ojr6hWdNQUk/maxresdefault.webp"

**Comment by dirkf** [comment]
You appear to be using yt-dlp aliased to youtube-dl. yt-dl doesn't know about `after:...`.

Is there not a `filename` in the JSON for each thumbnail that has been written?

**Comment by JamesClarke7283** [comment]
> You appear to be using yt-dlp aliased to youtube-dl. yt-dl doesn't know about `after:...`.
> 
> Is there not a `filename` in the JSON for each thumbnail that has been written?

As far as i know, its youtube-dl as an alias for hypervideo. that is what i am using, which uses youtubedl.

As i explained no, all there was, was this 'thumbnail' attribute.

But i have come close to a solution. I can strip out the rest to get the extension of the file this way.

```bash
youtube-dl --write-subs --write-thumbnail --write-info-json -o "%(title)s.%(ext)s" --convert-sub srt \
 --exec after_move:'TE=$(echo "%(thumbnail)s" | sed 's/^.*\.//' ) mv "%(title)s.$TE" "%(title)s-thumb.$TE"' \
 --exec after_move:'ytdl-nfo "%(title)s.info.json"' https://www.youtube.com/watch?v=Ojr6hWdNQUk
```
I get this
```bash
[Exec] Executing command: TE=$(echo "https://i.ytimg.com/vi_webp/Ojr6hWdNQUk/maxresdefault.webp" | sed s/^.*.// ) mv "A New Sitcom Coming This Fall To DTTV....$TE" "A New Sitcom Coming This Fall To DTTV...-thumb.$TE"
mv: cannot stat 'A New Sitcom Coming This Fall To DTTV....': No such file or directory
ERROR: Postprocessing: Command returned error code 1

```

It does not work,

**Comment by dirkf** [comment]
If that's ["A fork of youtube-dl without nonfree parts"](https://notabug.org/heckyel/hypervideo), it's quite strange because
1. it looks like a fork of a descendant of yt-dl, if not yt-dlp exactly
2. youtube-dl without nonfree parts == youtube-dl.

Anyhow the command you've used isn't valid for yt-dl, so you should raise the issue with the provider of hypervideo. There seems to be an empty issue tracker at the site linked above, so the owner should have a lot of time to help.

There should be a `thumbnails` list in the JSON where a `filename` member might be written in the dict of each thumbnail written. If we don't produce that, it would be a good idea.

**Comment by JamesClarke7283** [comment]
> If that's ["A fork of youtube-dl without nonfree parts"](https://notabug.org/heckyel/hypervideo), it's quite strange because
> 
>     1. it looks like a fork of a descendant of yt-dl, if not yt-dlp exactly
> 
>     2. youtube-dl without nonfree parts == youtube-dl.
> 
> 
> Anyhow the command you've used isn't valid for yt-dl, so you should raise the issue with the provider of hypervideo. There seems to be an empty issue tracker at the site linked above, so the owner should have a lot of time to help.
> 
> There should be a `thumbnails` list in the JSON where a `filename` member might be written in the dict of each thumbnail written. If we don't produce that, it would be a good idea.

It allows mp4 which is patent encumbered. But that is offtopic.
It gives you a list of URL's its fine i can work with that because the file extention is at the end so the "filename" does not matter, as long as i get the file extention right it will work fine.

I found out you can use `${VARNAME##*.}` to get the extention of any string in bash, anything after the dot.
I tried it with this command:
```bash
```

So i tried to set an env variable inline and failed with that:
```bash
youtube-dl --write-subs --write-thumbnail --write-info-json -o "%(title)s.%(ext)s" --convert-sub srt  \
--exec after_move:'TE=webp mv "%(title)s."${TE} "%(title)s-thumb."${TE}'  \
--exec after_move:'ytdl-nfo "%(title)s.info.json"' https://www.youtube.com/watch?v=Ojr6hWdNQUk
```

Result:
```bash
[Exec] Executing command: TE=webp mv "A New Sitcom Coming This Fall To DTTV...."${TE} "A New Sitcom Coming This Fall To DTTV...-thumb."${TE}
mv: cannot stat 'A New Sitcom Coming This Fall To DTTV....': No such file or directory
```

**Comment by JamesClarke7283** [comment]
> If that's ["A fork of youtube-dl without nonfree parts"](https://notabug.org/heckyel/hypervideo), it's quite strange because
> 
>     1. it looks like a fork of a descendant of yt-dl, if not yt-dlp exactly
> 
>     2. youtube-dl without nonfree parts == youtube-dl.
> 
> 
> Anyhow the command you've used isn't valid for yt-dl, so you should raise the issue with the provider of hypervideo. There seems to be an empty issue tracker at the site linked above, so the owner should have a lot of time to help.
> 
> There should be a `thumbnails` list in the JSON where a `filename` member might be written in the dict of each thumbnail written. If we don't produce that, it would be a good idea.

Oh sorry, no the issue was addressed with this `--exec after_move:'ytdl-nfo "%(title)s.info.json"'` earlier. The .nfo file is written so as far as that goes, its working when you use that tool. So users have a solution, although not builtin to youtube-dl yet.

I am just trying to do the thumbnail part to work well. Its the same issue with vanilla youtube-dl, because the thumbnail's default type is "jpg" but there are other types of image formats for thumbnails so i wanted to cover all bases.

**Comment by dirkf** [comment]
In the yt-dl code the thumbnail filenames are added to the `info_dict` just after it has been written as JSON. This is probably wrong. This may differ in the fork that you are using.

**Comment by JamesClarke7283** [comment]
I just said filenames were there.
I was trying to get the file extention from the file names.

**Comment by JamesClarke7283** [comment]
@ f1egmatik  started this issue so @dirkf  i dont think its fair to close this because of my comments on a seperate thing.

I think there was a misunderstanding, what @f1egmatik was talking about is that there is no .nfo output which is written to be compatable with media centres. We can argue wheather you should output to nfo or not.

But outdated-version makes no sense.

**Comment by dirkf** [comment]
After 5 years, no-one has wanted this enough to make a PR. Now there is a solution that addresses OP's specific need. And https://github.com/ytdl-org/youtube-dl/issues/13588#issuecomment-1179046387.

**Comment by JamesClarke7283** [comment]
I see, so your objection is not that i was talking slightly offtopic about thumbnail(sorry if i was). It was that that feature was never acted on in youtube and you dont think its needed in youtube-dl's end.

I guess that makes sense. But at least now  people can find this awesome tool.

**Comment by JamesClarke7283** [comment]
> 2017.07

All my commands were run after that version, so don't worry, the commands will apply because those fields were missing in a client i did not even posess. And i ran them in both versions to double check. Only difference was the default thumbnail format. But that was outside of scope, and just something on the side in case someone was running into issues with adapting their downloaded thumbnails to be recognized by kodi.  

Thanks for the discussion @dirkf and all your work hard work on this, i appreciate it.

I will hopefully be returning in the future with some pull requests at some point in the future, as there are some features which i would like to use personally that are not open here. But those wont be issues, i will just go ahead and do a PR, lots of issues here already i understand.

Have a great day @dirkf. 

And,
Happy Hacking (:
