### ISSUE TITLE
Output Filename Template: Request for upload-datetime

### ISSUE THREAD

**Issue by himadri0327** [ytdl-org/youtube-dl#1706]
The current %(upload_date)s gives YYYYMMDD. Could you please consider adding another that includes time like YYYYMMDD-hhmmss ? Maybe a date-time combination option %(upload_datetime)s or a separate %(upload_time)s ?

**Comment by l0b0** [comment]
Looks like because the way youtube-dl is architected (each site having custom code to extract the date string, and then unifying the formatting but returning the result as a string rather than a datetime) this might involve a lot of change (but none of it very complex AFAICT):

1. Instead of using `unified_strdate` return a `datetime` object in `_real_extract` and equivalent.
1. Detect when `info_dict` contains a datetime and format it when necessary. That way even the datetime formatting could be a configuration directive or parameter.

**Comment by djmixman** [comment]
Almost 5 years now... Still can't include an HHMM in the filename :'(

**Comment by tecxy** [comment]
I would be happy to get the format  "YYYY-MM-DDTHH:MM:SS "  in the filename too.

**Comment by shillshocked** [comment]
Upvoted!

**Comment by duckpuppy** [comment]
Having a separate upload_time field would be fine - If you're grabbing from a source that doesn't provide the time, then you won't use it in any templates or code, and it can default to midnight in whatever timezone the date is in (which should be knowable per extractor)... or just not be in the info_dict at all if it's not provided, and dependent code can check to see if upload_time is available as necessary. Since the extractors abstract all the parsing of the video info, they can make the determination on what should be in the upload_time field, or if it should exist in the dict at all.

@l0b0 has a decent suggestion as well to keep things unified.

**Comment by pukkandan** [comment]
There is already a `timestamp` field. Note however that if you are using YouTube, they don't provide the time information, so only the `upload_date` is available

**Comment by dirkf** [comment]
However, now: https://github.com/yt-dlp/yt-dlp/issues/9829#issuecomment-2090207026.
