### ISSUE TITLE
Support for yesmovies.to

### ISSUE THREAD

**Issue by sl4vkek** [ytdl-org/youtube-dl#20512]
What is the purpose of my issue?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I want support for https://yesmovies.to
Is this possible?
Thx, -sl4v

**Comment by aishajaawad** [comment]
Since [yesmovies](https://themacforums.com/yesmovie-download-free-movies/) went online, watching movies without paying has become a lot easier. From action movies to comedy to drama to sci-fi and more, GoMovies offers such a large collection of movies and TV shows that it would take years to see everything.
