### ISSUE TITLE
无法合并视频

### ISSUE THREAD

**Issue by dreamchonghua** [ytdl-org/youtube-dl#20564]
代码：youtube-dl.exe -f bestvideo+bestaudio --merge-output-format mp4 https://www.youtube.com/watch?v=r3V4sBPxMow --proxy "127.0.0.1:1080" --external-downloader aria2c --external-downloader-args "-x 90 -k 1M"

下载下来的视频，应该是视频格式（mp4）+音频格式（webm），无法自动合成，希望下一版本支持，谢谢，youtube-dl.exe -f bestvideo[mp4]+bestaudio[m4a] --merge-output-format mp4 https://www.youtube.com/watch?v=r3V4sBPxMow --proxy "127.0.0.1:1080" --external-downloader aria2c --external-downloader-args "-x 90 -k 1M"

还有音频格式，不要OPUS的音频，因为有的显卡不支持硬解，谢谢

**Comment by 907544030** [comment]
MPEG-4容器不能放入Opus格式的音频。不需要使用`--merge-output-format`，程序会自动转换成mkv文件。

MPEG-4 container can not put an audio in Opus format. you don't need to use `--merge-output-format`, because program will merge your files to `.mkv` automatically.


你的第二条命令有误：
Your second command is error.

请使用：
Please use:
-f bestvideo[ext=mp4]+bestaudio[ext=m4a] --merge-output-format mp4

**Comment by fc1104** [comment]
If outtmpl='-' is set, it will not merge automatically. How to solve this problem?

**Comment by dirkf** [comment]
Use `--external-downloader ffmpeg`. Also, don't post an unrelated question in a closewd issue.
