### ISSUE TITLE
getting "YouTube said: This video is restricted. Try signing in with a Google Apps account." recently

### ISSUE THREAD

**Issue by sokoow** [ytdl-org/youtube-dl#20846]
Is anybody else getting "YouTube said: This video is restricted. Try signing in with a Google Apps account." using youtube-dl recently ?

**Comment by SeanPM5** [comment]
I've encountered this issue a bunch today and it was because of AdGuard DNS which I just recently set up. Either the Safe Search, Safe Browsing, or Parental Control option was the cause. Video worked and played fine when logged into my YouTube account but was restricted as a guest (and thus youtube-dl couldn't download it). Once I disabled the AdGuard DNS stuff everything worked fine as expected. 

Just posting a possible solution in case it helps anyone finding this via search.

**Comment by jazzmonger** [comment]
It worked for me by disabling safe search
