### ISSUE TITLE
[Youtube] Having issues with videos downloaded from youtube movies.

### ISSUE THREAD

**Issue by ethanbreck** [ytdl-org/youtube-dl#21174]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
❯ youtube-dl --verbose s7_qI6_mIXc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u's7_qI6_mIXc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] s7_qI6_mIXc: Downloading webpage
[youtube] s7_qI6_mIXc: Downloading video info webpage
[youtube] s7_qI6_mIXc: Downloading MPD manifest
WARNING: [youtube] s7_qI6_mIXc: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r2---sn-o097znlr.googlevideo.com/videoplayback?id=d6e5a8a51c0e5e16&aitags=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224%2C225%2C226%2C227%2C273%2C274%2C275%2C279%2C280%2C317%2C318%2C357%2C358%2C359%2C360&itag=227&source=yt_media&requiressl=yes&mm=31%2C29&mn=sn-o097znlr%2Csn-n4v7sn76&ms=au%2Crdu&mv=m&pl=40&ei=xF3jXNX7DtLukgbVhL6QBQ&gcr=us&initcwndbps=2243750&mime=video%2Fmp4&aid=c6fd0e1d17810c44&asource=youtube&gir=yes&clen=5681871035&dur=5748.033&lmt=1548769415160173&mt=1558404466&fvip=1&keepalive=yes&c=WEB&ip=2603%3A3024%3A1a4e%3A0%3Ab060%3A6705%3A8e9c%3A2298&ipbits=0&expire=1558426148&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Caid%2Casource%2Cgir%2Cclen%2Cdur%2Clmt&signature=C7525CD22B372EC488A55F7D455BCD9239CAD2AF.91291E016979BAC4C0B2FE0755369222FF8F5B18&key=yt8&ratebypass=yes'
[download] Resuming download at byte 523264
[download] Destination: In The Mix-s7_qI6_mIXc.f227.mp4
[download]   0.2% of 5.29GiB at  4.30MiB/s ETA 20:58^C

```

## Description

Trying to download a movie to use for a school project, and the video failed. so i deleted and tried with another movie, with VLC this time, and the video just didnt play, apart from some audio, at the beginning. No credentials needed. As its the terminator movie, free on YouTube.  (https://www.youtube.com/watch?v=s7_qI6_mIXc). Unsure of a suggestion on how to fix DASH manifest: ExtractorError stuff

**Comment by antdude** [comment]
I just noticed this too today with several of them from https://www.youtube.com/playlist?list=PLHPTxTxtC0ibVZrT2_WKWUl2SAxsKuKwx. I think it is related to "manifest: HTTP Error 404: Not Found (caused by HTTPError())" error as shown below:

$ youtube-dl -v  https://www.youtube.com/watch?v=jlb6Qrvgt0Y
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=jlb6Qrvgt0Y']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-8-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jlb6Qrvgt0Y: Downloading webpage
[youtube] jlb6Qrvgt0Y: Downloading video info webpage
[youtube] jlb6Qrvgt0Y: Downloading MPD manifest
WARNING: [youtube] jlb6Qrvgt0Y: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-a5meknlz.googlevideo.com/videoplayback?id=4d2eacfd70b5b81d&aitags=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224%2C225%2C226%2C227%2C273%2C274%2C275%2C279%2C280%2C317%2C318%2C357%2C358%2C359%2C360&itag=227&source=yt_media&requiressl=yes&mm=31%2C26&mn=sn-a5meknlz%2Csn-q4flrnek&ms=au%2Conr&mv=m&pl=14&ei=QanpXKCBGJeCkgbSxpTwAQ&gcr=us&initcwndbps=1766250&mime=video%2Fmp4&aid=8e56fa42bbe0b746&asource=youtube&gir=yes&clen=3476185375&dur=4745.578&lmt=1549681906065708&mt=1558816811&fvip=4&keepalive=yes&c=WEB&ip=45.50.15.139&ipbits=0&expire=1558838689&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Caid%2Casource%2Cgir%2Cclen%2Cdur%2Clmt&signature=D9138CD810BC0C8AE9CA9AEFB1671B9DB65132F7.31C4397908C1D29E41AB588A9F86074F9FE35AED&key=yt8&ratebypass=yes'
[download] Destination: Code - Debugging the Gender Gap-jlb6Qrvgt0Y.f227.mp4
[download]   3.0% of 3.24GiB at  9.93MiB/s ETA 05:23
