### ISSUE TITLE
[YouTube] Issue Downloading - Hanging and broken downloads

### ISSUE THREAD

**Issue by HarshNormal** [ytdl-org/youtube-dl#21192]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
root@emby-server:/mnt/YouTube/GenerikB # youtube-dl --write-thumbnail --ffmpeg-location /usr/local/bin/ffmpeg --no-check-certificate -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/watch?v=UQacuhCxzwY&list=PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc" -v --write-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--write-thumbnail', u'--ffmpeg-location', u'/usr/local/bin/ffmpeg', u'--no-check-certificate', u'-o', u'%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'https://www.youtube.com/watch?v=UQacuhCxzwY&list=PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc', u'-v', u'--write-pages']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - FreeBSD-11.2-STABLE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc - add --no-playlist to just download video UQacuhCxzwY
[youtube:playlist] PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc: Downloading webpage
[youtube:playlist] Saving request to PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc_https_-_www.youtube.com_playlistdisable_polymer=true_list=PL7j0JO-w0xWlV1GYmvImyCIyIMmY0q4Bc.dump
[download] Downloading playlist: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)
[youtube:playlist] playlist Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p): Downloading 9 videos
[download] Downloading video 1 of 9
[youtube] UQacuhCxzwY: Downloading webpage
[youtube] Saving request to UQacuhCxzwY_https_-_www.youtube.com_watchhas_verified=1_bpctr=9999999999_hl=en_v=UQacuhCxzwY_disable_polymer=true_gl=US.dump
[youtube] UQacuhCxzwY: Downloading video info webpage
[youtube] Saving request to UQacuhCxzwY_https_-_www.youtube.com_get_video_infops=default_el=embedded_video_id=UQacuhCxzwY_hl=en_sts=18038_disable_polymer=true_gl=US_eurl=.dump
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] UQacuhCxzwY: Downloading thumbnail ...
[youtube] UQacuhCxzwY: Writing thumbnail to: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/1 - 'NEW SURVIVAL SEASON!!!' Subnautica Ep 01 1080p HD PC Gameplay Walkthrough.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/1 - 'NEW SURVIVAL SEASON!!!' Subnautica Ep 01 1080p HD PC Gameplay Walkthrough.mkv has already been downloaded and merged
[download] Downloading video 2 of 9
[youtube] RErwcs5YeyA: Downloading webpage
[youtube] Saving request to RErwcs5YeyA_https_-_www.youtube.com_watchhas_verified=1_bpctr=9999999999_hl=en_v=RErwcs5YeyA_disable_polymer=true_gl=US.dump
[youtube] RErwcs5YeyA: Downloading video info webpage
[youtube] Saving request to RErwcs5YeyA_https_-_www.youtube.com_get_video_infops=default_el=embedded_video_id=RErwcs5YeyA_hl=en_sts=18038_disable_polymer=true_gl=US_eurl=.dump
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] RErwcs5YeyA: Downloading thumbnail ...
[youtube] RErwcs5YeyA: Writing thumbnail to: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/2 - 'DOUBLE DECKER AQUARIUM!!!' Subnautica Ep 02 1080p HD PC Gameplay Walkthrough.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/2 - 'DOUBLE DECKER AQUARIUM!!!' Subnautica Ep 02 1080p HD PC Gameplay Walkthrough.mkv has already been downloaded and merged
[download] Downloading video 3 of 9
[youtube] ZqdxhuknVBE: Downloading webpage
[youtube] Saving request to ZqdxhuknVBE_https_-_www.youtube.com_watchhas_verified=1_bpctr=9999999999_hl=en_v=ZqdxhuknVBE_disable_polymer=true_gl=US.dump
[youtube] ZqdxhuknVBE: Downloading video info webpage
[youtube] Saving request to ZqdxhuknVBE_https_-_www.youtube.com_get_video_infops=default_el=embedded_video_id=ZqdxhuknVBE_hl=en_sts=18038_disable_polymer=true_gl=US_eurl=.dump
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] ZqdxhuknVBE: Downloading thumbnail ...
[youtube] ZqdxhuknVBE: Writing thumbnail to: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/3 - 'BLUEPRINT FRAGMENT HUNTING!!!' Subnautica Ep 03 1080p HD PC Gameplay Walkthrough.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/3 - 'BLUEPRINT FRAGMENT HUNTING!!!' Subnautica Ep 03 1080p HD PC Gameplay Walkthrough.mkv has already been downloaded and merged
[download] Downloading video 4 of 9
[youtube] i-Z0hlAljKU: Downloading webpage
[youtube] Saving request to i-Z0hlAljKU_https_-_www.youtube.com_watchhas_verified=1_bpctr=9999999999_hl=en_v=i-Z0hlAljKU_disable_polymer=true_gl=US.dump
[youtube] i-Z0hlAljKU: Downloading video info webpage
[youtube] Saving request to i-Z0hlAljKU_https_-_www.youtube.com_get_video_infops=default_el=embedded_video_id=i-Z0hlAljKU_hl=en_sts=18038_disable_polymer=true_gl=US_eurl=.dump
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] i-Z0hlAljKU: Downloading thumbnail ...
[youtube] i-Z0hlAljKU: Writing thumbnail to: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - 'AURORA CRASH EXPLORING!!!' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-q4fl6n7s.googlevideo.com/videoplayback?id=o-AD_uVjVpkRdw9AHJZ8bIPleBD5KDrsffug6qvlPXpHTj&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&itag=137&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-q4fl6n7s%2Csn-q4flrnle&ms=au%2Crdu&mv=m&pl=15&ei=gg7mXK3HI5CWigTmn4bQAQ&initcwndbps=1610000&mime=video%2Fmp4&gir=yes&clen=659413128&dur=1874.066&lmt=1457878598665478&mt=1558580682&fvip=3&keepalive=yes&c=WEB&ip=70.112.99.175&ipbits=0&expire=1558602466&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=C26BAF03BE20B44A6782BAFE42E22CE8B4BE8384.03590A3A2C1BF5184AF0AB628EA7721B73354853&key=yt8&ratebypass=yes'
[download] Unable to resume
[download] Destination: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - 'AURORA CRASH EXPLORING!!!' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.f137.mp4
[download] 100% of 43.00B in 00:00
[debug] Invoking downloader on u'https://r1---sn-q4fl6n7s.googlevideo.com/videoplayback?id=o-AD_uVjVpkRdw9AHJZ8bIPleBD5KDrsffug6qvlPXpHTj&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-q4fl6n7s%2Csn-q4flrnle&ms=au%2Crdu&mv=m&pl=15&ei=gg7mXK3HI5CWigTmn4bQAQ&initcwndbps=1610000&mime=audio%2Fwebm&gir=yes&clen=31214784&dur=1874.061&lmt=1457727163082579&mt=1558580682&fvip=3&keepalive=yes&c=WEB&ip=70.112.99.175&ipbits=0&expire=1558602466&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=6641F917C7CAD3C74DD8DE714CAD991315150C47.0F862614EE4D8D3BEBD2C2BE1747F21C02F933B8&key=yt8&ratebypass=yes'
[download] Unable to resume
[download] Destination: Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - 'AURORA CRASH EXPLORING!!!' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.f251.webm
[download] 100% of 43.00B in 00:00
[ffmpeg] Merging formats into "Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - 'AURORA CRASH EXPLORING!!!' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.mkv"
[debug] ffmpeg command line: /usr/local/bin/ffmpeg -y -loglevel 'repeat+info' -i 'file:Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - '"'"'AURORA CRASH EXPLORING!!!'"'"' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.f137.mp4' -i 'file:Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - '"'"'AURORA CRASH EXPLORING!!!'"'"' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Subnautica Survival! (Submarine Underwater Sandbox Survival 1080p)/4 - '"'"'AURORA CRASH EXPLORING!!!'"'"' Subnautica Ep 04 1080p HD PC Gameplay Walkthrough.temp.mkv'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: To ignore this, add a trailing '?' to the map.

```

## Description

Trying to download videos from a playlist but two things tend to happen: 
1) The download hangs and then times out
2) The separate audio and video files are not actually downloaded, instead a 43.00B file is downloaded for each and then ffmpeg fails to merge them

I've checked to make sure that the audio and video files are in fact audio and video only, ensuring that ffmpeg can merge them. However, like I said above, they are not the correct files as they are only 43.00B in size.

I've tried troubleshooting from a different environment with the most up to date youtube-dl and ffmpeg and still get the same errors. I'm seeing the traffic move out of my network so I'm confident that nothing is being blocked. 

Please tell me I'm missing something obvious and should be feeling silly. Any help would be much appreciated.

**Comment by sunxvogy** [comment]
I got this issue too.

`[youtube] IvgyfqzLC0A: Downloading webpage

[youtube] IvgyfqzLC0A: Downloading video info webpage

[youtube] Downloading just video IvgyfqzLC0A because of --no-playlist

[download] Destination: c:\tmpDownload\tmpvideo.mkv

[download]   0.0% of 110.32MiB at 64.14KiB/s ETA 29:21
[download]   0.0% of 110.32MiB at 192.42KiB/s ETA 09:47
[download]   0.0% of 110.32MiB at 448.97KiB/s ETA 04:11
[download]   0.0% of 110.32MiB at 962.08KiB/s ETA 01:57
[download]   0.0% of 110.32MiB at 821.06KiB/s ETA 02:17
[download]   0.1% of 110.32MiB at 912.08KiB/s ETA 02:03

[download]   0.1% of 110.32MiB at  1.24MiB/s ETA 01:29 

[download]   0.2% of 110.32MiB at  1.24MiB/s ETA 01:28 

[download]   0.5% of 110.32MiB at  1.47MiB/s ETA 01:14 

[download]   0.9% of 110.32MiB at  1.46MiB/s ETA 01:15 

[download]   1.8% of 110.32MiB at  1.68MiB/s ETA 01:04 

[download]   3.6% of 110.32MiB at  1.67MiB/s ETA 01:03 

[download]   5.1% of 110.32MiB at  1.71MiB/s ETA 01:01 

[download]   6.8% of 110.32MiB at  1.76MiB/s ETA 00:58 

[download]   8.5% of 110.32MiB at  1.75MiB/s ETA 00:57 

[download]  10.1% of 110.32MiB at  1.76MiB/s ETA 00:56 

[download]  11.7% of 110.32MiB at  1.77MiB/s ETA 00:55 

[download]  13.4% of 110.32MiB at  1.77MiB/s ETA 00:53 

[download]  15.0% of 110.32MiB at  1.77MiB/s ETA 00:53 

[download]  16.6% of 110.32MiB at  1.76MiB/s ETA 00:52 

[download]  18.1% of 110.32MiB at  1.74MiB/s ETA 00:51 

[download]  19.5% of 110.32MiB at  1.74MiB/s ETA 00:50 
ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)

[youtube] IvgyfqzLC0A: Downloading webpage

[youtube] IvgyfqzLC0A: Downloading video info webpage

[youtube] Downloading just video IvgyfqzLC0A because of --no-playlist

[download] Destination: c:\tmpDownload\tmpvideo.mkv

[download]   0.0% of 110.32MiB at 199.72KiB/s ETA 09:25
[download]   0.0% of 110.32MiB at 599.16KiB/s ETA 03:08
[download]   0.0% of 110.32MiB at  1.37MiB/s ETA 01:20 
[download]   0.0% of 110.32MiB at  2.93MiB/s ETA 00:37 

[download]   0.0% of 110.32MiB at 854.02KiB/s ETA 02:12
[download]   0.1% of 110.32MiB at 933.19KiB/s ETA 02:00
[download]   0.1% of 110.32MiB at  1.18MiB/s ETA 01:33 

[download]   0.2% of 110.32MiB at  1.21MiB/s ETA 01:30 

[download]   0.5% of 110.32MiB at  1.55MiB/s ETA 01:10 

[download]   0.9% of 110.32MiB at  1.35MiB/s ETA 01:20 

[download]   1.8% of 110.32MiB at  1.43MiB/s ETA 01:15 

[download]   3.2% of 110.32MiB at  1.46MiB/s ETA 01:13 

[download]   4.5% of 110.32MiB at  1.50MiB/s ETA 01:10 

[download]   6.0% of 110.32MiB at  1.49MiB/s ETA 01:09 

[download]   7.3% of 110.32MiB at  1.50MiB/s ETA 01:07 

[download]   8.7% of 110.32MiB at  1.43MiB/s ETA 01:10 

[download]   9.8% of 110.32MiB at  1.48MiB/s ETA 01:07 

[download]  11.6% of 110.32MiB at  1.55MiB/s ETA 01:02 

[download]  13.5% of 110.32MiB at  1.58MiB/s ETA 01:00 

[download]  15.1% of 110.32MiB at  1.60MiB/s ETA 00:58 

[download]  16.7% of 110.32MiB at  1.63MiB/s ETA 00:56 

[download]  18.5% of 110.32MiB at  1.65MiB/s ETA 00:54 

[download]  20.3% of 110.32MiB at  1.67MiB/s ETA 00:52 

[download]  22.0% of 110.32MiB at  1.69MiB/s ETA 00:51 

[download]  23.7% of 110.32MiB at  1.70MiB/s ETA 00:49 

[download]  25.4% of 110.32MiB at  1.69MiB/s ETA 00:48 

[download]  26.9% of 110.32MiB at  1.70MiB/s ETA 00:47 

[download]  28.5% of 110.32MiB at  1.71MiB/s ETA 00:46 

[download]  30.2% of 110.32MiB at  1.72MiB/s ETA 00:44 

[download]  31.9% of 110.32MiB at  1.71MiB/s ETA 00:43 

[download]  33.4% of 110.32MiB at  1.70MiB/s ETA 00:43 

[download]  34.7% of 110.32MiB at  1.70MiB/s ETA 00:42 

[download]  36.3% of 110.32MiB at  1.71MiB/s ETA 00:41 

[download]  38.0% of 110.32MiB at  1.71MiB/s ETA 00:40 

[download]  39.5% of 110.32MiB at  1.70MiB/s ETA 00:39 
**ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)**

`

**Comment by HarshNormal** [comment]
I also had an SSL issue, but I started downloading with the "--no-check-certificate" flag for the time being.

**Comment by sunxvogy** [comment]
Yes i used that flag.
Command:

`youtube-dl.exe --no-cache-dir --no-check-certificate --no-playlist -f bestvideo[ext=webm]/bestvideo[ext=mp4]/best -o c:\tmpdownload\tmpv.mkv https://www.youtube.com/watch?v=IvgyfqzLC0A`

**Comment by dstftw** [comment]
Most likely network/environment issue on your side.
