### ISSUE TITLE
twitter-video error

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#21251]
```
C:\Users\GEN32UC>youtube-dl https://twitter.com/artporns/status/1133735419735003141 --verbose
[debug] System config: []
[debug] User config: ['-o', 'H:/youtube-dl/%(extractor)s/%(title)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail']
[debug] Custom config: []
[debug] Command-line args: ['https://twitter.com/artporns/status/1133735419735003141', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Proxy map: {}
[twitter] 1133735419735003141: Downloading webpage
[twitter:card] 1133735419735003141: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by fodaveg** [comment]
+1 here.

`youtube-dl --verbose -f 'best[ext=mp4]' -q -o 'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s' --restrict-filenames https://twitter.com/only4laffs/status/1133861975870590976


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'best[ext=mp4]', u'-q', u'-o', u'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s', u'--restrict-filenames', u'https://twitter.com/only4laffs/status/1133861975870590976']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-148-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`

**Comment by Hrxn** [comment]
`HTTP 503`

But it does work in the browser, right, at the same time, same connection etc.?

**Comment by brachna** [comment]
Does it still not working?
I had a problem with my script for some hours because https://twitter.com/i/videos/tweet/{tweetid} would return error. However looking at the tweet on twitter itself - video plays normally.
But it seems to be working now (url that is).

**Comment by kawoukaka** [comment]
> +1 here.
> 
> `youtube-dl --verbose -f 'best[ext=mp4]' -q -o 'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s' --restrict-filenames https://twitter.com/only4laffs/status/1133861975870590976
> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--verbose', u'-f', u'best[ext=mp4]', u'-q', u'-o', u'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s', u'--restrict-filenames', u'https://twitter.com/only4laffs/status/1133861975870590976']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.05.20
> [debug] Python version 2.7.12 (CPython) - Linux-4.4.0-148-generic-x86_64-with-Ubuntu-16.04-xenial
> [debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
> [debug] Proxy map: {}
> ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
> return self._downloader.urlopen(url_or_request)
> File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
> return self._opener.open(req, timeout=self._socket_timeout)
> File "/usr/lib/python2.7/urllib2.py", line 435, in open
> response = meth(req, response)
> File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
> 'http', request, response, code, msg, hdrs)
> File "/usr/lib/python2.7/urllib2.py", line 473, in error
> return self._call_chain(*args)
> File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
> result = func(*args)
> File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
> raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`

It is working for me.
youtube-dl --verbose -f 'best[ext=mp4]' -q -o 'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s' --restrict-filenames https://twitter.com/only4laffs/status/1133861975870590976

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best[ext=mp4]', '-q', '-o', 'twitter_videos/3f7ce1f0ce903b50218d8c2e0a346a60.%(ext)s', '--restrict-filenames', 'https://twitter.com/only4laffs/status/1133861975870590976']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.6.7 (CPython) - Linux-4.18.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1133861939661217792/pu/pl/640x480/yaw0uQZ1VKYX6a_D.m3u8'
WARNING: 1133861975870590976: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.

**Comment by wankio** [comment]
> 
> 
> `HTTP 503`
> 
> But it does work in the browser, right, at the same time, same connection etc.?

yeah, it worked on browser. today i just test it again and it run well. so it's server-side or youtube-dl side ?
