### ISSUE TITLE
Orf

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#21457]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.06.08**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

C:\Users>y -v --geo-bypass-country AT https://tvthek.orf.at/live/Der-
Bestseller-Millionencoup-auf-Gran-Canaria/14019519
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass-country', 'AT', 'https://tv
thek.orf.at/live/Der-Bestseller-Millionencoup-auf-Gran-Canaria/14019519']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-93674-g1e01f66-Reino, ffprobe N-93674-g1e01f
66-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 84.118.136.214 (AT) as X-Forwarded-For.
[orf:tvthek] 14019519: Downloading webpage
[orf:tvthek] 14019519: Downloading f4m manifest
ERROR: 14019519: Failed to parse XML  (caused by ParseError('syntax error:
line 1, column 0',)); please report this issue on https://yt-dl.org/bug . M
ake sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete
 output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 849, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\compat.py", line 2522, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML

  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 849, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\compat.py", line 2522, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML

  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\orf.py", line 94, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 1467, in _extract_f4m_f
ormats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 842, in _download_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 826, in _download_xml_h
andle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3
esl0iyj\build\youtube_dl\extractor\common.py", line 853, in _parse_xml
youtube_dl.utils.ExtractorError: 14019519: Failed to parse XML  (caused by
ParseError('syntax error: line 1, column 0',)); please report this issue on
 https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
g and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by avagraha** [comment]
Or https://tvthek.orf.at/live/Fussball-Frauen-Laenderspiel-Oesterreich-Slowakei-Highlights/14019558

**Comment by annomatik** [comment]
$ youtube-dl --verbose https://tvthek.orf.at/profile/Bewusst-gesund/1714463/Bewusst-gesund-Das-Magazin/14018265
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tvthek.orf.at/profile/Bewusst-gesund/1714463/Bewusst-gesund-Das-Magazin/14018265']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 2.7.13 (CPython) - Linux-4.14.98-v7+-armv7l-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[orf:tvthek] 14018265: Downloading webpage
[orf:tvthek] 14520487: Downloading m3u8 information
[orf:tvthek] 14520487: Downloading f4m manifest
[orf:tvthek] 14520487: Downloading f4m manifest
ERROR: Unable to download f4m manifest: IncompleteRead(1268 bytes read) (caused by IncompleteRead(1268 bytes read)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1028, in http_response
    content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 627, in _read_chunked
    raise IncompleteRead(''.join(value))

**Comment by avagraha** [comment]
I guess that mine issue (the main topic) is different thans your due to 
failing --geo-bypass


  ----- Original Message -----

**Comment by annomatik** [comment]
Didn't know about that flag. I'm located in Austria, until now, I could download ORF stuff without any flags. Currently, downloading from ORF does not work for me with youtube-dl, but it works with jDownloader.

**Comment by dirkf** [comment]
Superseded by #32798.
