### ISSUE TITLE
[BBC.co.uk] "No Video Formats Found"

### ISSUE THREAD

**Issue by darthhaggis** [ytdl-org/youtube-dl#21517]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Video\Downloads>youtube-dl "https://www.bbc.co.uk/iplayer/episode/p01fj
94w/peaky-blinders-series-1-episode-1" -v
[debug] System config: []
[debug] User config: ['--all-subs', '--sub-format', 'srt', '--convert-subs', 'sr
t', '--embed-subs', '--merge-output-format', 'mkv', '--recode-video', 'mkv', '--
format', 'bestvideo[width=1280]+bestaudio/best', '-o', 'D:/Video/Downloads/%(ser
ies)s/%(series)s - %(season_number)sx%(episode_number)02d - %(title)s [%(height)
s] [%(id)s].%(ext)s', '--prefer-ffmpeg', '--ffmpeg-location', 'D:\\Video\\FFMPEG
\\bin', '--download-archive', 'D:/Video/Downloads/Archive.txt', '--exec', 'D:\\V
ideo\\FFMPEG\\bin\\ffmpeg.exe -i {} -map 0 {}_+.mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://www.bbc.co.uk/iplayer/episode/p01fj94w/peak
y-blinders-series-1-episode-1', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90771-g5079e96bcc, ffprobe N-90771-g5079e96bcc
[debug] Proxy map: {}
[bbc.co.uk] p01fj94w: Downloading video page
[bbc.co.uk] p01fj94w: Downloading playlist JSON
[bbc.co.uk] b03b3c95: Downloading media selection XML
[bbc.co.uk] b03b3c95: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading captions
[bbc.co.uk] b03b3c95: Downloading captions
WARNING: Unable to download XML: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\bbc.py", line 577, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

```

## Description

Until this past week, the BBC site was working without any major issues. Now however, since updating the software, every file returns an error message stating that there are "No Video Formats Found."  This includes for videos that were working normally last week. These videos still work within the browser without issue.
URL of video tested above: https://www.bbc.co.uk/iplayer/episode/p01fj94w/peaky-blinders-series-1-episode-1

**Comment by dstftw** [comment]
For any work on this you must provide working GB proxy/vpn.

**Comment by darthhaggis** [comment]
> 
> 
> For any work on this you must provide working GB proxy/vpn.

How am I expected to provide a working proxy/vpn if I don't have one and none is required for me to access this content here in the UK?

**Comment by Carlz10** [comment]
I just came to the issue as I was about to log one for the same problem, as I have been having issues with BBC iPlayer links since last week also (I'm in Aus using a VPN).
However, I've just attempted to replicate and to my surprise, this one actually started downloading for me --

`>youtube-dl.exe -v -c -w "https://www.bbc.co.uk/iplayer/episode/p01fj94w/peaky-blinders-series-1-episode-1" -o "%(title)s.%(ext)s" --sub-lang en --write-sub --convert-subtitles srt --embed-subs --ignore-errors --add-metadata
[debug] System config: []
[debug] User config: []                                                                                                               [debug] Custom config: []
[debug] Command-line args: ['-v', '-c', '-w', 'https://www.bbc.co.uk/iplayer/episode/p01fj94w/peaky-blinders-series-1-episode-1', '-o', '%(title)s.%(ext)s', '--sub-lang', 'en', '--write-sub', '--convert-subtitles', 'srt', '--embed-subs', '--ignore-errors', '--add-metadata']                                                                                                                                [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[bbc.co.uk] p01fj94w: Downloading video page
[bbc.co.uk] p01fj94w: Downloading playlist JSON
[bbc.co.uk] b03b3c95: Downloading media selection XML                                                                                 [bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest                                                                                        WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest                                                                                        [bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden                                                               [bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden                                                               [bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden                                                               [bbc.co.uk] b03b3c95: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden                                                                   [bbc.co.uk] b03b3c95: Downloading MPD manifest
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information                                                                                    WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden                                                               [bbc.co.uk] b03b3c95: Downloading captions                                                                                            [bbc.co.uk] b03b3c95: Downloading captions
WARNING: Unable to download XML: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading captions                                                                                            WARNING: Unable to download XML: HTTP Error 403: Forbidden                                                                            [debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Peaky Blinders, Series 1, Episode 1.en.ttml
[debug] Invoking downloader on 'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/88b0e4-b03b3c95/vf_b03b3c95_aab2d8c5-3f73-41d1-95a7-26f1ff871eed.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1561669611&e=1561712811&h=43f47f9dc00ad921fdde08ff15288310'                                                                                                                            [dashsegments] Total fragments: 892                                                                                                   [download] Destination: Peaky Blinders, Series 1, Episode 1.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download]   0.3% of ~1.21GiB at 142.46KiB/s ETA 01:09:33`

**Comment by Carlz10** [comment]
`
youtube-dl.exe -v -c -w "https://www.bbc.co.uk/iplayer/episode/p01fj94w/peaky-blinders-series-1-episode-1" -o "%(title)s.%(ext)s" --sub-lang en --write-sub --convert-subtitles srt --embed-subs --ignore-errors --add-metadata
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-c', '-w', 'https://www.bbc.co.uk/iplayer/episode/p01fj94w/peaky-blinders-series-1-episode-1', '-o', '%(title)s.%(ext)s', '--sub-lang', 'en', '--write-sub', '--convert-subtitles', 'srt', '--embed-subs', '--ignore-errors', '--add-metadata']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[bbc.co.uk] p01fj94w: Downloading video page
[bbc.co.uk] p01fj94w: Downloading playlist JSON
[bbc.co.uk] b03b3c95: Downloading media selection XML
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading MPD manifest
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading captions
[bbc.co.uk] b03b3c95: Downloading captions
WARNING: Unable to download XML: HTTP Error 403: Forbidden
[bbc.co.uk] b03b3c95: Downloading captions
WARNING: Unable to download XML: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Peaky Blinders, Series 1, Episode 1.en.ttml
[debug] Invoking downloader on 'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/88b0e4-b03b3c95/vf_b03b3c95_aab2d8c5-3f73-41d1-95a7-26f1ff871eed.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1561670493&e=1561713693&h=1faffa102329694a62f4dc43194ab426'
[dashsegments] Total fragments: 892
[download] Destination: Peaky Blinders, Series 1, Episode 1.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download]   0.3% of ~1.21GiB at 142.46KiB/s ETA 01:09:33
`

**Comment by Carlz10** [comment]
@darthhaggis hopefully this is working for you now again also. I actually tried to resume a partially downloaded file when it first stopped working; initially with the 'no video formats found' error, which was then replaced by a 503 a day or two later.
Guessing something may have changed on the BBC site.
