### ISSUE TITLE
Youtube age-restricted video with disabled embeds won't download

### ISSUE THREAD

**Issue by TomArrow** [ytdl-org/youtube-dl#21691]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=I7gtoLmHd5w', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92574-g72b047a7a7, ffprobe N-92574-g72b047a7a7
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] I7gtoLmHd5w: Downloading webpage
[youtube] I7gtoLmHd5w: Downloading embed webpage
[youtube] I7gtoLmHd5w: Refetching age-gated info webpage
ERROR: Content Warning
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\youtube.py", line 2097, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
--



```

## Description

I can't download this video: https://www.youtube.com/watch?v=I7gtoLmHd5w

It's age-restricted and embeds are disabled (checked by changing URL with the /embed/ trick). 

I tried both without and with the --username and --password options. I am using the most up to date version released.

Getting the error noted in verbose log.

**Comment by stickbear2015** [comment]
@dstftw dstftw
IF your going to close an issue, please provide context for the reason you closed it, this includes providing issue numbers to what you perceive are duplicate issues. With over 21600 issues their's a lot and people MAY NOT BE able to find the same issues that you find that you consider duplicate issues OF OPENED issues.
Thank you.

**Comment by TomArrow** [comment]
@dstftw Yeah this isn't helpful at all, can you please reference the issue that you think this is a duplicate of? I couldn't find it.

**Comment by bitraid** [comment]
I found two similar issues (#15184, #17216) on the first page of my search (took me literally no more than 15 seconds). I wonder why so many people find it so hard to discover what they are looking for. BTW have you tried `--cookies` ?

**Comment by betathetatau** [comment]
@TomArrow Issue #11270 appears to be the root of the username/login issue.  Also @bitraid's suggestion works.  Get https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ and export your current cookies with it to a cookies.txt file  (FWIW: I had to restart Firefox before this addon's toolbar button would actually work).  Then add "--cookies c:\your_path_here\cookies.txt" to your youtube-dl command line.

@dstftw youtube-dl can be the reason people come to Github for the first time. I wonder if to cut down on duplicates (and therefore your fatigue factor), you should change this text in your Checklist from:

[x]  I've searched the bugtracker for similar issues including closed ones

to something that is more instructive for newcomers, like:

[x]  I've searched the bugtracker for similar issues that are open
[x]  I've searched the bugtracker for similar issues that are closed (by changed the default "is:issue is:open" text in the search field to "is:issue is:closed").
Note: some issues may remain open for years due to their evolving natures and complexities. When searching for open or closed issues, please examine all search results going back years. You can also sort your search results by "Recently updated" to find old issues that are still being worked on.
