### ISSUE TITLE
Extractor implementation abandoned

### ISSUE THREAD

**Issue by kevin-hv** [ytdl-org/youtube-dl#22190]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I would like to ask what happened to this extractor implementation: [Mediaklikk extractor](https://github.com/ytdl-org/youtube-dl/pull/17453)

Because as far as I see the developer (with whom I have spoken, who strengthened my belief) has completed all the fixes that were proposed, yet they were not reviewed and the implementation is stuck in that pending-fixes state from September 2018.

Others have also wanted youtube-dl to support this site: [Site support request](https://github.com/ytdl-org/youtube-dl/issues/21431)

Could any of the maintainers follow up on this please? @dstftw, @remitamine 
Thank you in advance.

**Comment by uno20001** [comment]
I would like to get an answer to this question as well. Since there is demand (however small it might be), and the requested changes have been implemented in the aforementioned pull request; I fail to see why it's been open for more than a year and not merged into `master`, or - at least - why there haven't been more requests for change. So please @dstftw and @remitamine, shed some light on the issues preventing the PR from being merged.

**Comment by dstftw** [comment]
Author ignored code review comments.

**Comment by mrx23dot** [comment]
any update?
