### ISSUE TITLE
Why -F not listing all available video formats on Hotstar (for particular TV show, "Siya Ke Ram")?

### ISSUE THREAD

**Issue by dev-ajay** [ytdl-org/youtube-dl#22323]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Q: Why -F is not listing all available video formats on Hotstar (for *PARTICULAR* TV show, "Siya Ke Ram")? It has 1280x720 video also, which was not listed in result of "yotube-dl -F".

take any video link of this show (of any episode):
e.g. "https://www.hotstar.com/tv/siya-ke-ram/s-402/janaks-daughter-sita-arrives/1000076668"

I run below command (On Windows):
youtube-dl -F "https://www.hotstar.com/tv/siya-ke-ram/s-402/janaks-daughter-sita-arrives/1000076668"

I get below result: (It has 1280x720 video also, which was not listed in result.)
[hotstar] 1000076668: Downloading webpage
[hotstar] 1000076668: Downloading JSON metadata
[hotstar] 1000076668: Downloading m3u8 information
[info] Available formats for 1000076668:
format code  extension  resolution note
hls-170      mp4        320x180     170k , avc1.66.30, mp4a.40.2
hls-327      mp4        320x180     327k , avc1.66.30, mp4a.40.2
hls-552      mp4        416x234     552k , avc1.66.30, mp4a.40.2
hls-960      mp4        640x360     960k , avc1.66.30, mp4a.40.2
hls-1470     mp4        720x404    1470k , avc1.66.30, mp4a.40.2 (best)

I know that, It has 1280x720 video also, by using firefox plugin "Video DownloadHelper". "Video DownloadHelper" list 1280x720 video also apart from rest of the results, which I am able to download. But I wish to do it using youtube-dl as it has 326 episodes.

**Comment by Y4shSHD** [comment]
The reason for this is Hotstar changed the way it addresses URL's, example, in this case, if you download the episode of this show, which was before 2018, and not rebroadcasted on TV recently, they're addressed as:
**_Example:_** 
Episode 1- Siya Ke Ram: Public link: https://www.hotstar.com/1000076668
Stream URL (best quality chosen: youtube-dl -f best "https://www.hotstar.com/1000076668"):
https://staragvodweb1-vh.akamaihd.net/i/videos/plus/skr/1/1000076668_,**16,54,106,180,400,800,1300,2000,3000,4500**,_STAR.mp4.csmil/**index_7_av.m3u8**

See that?
the numbers in bold mention the following bitrates (in kbps)
0. 16kbps
1. 54kbps
2. 106kbps
3. 180kbps
4. 400kbps
5. 800kbps
6. 1300kbps
7. 2000kbps (720p video)
8. 3000kbps (900p video)
9. 4500kbps (1080p video)

I've stated with 0 and not 1, because this tells the index to which the player should give.

Hotstar prefers delivering the video in **720p** if not reoptimized for 2018, hence **index_7.av.m3u8**
If you want better, 1080p video: change **index_7.av.m3u8** to **index_9.av.m3u8**, 

try this stream url:
https://staragvodweb1-vh.akamaihd.net/i/videos/plus/skr/1/1000076668_,**16,54,106,180,400,800,1300,2000,3000,4500**,_STAR.mp4.csmil/**index_9_av.m3u8**
