### ISSUE TITLE
[pornhub] HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by astronouth7303** [ytdl-org/youtube-dl#22449]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 % youtube-dl https://www.pornhub.com/model/demora-avarice --verbose
[debug] System config: []
[debug] User config: [u'--xattrs', u'--embed-subs', u'--embed-thumbnail', u'--all-subs', u'--add-metadata']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhub.com/model/demora-avarice', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.16+ (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[PornHubPagedVideoList] model/demora-avarice/videos: Downloading page 1
[download] Downloading playlist: model/demora-avarice/videos
[PornHubPagedVideoList] playlist model/demora-avarice/videos: Collected 29 video ids (downloading 29 of them)
[download] Downloading video 1 of 29
[PornHub] ph5d6e0e3326ddb: Downloading pc webpage
[PornHub] ph5d6e0e3326ddb: Downloading tv webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2229, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

I suspect this is because it's using the newer model user page instead of the classic?

**Comment by MildPanda** [comment]
Guess I'll bump this a bit cause I'm sad it isn't working :(
I'm encountering this error ONLY when ripping from a model instead of an individual video. My error isn't the exact same but since the main "unable to download webpage: HTTP error 404" I'll bump this and post my log here too cause I'd love for this to be looked into, thanks!

`ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
`
I know pornhub has been abusive towards youtube-dl but hopefully they chill out and let us keep downloading the videos we enjoy.

**Comment by themamodoking** [comment]
If you just need the free videos "youtube-dl https://www.pornhub.com/model/demora-avarice/videos/upload" works for me.

**Comment by github-userx** [comment]
I just wish we could get 1080p download for free videos. So many pornhub models now have their free videos in 1080p but ytdl only gets 720p :(

**Comment by github-userx** [comment]
Paging @ajj8 and @F30529D0-F310-40EB-A118-F2F835441610

**Comment by ajj8** [comment]
This isn't a problem with the models page but rather how the videos are processed, the extractor can't find any URLs on the paid PC page and it seems that paid TV pages give a 404. At any rate, the extractor should be updated to raise an error or skip the video if a locked player is detected, though I'm not sure how to properly implement that. Maybe something to do with the player div id being "lockedPlayer" when it's paid.
