### ISSUE TITLE
Dropbox password-protected folder?

### ISSUE THREAD

**Issue by astronouth7303** [ytdl-org/youtube-dl#22502]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Dropbox has the option for password-protected folders--"public" links, but you need to put in a password to access the contents.

How do I specify that?

(To be clear, I'm looking at a folder with downloads disabled.)

**Comment by remitamine** [comment]
> How do I specify that?

```
--video-password PASSWORD        Video password (vimeo, smotri, youku)
```
however, the option won't work for DropBox because both DropBox folders and password-protected are not yet supported.
for individual password-protected videos, using cookies might help.
anyway in order to add support, you can fill a proper support request(including the URL of a page that you're willing to share its password).
