### ISSUE TITLE
Error parsing Discovery Network video

### ISSUE THREAD

**Issue by gremlin-58** [ytdl-org/youtube-dl#22854]
This il the verbose log:

$ youtube-dl --no-overwrites -o "%(title)s.%(ext)s" -f "best[height=360]" --verbose "https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-18-del-25-ottobre-2019"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-overwrites', u'-o', u'%(title)s.%(ext)s', u'-f', u'best[height=360]', u'--verbose', u'https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-18-del-25-ottobre-2019']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.13 (CPython) - Linux-4.19.0-1-amd64-x86_64-with-MX-18.3-Continuum
[debug] exe versions: avconv 3.3.4-1mx17, avprobe 3.3.4-1mx17, ffmpeg 3.3.4-1mx17, ffprobe 3.3.4-1mx17
[debug] Proxy map: {}
[debug] Using fake IP 79.44.248.181 (IT) as X-Forwarded-For.
[DPlayIt] stagione-3-episodio-18-del-25-ottobre-2019: Downloading webpage
[DPlayIt] stagione-3-episodio-18-del-25-ottobre-2019: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 333, in _real_extract
    error = info['errors'][0]
KeyError: u'errors'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ancucchi** [comment]
I have the same trouble:
`$ youtube-dl -v https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-17-del-18-ottobre-2019/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-17-del-18-ottobre-2019/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-65-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[debug] Using fake IP 79.29.22.50 (IT) as X-Forwarded-For.
[DPlayIt] stagione-3-episodio-17-del-18-ottobre-2019: Downloading webpage
[DPlayIt] stagione-3-episodio-17-del-18-ottobre-2019: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 333, in _real_extract
    error = info['errors'][0]
KeyError: u'errors'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
