### ISSUE TITLE
Mixer:vod ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by nixtar** [ytdl-org/youtube-dl#22871]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Nick>youtube-dl "https://mixer.com/shroud?vod=h3nT6aCznEezn6d4Em33aw" --verbose
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'C:\\ffmpeg\\ffmpeg-20180211-8b154cb-win64-static\\bin']
[debug] Custom config: []
[debug] Command-line args: ['https://mixer.com/shroud?vod=h3nT6aCznEezn6d4Em33aw', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89994-g8b154cb3e9, ffprobe N-89994-g8b154cb3e9
[debug] Proxy map: {}
[Mixer:vod] h3nT6aCznEezn6d4Em33aw: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

Get the above error when trying to download VODs from mixer.com.
Example vod: https://mixer.com/shroud?vod=h3nT6aCznEezn6d4Em33aw

**Comment by DanDog419** [comment]
Hi I am new to github so please excuse my poor etiquette. I too was trying to download shrouds first vod on mixer. I also previously have had issues downloading videos and after some googling and reading around on youtube-dl issues, I found the "" quotes trick. What I learnt from that first experience trouble shooting was to look around the webpage using the browsers inspector. This is the method I used previously to fix my issue of downloading videos from roosterteeth.com. The visual tool that allows to select elements and by hovering over the video playing and going to to video player src= attribute and finding the akamaized cdn url. Since the akamaized src attribute had a key pair that had to be enclosed in quotes to be accepted as a good valid url to youtube-dl. I tried the same thing on the shroud first mixer.com vod and there wasn't src attribue that would be accepted as a download url on youtube-dl. So I digged deeper using the network monitor in the browser. Using that I could see each video .ts segment being downloaded on mixer. I snooped around more and found this url https://mixer.com/api/v2/vods/h3nT6aCznEezn6d4Em33aw once I visited this I got back some json and in that json there was an url with the locatorType: Dowload "https://vodcontent-5001.xboxlive.com/channel-103551540-public/e9d37987-b3a0-479c-b39f-a778126df76b/source.mp4?__gda__=2202937527_37659abb30a3a018a6f7612c8520822b" I used that url on youtube-dl and it worked like a charm. If any developer wants to use this  info and fix the mixer download and roosterteeth download function in youtube-dl that would be much appreciated. If you have any more questions feel free to message me. I apologize for being so rambly I am new to github any constructive criticisms would be apprenticed. Thanks
