### ISSUE TITLE
720p ABC iView

### ISSUE THREAD

**Issue by gitAuss1e** [ytdl-org/youtube-dl#22907]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

ABC iView has recently started streaming a lot of their stuff in 720p. Youtube-dl doesn't pick up the 720p videos and only downloads 540p. If you could get 720p ABC iView downloading on youtube-dl that would be awesome! Thanks!

**Comment by Pher0ah** [comment]
This issue is still not fixed; I am having the same issue on the latest version 2020.03.24

Please Note: You will need to appear coming from Australia for the video to play.

URL of Video:
https://iview.abc.net.au/show/stateless/series/1/video/DR1820S001S00

Extracted MPD File:
https://iview-vod.akamaized.net/prod/dr1/DR1820S001S00MA1D1/20200220162328/mpegdash/720.mpd

Output of Command:
PS 03/25/2020 09:24:48> C:\Portable\Downloaders\YT\youtube-dl.exe --verbose --continue --format bestvideo+bestaudio "https://iview-vod.akamaized.net/prod/dr1/DR1820S001S00MA1D1/20200220162328/mpegdash/720.mpd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--continue', '--format', 'bestvideo+bestaudio', 'https://iview-vod.akamaized.net/prod/dr1/DR1820S001S00MA1D1/20200220162328/mpegdash/720.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-03-1c15111, ffprobe git-2020-02-03-1c15111
[debug] Proxy map: {}
[generic] 720: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 720: Downloading webpage
[generic] 720: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 2397, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
