### ISSUE TITLE
How to download all videos form user's twitch channel?

### ISSUE THREAD

**Issue by shadowzoom** [ytdl-org/youtube-dl#22979]
How to download all videos form user's twitch channel?
youtube-dl "https://www.twitch.tv/username/videos?filter=all&sort=time" -f best is not working

**Comment by ualnwe** [comment]
Since the new web UI design, most of the URLs changed to use `?filter=xxx`

As a work around until the Twitch extractor is updated, using `/all` still works.
E.g. `https://www.twitch.tv/username/videos/all`

Side note, the current parsing will interpret that `?filter=xxx` url as wanting to download the user's live stream, as if you passed `https://www.twitch.tv/username`, which may download partial streams if they’re live when you run it

**Comment by Ste-etS** [comment]
For anybody reading this in the future, the `/all` workaround no longer functions. The latest version of Twitch's API now requires a UserID instead of a channel name.
