### ISSUE TITLE
Get playlist title / name only. without downloading files

### ISSUE THREAD

**Issue by BlisteringSyko** [ytdl-org/youtube-dl#23442]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, 

I'm trying to get just the name of a playlist in a bash script without downloading the files. I've gone through the manual multiple times and put forth my best google foo.

Currently I'm downloading an entire playlist into a folder with a random name, then zipping it up before offering it to my users. Id just like to get that zip file named after the playlist and not jibberish. Ive tried to awk and sed with various options with no luck.

youtube-dl 2019.11.28
Ubuntu 19.04

Thanks.

**Comment by dstftw** [comment]
```
-J, --dump-single-json           Simulate, quiet but print JSON information
                                 for each command-line argument. If the URL
                                 refers to a playlist, dump the whole
                                 playlist information in a single line.
```

**Comment by BlisteringSyko** [comment]
Thanks. Did the trick using jq to get the value of title.

`#! /bin/bash`
`export LC_ALL=en_US.UTF-8`
`name=$(youtube-dl --no-warnings --dump-single-json $1 | jq -r '.title')`
`echo $name`

**Comment by dannielsoares** [comment]
I hope this does't hurt netiquette. Just in case someone stumbles with this thread while looking for the same solution, as I did a little while ago, maybe they'd rather adopt this version of the solution or something more like it:

 `wget -qO- $u |  perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si'`

where "$u" is the youtube playlist URL (the entire url, not the url's ID), but can really be any  URL of a more or less standard website, I'd guess, it will give really the page title, that happens to include the playlist title in such cases, but also the ending with " - Youtube." I didn't came up with it, I had found it looking for something else a while ago, maybe titles of videos youtube-dl doesn't get, but I don't know.

This solution seems to work considerably faster than the one with youtube-dl or yt-dlp, that's why I'm putting it on the table. Whether it's youtube-dl or the jq thing that's slow, or somehow something else, I don't know.

**Comment by terminated-star** [comment]
Adding `--flat-playlist` seems to considerably increase the speed.

**Comment by PacoH** [comment]
I find all these methods unintuitive, messy, or not working fully.

e.g.,

	u=https://www.youtube.com/playlist?list=PLgFjl6LxD3nuffjHcUnxChy7gdkW5zL5c
	youtube-dl --no-warnings --dump-single-json --flat-playlist --playlist-end 1 "$u" | jq -r '.title'
	-bash: jq: command not found

	wget -qO- $u | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si'
	DIRECTOR&#39;S CUT (OUR FAVORITES) - YouTube

What I finally got to work:
	`t="$(youtube-dl -o "%(playlist_title)s" --flat-playlist --playlist-end 1 --skip-download "$u" | tail -n 1 | awk -F": " '{print $NF}')"; echo "$t"`
	`DIRECTOR'S CUT (OUR FAVORITES)`

I had to get the last line of the output and separate out the title.

	youtube-dl -o "%(playlist_title)s" --flat-playlist --playlist-end 1 --skip-download "$u"
	[youtube:tab] PLgFjl6LxD3nuffjHcUnxChy7gdkW5zL5c: Downloading webpage
	[youtube:tab] PLgFjl6LxD3nuffjHcUnxChy7gdkW5zL5c: Redownloading playlist API JSON with unavailable videos
	[download] Downloading playlist: DIRECTOR'S CUT (OUR FAVORITES)
	[youtube:tab] Playlist DIRECTOR'S CUT (OUR FAVORITES): Downloading 1 videos of 9
	[download] Downloading video 1 of 1
	[download] Finished downloading playlist: DIRECTOR'S CUT (OUR FAVORITES)

There is probably a better way but I could not find it.

**Comment by rautamiekka** [comment]
> ```
> u=https://www.youtube.com/playlist?list=PLgFjl6LxD3nuffjHcUnxChy7gdkW5zL5c
> youtube-dl --no-warnings --dump-single-json --flat-playlist --playlist-end 1 "$u" | jq -r '.title'
> ```

Unless you reuse the URL, no point in saving it into a var, just put it inside single quotes in place of `"$u"` just like you did with `'.title'`.

> `-bash: jq: command not found`

Just install it.
