### ISSUE TITLE
ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by Aphexus** [ytdl-org/youtube-dl#23468]
Happening on a lot of videos. Also does not display video url so I have no idea which videos it is.

**Comment by Aphexus** [comment]
Also it doesn't seem to be reporting a proper error code for use in batch files. I do have --ignore-errors set but that is to ignore other errors. I'd like to know which videos are not downloaded.

**Comment by caph1993** [comment]
It has happened many times to me as well. It would be nice if the actual cause of the error is found, because the exception says `ERROR: This video is unavailable.` but the videos are indeed available through the browser, even in incognito mode (no login).

These are some examples that can be used to reproduce the error. Try downloading any of the youtube ids below.

```
EzqPPbf1qUk
2vbeNshimz8
nuajmL5Nx8g
vqcjoseWAi4
T13L4UtV_pI
```
