### ISSUE TITLE
https://mubi.com/

### ISSUE THREAD

**Issue by girod2033** [ytdl-org/youtube-dl#23899]
## Checklist

- [ ] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2020.01.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://mubi.com/films/tales-of-ginza/
- Single video: https://mubi.com/films/tales-of-ginza/
- Playlist: ...

## Description

Hi!
Please do support so that you can download subtitles.
youtube-dl_2020.01.24 -F --cookies "c:\130\cookies (2).txt" "https
://germany-edge15.mubicdn.net/stream/99f5b127c2018f41efc124e2af8b1041/5e329fa7/m
ubi-cloud-films/220573/tales-of-ginza_ja_xx_1440x1080_50000_ea7677/1311_v3/drm_p
laylist.ism/playlist.mpd"
[generic] playlist: Requesting header
WARNING: Falling back on generic information extractor.
[generic] playlist: Downloading webpage
[generic] playlist: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.

mpd: https://pastebin.com/eiGVNVPi

Subtitles are not encrypted.

**Comment by dia3olik** [comment]
mubi support would be great!

**Comment by LucaNonato** [comment]
Indeed! I have a 90 day trial account, if you need help, URLs or anything (But the credentials :])

**Comment by ijbh** [comment]
So it's not possible to do the netrc code on Mubi?

**Comment by ijbh** [comment]
It doesn't seem Mubi is included among the extractor files. Does that mean youtube-dl wouldn't work even if I bought access to the site?

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by gamer191** [comment]
> Issue should be closed, URL is dead

Why? The website's not dead

**Comment by 89z** [comment]
@gamer191 the site support request template requires at least one valid example URL. If you have one, please provide it. Otherwise issue should be closed.

**Comment by gamer191** [comment]
@89z for a start, the example URL isn't dead it's probably just geoblocked for you

**Comment by 89z** [comment]
> This film is not currently playing on MUBI, but many other great films are. See what’s [now showing >](https://mubi.com/showing)

**Comment by gamer191-2** [comment]
> > This film is not currently playing on MUBI, but many other great films are. See what’s [now showing >](https://mubi.com/showing)

In that case, just pick a random url from https://mubi.com/showing and use that as the example URL

**Comment by gamer191** [comment]
> > This film is not currently playing on MUBI, but many other great films are. See what’s [now showing >](https://mubi.com/showing)

In that case, just pick a random url from https://mubi.com/showing and use that as the example URL

**Comment by 89z** [comment]
@gamer191 we are asking YOU to do that. Otherwise the issue should be closed

**Comment by gamer191** [comment]
@89z
1. you are not a maintainer
2. I don't actually care whether this issue gets fixed, I just don't want Youtube-DL to set a ridiculous precedent that site support requests get closed the second the video gets taken down, even if there are other videos easily accessible on the website

**Comment by 89z** [comment]
> 1. you are not a maintainer

@gamer191 well, that didn't [take long][1]...

> 2. I don't actually care whether this issue gets fixed, I just don't want Youtube-DL to set a ridiculous precedent that site support requests get closed the second the video gets taken down, even if there are other videos easily accessible on the website

Sorry but that ship [has sailed][2] already...

[1]://wikipedia.org/wiki/Argument_from_authority
[2]://github.com/ytdl-org/youtube-dl/issues/28587

**Comment by gamer191-2** [comment]
> Sorry but that ship [has sailed](//github.com/ytdl-org/youtube-dl/issues/28587) already...

If you actually read that issue, you'd see that the reason it was closed is because that website is now DRM protected

**Comment by gamer191** [comment]
> Sorry but that ship [has sailed](//github.com/ytdl-org/youtube-dl/issues/28587) already...

If you actually read that issue, you'd see that the reason it was closed is because that website is now DRM protected

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by gamer191** [comment]
> Issue should be closed, URL is dead

I said to read the issue, not just your comment

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
@gamer191 by your own admission [1], youre not arguing in good faith. So why should I?


1. https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116138684

**Comment by gamer191** [comment]
> @gamer191 by your own admission [1], youre not arguing in good faith.

I don't care about this specific site, correct. I do, however, care about the precedent this sets. There's nothing wrong with that, just like how you argued for hours the other day that mrdeepfakes should get added to yt-dlp, but then afterwards said:
> with all due respect, I only looked into this because I didn't like that [@gamer191](https://github.com/gamer191) and pukkandan were trying to impose their morals on this project

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
> I don't care about this specific site, correct. I do, however, care about the precedent this sets. There's nothing wrong with that, just like how you argued for hours the other day that

@gamer191 the difference between you and me, is I am actually able to provide contributions to the project:

https://github.com/ytdl-org/youtube-dl/issues/30764#issuecomment-1114055990

while to date, youve provided nothing but troll and shitposting.

**Comment by gamer191** [comment]
I happen to have this entire discussion archived. Here you go:
>Issue should be closed, URL is dead

Why? The website's not dead
>[@gamer191](https://github.com/gamer191) the site support request template requires at least one valid example URL. If you have one, please provide it. Otherwise issue should be closed.

@89z for a start, the example URL isn't dead, it's probably just geoblocked for you
>>This film is not currently playing on MUBI, but many other great films are. See what’s [now showing >](https://mubi.com/showing)

In that case, just pick a random url from https://mubi.com/showing and use that as the example URL
>[@gamer191](https://github.com/gamer191) we are asking YOU to do that. Otherwise the issue should be closed

1. you are not a maintainer
2. I don't actually care whether this issue gets fixed, I just don't want Youtube-DL to set a ridiculous precedent that site support requests get closed the second the video gets taken down, even if there are other videos easily accessible on the website
>>you are not a maintainer

>[@gamer191](https://github.com/gamer191) well, that didn't [take long](https://wikipedia.org/wiki/Argument_from_authority)...

>>I don't actually care whether this issue gets fixed, I just don't want Youtube-DL to set a ridiculous precedent that site support requests get closed the second the video gets taken down, even if there are other videos easily accessible on the website

>Sorry but that ship [has sailed](https://github.com/ytdl-org/youtube-dl/issues/28587) already...

If you actually read that issue, you'd see that the reason it was closed is because that website is now DRM protected
>Issue should be closed, URL is dead

I said to read the issue, not just your comment
>Issue should be closed, URL is dead

@89z why did you delete all your previous comments?
>Issue should be closed, URL is dead

@89z are you serious? Just deleting all your comments, deleting a (somewhat) productive conversation, and then ensuring your opinion stays at the bottom of the thread???
>Issue should be closed, URL is dead



> @gamer191 by your own admission [1], you're not arguing in good faith:
> 
> > I don't actually care whether this issue gets fixed
> 
> So why should I?
> 
> 1. https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116138684

I don't care about this specific site, correct. I do, however, care about the precedent this sets. There's nothing wrong with that, just like how you argued for hours the other day that mrdeepfakes should get added to yt-dlp, but then afterwards said:
"with all due respect, I only looked into this because I didn't like that [@gamer191](https://github.com/gamer191) and pukkandan were trying to impose their morals on this project"
> Issue should be closed, URL is dead

> @gamer191 the difference between you and me, is I am actually able to provide contributions to the project:
> 
> [#30764 (comment)](https://github.com/ytdl-org/youtube-dl/issues/30764#issuecomment-1114055990)
> 
> while to date, you've provided nothing but troll and shitposting.

**Comment by gamer191** [comment]
> while to date, you've provided nothing but troll and shitposting.

Make whatever accusations you want 🤣
Was this also shitposting? https://github.com/ytdl-org/youtube-dl/issues/30756
How about this? https://github.com/ytdl-org/youtube-dl/issues/30911#issuecomment-1116093505

**Comment by 89z** [comment]
> I happen to have this entire discussion archived.

If you think reposting stuff that I deleted is going to bother me, you're going to be disappointed. I deleted the comments for a reason. If you want to disrespect that reason, that's your choice. Sorry to disappoint, but you aren't the first person to do this.

**Comment by gamer191** [comment]
> If you think reposting stuff that I deleted is going to bother me, you're going to be disappointed. I deleted the comments for a reason. If you want to disrespect that reason, that's your choice. Sorry to disappoint, but you aren't the first person to do this.

Sorry, I should have asked that reason, I will delete my archive. I assumed you were just trying to stay on topic, so I figured it would help to consolidate it into one message. May I ask what that reason is? Just curious

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
> May I ask what that reason is?

@gamer191 may I ask you to delete all your comments, and never comment on this project again? Just curious

**Comment by gamer191** [comment]
@89z Actually I changed my mind, I'm no longer "just curious", because you are clearly just trying to block out my opinion, by making all my messages about it meaningless. I will post the archive, unless you state what that reason is or which messages you want me to redact. Otherwise all you are doing is trying to block out my opinion. Lots of public forums don't even allow you to delete messages if someone has replied. I wish this forum was the same!

**Comment by gamer191** [comment]
> @gamer191 may I ask you to delete all your comments, and never comment on this project again? Just curious

Sure, but I will respond with a no.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by gamer191** [comment]
> Issue should be closed, URL is dead

So there's no reason. Very well, I'm sending the archive now:

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by 89z** [comment]
> Actually I changed my mind, I'm no longer "just curious", because you are clearly just trying to block out my opinion, by making all my messages about it meaningless. 

@gamer191 you never had an opinion. By your own admission you are just trolling:

> I don't actually care whether this issue gets fixed

https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116138684

> I don't care about this specific site

https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116213739

> I will post the archive, unless you state what that reason is or which messages you want me to redact.

Sorry, I dont respond to blackmail.

**Comment by gamer191** [comment]
> @gamer191 you never had an opinion. By your own admission you are just trolling:

refer to this:
> I do, however, care about the precedent this sets

https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116213739
> Sorry, I dont respond to blackmail.

It's not blackmail. I'm just sick of you trolling and then deleting your messages. If you have a specific reason this time, go ahead, but I don't believe you do

**Comment by gamer191** [comment]
You know what, stuff this, I'm not going to bother sharing an archive, because it's to much effort and you clearly very much don't want it. Just know that in future, I will always quote your entire message in my reply, so your days of trolling are over!

**Comment by 89z** [comment]
> so your days of trolling are over!

@gamer191 The difference between you and me, is I am able to actually contribute to the project:

https://github.com/ytdl-org/youtube-dl/issues/30764#issuecomment-1114055990

while to date you have done nothing but derail threads:

> I don't actually care whether this issue gets fixed

https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116138684

> I don't care about this specific site

https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116213739

> It's not blackmail.

> Blackmail is an act of coercion using the threat of revealing or publicizing either substantially true or false information about a person or people unless certain demands are met.

Seems to fit pretty well to me.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by gamer191** [comment]
> @gamer191 The difference between you and me, is I am able to actually contribute to the project:

See here https://github.com/ytdl-org/youtube-dl/issues/23899#issuecomment-1116229900
> Seems to fit pretty well to me:
> 
> > Blackmail is an act of coercion using the threat of revealing or publicizing either substantially true or false information about a person or people unless certain demands are met.

1. it's not private information about you, it's your posts in a public forum
2. I don't see asking someone to demonstrate why you publishing something will harm them as a form of blackmail. I was actually just trying to give you an opportunity to explain why you didn't want me to upload an archive of your comments in this issue, because you told me that you had a reason, and so I had voluntarily deleted my archive in response. I'm sorry if you feel it was blackmail, I won't do it again. I have already said I won't upload the archive, can we please stop talking about this and put it behind us.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by gamer191** [comment]
> I would strongly suggest you rethink attempting to blackmail someone in a public forum

I have already apologised. Also, I don't see how it was blackmail:
> [Blackmail] is normally carried out for personal gain, most commonly of position, money, or property.[[1]](https://en.wikipedia.org/wiki/Blackmail#cite_note-merriam-webster-1)[[3]](https://en.wikipedia.org/wiki/Blackmail#cite_note-merriam-webster.com-3)[[4]](https://en.wikipedia.org/wiki/Blackmail#cite_note-Burton-4)[[5]](https://en.wikipedia.org/wiki/Blackmail#cite_note-Newton-5) It is also used, sometimes by state agencies, to exert influence

I was not trying to gain any of those, I was simply trying to give you a chance to explain why you were deleting all your posts (which I consider trolling). I don't believe I would have gotten any benefit from finding out why you didn't want me reposting your deleted messages, I was just trying to give you a chance to explain why I shouldn't repost your messages. I'm very sorry anyway. Perhaps the reason is something personal, I don't know. When I sent the message I thought I was doing a good thing, by giving you a chance to stop me from reposting your messages (which I wouldn't have considered wrong for me to do), if you just explained why you didn't want me to. I can see now that it was potentially hurtful, and definitely the wrong thing to do, so I'm sorry. Please can this be over, I'm truly sorry, I meant no harm

**Comment by 89z** [comment]
> Please can this be over, I'm truly sorry, I meant no harm

@gamer191 honestly I don't believe you. But if you are sincere, then all I ask is that you remove all your comments here. Every single comments you've posted, is off topic. If you wish to discuss the rules regarding what should and should not be closed, make a new issue for that. Dont hijack and existing issue (like you've done before) for your own reasons.

If you have a valid current link for Mubi site, then please post it. Otherwise, it seems you have no business in this thread.

**Comment by 89z** [comment]
Issue should be closed, URL is dead.

**Comment by gamer191** [comment]
Here's a new URL:
https://mubi.com/films/tales-of-ginza/trailer

**Comment by 89z** [comment]
@gamer191 that's just a trailer. According to the original post, it seems the OP is interested in full videos.

**Comment by gamer191** [comment]
> @gamer191 that's just a trailer. According to the original post, it seems the OP is interested in full videos.

Good point
On a different note, I just noticed that according to the original post:
> Subtitles are not encrypted

which implies that the videos are DRM protected. If that's the case, this issue should be closed, unless someone can find a way to get the manifests DRM free.

Alternatively, perhaps `--ignore-no-formats-error` could be backported from yt-dlp, but that probably belongs in it's own issue

**Comment by gamer191** [comment]
oh, I forgot to share a link to a full video, here you go: https://mubi.com/films/in-the-aisles

**Comment by 89z** [comment]
> which implies that the videos are DRM protected.

Key word here is "implies", rather than "guarantees".

It seems that even if you sign up for the free trial, upon canceling your ability to watch ends immediately. So someone will need to provide an account in order for work to continue.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/16091

**Comment by 89z** [comment]
I think I am able to download these now, but I don't have an account. If someone has an account I can borrow, I can continue work on this.

**Comment by wokawoka** [comment]
@89z sounds great. Unfortunately I don't have anymore an active account to borrow atm, but I guess you could open a 30 day free trial account from here https://mubi.com/promos/tokyo.
I hope it helps.

**Comment by 89z** [comment]
Sorry, that doesn't work. I tried that before, and again just now. What happen is, as soon as you cancel, you lose the ability to watch. I need to cancel the free trial immediately, so that I don't forget. But doing that kills playback immediately. So unless someone can share an account, I cannot share my solution.

**Comment by wokawoka** [comment]
there was a promotion going for 4 months for just 4€ but unfortunately it did expire a couple of days ago ...
Personally I woulg go for the1 month trial and set an alarm in 25 days or so.

**Comment by 89z** [comment]
No, I must cancel immediately. I do not want to take even the smallest risk of forgetting and have to pay a charge. So unless someone can lend an account, then I cannot share my solution. Other sites offer short free trials, and even if you cancel right away, you can use the site until trial expires. Because Mubi stops the trial immediately, I need someone to share an account.

**Comment by 3052** [comment]
sorry for the extremely long delay, but this is done now:

~~~
msg=GET URL=https://api.mubi.com/v3/films/in-the-aisles
msg=POST URL=https://api.mubi.com/v3/films/191441/viewing
msg=GET URL=https://api.mubi.com/v3/films/191441/viewing/secure_url
msg=GET URL=https://germany-edge3.mubicdn.net/stream/6e5f75dd955f3edfbc76c058c5f42d55/65d71066/cd3c0d3c/mubi-films/191441/in-the-aisles_deu_zxx_1800x1080_50000_mezz38714/5e715cb8c8/drm_playlist.0ea046c87e.ism/default/ver1.AVC1.2160p.mpd
msg=POST URL=https://lic.drmtoday.com/license-proxy-widevine/cenc/
msg=GET URL="https://germany-edge3.mubicdn.net/stream/6e5f75dd955f3edfbc76c058c5f42d55/65d71066/cd3c0d3c/mubi-films/191441/in-the-aisles_deu_zxx_1800x1080_50000_mezz38714/5e715cb8c8/drm_playlist.0ea046c87e.ism/default/drm_playlist.0ea046c87e-video=5500054.dash"
msg="0.14 %" size="442.72 kilobyte" rate="394.79 kilobyte/s"
~~~

I dont think YouTube-DL want to support the security that protects this content, so you would need to check my repo instead

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2743

**Comment by 3052** [comment]
https://github.com/3052/media/tree/main/mubi
