### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by mkranthikmr** [ytdl-org/youtube-dl#24612]
Unable to download videos from Pluralsight. 

youtube-dl version: 2020.03.24

ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by ph-py** [comment]
Correct this issue by downloading the cookies from Pluralsight

1 - Download this plugin for google chrome [cookiestxt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)
2 - Access Pluralsight like a normal user and navigate to the course you want to download
3 - After navigate, click on the cookiestxt button and "**click here**" blue link to download the cookies.txt file
4 - Add your username, password, user-agent, sleep-interval, cookies and subtitles (optional) to your download
`youtube-dl --username "xxxx@mail.com" --password "xxxx" --verbose --sleep-interval 120 "https://app.pluralsight.com/library/courses/course-of-your-choice/table-of-contents" --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" --cookies cookies.txt --sub-lang en --sub-format srt --write-sub`
5 - Users of distros like ubuntu related problems downloading this way, I have made it all in windows 10
6 - **Try Harder!**

**Comment by askar05** [comment]
I have same Problem:
I see your comment on "Pluralsight JSON download problem #24622"

./../../youtube-dl --username "working@email" --password "workingPassword" --min-sleep-interval 120 --max-sleep-interval 200 --all-subs --verbose --restrict-filenames https://app.pluralsight.com/library/courses/java-fundamentals-language/table-of-contents --playlist-start 1 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--min-sleep-interval', u'120', u'--max-sleep-interval', u'200', u'--all-subs', u'--verbose', u'--restrict-filenames', u'https://app.pluralsight.com/library/courses/java-fundamentals-language/table-of-contents', u'--playlist-start', u'1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] java-fundamentals-language: Downloading JSON metadata
[download] Downloading playlist: Java Fundamentals: The Java Language
[pluralsight:course] playlist Java Fundamentals: The Java Language: Collected 131 video ids (downloading 131 of them)
[download] Downloading video 1 of 131
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./../../youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./../../youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by ph-py** [comment]
Correct this issue by downloading the cookies from Pluralsight

1 - Download this plugin for google chrome [cookiestxt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)
2 - Access Pluralsight like a normal user and navigate to the course you want to download
3 - After navigate, click on the **cookiestxt** button and "**click here**" blue link to download the cookies.txt file
4 - Add your username, password, user-agent, sleep-interval, cookie and subtitles (optional) to your download
`youtube-dl --username "xxxx@mail.com" --password "xxxxxx" --verbose --min-sleep-interval 120 --max-sleep-interval 240 "https://app.pluralsight.com/library/courses/course-of-your-choice/table-of-contents" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" --cookies cookies.txt --sub-lang en --sub-format srt --write-sub`
5 - Users of distros like ubuntu related problems downloading this way, I have made it all in windows 10
6 - Watch out to not be banned by Pluralsight
7 - Try Harder!

**Comment by leobastiani** [comment]
> Correct this issue by downloading the cookies from Pluralsight
> 
> 1 - Download this plugin for google chrome [cookiestxt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)
> 2 - Access Pluralsight like a normal user and navigate to the course you want to download
> 3 - After navigate, click on the **cookiestxt** button and "**click here**" blue link to download the cookies.txt file
> 4 - Add your username, password, user-agent, sleep-interval, cookie and subtitles (optional) to your download
> `youtube-dl --username "xxxx@mail.com" --password "xxxxxx" --verbose --min-sleep-interval 120 --max-sleep-interval 240 "https://app.pluralsight.com/library/courses/course-of-your-choice/table-of-contents" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" --cookies cookies.txt --sub-lang en --sub-format srt --write-sub`
> 5 - Users of distros like ubuntu reported problems downloading this way, I have made it all in windows 10
> 6 - Watch out to not be banned by Pluralsight
> 7 - Try Harder!

thank you!
