### ISSUE TITLE
No longer working on iview.abc.net.au

### ISSUE THREAD

**Issue by recklessinoz** [ytdl-org/youtube-dl#24680]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
C:\Users\xxxxx\Desktop>youtube-dl -x https://iview.abc.net.au/show/bluey/series/0/video/CH1903Q023S00 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', 'https://iview.abc.net.au/show/bluey/series/0/video/CH1903Q023S00', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 1.159.158.165 (AU) as X-Forwarded-For.
[abc.net.au:iview] CH1903Q023S00: Downloading JSON metadata
[abc.net.au:iview] CH1903Q023S00: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

The 'share' link on iview.abc.net.au used to be sufficient for you8tube-dl, but a few days ago this stopped working. I assume the website has changed it's structure, but I have no idea how to untangle it

**Comment by ilike2burnthing** [comment]
Working here ok. Can you play the videos in browser?

**Comment by recklessinoz** [comment]
> Working here ok. Can you play the videos in browser?

yep, videos play fine. 
this is an example url:
https://iview.abc.net.au/show/bluey/series/0/video/CH1903Q012S00

**Comment by ilike2burnthing** [comment]
Yea, I used the one in your log, no issues. Tried that one too, downloaded fine. Was also able to access and download other series on the site.

I can get a `403 Forbidden` error if I extract the m3u8 URL using `youtube-dl -g` and then try to feed it to ffmpeg, but not a `404 Not Found`.

Only suggestions I can think of at the moment are:
- Go to `C:\Users\USERNAME\.cache\youtube-dl` and delete anything there (I don't have anything for ABC, but just in case you do)
- Make sure you're not using a VPN or proxy (though it shouldn't matter because X-Forwarded-For is used)
- Clear out your build archive in AppData\Roaming and start from scratch (fresh youtube-dl, fresh ffmpeg, fresh GUI if you use it)
- Update Python - I don't have it installed at all, so that's another option as well, removing it if you don't otherwise need it - my money would be on Python being the problem, given that it is the source of the error in your log

If none of that works, and you're posting because this is a _'running out of ways to entertain the kid(s) during the COVID lockdown'_ situation, then let me know 😉

**Comment by recklessinoz** [comment]
Thanks so much for looking into this!
I tried a fresh install using my work PC and everything downloaded fine. I'll have to go through my own computer, clear it out and start again.

Also it's not specifically an 'entertain the kids' situation, but I definitely want to hang onto these eps once they're gone from iview.

Thanks again
