### ISSUE TITLE
unable to download subtitles from youtube.com

### ISSUE THREAD

**Issue by starenka** [ytdl-org/youtube-dl#24705]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
% youtube-dl --list-subs 'https://www.youtube.com/embed/3UawxEP33FE?feature=oembed' --verbose --print-traffic
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--list-subs', u'https://www.youtube.com/embed/3UawxEP33FE?feature=oembed', u'--verbose', u'--print-traffic']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16+ (CPython) - Linux-5.4.0-4-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: avconv 4.2.2-1, avprobe 4.2.2-1, ffmpeg 4.2.2-1, ffprobe 4.2.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 3UawxEP33FE: Downloading webpage
send: u'GET /watch?has_verified=1&bpctr=9999999999&hl=en&v=3UawxEP33FE&disable_polymer=true&gl=US HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.123 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: www.youtube.com\r\nCookie: PREF=f1=50000000&hl=en\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control: no-cache
header: Strict-Transport-Security: max-age=31536000
header: Content-Type: text/html; charset=utf-8
header: X-Frame-Options: SAMEORIGIN
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Expires: Tue, 27 Apr 1971 19:44:06 GMT
header: Date: Fri, 10 Apr 2020 10:34:46 GMT
header: Server: YouTube Frontend Proxy
header: X-XSS-Protection: 0
header: Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Fri, 10-Apr-2020 11:04:46 GMT
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Set-Cookie: YSC=QfBVh5GTBCY; path=/; domain=.youtube.com; secure; httponly; samesite=None
header: Set-Cookie: VISITOR_INFO1_LIVE=QNVxRY_hVN8; path=/; domain=.youtube.com; secure; expires=Wed, 07-Oct-2020 10:34:46 GMT; httponly; samesite=None
header: Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
header: Connection: close
header: Transfer-Encoding: chunked
send: u'GET /timedtext?disable_polymer=true&type=list&hl=en&v=3UawxEP33FE HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.123 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: video.google.com\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Fri, 10 Apr 2020 10:34:47 GMT
header: Pragma: no-cache
header: Expires: Fri, 01 Jan 1990 00:00:00 GMT
header: Cache-Control: no-cache, must-revalidate
header: X-Content-Type-Options: nosniff
header: Content-Type: text/html; charset=UTF-8
header: Server: video-timedtext
header: Content-Length: 1633
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
header: Connection: close
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] 3UawxEP33FE: Looking for automatic captions
[youtube] 3UawxEP33FE: Downloading MPD manifest
send: u'GET /api/manifest/dash/expire/1586536486/ei/xkuQXoX-G8GExgKmpauQDg/ip/89.102.206.225/id/dd46b0c443f7dc51/source/youtube/requiressl/yes/playback_host/r5---sn-2gb7sn7k.googlevideo.com/mh/71/mm/31%2C26/mn/sn-2gb7sn7k%2Csn-4g5ednss/ms/au%2Conr/mv/m/mvi/4/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1463750/vprv/1/mt/1586514815/fvip/5/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AJpPlLswRAIgafGSayqfmHTdF0NJJuGOCyU98RjElH90ls-GS2gUdTsCIFdPk0mzEcFPH6XOBz576kQEo5rCFBfeHxz6KZMUMvsu/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/ALrAebAwRQIhAISMOi4qeiPpcc6BgvSan1Rnkz3z1VzPj0Wcr7BUlxdgAiBJXLlKgGEFsKfnrfdTLEjfx2ZkXIHQlVsalaFijJr0Iw%3D%3D?disable_polymer=true HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.123 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: manifest.googlevideo.com\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: video/vnd.mpeg.dash.mpd
header: Date: Fri, 10 Apr 2020 10:34:47 GMT
header: Pragma: no-cache
header: Expires: Fri, 01 Jan 1990 00:00:00 GMT
header: Cache-Control: no-cache, must-revalidate
header: Content-Encoding: gzip
header: Server: HTTP server (unknown)
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
header: Connection: close
header: Transfer-Encoding: chunked
Available automatic captions for 3UawxEP33FE:
Language formats
gu       vtt, ttml, srv3, srv2, srv1
zh-Hans  vtt, ttml, srv3, srv2, srv1
zh-Hant  vtt, ttml, srv3, srv2, srv1
gd       vtt, ttml, srv3, srv2, srv1
ga       vtt, ttml, srv3, srv2, srv1
gl       vtt, ttml, srv3, srv2, srv1
lb       vtt, ttml, srv3, srv2, srv1
la       vtt, ttml, srv3, srv2, srv1
lo       vtt, ttml, srv3, srv2, srv1
tt       vtt, ttml, srv3, srv2, srv1
tr       vtt, ttml, srv3, srv2, srv1
lv       vtt, ttml, srv3, srv2, srv1
lt       vtt, ttml, srv3, srv2, srv1
tk       vtt, ttml, srv3, srv2, srv1
th       vtt, ttml, srv3, srv2, srv1
tg       vtt, ttml, srv3, srv2, srv1
te       vtt, ttml, srv3, srv2, srv1
fil      vtt, ttml, srv3, srv2, srv1
haw      vtt, ttml, srv3, srv2, srv1
yi       vtt, ttml, srv3, srv2, srv1
ceb      vtt, ttml, srv3, srv2, srv1
yo       vtt, ttml, srv3, srv2, srv1
de       vtt, ttml, srv3, srv2, srv1
da       vtt, ttml, srv3, srv2, srv1
el       vtt, ttml, srv3, srv2, srv1
eo       vtt, ttml, srv3, srv2, srv1
en       vtt, ttml, srv3, srv2, srv1
eu       vtt, ttml, srv3, srv2, srv1
et       vtt, ttml, srv3, srv2, srv1
es       vtt, ttml, srv3, srv2, srv1
ru       vtt, ttml, srv3, srv2, srv1
rw       vtt, ttml, srv3, srv2, srv1
ro       vtt, ttml, srv3, srv2, srv1
bn       vtt, ttml, srv3, srv2, srv1
be       vtt, ttml, srv3, srv2, srv1
bg       vtt, ttml, srv3, srv2, srv1
uk       vtt, ttml, srv3, srv2, srv1
jv       vtt, ttml, srv3, srv2, srv1
bs       vtt, ttml, srv3, srv2, srv1
ja       vtt, ttml, srv3, srv2, srv1
or       vtt, ttml, srv3, srv2, srv1
xh       vtt, ttml, srv3, srv2, srv1
co       vtt, ttml, srv3, srv2, srv1
ca       vtt, ttml, srv3, srv2, srv1
cy       vtt, ttml, srv3, srv2, srv1
cs       vtt, ttml, srv3, srv2, srv1
ps       vtt, ttml, srv3, srv2, srv1
pt       vtt, ttml, srv3, srv2, srv1
pa       vtt, ttml, srv3, srv2, srv1
vi       vtt, ttml, srv3, srv2, srv1
pl       vtt, ttml, srv3, srv2, srv1
hy       vtt, ttml, srv3, srv2, srv1
hr       vtt, ttml, srv3, srv2, srv1
ht       vtt, ttml, srv3, srv2, srv1
hu       vtt, ttml, srv3, srv2, srv1
hmn      vtt, ttml, srv3, srv2, srv1
hi       vtt, ttml, srv3, srv2, srv1
ha       vtt, ttml, srv3, srv2, srv1
mg       vtt, ttml, srv3, srv2, srv1
uz       vtt, ttml, srv3, srv2, srv1
ml       vtt, ttml, srv3, srv2, srv1
mn       vtt, ttml, srv3, srv2, srv1
mi       vtt, ttml, srv3, srv2, srv1
mk       vtt, ttml, srv3, srv2, srv1
ur       vtt, ttml, srv3, srv2, srv1
mt       vtt, ttml, srv3, srv2, srv1
ms       vtt, ttml, srv3, srv2, srv1
mr       vtt, ttml, srv3, srv2, srv1
ug       vtt, ttml, srv3, srv2, srv1
ta       vtt, ttml, srv3, srv2, srv1
my       vtt, ttml, srv3, srv2, srv1
af       vtt, ttml, srv3, srv2, srv1
sw       vtt, ttml, srv3, srv2, srv1
is       vtt, ttml, srv3, srv2, srv1
am       vtt, ttml, srv3, srv2, srv1
it       vtt, ttml, srv3, srv2, srv1
iw       vtt, ttml, srv3, srv2, srv1
sv       vtt, ttml, srv3, srv2, srv1
ar       vtt, ttml, srv3, srv2, srv1
su       vtt, ttml, srv3, srv2, srv1
zu       vtt, ttml, srv3, srv2, srv1
az       vtt, ttml, srv3, srv2, srv1
id       vtt, ttml, srv3, srv2, srv1
ig       vtt, ttml, srv3, srv2, srv1
nl       vtt, ttml, srv3, srv2, srv1
no       vtt, ttml, srv3, srv2, srv1
ne       vtt, ttml, srv3, srv2, srv1
ny       vtt, ttml, srv3, srv2, srv1
fr       vtt, ttml, srv3, srv2, srv1
ku       vtt, ttml, srv3, srv2, srv1
fy       vtt, ttml, srv3, srv2, srv1
fa       vtt, ttml, srv3, srv2, srv1
fi       vtt, ttml, srv3, srv2, srv1
ka       vtt, ttml, srv3, srv2, srv1
kk       vtt, ttml, srv3, srv2, srv1
sr       vtt, ttml, srv3, srv2, srv1
sq       vtt, ttml, srv3, srv2, srv1
ko       vtt, ttml, srv3, srv2, srv1
kn       vtt, ttml, srv3, srv2, srv1
km       vtt, ttml, srv3, srv2, srv1
st       vtt, ttml, srv3, srv2, srv1
sk       vtt, ttml, srv3, srv2, srv1
si       vtt, ttml, srv3, srv2, srv1
so       vtt, ttml, srv3, srv2, srv1
sn       vtt, ttml, srv3, srv2, srv1
sm       vtt, ttml, srv3, srv2, srv1
sl       vtt, ttml, srv3, srv2, srv1
ky       vtt, ttml, srv3, srv2, srv1
sd       vtt, ttml, srv3, srv2, srv1
3UawxEP33FE has no subtitles
```

## Description

Video contains subtitles. I had no trouble getting the subtitles (even dowload them) until yesterday :(
This seems to be the culprit:
```
send: u'GET /timedtext?disable_polymer=true&type=list&hl=en&v=3UawxEP33FE HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.123 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: video.google.com\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'```

**Comment by ttocs47** [comment]
I _think_ I am having the same problem.  A video that I can watch with subtitles will not download them, although similar videos have no issue. ( https://youtu.be/bdlgsSMc09I  made by the same user has the same issue ).


> % youtube-dl -f 'best[ext!=webm]' --prefer-ffmpeg --write-sub -v 'https://youtu.be/5NsITeJibEs'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best[ext!=webm]', u'--prefer-ffmpeg', u'--write-sub', u'-v', u'https://youtu.be/5NsITeJibEs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 5NsITeJibEs: Downloading webpage
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] 5NsITeJibEs: Downloading MPD manifest
[debug] Invoking downloader on u'https://r4---sn-ab5l6nzy.googlevideo.com/videoplayback?expire=1586750116&ei=RI6TXpCzMfmB2LYPi5uiWA&ip=129.49.88.68&id=o-AIT_4CBLbNQRL2huYi_SIBTG7OS0klJufAhv6xtpZowY&itag=18&source=youtube&requiressl=yes&mh=uw&mm=31%2C29&mn=sn-ab5l6nzy%2Csn-ab5sznl7&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=7533750&vprv=1&mime=video%2Fmp4&gir=yes&clen=118701708&ratebypass=yes&dur=2610.944&lmt=1562696524415699&mt=1586728418&fvip=4&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIhANTrhSaQFUY-g3_BEybgY8hWu3EHRQzv8gADlkV4yMchAiB2b3-SpuV1I595Rycoc8iaPOQ7pUzwm2AVNgYyICdRSg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgTBwkOBcc4B_4P2TR8ggLCbNppZMarBjGaiQtDWXlTjMCIFVteCBINagQr9vcnaiaXiUHt8WOR6ooFQ0uO_tbqPJh'
[download] 20160404 MAT126 L18-5NsITeJibEs.mp4 has already been downloaded
[download] 100% of 113.20MiB

> % youtube-dl --list-subs 'https://youtu.be/5NsITeJibEs'
[youtube] 5NsITeJibEs: Downloading webpage
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] 5NsITeJibEs: Looking for automatic captions
[youtube] 5NsITeJibEs: Downloading MPD manifest
Available automatic captions for 5NsITeJibEs:
Language formats
gu       vtt, ttml, srv3, srv2, srv1
zh-Hans  vtt, ttml, srv3, srv2, srv1
zh-Hant  vtt, ttml, srv3, srv2, srv1
gd       vtt, ttml, srv3, srv2, srv1
ga       vtt, ttml, srv3, srv2, srv1
gl       vtt, ttml, srv3, srv2, srv1
lb       vtt, ttml, srv3, srv2, srv1
la       vtt, ttml, srv3, srv2, srv1
lo       vtt, ttml, srv3, srv2, srv1
tt       vtt, ttml, srv3, srv2, srv1
tr       vtt, ttml, srv3, srv2, srv1
lv       vtt, ttml, srv3, srv2, srv1
lt       vtt, ttml, srv3, srv2, srv1
tk       vtt, ttml, srv3, srv2, srv1
th       vtt, ttml, srv3, srv2, srv1
tg       vtt, ttml, srv3, srv2, srv1
te       vtt, ttml, srv3, srv2, srv1
fil      vtt, ttml, srv3, srv2, srv1
haw      vtt, ttml, srv3, srv2, srv1
yi       vtt, ttml, srv3, srv2, srv1
ceb      vtt, ttml, srv3, srv2, srv1
yo       vtt, ttml, srv3, srv2, srv1
de       vtt, ttml, srv3, srv2, srv1
da       vtt, ttml, srv3, srv2, srv1
el       vtt, ttml, srv3, srv2, srv1
eo       vtt, ttml, srv3, srv2, srv1
en       vtt, ttml, srv3, srv2, srv1
eu       vtt, ttml, srv3, srv2, srv1
et       vtt, ttml, srv3, srv2, srv1
es       vtt, ttml, srv3, srv2, srv1
ru       vtt, ttml, srv3, srv2, srv1
rw       vtt, ttml, srv3, srv2, srv1
ro       vtt, ttml, srv3, srv2, srv1
bn       vtt, ttml, srv3, srv2, srv1
be       vtt, ttml, srv3, srv2, srv1
bg       vtt, ttml, srv3, srv2, srv1
uk       vtt, ttml, srv3, srv2, srv1
jv       vtt, ttml, srv3, srv2, srv1
bs       vtt, ttml, srv3, srv2, srv1
ja       vtt, ttml, srv3, srv2, srv1
or       vtt, ttml, srv3, srv2, srv1
xh       vtt, ttml, srv3, srv2, srv1
co       vtt, ttml, srv3, srv2, srv1
ca       vtt, ttml, srv3, srv2, srv1
cy       vtt, ttml, srv3, srv2, srv1
cs       vtt, ttml, srv3, srv2, srv1
ps       vtt, ttml, srv3, srv2, srv1
pt       vtt, ttml, srv3, srv2, srv1
pa       vtt, ttml, srv3, srv2, srv1
vi       vtt, ttml, srv3, srv2, srv1
pl       vtt, ttml, srv3, srv2, srv1
hy       vtt, ttml, srv3, srv2, srv1
hr       vtt, ttml, srv3, srv2, srv1
ht       vtt, ttml, srv3, srv2, srv1
hu       vtt, ttml, srv3, srv2, srv1
hmn      vtt, ttml, srv3, srv2, srv1
hi       vtt, ttml, srv3, srv2, srv1
ha       vtt, ttml, srv3, srv2, srv1
mg       vtt, ttml, srv3, srv2, srv1
uz       vtt, ttml, srv3, srv2, srv1
ml       vtt, ttml, srv3, srv2, srv1
mn       vtt, ttml, srv3, srv2, srv1
mi       vtt, ttml, srv3, srv2, srv1
mk       vtt, ttml, srv3, srv2, srv1
ur       vtt, ttml, srv3, srv2, srv1
mt       vtt, ttml, srv3, srv2, srv1
ms       vtt, ttml, srv3, srv2, srv1
mr       vtt, ttml, srv3, srv2, srv1
ug       vtt, ttml, srv3, srv2, srv1
ta       vtt, ttml, srv3, srv2, srv1
my       vtt, ttml, srv3, srv2, srv1
af       vtt, ttml, srv3, srv2, srv1
sw       vtt, ttml, srv3, srv2, srv1
is       vtt, ttml, srv3, srv2, srv1
am       vtt, ttml, srv3, srv2, srv1
it       vtt, ttml, srv3, srv2, srv1
iw       vtt, ttml, srv3, srv2, srv1
sv       vtt, ttml, srv3, srv2, srv1
ar       vtt, ttml, srv3, srv2, srv1
su       vtt, ttml, srv3, srv2, srv1
zu       vtt, ttml, srv3, srv2, srv1
az       vtt, ttml, srv3, srv2, srv1
id       vtt, ttml, srv3, srv2, srv1
ig       vtt, ttml, srv3, srv2, srv1
nl       vtt, ttml, srv3, srv2, srv1
no       vtt, ttml, srv3, srv2, srv1
ne       vtt, ttml, srv3, srv2, srv1
ny       vtt, ttml, srv3, srv2, srv1
fr       vtt, ttml, srv3, srv2, srv1
ku       vtt, ttml, srv3, srv2, srv1
fy       vtt, ttml, srv3, srv2, srv1
fa       vtt, ttml, srv3, srv2, srv1
fi       vtt, ttml, srv3, srv2, srv1
ka       vtt, ttml, srv3, srv2, srv1
kk       vtt, ttml, srv3, srv2, srv1
sr       vtt, ttml, srv3, srv2, srv1
sq       vtt, ttml, srv3, srv2, srv1
ko       vtt, ttml, srv3, srv2, srv1
kn       vtt, ttml, srv3, srv2, srv1
km       vtt, ttml, srv3, srv2, srv1
st       vtt, ttml, srv3, srv2, srv1
sk       vtt, ttml, srv3, srv2, srv1
si       vtt, ttml, srv3, srv2, srv1
so       vtt, ttml, srv3, srv2, srv1
sn       vtt, ttml, srv3, srv2, srv1
sm       vtt, ttml, srv3, srv2, srv1
sl       vtt, ttml, srv3, srv2, srv1
ky       vtt, ttml, srv3, srv2, srv1
sd       vtt, ttml, srv3, srv2, srv1
5NsITeJibEs has no subtitles

**Comment by Chocobozzz** [comment]
Same here. Seems related to the video privacy setting: if I use `Public` intead of `Unlisted`, youtube-dl correctly fetches subtitles.

**Comment by starenka** [comment]
> if I use `Public` intead of `Unlisted`
what do you mean by that?

**Comment by Chocobozzz** [comment]
I update my comment. I'm the owner of the video, so I changed the video privacy setting

**Comment by starenka** [comment]
That's what I thought, unfortunately those vids are not mine :(

**Comment by ivanistheone** [comment]
I can confirm the issue is only for `Unlisted` videos, like this [one](https://www.youtube.com/watch?v=lvIDEzO60w4) for example.

Using `youtube-dl` v `2020.03.24` and calling:
```
youtube-dl --list-subs --all-sub "https://www.youtube.com/watch?v=lvIDEzO60w4"
```

### Expected
To get one sub available `pt` 


### Actual
```
[youtube] lvIDEzO60w4: Downloading webpage
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] lvIDEzO60w4: Looking for automatic captions
[youtube] lvIDEzO60w4: Downloading MPD manifest
Available automatic captions for lvIDEzO60w4:
Language formats
af       vtt, ttml, srv3, srv2, srv1
sq       vtt, ttml, srv3, srv2, srv1
...~100 lines truncated...
yo       vtt, ttml, srv3, srv2, srv1
zu       vtt, ttml, srv3, srv2, srv1
lvIDEzO60w4 has no subtitles
```


As a side question --- is there a way to know which of the automatic captions actually exist instead of seeing the full list?  This [specific example video](https://www.youtube.com/watch?v=lvIDEzO60w4) only shows the `pt-BR` automatic captions in the youtube player, but `--list-subs` returns a full list of 109 language codes. I'm guessing all those other languages are technically available because of auto-translate feature, but it would be useful to know which ones are already there vs. the ones that _could_ be there.

**Comment by ivanistheone** [comment]
@jaimeMF Would you have any pointers for possible workaround for this? Basically `video.google.com/timedtext?hl=en&type=list&v={youtube_id}&disable_polymer=true` doesn't work anymore for Unlisted videos as of two weeks ago.

If saw in the git commit history you worked on this part of the code so I'm wondering if there was another option for getting the subtitles. Can we imitate how the browser client does it? Any pointers would be appreciated, and if it seems feasible I can try to fix.

**Comment by ivanistheone** [comment]
Okay, this issue seems to have been only transient (for about two weeks).

I just tried running:
```
youtube-dl --list-subs --all-sub "https://www.youtube.com/watch?v=lvIDEzO60w4"
```

and got no errors and the correct output (matching what I see online):

```
[youtube] lvIDEzO60w4: Downloading webpage
[youtube] lvIDEzO60w4: Looking for automatic captions
[youtube] lvIDEzO60w4: Downloading MPD manifest
Available automatic captions for lvIDEzO60w4:
Language formats
af       vtt, ttml, srv3, srv2, srv1
....
....
zu       vtt, ttml, srv3, srv2, srv1
Available subtitles for lvIDEzO60w4:
Language formats
pt       vtt, ttml, srv3, srv2, srv1
```


@starenka @ttocs47 I checked on the videos you posted too and I can get subs for them now. So motion to close this issue .... and hope it never comes back :)
