### ISSUE TITLE
not work wih pluralsight courses

### ISSUE THREAD

**Issue by motacano** [ytdl-org/youtube-dl#24976]
**my youtube-dl.conf**

-u ???
-p ??? info restricted
-i
-c
--no-warnings
--console-title
--batch-file='C:\Users\mamota\batch-file.txt'
--max-sleep-interval 80
--min-sleep-interval 60
-o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'
-f 'best[height<=720]/worst[height>720]'

**error**
[download] Downloading video 49 of 50
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure 
you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ugultopu** [comment]
@dstftw I had the same problem and in my case, it turned out that youtube-dl was using Python 2, which is the default Python version on Mac. When I created and activated a virtualenv which had Python 3 (.7) as the default Python version, it worked. Wouldn't it make sense for the program to force the users to use Python 3, and exit with this error message when it detects Python 2?
