### ISSUE TITLE
Hotstar downloads are not working anymore (not a Geo-restriction problem).

### ISSUE THREAD

**Issue by xabayx** [ytdl-org/youtube-dl#25003]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\dl\Downloads>youtube-dl -v https://www.hotstar.com/in/tv/radhakrishn/s-1695/the-classic-love-saga/1000221006
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/in/tv/radhakrishn/s-1695/the-classic-love-saga/1000221006']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-12-02-968c4cb, ffprobe git-2019-12-02-968c4cb
[debug] Proxy map: {}
[hotstar] 1000221006: Downloading webpage
[hotstar] 1000221006: Downloading JSON metadata
[hotstar] 1000221006: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://hses4.akamaized.net/videos/hotstarint/forceup/1260025161/1586341016779/fcc2ab35a8cfbd1315af85b0085f1689/media-8/index.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: The Classic Love Saga-1000221006.mp4
[download] 100% of 1.02MiB in 00:13
[debug] ffmpeg command line: ffprobe -show_streams "file:The Classic Love Saga-1000221006.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "The Classic Love Saga-1000221006.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:The Classic Love Saga-1000221006.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:The Classic Love Saga-1000221006.temp.mp4"```


## Description
Hi, 
this issue: https://github.com/ytdl-org/youtube-dl/issues/24707
got closed because hotstar is geo-restricted.
BUT the Geo Restriction in this case is not the problem.
I've  using different VPN servers since some months (so far I've tried with 3 different working VPN servers) and I am being able to open and watch the videos directly with my browser and one could also download with youtube-dl until it just stopped working some days ago :
youtube-dl only downloads now a small video (5 seconds long) with the following text in it:
"This version of Hotstar is no longer supported.
Please download the latest version from the App Store. If you are unable to view content even after upgrading your app, please uninstall and reinstall the app.".

Any help would be greatly appreciated!

Best regards :)

**Comment by dstftw** [comment]
I've already pointed out: out must provide proxy/VPN for any work on this.

**Comment by xabayx** [comment]
> I've already pointed out: out must provide proxy/VPN for any work on this.

Thank you for the fast answer!
Sorry, I don't understand, could you kindly explain what one has to do with the VPN?
Thank you in advance :)

**Comment by FaArIsH** [comment]
@dstftw 
i tried this and  when i run make it gives a error (because of import requests) but youtube-dl is working fine and hotstar is working now
https://github.com/FaArIsH/youtube-dl/commit/fd38d552ec6d44191561fc59d3057f8ca336f1f3

> root@ubuntu:~/youtube-dl# make
mkdir -p zip
for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
mv zip/youtube_dl/__main__.py zip/
cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl
COLUMNS=80 /usr/bin/env python youtube_dl/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
Traceback (most recent call last):
  File "youtube_dl/__main__.py", line 16, in <module>
    import youtube_dl
  File "/root/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/root/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/root/youtube-dl/youtube_dl/extractor/extractors.py", line 437, in <module>
    from .hotstar import (
  File "/root/youtube-dl/youtube_dl/extractor/hotstar.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 115, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 13, in <module>
    from . import sessions
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 28, in <module>
    from .adapters import HTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 44, in <module>
    from urllib3.contrib.socks import SOCKSProxyManager
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/socks.py", line 40, in <module>
    import socks
  File "/root/youtube-dl/youtube_dl/socks.py", line 15, in <module>
    from .compat import (
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "devscripts/make_readme.py", line 19, in <module>
    options = helptext[helptext.index('  General Options:') + 19:]
ValueError: substring not found
Makefile:76: recipe for target 'README.md' failed
make: *** [README.md] Error 1
root@ubuntu:~/youtube-dl#
