### ISSUE TITLE
[udemy:course] Downloading login popup Error 403:

### ISSUE THREAD

**Issue by Mtea994** [ytdl-org/youtube-dl#25023]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/course/fiverr-blueprint-masterclass/', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Windows-10-10.0.18362
[debug] exe versions: avconv 11.3, avprobe 11.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

WRITE DESCRIPTION HERE
i am trying to download a course from udemy which i have purchased but i am not being able to login in youtube-dl command line i think their might be a missed bug here in the updated version

**Comment by ichux** [comment]
I do not know if this might serve you, but here is a suggest that I tried and which worked out.

`youtube-dl https://mp4-a.udemycdn.com/2020-01-13_10-04-58-11535c098e4f6536719b1491d8515bed/WebHD_720p.mp4?mGqlQkC4VP0v95lVk7sV1Ww0ONDK_lD1OsGBogVvDHaKoW4QGLVWXp3xLHebKwnBH_D8WBUQXKK8lMC67eqqZA6Dkwl7rrTsM4OInBvTU4resAilX-07neC_ltkXkh22XwnJA4M1LDlcEIrPpaRt5uGSdPB2HvoP6awPH2XZN21egg`

The URL I posted was gotten by visiting the page you posted, https://www.udemy.com/course/fiverr-blueprint-masterclass/ but before I did that, I opened the network tab in the developers tool SECTION.

The URL had the type *mp4*. I just copied that one since the authentication code is already in the URL and I supplied it to youtube-dl and it downloaded the mp4.

The mp4 I downloaded is the one of the page that serves as the introduction when that URL of the page you posted is visited. I want to believe that it might work for when you are also logged in.

Note: the URL I posted in front of youtube-dl might have expired by the time you want to test it, so, repeat the process I have done to get a fresh one. Cheers
