### ISSUE TITLE
NHK World audio on demand: some "Friends Around the World" URLs unsupported

### ISSUE THREAD

**Issue by an-nhk-world-fan** [ytdl-org/youtube-dl#25286]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\>youtube-dl -v https://www3.nhk.or.jp/nhkworld/en/ondemand/audio/listener-20200315-en/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/audio/listener-20200315-en/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.2, ffprobe N-91666-g70d2bab80b, rtmpdump 2.3
[debug] Proxy map: {}
[generic] listener-20200315-en: Requesting header
WARNING: Falling back on generic information extractor.
[generic] listener-20200315-en: Downloading webpage
[generic] listener-20200315-en: Extracting information
ERROR: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/audio/listener-20200315-en/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swg
z7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swg
z7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swg
z7\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/audio/listener-20200315-en/
```

## Description

Some [Friends Around the World](https://www3.nhk.or.jp/nhkworld/en/ondemand/program/audio/listener/?type=radioEpisode&) URLs unsupported, such as https://www3.nhk.or.jp/nhkworld/en/ondemand/audio/listener-20200329-en/

Perhaps this is because of the "-en" at the end of the URL?

**Comment by rolledback** [comment]
@remitamine I intended to fix this issue, but it looks like your commit (b79df1b68d547e822eb87f6379c847866234396f) has already fixed it, sort of.

While the NHK extractor does now support this URL, the id that ends up being used is a bit odd. It ends up being:
```
listener-20200315-en-en
```
In your change, you reverted my change of how the id of things were being calculated. I moved the extractor to using information from the API, while you reverted it back to using information from the URL*. With my original method of id calculated, the id would be:
```
listener-20200315-en
```

If I were to guess, I'd say you were not a fan of my changing of id calculation. Maybe that was the part of the change that you didn't consider to be a "minimalistic approach". To be fair though, I can understand the benefits of using the information from the URL.

Since the URL has been matched with a regex, we know we have all of the parameters we want, so as long as the URL is valid, things will likely continue to work. The downside though is that you get cases like this, where now you have to special case the id calculation to drop the extra `-en`. 

On the other hand, if we instead used information from the API, then we get the benefit of a more accurate/consistent id calculation. This URL is a good example of that. The downside to it though is that while the URL might stay the same, the API might change, and if it changes in such a way that the information we were using is no longer available, then we might be forced into doing a breaking change.

So I see the benefits and downsides of each way. Personally, I think it'd be good to un-revert my method of id calculation, and leave in the original method as a fallback incase the API changes. The information I was extracting from the API seems to be the same as the ID in the URL for now, so I think that would be a good compromise. Let me know what you think.

* While you did do this for both video and audio clips/episodes, on line 66, you override the `'id'` value in the info dict to be something from the API. That `'id'` doesn't seem to be used in the end though? I'm not really sure what that is for.

**Comment by remitamine** [comment]
```
With my original method of id calculated, the id would be:
listener-20200315-en
```
even with your code, the id would've been `listener-20200315-en-en`

> While you did do this for both video and audio clips/episodes, on line 66, you override the 'id' value (which was calculated via URL information) in the info dict to be something from the API. That 'id' doesn't seem to be used in the end though? I'm not really sure what that is for.

helps when the user is downloading programs while using the `--download-archive` option because the id that ends up being used for videos is the `PikselIE` video id, not the `NhkVodIE` video id.

Closing the issue as it appears that this has been fixed.
