### ISSUE TITLE
[BUG] `--write-sub -o -` writes subtitle to a file named -

### ISSUE THREAD

**Issue by NightMachinery** [ytdl-org/youtube-dl#25344]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

`--write-sub -o -` writes subtitle to a file named -. It should use the video's name or accept a name with a new cli option.

**Comment by rafinetiz** [comment]
you can't write the output to file named -, as i know, when you pass - to -o option, the output will be written to STDOUT.

and if you mean you want to write subtitle to different name, i think this is not a bug but a feature request.

**Comment by NightMachinary** [comment]
@rafinetiz the problem is that the video file is going into stdout, so the subtitle file has nowhere to go.

**Comment by jrauhamaa** [comment]
Same thing seems to happen when format is specified. 
`$ youtube-dl <url> -o - > video`
writes to a file named 'video', while
`$ youtube-dl <url> -f <FORMAT> -o - > video`
writes the video to '-.mkv'

Somehow the `-o -` option gets interpreted differently depending on whether format options are provided or not.

**Comment by nadermx** [comment]
Not sure if this helps anyone here, but to get around this issue, I had yt-dlp just output the subtitle url 
```
yt-dlp --skip-download --write-subs --sub-lang en --print "requested_subtitles.en.url" VIDEO_URL
```

**Comment by dirkf** [comment]
The _yt-dl_ version of that would involve writing a JSON file of known name (possibly a named pipe) and then extracting the desired subtitle URL with (eg) _jq_. But the real point, as originally discussed, is that the subtitle extraction mechanism doesn't/can't work with `-o -` because there's only a single output stream in `stdout` and you need at least two.

>...
`$ youtube-dl <url> -f <FORMAT> -o - > video`
writes the video to '-.mkv'

I'm fairly sure that doesn't happen now. If it does, it should be reported in a new issue.
