### ISSUE TITLE
ffmpeg v4.1 (and v4.2) reports an "Unsupported codec with id 100359 for input stream 2" when using "youtube-dl --add-metadata"

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#25496]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --ignore-config -v -f 18 https://www.youtube.com/watch?v=huf1UlSh_LY --restrict-filenames --add-metadata
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-f', '18', 'https://www.youtube.com/watch?v=huf1UlSh_LY', '--restrict-filenames', '--add-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.6.8 (CPython) - Linux-4.4.0-148-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 4.1.3-0york1, avprobe 4.1.3-0york1, ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] huf1UlSh_LY: Downloading webpage
[debug] Invoking downloader on 'https://redirector.googlevideo.com/videoplayback?expire=1591120775&ei=Jz_WXpzsFYn91waLjqLACA&ip=2a01%3Ae0a%3A5ea%3A7020%3Ab923%3Ae287%3A1cec%3Aaa60&id=86e7f55254a1fcb6&itag=18&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&gir=yes&clen=124245082&ratebypass=yes&dur=1617.641&lmt=1548612218608764&fexp=23882513&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOy0P79gYFbYgnYbA2O9SbrAYdZrk7APRarI5l525acdAiB90qxFbwbCZ_6sRdJBK1_DkMsFhOmS66_MmvC5cjFqeQ%3D%3D'
[download] Destination: Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4
[download] 100% of 118.49MiB in 00:04
[ffmpeg] Adding metadata to 'Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4 -i file:Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.meta -c copy -metadata 'title=Don'"'"'t Rely On People | Joel Osteen' -metadata date=20160604 -metadata 'description=Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?

🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit.ly/JoelYTSub

One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivated.

Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful life, but your relationships will improve, too!

This is Message #691 "Don'"'"'t Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages

Follow #JoelOsteen on social!
Twitter - http://Bit.ly/JoelOTW
Instagram - http://BIt.lu/JoelIG
Facebook - http://Bit.ly/JoelOFB' -metadata 'comment=Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?

🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit.ly/JoelYTSub

One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivated.

Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful life, but your relationships will improve, too!

This is Message #691 "Don'"'"'t Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages

Follow #JoelOsteen on social!
Twitter - http://Bit.ly/JoelOTW
Instagram - http://BIt.lu/JoelIG
Facebook - http://Bit.ly/JoelOFB' -metadata 'purl=https://www.youtube.com/watch?v=huf1UlSh_LY' -metadata 'artist=Joel Osteen' -map_metadata 1 file:Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.temp.mp4
$ ffprobe -hide_banner Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Don't Rely On People | Joel Osteen
    artist          : Joel Osteen
    date            : 20160604
    encoder         : Lavf58.20.100
    comment         : Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?
                    : 
                    : 🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit.ly/JoelYTSub
                    : 
                    : One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivate
                    : 
                    : Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful
                    : 
                    : This is Message #691 "Don't Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages
                    : 
                    : Follow #JoelOsteen on social!
                    : Twitter - http://Bit.ly/JoelOTW
                    : Instagram - http://BIt.lu/JoelIG
                    : Facebook - http://Bit.ly/JoelOFB
    description     : Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?
                    : 
                    : 🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit.ly/JoelYTSub
                    : 
                    : One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivate
                    : 
                    : Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful
                    : 
                    : This is Message #691 "Don't Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages
                    : 
                    : Follow #JoelOsteen on social!
                    : Twitter - http://Bit.ly/JoelOTW
                    : Instagram - http://BIt.lu/JoelIG
                    : Facebook - http://Bit.ly/JoelOFB
  Duration: 00:26:58.00, start: 0.000000, bitrate: 618 kb/s
    Chapter #0:0: start 0.000000, end 1618.000000
    Metadata:
      title           : Paul said in Philippians , “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful lif
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 515 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/27/2019.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/27/2019.
    Stream #0:2(eng): Data: bin_data (text / 0x74786574), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
Unsupported codec with id 100359 for input stream 2
```

## Description

`ffmpeg` v4.1 (and v4.2) reports an `Unsupported codec with id 100359 for input stream 2` on the videofile when it was downloaded using `youtube-dl --add-metadata`

**Comment by Dullaz** [comment]
I cannot reproduce the error using
OS: Ubuntu 20.04.1 LTS
Python: 2.7.18rc1
YTDL : 2020.09.20
FFMPEG: version 4.2.4-1ubuntu0.1

Command: 
`youtube-dl --ignore-config -v -f 18 https://www.youtube.com/watch?v=huf1UlSh_LY --restrict-filenames --add-metadata`

Output:
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'-f', u'18', u'https://www.youtube.com/watch?v=huf1UlSh_LY', u'--restrict-filenames', u'--add-metadata']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18rc1 (CPython) - Linux-4.19.128-microsoft-standard-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] huf1UlSh_LY: Downloading webpage
[debug] Invoking downloader on u'https://r4---sn-8pgbpohxqp5-auo6.googlevideo.com/videoplayback?expire=1601010634&ei=aidtX6-SDZLYsAKjlboQ&ip=82.7.114.115&id=o-AEO3VWn4bushH__1btxLOfQiZCl2BDndx6EAqQKFA1kV&itag=18&source=youtube&requiressl=yes&mh=Tb&mm=31%2C29&mn=sn-8pgbpohxqp5-auo6%2Csn-aigzrn7e&ms=au%2Crdu&mv=m&mvi=4&pl=22&initcwndbps=2117500&vprv=1&mime=video%2Fmp4&gir=yes&clen=124245082&ratebypass=yes&dur=1617.641&lmt=1548612218608764&mt=1600988915&fvip=4&fexp=23915654&beids=9466586&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMZTZERTs5FX3BGnujIB_U0U09a06EdEhn6CgnWlxo4GAiAak9GKTxGG6RWtT_HIcG3QfwE4OL0JOG3On_B1NPOS5w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJg-f7-8AbXP2gSkiNyKKyxlVUC4q_X52k4Zqs94_MWECIAGPDLChVNsAec1I5ttCm1A4IsbnRdha9yVJcTd3nM7B'
[download] Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4 has already been downloaded
[download] 100% of 119.32MiB
[ffmpeg] Adding metadata to 'Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.mp4' -c copy -metadata 'comment=Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?

🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit .ly/JoelYTSub

One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivated.

Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful life, but your relationships will improve, too!

This is Message #691 "Don'"'"'t Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages

Follow #JoelOsteen on social!
Twitter - http://Bit.ly/JoelOTW
Instagram - http://BIt.lu/JoelIG
Facebook - http://Bit.ly/JoelOFB' -metadata 'description=Are you relying on what others say or don’t say for your value? Are you frustrated today because you don’t have the support from others around you?

🛎Subscribe to receive weekly messages of hope, encouragement, and inspiration from Joel! http://bit .ly/JoelYTSub

One of the greatest lessons in life is to learn that your true value does not come from people; it comes from Almighty God. Yet many people today rely on the complements, encouragement and approval of others to feel good about themselves and stay motivated.

Paul said in Philippians 4:13, “I am self-sufficient in Christ’s sufficiency.” Let Joel show you who you are in Christ and how to go to Him for your value and self-worth. As you apply these biblical principles, not only will you live a more peaceful life, but your relationships will improve, too!

This is Message #691 "Don'"'"'t Rely on People" by Joel Osteen. For more inspirational messages, visit https://www.JoelOsteen.com/Messages

Follow #JoelOsteen on social!
Twitter - http://Bit.ly/JoelOTW
Instagram - http://BIt.lu/JoelIG
Facebook - http://Bit.ly/JoelOFB' -metadata 'artist=Joel Osteen' -metadata 'title=Don'"'"'t Rely On People | Joel Osteen' -metadata 'date=20160604' -metadata 'purl=https://www.youtube.com/watch?v=huf1UlSh_LY' 'file:Don_t_Rely_On_People_Joel_Osteen-huf1UlSh_LY.temp.mp4'`

Might need some more information about the environment you're running in to reproduce

**Comment by sebma** [comment]
@Dullaz On the 2nd of June, YTDL version was  2020.05.29.
With the current YTDL version 2020.09.20, this pb. does not appear anymore, seems to have been fixed between the 2nd of June and the 20th of September.
Closing this issue because it's now fixed.
