### ISSUE TITLE
DMAX videos now played embedded - no URL

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#25636]
The dmax.de site plays the videos embedded in the main page so we can no long fetch the URLs
Example: https://dmax.de/sendungen/goldrausch-in-alaska/

**Comment by aruscher** [comment]
DMAX is broken due to a mismatch in the url encoding (old: https://www.dmax.de/programme/dmax-highlights/video/tuning-star-sidney-hoffmann-exklusiv-bei-dmax/191023082312316, new: https://dmax.de/sendungen/goldrausch-in-alaska/).

@Reiner1210 : For now you can use https://github.com/Brawl345/Get-DMAX-Links to generate a bunch of youtube-dl calls  :)

**Comment by Reiner1210** [comment]
Ok but the script throws an error

python dmax.py 7163 -s 3

2020-06-19 11:52:45,569 - DMAX - INFO - Getting Authorization token...
2020-06-19 11:52:45,816 - DMAX - INFO - Getting show data
2020-06-19 11:52:46,055 - DMAX - INFO - => Outback Opal Hunters -  
Edelsteinjagd in Australien
2020-06-19 11:52:46,055 - DMAX - INFO - Getting link 1 of 4
2020-06-19 11:52:46,282 - DMAX - INFO - Getting link 2 of 4
2020-06-19 11:52:46,483 - DMAX - INFO - Getting link 3 of 4
Traceback (most recent call last):
   File "dmax.py", line 232, in <module>
     chosen_episode=arguments.episode
   File "dmax.py", line 170, in main
     episode_name=episode.name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in 
position 11: ordinal not in range(128)

I have found a manual way. Look in the Browser under network, filter 
m3u, clear lig and click video. The entry starting with playlist should 
it be.

Reiner

**Comment by faulesocke** [comment]
How would we fix this? The user only has an URL like https://dmax.de/sendungen/goldrausch-in-alaska/ but usually does not want to download *all* episodes but only one or two. There already exist some options for video selection but these are primarily made for youtube playlists. So I recommend the following behaviour:

When no options are given, youtube-dl starts downloading *all* episodes from *all* seasons available. In addition we can try to modify the `--playlist-items` option so that it accepts strings like `S02E05`. Another option would be to have a new `--episode` or `--episode-list` option.

I can start implementing this and open a PR if you are okay with this design.

**Comment by Reiner1210** [comment]
At the moment I manually extract the URL from the network debug window in Firefox.
I think a list function `(--episode-list)` would be helpful. And then an option to put the output string of the episode as option in the download.
