### ISSUE TITLE
youtube-dl --external-downloader doesn't work with a Full Path

### ISSUE THREAD

**Issue by SwiftMove** [ytdl-org/youtube-dl#25852]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Using the "--external-downloader" argument doesn't work with a full path...

`youtube-dl.exe --external-downloader=D:\aria2\aria2c.exe`

However, if I put "aria2c.exe" in the folder above youtube-dl.exe, then this command does work...

`youtube-dl.exe --external-downloader=..\aria2c.exe`

I'm well aware that I can change the PATH variable, and just use "aria2c" instead of a Full Path, but I was just curious on why using a Full Path doesn't work? Was not allowing full paths the intended behavior? Or is this just an oversight?

**Comment by glenn-slayden** [comment]
On Windows (at least), you need to use double-quotes, and backslashes must be escaped. The following works for me:

    youtube-dl --external-downloader "C:\\Program Files\\aria2\\aria2c.exe" https://www.youtube.com/watch?v=vwnXqmgNBEw

Forward-slashes also work on Windows (again with double-quotes), if you prefer:

    youtube-dl --external-downloader "C:/Program Files/aria2/aria2c.exe" https://www.youtube.com/watch?v=vwnXqmgNBEw

Don't forget to specify your `--external-downloader-args`, if any.

**Comment by SwiftMove** [comment]
I was already using double-quotes, but not escaped backslashes. However, I just tried using double-quotes AND escaped backslashes like you mentioned, but it still doesn't work.

I noticed that you have installed aria2c on your system, that means that "aria2" is probably listed in your PATH environment variable which is why it's probably working for you. Go remove the "C:\Program Files\aria2\aria2c.exe" from your envorinment PATH and try it again. I'm testing this on a system where aria2c is only being used by calling the EXE directly.

**Comment by glenn-slayden** [comment]
Hmm, that would be weird, because according to what you're saying, `youtube-dl` would have to be taking a fully-specified command line argument, and explicitly stripping away the path part, to obtain just the executable name -- that it would then launch, now dependent on the environment PATH?

Anyway, @dstftw please don't let my observation affect whether you look into this...

p.s. I assume your `aria2c` is the statically linked version (i.e., not the mingw version), so there's no issue of it somehow not finding its own libraries....

**Comment by SwiftMove** [comment]
Yeah, my aria2c.exe binary works just fine, no issues there, and like I said in the OP, it works just fine if I use "--external-downloader aria2c", it just doesn't work when I use the full path. I know I can add my aria2c path to my PATH environment variable, but it doesn't make sense why youtube-dl isn't accepting the full path with "--external-downloader". Seems like it's probably just a simple oversight to me.

For example, the batch script below works just fine and aria2c is correctly being called from my "D:\Temp\aria2c" folder...
`@echo off`
`set path=%path%;D:\Temp\aria2c`
`youtube-dl.exe --external-downloader=aria2c http://www.website.com/video.mp4`

However. this batch script below doesn't work when I use the full path with "--external-downloader" instead of using the %path% variable...
For example, the batch script below works just fine and aria2c is correctly being called from my "D:\Temp\aria2c" folder...

`@echo off`
`youtube-dl.exe --external-downloader="D:\Temp\aria2c\aria2c.exe" http://www.website.com/video.mp4`

None of the syntax's below are working....
`"D:\Temp\aria2c\aria2c.exe"`
`"D:\\Temp\\aria2c\\aria2c.exe"`
`"D:/Temp/aria2c/aria2c.exe"`

**Comment by barsnick** [comment]
The ```--external-downloader``` is not designed to take a path, it takes a name and checks that against the internal list of supported downloaders. (I'm not saying this couldn't be changed, I'm just saying what [the current implementation does](https://github.com/ytdl-org/youtube-dl/blob/71f47617c8845900c1a3c2da79f9f7654199fedb/youtube_dl/downloader/external.py#L366)).

The option certainly needs to _understand_ which tool it is given on the command line, in order to apply the correct options.

**Comment by SwiftMove** [comment]
That's exactly what I figured the issue was. Thank You for confirming.

**Comment by pukkandan** [comment]
yt-dlp has an implementation to allow full paths https://github.com/yt-dlp/yt-dlp/commit/7f7de7f94dfeacb0eb78cb9487dfcaf5707da381 https://github.com/yt-dlp/yt-dlp/commit/e1eabd7beb4cc83338a7422546ae1c9ae8b2097f

This doesn't work for ffmpeg since it has it's own option
