### ISSUE TITLE
Empty descriptions on YouTube are replaced with the string "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube."

### ISSUE THREAD

**Issue by 0x9fff00** [ytdl-org/youtube-dl#26006]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ python -m youtube_dl -v --get-description https://www.youtube.com/watch?v=dCO8fj_DQQo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--get-description', 'https://www.youtube.com/watch?v=dCO8fj_DQQo']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Git HEAD: a115e0759
[debug] Python version 3.8.3 (CPython) - Linux-5.7.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.
```

## Description

As @libjared pointed out in a [comment](https://github.com/ytdl-org/youtube-dl/issues/25937#issuecomment-657477902) on #25937 (#25980 fixed points 2 and 3 but not 1), empty descriptions on YouTube are now replaced with the string "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.".

**Comment by libjared** [comment]
I have a set of >4000 info JSONs from around May 9th, way before YT broke things.
I did a diff between those descriptions and the descriptions created by the current version of YTDL. These are the differences (not necessarily defects) that I found between them:

## 1. This issue - No-description videos now use a generic tagline

[Example](https://www.youtube.com/watch?v=4Xdfo9RYXQ0):

```diff
-    "description": ""
+    "description": "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube."
```

An empty string seems more correct to me.

## 2. What was `\n` is now `\r\n`, but only for some examples
[Example of change](https://www.youtube.com/watch?v=-YGwRL60klo):

```diff
-     "description": "I guess this is why Falco prefers the air.\n\nHigher quality\n\n..."
+     "description": "I guess this is why Falco prefers the air.\r\n\r\nHigher quality\r\n\r\n..."
```

[Example of no change](https://www.youtube.com/watch?v=4txVqr1eNwc):

```
     "description": "Cool Guy 2 - Out Now!\n\nHigh Quality Song Download: http://devinmontes.bandcamp.com/track/cool-guy\n\nJust Cool Guy doin' what he do best!"
```

I think we should apply `sed s/\r\n/\n/g` to the description, always.

## 3. The original language description is used instead of the translated one

[Example](https://www.youtube.com/watch?v=yCHwmvDYKe8):

```diff
-    "description": "Song:  O-Ku-Ri-Mo-No Sunday! (Game ver.)\nUnit Name: miroir..."
+    "description": "曲名：O-Ku-Ri-Mo-No Sunday！ (Game ver.)\nユニット名：miroir..."
```

This is a weird side effect. I'm not sure which one I'd prefer. It would be fantastic if we picked just one of the descriptions for most cases, and for `--write-info-json` scrape *all* translated descriptions and place them in an JSON object keyed by language.

## Other minor changes
4. YouTube links are no longer auto-corrected. Old behavior was to scrub off subdomains like ca.youtube.com, make them https, or to remove the old &fmt=18 hack. New behavior is the original link as entered. I prefer it like this.
5. Trailing whitespace behind some newlines is added on some examples.
6. Quotes and parentheses characters surrounding the entire description were trimmed off sometimes. This is fixed.
7. Zalgo-text is very different on the byte level, but surprisingly looks the same.
