### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by )

### ISSUE THREAD

**Issue by Hyper-hi** [ytdl-org/youtube-dl#26378]
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by ); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the verbose flag and include its complete output.

**Comment by ReactionaryFuture** [comment]
Yes same here.

`youtube-dl https://www.youtube.com/channel/UCMRs0Ml8RF0cWVAOeQeBxTw --download-archive archive.txt -o '%(uploader)s_%(upload-dates)_%(title)s.%(ext)s' --restrict-filenames --merge-output-format mkv --ignore-errors --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/channel/UCMRs0Ml8RF0cWVAOeQeBxTw', '--download-archive', 'archive.txt', '-o', '%(uploader)s_%(upload-dates)_%(title)s.%(ext)s', '--restrict-filenames', '--merge-output-format', 'mkv', '--ignore-errors', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.0 (CPython) - Linux-4.15.0-54-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube:channel] UCMRs0Ml8RF0cWVAOeQeBxTw: Downloading channel page
[youtube:playlist] UUMRs0Ml8RF0cWVAOeQeBxTw: Downloading webpage
[download] Downloading playlist: Uploads from Dr. Edward Dutton: The Jolly Heretic
[youtube:playlist] playlist Uploads from Dr. Edward Dutton: The Jolly Heretic: Downloading 49 videos
[download] Downloading video 1 of 49
[youtube] dBf2I71F-mU: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)`

**Comment by kietheros** [comment]
- Use --force-ipv4
- Youtube can block your IP. Try using proxy.

**Comment by M4T14SG4M3R** [comment]
Same here. The problem is that i use pterodactyl with sinusbot and it uses docker, so there is no /etc/youtube-dl.conf file and sinusbot does not allow to modify the sinusbot command, how i can use youtube-dl with those argumenta without the youtube-dl.conf file?
