### ISSUE TITLE
How is the windows binary created?

### ISSUE THREAD

**Issue by ohnekopf** [ytdl-org/youtube-dl#26466]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

This is just a simple question I'm asking out of curiosity, I'd Like to know how the youtube-dl Windows executable is 'compiled' , and if this can be done from source from a Windows (or Linux) machine
cheers!

**Comment by blackjack4494** [comment]
`python3 -m pip install pyinstaller`
`pyinstaller youtube_dl\__main__.py --onefile --name youtube-dl`

The official windows executable is generated using py2exe as far as I kmow. But it's basically deprecated. There is some community successor under the same name supporting python3.4+ but `pyinstaller` will do the job.

**Comment by zackmark29** [comment]
@blackjack4494 is that pyinstaller is included already after installing python?

Can I compile only selected extractor? like Viki?

**Comment by blackjack4494** [comment]
@zackmark29 shouldn't be installed by default that is why I wrote that explicitly.
For your second question. I don't think that is possible out of the box. You could delete or move all other extractors somewhere else (but the base extractors `common*.py`)
Or write your own viki downloader without relying on youtube-dl which isn't that difficulty actually - especially for viki since they have an api. If you looking for something in python I can give you this [gist](https://gist.github.com/blackjack4494/3dfc0aa2b8920cc17ce9e70174620fda#file-viki_test-py) as a starting point. I already made some more modifications on it locally to test some api calls (e.g. for subtitles etc). Since I noticed you mainly use C# you can probably easily port python to c# and vice versa as the languages are quite similar when coding.

**Comment by zackmark29** [comment]
> @zackmark29 shouldn't be installed by default that is why I wrote that explicitly.
> For your second question. I don't think that is possible out of the box. You could delete or move all other extractors somewhere else (but the base extractors `common*.py`)
> Or write your own viki downloader without relying on youtube-dl which isn't that difficulty actually - especially for viki since they have an api. If you looking for something in python I can give you this [gist](https://gist.github.com/blackjack4494/3dfc0aa2b8920cc17ce9e70174620fda#file-viki_test-py) as a starting point. I already made some more modifications on it locally to test some api calls (e.g. for subtitles etc). Since I noticed you mainly use C# you can probably easily port python to c# and vice versa as the languages are quite similar when coding.

THank you for that @blackjack4494 .  I'll check it out. Yes my mainly Language is C#. I'm actually learning basic Python codes. But I'm not totally want to code on python rather I want to undestand the flow of  the code. so that I can easily convert to C# code
