### ISSUE TITLE
Youtube Music Mixes not downloading correctly

### ISSUE THREAD

**Issue by gnations56** [ytdl-org/youtube-dl#26509]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v --download-archive downloaded.txt -x --audio-format mp3 -o "%(artist)s/%(album)s/%(title)s.%(ext)s" "https://m
usic.youtube.com/playlist?list=RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI&feature=share&playnext=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--download-archive', 'downloaded.txt', '-x', '--audio-format', 'mp3', '-o', '%(artist)s/%(album)s/%(title)s.%(ext)s', 'https://music.youtube.com/playlist
?list=RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI&feature=share&playnext=1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:playlist] RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI
[youtube:playlist] playlist RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCLAK5uy_kx0d2-VPr69KAkIQOTVFq04hCBsJE9LaI

## Description

When I try to download a mix from youtube music, youtube-dl finds no videos. The link below works fine in the browser
https://music.youtube.com/playlist?list=RDCLAK5uy_k27uu-EtQ_b5U2r26DNDZOmNqGdccUIGQ

**Comment by bubbleguuum** [comment]
That supposed fix (after patching youtube.py) does not work for me, with "https://m
usic.youtube.com/playlist?list=<id>&feature=share&playnext=1" style URLs, with 0 items always returned in the resulting Playlist.

**Comment by W4lv1s** [comment]
Doesn't work for me either.   
Command

youtube-dl -i --audio-format=mp3 https://www.youtube.com/playlist?list=RDI85acNP2egM -vv            
Error:
[youtube:playlist] playlist RDI85acNP2egM: Collected 0 video ids (downloading 0 of them)

Playlist/mix works fine in a browser

**Comment by Kite1024** [comment]
Experiencing the same issue: Command+Output:

youtube-dl.exe -f bestaudio RDY1Bx0b0394M --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', 'RDY1Bx0b0394M', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-08-12-bb59bdb, ffprobe git-2020-08-12-bb59bdb
[debug] Proxy map: {}
[youtube:playlist] RDY1Bx0b0394M: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDY1Bx0b0394M
[youtube:playlist] playlist RDY1Bx0b0394M: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDY1Bx0b0394M

---

The issue is specifically with youtube-mixes, have not had an issue with other playlists so far.

I noticed I am unable to visit the mix posted by W4lv1s, so I though maybe it's a session issue. So I have also tried using the cookies from the session where the mix was made but to no avail. (output below)

---

youtube-dl.exe --cookies cookies.txt -f bestaudio RDY1Bx0b0394M --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-f', 'bestaudio', 'RDY1Bx0b0394M', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-08-12-bb59bdb, ffprobe git-2020-08-12-bb59bdb
[debug] Proxy map: {}
[youtube:playlist] RDY1Bx0b0394M: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDY1Bx0b0394M
[youtube:playlist] playlist RDY1Bx0b0394M: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDY1Bx0b0394M

**Comment by Kite1024** [comment]
This does not seem fixed, when I just tried the above again it failed.
---
youtube-dl.exe -f bestaudio RDY1Bx0b0394M --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', 'RDY1Bx0b0394M', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-12-bb59bdb, ffprobe git-2020-08-12-bb59bdb
[debug] Proxy map: {}
[youtube:tab] RDY1Bx0b0394M: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\youtube.py", line 2951, in _real_extract
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
