### ISSUE TITLE
Twitch - ERROR: Failed to download m3u8 information: <urlopen error _ssl.c:835: The handshake operation timed out> 

### ISSUE THREAD

**Issue by kolt54321** [ytdl-org/youtube-dl#26687]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[download] Downloading video 16 of 487
[twitch:vod] 701585716: Downloading video info JSON
[twitch:vod] 701585716: Downloading vod access token
[twitch:vod] 701585716: Downloading m3u8 information
ERROR: Failed to download m3u8 information: <urlopen error _ssl.c:835: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:835: The handshake operation timed out',),))
  File "/home/Li/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/Li/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/Li/.local/lib/python3.6/site-packages/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
```

## Description

Twitch videos seem to fail with the above error across multiple channels. I've made sure the channel video links are accessible, and youtube videos don't have this issue (even longer ones).

**Comment by BlazinWings** [comment]
For anyone like me searching for this issue in the future, the problem is best fixed by passing cookies through YDL. Here's the quote from the ReadMe.
Use the --cookies option, for example --cookies /path/to/cookies/file.txt.
In order to extract cookies from browser use any conforming browser extension for exporting cookies. For example, Get cookies.txt (https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/) (for Chrome) or cookies.txt (https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) (for Firefox).
Note that the cookies file must be in Mozilla/Netscape format and the first line of the cookies file must be either # HTTP Cookie File or # Netscape HTTP Cookie File. Make sure you have correct newline format (https://en.wikipedia.org/wiki/Newline) in the cookies file and convert newlines if necessary to correspond with your OS, namely CRLF (\r\n) for Windows and LF (\n) for Unix and Unix-like systems (Linux, macOS, etc.). HTTP Error 400: Bad Request when using --cookies is a good sign of invalid newline format.
Passing cookies to youtube-dl is a good way to workaround login when a particular extractor does not implement it explicitly. Another use case is working around CAPTCHA (https://en.wikipedia.org/wiki/CAPTCHA) some websites require you to solve in particular cases in order to get access (e.g. YouTube, CloudFlare).
