### ISSUE TITLE
ERROR: No video formats found

### ISSUE THREAD

**Issue by BlueAquan** [ytdl-org/youtube-dl#26729]
Trying to download a video on Ubuntu 20.04 and youtube-dl throws up this error.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-formats', '--verbose', 'https://youtu.be/wH8Ajv_6Xj4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-48-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wH8Ajv_6Xj4: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by u2n** [comment]
Getting this exact output (only different vid id). This only happens with some vids, not all. Last fail was OGK- jEZ- 1e248 (without dashes and spaces. No apparent difference in webpages that work and those that don't. Strange.

**Comment by pukkandan** [comment]
> Make sure you are using the latest version; see https://yt-dl.org/update on how to update.

**Comment by u2n** [comment]
Don't all users go through that? That is: Receive error, hunt around for cause, find possibility of need for update, do update, find that fixed it, remind self to *always* update before using. Then next time, forget to update (of course, because too many things on mind), get error, remember last time update fixed it, update, error gone again. Then next time, just update before using program. No more errors. Done.

Except this time, updates don't fix. "This only happens with some vids..."

Just checked update, still current, noted vid still throws same error.

**Comment by pukkandan** [comment]
@u2n 
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

@BlueAquan gave log, but his version was outdated.
On the other hand, you didn't give any logs, so how can you expect anyone to help?

**Comment by u2n** [comment]
@pukkandan, the logs were almost identical, as I indicated, but thanks for the smack which led to discovery of the problem:

Two versions were installed, one the same as @BlueAquan in /usr/bin -- which IS outdated -- and the latest in $HOME/.local/bin. (Not sure how that happened since I always update with 'pip3 install --upgrade youtube-dl'.)

Even though the latest version was installed, the older version was being run.

Fixed by uninstalling both versions and reinstalling latest (now in /usr/local/bin). Everything back to normal so all good.

Interesting that the older version still worked on many vids. Multiple versions might have been the source of @BlueAquan's trouble too. Anyways, if this were my issue, I'd close it now.
