### ISSUE TITLE
What will happen with blackjack4494 (and many other) fork's progress?

### ISSUE THREAD

**Issue by bruwalfas** [ytdl-org/youtube-dl#27008]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

First of all, I want to say I'm very glad the original project came back. And I'm also glad that, while the big boys weren't home, some people still gathered, and have made a lot of progress solving bugs, developing support for some more websites, and probably a lot more.

Having said that, what will happen with all of the changes made during the time this repo was taken down? I speak mostly because of the repo I know from @blackjack4494, but I'm sure there's a lot more whose commits are equally valuable to the project. Are you planning on merging them, or something similar?

Again, congrats on your comeback, and cheers.

**Comment by hiqua** [comment]
The fork you mentioned existed before the repo was taken down, so it's not related.

**Comment by Matterhorn56** [comment]
It has been merging in fixes and features that ydl did not, even though ydl could have merged them in when the came ages ago.
It seems that they are merging in at a rapid rate ever since the DMCA situation, almost like a response to people realizing that ydlc was better than ydl. But jibes aside, it seems that at this rate, ydl can potentially surpass ydlc - but until then I'm sticking to ydlc
