### ISSUE TITLE
[Vimeo Showcase] ERROR: Unable to extract bootstrap data 

### ISSUE THREAD

**Issue by vpbonillas** [ytdl-org/youtube-dl#27079]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

Hello,

I tried to download the audio from a video protected by a password. I have updated youtube-dl to the latest version, but the problem persists. A previous issue related to Vimeo Showcase was reported but it seems there is not yet a solution Vimeo [Showcase not downloading #26329 ](https://github.com/ytdl-org/youtube-dl/issues/26329)

I paste below the first try, with out using `--force-generic-extractor `:

`~$ youtube-dl -v -x --audio-format flac --video-password forets https://vimeo.com/showcase/7774146
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'flac', u'--video-password', u'PRIVATE', u'https://vimeo.com/showcase/7774146']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[vimeo:album] 7774146: Downloading webpage
ERROR: Unable to extract bootstrap data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 952, in _real_extract
    webpage, 'bootstrap data'), album_id)['viewer']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract bootstrap data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

And this is the output when using the `--force-generic-extractor `:

`~$ youtube-dl -v -x --audio-format flac --force-generic-extractor --video-password forets https://vimeo.com/showcase/7774146
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'flac', u'--force-generic-extractor', u'--video-password', u'PRIVATE', u'https://vimeo.com/showcase/7774146']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] 7774146: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 7774146: Downloading webpage
[generic] 7774146: Extracting information
ERROR: Unsupported URL: https://vimeo.com/showcase/7774146
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2388, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3381, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://vimeo.com/showcase/7774146
`

It seems then that showcase vimeo URL are not supported by youtube-dl.

Thanks.

**Comment by vpbonillas** [comment]
Hi @remitamine , 
Please accept my apologies, yesterday when I first posted the issue I did not read the template. 
I have updated it, carefully following the rules. I hope I did it correctly.
Thanks.

**Comment by vpbonillas** [comment]
Hi,

May I ask why this is still incomplete?

**Comment by remitamine** [comment]
forgot to update the labels, the fix will be available in the next version.

**Comment by someziggyman** [comment]
@remitamine a sight improvement may be needed in this "showcase" issue. 
Show case URLs can have a format of "direct" link to showcase video: https://vimeo.com/showcase/6733390/video/389861851

Right now link of type: https://vimeo.com/showcase/6733390 are working fine, but "direct link" to showcase video gives a following ytdl output:

_ERROR: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./vydl/youtube_dl/extractor/vimeo.py", line 658, in _real_extract
    config = json.loads(config)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)
Traceback (most recent call last):
  File "./vydl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./vydl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./vydl/youtube_dl/extractor/vimeo.py", line 671, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output._

**Comment by remitamine** [comment]
you have reported this problem before, I'm not planning to work on it now.

**Comment by someziggyman** [comment]
> you have reported this problem before, I'm not planning to work on it now.

oh, OK. I understand. Just thought it's worth mentioning. Appreciate your hard work with these fixes! cheers
