### ISSUE TITLE
Error when try to download video from Facebook

### ISSUE THREAD

**Issue by hellishvictor** [ytdl-org/youtube-dl#27329]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '-v', '--verbose', 'https://www.facebook.com/1
00003347374780/videos/3493885574066321/', '-o', 'D:/+/%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.07
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[facebook] 3493885574066321: Downloading webpage
[facebook] 3493885574066321: Downloading webpage
[facebook] 3493885574066321: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Ma
ke sure you are using the latest version; type  youtube-dl -U  to update. Be sur
e to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc
4o\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc
4o\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc
4o\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc
4o\build\youtube_dl\extractor\facebook.py", line 484, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc
4o\build\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtub
e-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.

```

## Description

Hi, today I noticed that now it doesn't download a video from facebook (here is [the link](https://www.facebook.com/100003347374780/videos/3493885574066321/)). I did the update, but still the same.
Cheers.

**Comment by october262** [comment]
says content not available right now.

**Comment by hellishvictor** [comment]
Is a private group and only members can see the content; since I'm member, I can see it.

**Comment by october262** [comment]
> 
> 
> Is a private group and only members can see the content; since I'm member, I can see it.

play the video and see if there's 3 dots ... in the upper right hand corner of the video
click on the three dots ... and there should be an option to copy the URL, use that link
and see if you are able to download the video.

**Comment by hellishvictor** [comment]
That's how I got the link included here xD

**Comment by dim0147** [comment]
If you want to download for usage not auto, there are many extensions for this, I'm using this one it's work good https://chrome.google.com/webstore/detail/dyl-download-facebook-vid/honmapcmnfgjmahijdniaaollhhfpcnj

**Comment by gpvos** [comment]
Same here with https://www.facebook.com/699242144/videos/10158793208827145/ (also in a private group; I convert my Firefox cookies to cookie.jar format and pass the cookie file with the --cookies option). youtube-dl version 2020.12.09. Also had it a week or so with another Facebook video. Essentially the same stack backtrace.

**Comment by hellishvictor** [comment]
> 
> 
> I convert my Firefox cookies to cookie.jar format

How?

**Comment by gpvos** [comment]
I have a script for that; I'll publish it sometime.

**Comment by gpvos** [comment]
There you go: https://github.com/gpvos/cookie-sqlite-to-jar/blob/main/cookie-sqlite-to-jar

**Comment by hellishvictor** [comment]
How I do to make that run? I use a Firefox (portableapp version) which store the cookies.sqlite file on Firefox\Data\profile\

**Comment by gpvos** [comment]
Follow the instructions in the file itself. It's a command line program, you need Perl installed and then you can do "perl cookie-sqlite-to-jar inputfile outputfile", or install it into your path; educate yourself. For further questions, please ask over there; it's off-topic here.

**Comment by hellishvictor** [comment]
Yeah, I have noticed a minute ago its in Perl... now I think I can live without that video xD Hope that youtube-dl get it fixed somehow soon. Thank you anyway for upload the script and share it here, man.

**Comment by bonacker1** [comment]
Here is a workaround that worked for me that might be useful until Youtube-dl fixes its Facebook extractor.

1. Go to the video you want to livestream or download. If the video is on a page with other videos, get it on a page by itself by clicking  the time stamp for the video you want. If it's a live video that just started, it will say "Just Now" instead of an hour or a date.

2. Go to the html source code for that page. In most browsers, it's ctrl-U. In some mobile browsers you can prefix the URL of the page with "view-source:"

3. In the HML code, search for "videoID." It should be a 15 digit number with no letters or special characters. This number appears several times in the source. The "videoID" search seemed to be the most reliable search to find it. The number you're looking for may not be proximate to all the "videoIDs." Hit enter or click next to find the number. The number was also seen after "container_id" but not in every video I tested. The string you're looking for may look like this: "quot;videoID&quot;:&quot;876216249851731"

4. Use this template https://m.facebook.com/story.php?story_fbid=xxxxxxxxxxxxxxx&id=1 where the 15 x's are that videoID #.

An alternative URL template could be: https://www.facebook.com/[name of facebook page]/videos/[videoID #]


5. The URL you made in step 4 should work in youtube-dl. I was usng the latest version 12.9.2020.

I tried this out in 4 or 5 live Facebook videos and it worked in all of them. Older FB videos (maybe ones as recent as 4 or 5 days ago) don't need this. I think all new FB videos will require this.

I tried to follow the YT-DL issues for this FB change without success. Most posts by users who reported the change were labeled "duplicate," but I was unable to find the original post despite a great deal of searching. It seems to me like the YT-DL coders make it more difficult to follow for average users than necessary. They under-communicate, imo.

I saw no issue that stated that this change would be incorporated in the next version. I saw nothing useful in the issues other than users reporting the problem.

This reminds me of the C-Span problem. There was some discussion in the issues about why C-Span videos were no longer downloadable in YT-DL, but it took two or three YEARS before the C-Span extractor was updated. I just noticed that C-Span videos finally work in YT-DL.

**Comment by hellishvictor** [comment]
Now, with the latest version [2020.12.12](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.12.12) is possible do it: adding the parameters "-u" (or "--username") YOURUSERNAMEOREMAIL and "-p" (or "--password") THEPASSWORD it works like a charm :) Thank you to the developer and you all!
