### ISSUE TITLE
Downloading videos from members section of site (videos hosted on vimeo)

### ISSUE THREAD

**Issue by rvrvgithub** [ytdl-org/youtube-dl#27514]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Iam trying to archive videos for offline viewing from an online seminar I purchased. 

The videos are played from the private members section of the seminar webpage.

I login to seminar members section and click on videos that are streamed from Vimeo servers.

The actual links are pointing to Vimeo. 
URLs extracted from seminar HTML look like https://player.vimeo.com/video/######### (video number removed for privacy)

When i try to open the video directly in a browser tab i get error:
**"Sorry. Because of its privacy settings, this video cannot be played here."**

When i try to open it in youtube-dl by command:
_ytdl -F https://player.vimeo.com/video/#########_
i get this error:
**ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.**

I tried to google the error message or ytdl documentation of options, but couldnt find anything about "embeding", other than embeding ytdl as command into a python script - thats not on the topic.

Once I login to seminar members section with my login credentials. The seminar page is running a player script that pre-authenticates itself in background to Vimeo servers. A trust is established and Vimeo lets the browser play the videos.
However when i try to open the plain video URL in a new tab or ytdl the pre-authentication is not there so i get refused that the video is private.

Is there any way to download these videos ?

**Comment by avelican** [comment]
Why was this closed? This still doesn't work.

Example page: https://www.flowsummitcroatia.com/day-4/

Note, this link will only work for a short time (which is of course the whole point of downloading it via youtube-dl).

View page source, ctrl+f "vimeo" reveals the URLs, eg. https://player.vimeo.com/video/707335550
Opening them in a new tab gives the error **"Sorry. Because of its privacy settings, this video cannot be played here."**

Putting the vimeo URLs into youtube-dl gives `ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.`

Copying the embedding page url (example page above) into youtube-dl gives `ERROR: Unsupported URL`

**Comment by 89z** [comment]
you should comment on an open issue, or open a new issue
