### ISSUE TITLE
Some STV Player downloads (only numbers after episode) fail to download

### ISSUE THREAD

**Issue by TIGHazard1** [ytdl-org/youtube-dl#27630]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
NOT WORKING URL

youtube-dl.exe -v https://player.stv.tv/episode/4171/pride-of-scotland
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.stv.tv/episode/4171/pride-of-scotland']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[stv:player] 4171: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

WORKING URL

youtube-dl.exe -v https://player.stv.tv/episode/416h/emmerdale
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.stv.tv/episode/416h/emmerdale']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[stv:player] 416h: Downloading JSON metadata
[brightcove:new] 6218771372001: Downloading JSON metadata
[brightcove:new] 6218771372001: Downloading JSON metadata
[brightcove:new] 6218771372001: Downloading m3u8 information
[brightcove:new] 6218771372001: Downloading m3u8 information
[brightcove:new] 6218771372001: Downloading m3u8 information
[brightcove:new] 6218771372001: Downloading m3u8 information
[brightcove:new] 6218771372001: Downloading MPD manifest
[brightcove:new] 6218771372001: Downloading MPD manifest
[brightcove:new] 6218771372001: Downloading MPD manifest
[brightcove:new] 6218771372001: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://manifest.prod.boltdns.net/manifest/v1/hls/v3/clear/1486976045/a377aec0-a06a-4753-bc32-bc1df2f31e7c/b8a4f60b-8982-4f8a-91ca-bf6e4f0ce116/2b70927e-ad9e-429e-8088-1be62f8ba229/10s/rendition.m3u8?fastly_token=NjAxNTQ3NWRfMjc4Y2FhNDFmNjZkYTEzMzgwYTAyMWFhMzU4OWQ1ODdhYTk2NzUzMDRjOTZjMjE3ZWU0YmU4MmYzOGRjOTRhNA%3D%3D'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 281
[download] Destination: Emmerdale - Friday, January 1, 2021-6218771372001.mp4
[download] 100% of 1.24GiB in 02:04

```

## Description

Some STV Player videos fail to download. Seems to only be ones with all numbers after episode. Previous requests have said this service needs an account but that may just be to browse the website itself. (registration requires a Scottish postcode)

**Comment by dstftw** [comment]
>Please sign in to your STV account. If you don't have an account, create one now for free.

**Comment by TIGHazard1** [comment]
Except I am signed in. Otherwise stuff like Emmerdale, Coronation Street, The Chase or Tipping Point surely wouldn't download.

WORKING URL'S

https://player.stv.tv/episode/416l/tipping-point

https://player.stv.tv/episode/416j/the-chase

https://player.stv.tv/episode/416h/emmerdale

https://player.stv.tv/episode/416i/coronation-street

NON WORKING URL'S

https://player.stv.tv/episode/4171/pride-of-scotland

https://player.stv.tv/episode/4166/billy-connolly-pleasure

**Comment by Vangelis66** [comment]
With all due respect :smile_cat: , this isn't an `invalid` bug report, but rather a **duplicate** of https://github.com/ytdl-org/youtube-dl/issues/23083, 
which was filed more than a year ago... 

I myself was recently bitten by this bug twice, latest time when trying to fetch:  

https://player.stv.tv/episode/4125/jennifer-saunders-memory-lane

(will expire on **24 Dec 2021**, so it's a perfect test case...). 

 As both @TIGHazard1 and @james-wallace-ghub (before him) have detailed, the STVplayer InfoExtractor chokes only on programmes whose 4-character ID contains ALL four numbers (i.e. NO letters). 
You don't otherwise need account credentials to download from STVPlayer (just be in one of the whitelisted regions). Though I understand an STV account _might_ be needed for a dev to troubleshoot this further; @remitamine, you were the one to create the STV-IE to begin with, could you be once more kind enough to investigate? (I can supply STV account credentials, if asked by the devs, but **not here, in a public** spot...).

yt-dl (**2021.01.03**) states:

`ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found`

but my browser is indeed able to make the `GET HXR` request to: 

https://player.api.stv.tv/v1/episodes/jennifer-saunders-memory-lane-20201223-2100/?groupToken=0071

![STVbug](https://user-images.githubusercontent.com/9669492/103472720-58cb8500-4d99-11eb-9639-6e10d4832c0a.JPG)

As a side note, STV-IE uses **brightcove:new** IE under the hood, but I don't think the latter is linked, because yt-dl chokes right from the start...

Kindest regards :smile:

**Comment by remitamine** [comment]
support for this URLs will be included in the next version.

**Comment by Vangelis66** [comment]
> support for this URLs will be included in the **next** version.

Your **promptness** and **high expertise** are greatly appreciated :+1: :+1: 
I just took a look into https://github.com/ytdl-org/youtube-dl/commit/ac71fd5 and it wasn't an easy fix either... 
Many congrats!

I just compiled from the **master** branch (py3.7.9, pyinstaller 4.1) 
and your fix works magnificently here: 

`youtube-dl -F "https://player.stv.tv/episode/4125/jennifer-saunders-memory-lane" -v > verbose-stv-log.txt 2>&1`

=> [verbose-stv-log.txt](https://github.com/ytdl-org/youtube-dl/files/5762400/verbose-stv-log.txt)

All the best!

PS: For completeness, could the `invalid` label here be replaced with a `duplicate` one?
