### ISSUE TITLE
The script at https://yt-dl.org/downloads/latest/youtube_dl doesn't works at Ubuntu 20.04.

### ISSUE THREAD

**Issue by DNonov** [ytdl-org/youtube-dl#27649]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.01.03**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
/usr/bin/env: 'python': No such file or directory
```

## Description

The script at
https://yt-dl.org/downloads/latest/youtube_dl use 'python' binary which
is not existing at Ubuntu 20.04 and this introduces a bug that the
script cannot find the 'python' binary. The only python binaries by
default are 'python3, python3.8, python3-futurize, python3-pasteurize'.
So simple symbolic link can solve the issue.

Since there is no support for "python 2" anymore. I think this bug
exist in many OS's and further investigation is needed.

**Comment by dstftw** [comment]
That's not a problem of youtube-dl.

**Comment by DNonov** [comment]
However this is not a problem of youtube-dl, IMO additional information about the problem is valuable. I've just submitted a pull request that updates the installation guide at README.md. #27650.

**Comment by Kikobeats** [comment]
IMO youtube-dl should handle this.

Ubuntu is shipping python3 for a good reason: it wants to be sure you know what version of python you are using.

So `youtube-dl` could try to be a bit smart there, trying to get python binary as `python3` or `python2` or `python` as python binary fallbacks.

In fact, in this way, `youtube-dl` could easily choose a more modern python build as preferred rather than a slow python compiler version.

**Comment by rautamiekka** [comment]
^ The recurrence, the fact ppl can't google, and the fact distros are being dicks are exactly the reasons why something has to be done.

But that'll be problematic cuz the way the mentioned "binary" is created you can't target Py2 and 3 with the same line, and you can't have multiple shebangs, and you can't have any code before the shebang.

^ The only way to circumvent that is a db of default Python versions (2 or 3, no need for stricter) for the script which creates the "binary". Which, to be blunt, is gonna be an impossible cat-and-mouse.

^ And don't get me started on the CI using separate distros running [near-]identical scripts.

**Comment by MichaIng** [comment]
I see the problem, but in fact `youtube-dl` on most current distros by default currently causes this error or calls deprecated Python 2 while supported Python 3 might be installed but not used.

What about dropping Python 2 support and explicitly required Python 3 by using `/usr/bin/env python3` shebang?

**Comment by Kikobeats** [comment]
If you are under a Node.js project, consider using [youtube-dl-exec](https://github.com/microlinkhq/youtube-dl-exec) since it [checks](https://github.com/microlinkhq/youtube-dl-exec/blob/master/package.json#L81) for python version before installing the dependency, throwing an error if the right Python version is not found.
