### ISSUE TITLE
Will you drop support for python2?

### ISSUE THREAD

**Issue by ccapitalK** [ytdl-org/youtube-dl#27655]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Are there any plans to drop support for python2? It's been over a year since it has become EOL, and I haven't been able to find anything on how long python2 support will be extended beyond that date. I know that it must be a pain to write code to work on both python2 and python3, so I was just wondering what the plan is in case it will be deprecated soon.

**Comment by dstftw** [comment]
No plans to drop python 2 support sooner than RHEL/CentOS do that (2024). Anyway most of the differences between python versions are hidden behind compat routines long time ago and don't make much trouble.

**Comment by rautamiekka** [comment]
And according to [DistroWatch's package search](https://distrowatch.com/search.php?pkg=Python&relation=similar&pkgver=2.*&distrorange=InLatest#pkgsearch), openSUSE Tumbleweed will be using 2.7.18 (or at least defaulting to) instead of 15.2's 3.6.10, which already is stupidly old. It's a very popular distro, so that's also a blocker.

**Comment by ccapitalK** [comment]
Thank you for the quick response!
