### ISSUE TITLE
ceskatelevize.cz is not working anymore

### ISSUE THREAD

**Issue by batoo696** [ytdl-org/youtube-dl#27677]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.01.03**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ceskatelevize.py", line 201, in _real_extract
    self._sort_formats(e['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

WRITE DESCRIPTION HERE
Download stopped working, I was able to download from the site approx. 2 weeks before.

https://www.ceskatelevize.cz/porady/11346647457-bozena/218512120070001/
This link doesn't work.

**Comment by fossdd** [comment]
Hmm, the error is passing here:

https://github.com/ytdl-org/youtube-dl/blob/430c4bc9d02b49e180309dc55c62b96d5cada535/youtube_dl/extractor/ceskatelevize.py#L201

But i'm wondering that youtube-dl uses the `CeskaTelevizeIE`-Class

https://github.com/ytdl-org/youtube-dl/blob/430c4bc9d02b49e180309dc55c62b96d5cada535/youtube_dl/extractor/ceskatelevize.py#L22-L23

instead of the `CeskaTelevizePoradyIE` Class which maybe works:

https://github.com/ytdl-org/youtube-dl/blob/430c4bc9d02b49e180309dc55c62b96d5cada535/youtube_dl/extractor/ceskatelevize.py#L241-L242
