### ISSUE TITLE
Odd behaviour of project maintainers

### ISSUE THREAD

**Issue by cypheron** [ytdl-org/youtube-dl#27691]
It's obvious the two main maintainers of this project can't keep up with the backlog. I have two questions regarding to that:
1) Why do you not seek additional help for working on the issues and PR's?
2) Why is @dstftw stalling/discouraging potential contributors by posting "Read coding conventions" under every single new feature PR without ever commenting on the actual code? That is plain rude behavior. Not a single new feature has been merged in the last months, so if he / you guys are busy with other stuff, why comment at all? 

I love the yt-dl project and I love that it's back alive. I love the work that's being put into it. I'd be very happy to see my questions answered.

**Comment by llacb47** [comment]
> 2\. Not a single new feature has been merged in the last months

https://github.com/ytdl-org/youtube-dl/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged

**Comment by dstftw** [comment]
1. What concretely do you mean by "additional help"? Anyone is free to help by answering issues/reviewing PRs, no approval is required from maintainers for that. As for adding more maintainers, I've already mentioned that currently I don't see candidates with enough expertise who can be trusted with write access to the repo and who is willing to contribute on more or less regular basis.
2. I don't see much point wasting time by retyping the same portions of coding conventions for every other PR over and over again just because someone doesn't want to bother reading new PR template and documents linked. I don't think this is rude, what's really rude is to send PRs completely ignoring established rules.
>Not a single new feature has been merged in the last months

That's not true, see git log.

**Comment by cypheron** [comment]
1. You don't see or you don't want to see? Judging from your poor code reviews I would assume the latter.
2. Yes, it's rude and weak judgement to assume that people don't read the conventions in fact they do. Also you just made up the part that rules are "completely ignored", people said they followed the rules and you couldn't name even one thing that was off.

The git log does not contain any recent merges for additional features adding support for new extractors.

**Comment by cypheron** [comment]
Also very unprofessional how you closed this issue so quickly without waiting for the answer to your first question and waiting for follow up questions. Nice demonstration on how NOT to handle feedback.

**Comment by cypheron** [comment]
Just an example how tedious the process of merging with @dstftw can be: https://github.com/ytdl-org/youtube-dl/pull/20618. The contributor virtually had to beg for over a year to get the PR merged. It's absolutely ridiculous.

**Comment by dstftw** [comment]
Then go and do your own non-poor and highly "professional" reviews for free and we'll see for how long you'll last.
Fed the troll.
