### ISSUE TITLE
ERROR: Unable to download m3u8 information for sub-only Twitch VODs

### ISSUE THREAD

**Issue by andrew1-1** [ytdl-org/youtube-dl#27832]
When I try to download Twitch sub-only VODs using --cookies I get this: **ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError())** 
I tried do download to different sub-only VODs from the same Twitch channel but I get the same error. Unfortunately I can't try with other channels cause I'm subbed to only one Twitch channel.
I tried to download public VODs from other Twitch channels and it works fine. 
I've also tried to download Youtube member-only videos using --cookies and that will work fine as well. 
So I guess it's a problem specific on downloading Twitch sub-only VODs.
Below I attached two screenshots of Command Prompt.
![77bf8d96ea84382746c1ebf78ae8ba36](https://user-images.githubusercontent.com/35116193/104742649-fab08180-574a-11eb-96ce-45a113b9014c.png)
![54758d0dd83948b56bf372180d7d40ec](https://user-images.githubusercontent.com/35116193/104742651-fb491800-574a-11eb-8da7-fc2c2a4b5883.png)

**Comment by glubsy** [comment]
Could you at least point to the duplicate topic?

**Comment by BlazinWings** [comment]
For anyone like me searching for this issue in the future, the problem is best fixed by passing cookies through YDL. Here's the quote from the ReadMe.
Use the --cookies option, for example --cookies /path/to/cookies/file.txt.
In order to extract cookies from browser use any conforming browser extension for exporting cookies. For example, Get cookies.txt (https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/) (for Chrome) or cookies.txt (https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) (for Firefox).
Note that the cookies file must be in Mozilla/Netscape format and the first line of the cookies file must be either # HTTP Cookie File or # Netscape HTTP Cookie File. Make sure you have correct newline format (https://en.wikipedia.org/wiki/Newline) in the cookies file and convert newlines if necessary to correspond with your OS, namely CRLF (\r\n) for Windows and LF (\n) for Unix and Unix-like systems (Linux, macOS, etc.). HTTP Error 400: Bad Request when using --cookies is a good sign of invalid newline format.
Passing cookies to youtube-dl is a good way to workaround login when a particular extractor does not implement it explicitly. Another use case is working around CAPTCHA (https://en.wikipedia.org/wiki/CAPTCHA) some websites require you to solve in particular cases in order to get access (e.g. YouTube, CloudFlare).
