### ISSUE TITLE
How to download the most HD video on YouTube

### ISSUE THREAD

**Issue by alvanllin** [ytdl-org/youtube-dl#27867]
![image](https://user-images.githubusercontent.com/77631593/104948109-bdbce700-59f7-11eb-9b90-e5af1fdc6544.png)
PS D:\下载\youtube-dl-2021.01.16\新建文件夹> cmd
Microsoft Windows [版本 10.0.19041.746]
(c) 2020 Microsoft Corporation. 保留所有权利。

D:\下载\youtube-dl-2021.01.16\新建文件夹>youtube-dl https://www.youtube.com/watch?v=DQ7HSI5VeB4
[youtube] DQ7HSI5VeB4: Downloading webpage
[download] Destination: 五月天 [ 好好好想見到你 ] Mayday fly to 2021 跨年演唱會｜線上特別版-DQ7HSI5VeB4.mp4
[download] 100% of 254.63MiB in 00:48

**Comment by alvanllin** [comment]
New person teaching thank~

**Comment by rautamiekka** [comment]
With the default command and no config there's nothing you need to do.

The readme says the software defaults to `bestvideo+bestaudio/best`, so, unless YT misreports, the very best is downloaded: 1st it tries to get the vid and audio separately (assuming you allowed FFmpeg), otherwise it takes the best single package YT has.

**Comment by remitamine** [comment]
install FFmpeg.
