### ISSUE TITLE
Images & GIFs

### ISSUE THREAD

**Issue by jimmy-1000** [ytdl-org/youtube-dl#28083]
Youtube-dl is a powerful and useful tool, not only for downloads but watch online content (example via MPV or SMplayer).
It would be great if in addition to videos we could view online pictures and GIFs too (the whole package).
I know some programs like JDownloader can download all but it doesn't work for view online content through video-players like MPV or SMplayer.

**Comment by rautamiekka** [comment]
That's been asked before and they 100% refuse cuz to them it's outta scope.

Try gallery-dl instead. It can optionally delegate to youtube-dl when the latter already has support for the content.

**Comment by pukkandan** [comment]
I often don't agree with the youtube-dl maintainers an rejecting feature requests, but this is one thing I totally agree on. To enable image/gif downloading, large parts of the core program will need to be altered. It is much better to use a seperate program like gallery-dl that specializes in image downloads

**Comment by rautamiekka** [comment]
> To enable image/gif downloading, large parts of the core program will need to be altered.

I'm not sure I agree with that. Like, ytdl already uses OAuth (although in a roundabout way: instead of using the protocol, ytdl interprets JSON's and manually constructs the queries) for sites which require it, and to me the infrastructure looks like it could easily accommodate new extractors or updates to existing ones to support pics.

If anything, if Selenium and xpaths (and by extension Requests, which Selenium depends on) were to be used, then shit would change (1 glaring diff would be needing to install packages, which ytdl's tried to avoid no matter the cost), but existing already working extractors wouldn't need porting (unless Selenium would be the only method). However, until Selenium 4 for Python comes out, support stops at 3.6.

^ YT itself's something like a miracle or black magic: a lot of code was needed, but Google was providing the access if you knew where to look. Last I checked, 99% of the other extractors are tiny by comparison.

**Comment by pukkandan** [comment]
>  Like, ytdl already uses OAuth (although in a roundabout way: instead of using the protocol, ytdl interprets JSON's and manually constructs the queries) for sites which require it, and to me the infrastructure looks like it could easily accommodate new extractors or updates to existing ones to support pics.

Yes, a lot of the code can be reused. But my point is that the core of the program (the YoutubeDl module itself, not the extractors/downloaders) are designed with video downloads in mind. 

> YT itself's something like a miracle or black magic: a lot of code was needed, but Google was providing the access if you knew where to look. Last I checked, 99% of the other extractors are tiny by comparison.

It is mostly because the youtube webpage itself is very complex. Nowadays, the youtube extractor has actually simplified quite a bit since most of the data is now extracted from inside `ytInitialPlayerResponse` and `ytInitialData` objects instead of having to regex them from the whole webpage

**Comment by jimmy-1000** [comment]
@rautamiekka and @pukkandan:

The idea is not to download a gallery of pictures (in this case I would use JDownloader). I will explain again, some sites on the Internet have content mixed with videos, pictures and GIFs, if I want to watch them online (streaming) through players that use youtube-dl such as MPV or SMplayer, the player only gets and shows the videos that are found on the site and ignores photos and GIFs, the idea is that the player shows everything.

**Comment by pukkandan** [comment]
Example? Also, does any player even support this kind of playback?

**Comment by jimmy-1000** [comment]
> 
> 
> Example? Also, does any player even support this kind of playback?

All players can handle pictures and GIFs. Drag and drop a picture or GIF from your computer to your player and it show it.
Even you can put a link from de Internet (link of image or GIF) into your player and it show it.

**Comment by pukkandan** [comment]
> content mixed with videos, pictures and GIFs,

You weren't talking about individual pictures though. Am I misunderstanding something? It also doesn't help that you are not giving examples

**Comment by jimmy-1000** [comment]
> 
> 
> You weren't talking about individual pictures though. Am I misunderstanding something? It also doesn't help that you are not giving examples

Could you explain me exactly what kind of example?
