### ISSUE TITLE
Allow combining formats while writing to stdout

### ISSUE THREAD

**Issue by redbrain** [ytdl-org/youtube-dl#28146]
## Checklist
- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.02.10**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description
Currently, youtube-dl wil only stream true "best" to stdout.
If a flag like `-f bestvideo+bestaudio` is specified as well as `-o -`, it actually makes a file called `-.webm` instead of streaming.
A quick search shows that this was briefly discussed in #27265.
However, it was quickly dismissed, with the argument that making temp-files (for combining formats) makes stdout worthless.
I believe it's important to allow temp files with stdout, for example, to pipe the output to another program.
Objectively, it seems as if this would be trivial to program as well.
Please let me know if this can/will be implemented.
Also, thanks for your tireless upkeep of youtube-dl, especially through all the legal issues; you don't get enough credit for that.

**Comment by pukkandan** [comment]
Could you explain what is the use-case for this? According to your proposal, youtube-dl will download the files to disk, merge them with ffmpeg and then write the file to stdout. In that case, why not just use `--exec`?

**Comment by redbrain** [comment]
How could `--exec` be used to accomplish this?

**Comment by pukkandan** [comment]
Well, I don't know if your use-case is possible with `--exec` since you didn't bother to explain it. The uses I can think of does work with it. For example, if you want to pass the file to ffplay, you can do: `--exec "ffplay -i {}"`

**Comment by redbrain** [comment]
My apologies, when opening this feature request I didn't think to explain any specific cases. Here's a contrived example for you.
youtube-dl could be used in Apache+PHP to send the stdout to the web response without filling up disk space over time.
`youtube-dl [LINK] -q -f "bestvideo+bestaudio/best" --recode-video mp4 --exec "cat {} && rm {}"` works in bash but not in PHP.
Meanwhile, `youtube-dl [LINK] -q -f "mp4" -o -` works in both bash and PHP.
I'm assuming that php won't read the exec-ed `cat` as the output, which is what causes it to fail.

**Comment by rautamiekka** [comment]
^ The one with `--exec "cat` fails cuz PHP protects against using shell commands for wrong purposes (for any purposes, really). I'm pretty sure even that can be conffed to be allowed, but it's extremely dangerous, so unless you're able to secure the PHP, the Web Server, and the host OS, you shouldn't try that.

You can sorta circumvent the problem of using files by using a queue instead of processing multiple files at once, and placing the file into a RAM disk, meaning a semi-virtual area by mounting a folder using the `ramfs` filesystem. There're no mount options for it. I don't recommend using `tmpfs` (https://www.kernel.org/doc/html/latest/filesystems/tmpfs.html) cuz it'll use your swap for backing up the data, at which point you might as well use an actual HDD/SSD for storing the files. I've never tested `tmpfs`, so I can't tell if the backing up affects the performance, but I guess not cuz some ppl recommend it for speed reasons.

**Comment by redbrain** [comment]
Now it's easier to see why muxing doesn't already support stdout; it appears to be more painful than I initially thought.
Temporary storage is probably best for that sort of webserver anyways; after all it was a hypothetical example.
Closing the feature request; it now appears that it's best this is left unchanged.
