### ISSUE TITLE
Unable to download JSON metadata

### ISSUE THREAD

**Issue by 45145v** [ytdl-org/youtube-dl#28202]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by 45145v** [comment]
not working

**Comment by reekrd** [comment]
youtube-dl https://soundcloud.com/lughatalrouh/waxwoods-interpretation-67
[soundcloud] lughatalrouh/waxwoods-interpretation-67: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

youtube-dl --version                                                     
2021.03.02

**Comment by C-Srg** [comment]
Impossible de télécharger vidéos depuis "Arte" alors que c'est possible avec "Qarte".

**avec "youtube-dl"** : 
serge@serge-N85-Mint:~/Vidéos$ /usr/bin/youtube-dl -v --print-traffic https://www.arte.tv/fr/videos/081554-001-A/afghanistan-pays-meurtri-par-la-guerre-1-4/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--print-traffic', 'https://www.arte.tv/fr/videos/081554-001-A/afghanistan-pays-meurtri-par-la-guerre-1-4/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-26-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[ArteTV] 081554-001-A: Downloading JSON metadata
send: b'GET /api/player/v1/config/fr/081554-001-A HTTP/1.1\r\nHost: api.arte.tv\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.6 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Content-Type: application/vnd.api+json; charset=utf-8
header: strict-transport-security: max-age=15768000
header: Content-Encoding: gzip
header: Server: Nginx
header: Content-Length: 513
header: Cache-Control: public, max-age=60, s-maxage=60
header: Date: Wed, 17 Aug 2022 05:02:57 GMT
header: Connection: close
header: Vary: Accept-Encoding
header: Vary: Authorization, Origin, Accept-Encoding
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
-------
avec "Qarte" : 
06:14:29: INFO - artetv Configure downloading of Afghanistan, pays meurtri par la guerre (1/4)
06:14:29: INFO - gui.tvdownloadingconfig Config downloading lang: fr, quality: {'audio': 'medias/081554-001-A_aud_VF.m3u8', 'subtitle': 'medias/081554-001-A_st_VF-FRA.m3u8', 'name': 'VF', 'is_hls': False, 'lang': 'Français', 'id': 1, 'resolution': (1280, 720), 'bandwidth': 2426328, 'uri': 'medias/081554-001-A_v720.m3u8', 'base_url': 'https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/'}
06:14:59: INFO - core Choose: Afghanistan, pays meurtri par la guerre (1/4)
06:15:00: INFO - core Choose: Afghanistan, pays meurtri par la guerre (1/4)
06:15:03: INFO - artetv Load page: https://api.arte.tv/api/player/v2/config/fr/081554-001-A
06:15:03: INFO - artetv Get versions available
	url: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/081554-001-A_VF-STF_XQ.m3u8
06:15:03: INFO - artetv Get versions available
	url: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/081554-001-A_VF-STMF_XQ.m3u8
06:15:03: INFO - artetv Get versions available
	url: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/081554-001-A_VOA-STA_XQ.m3u8
06:15:03: INFO - artetv Get versions available
	url: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/081554-001-A_VOA-STMA_XQ.m3u8
06:15:03: INFO - downloader Task added: 081554-001-A
06:15:30: INFO - core Choose: Afghanistan, pays meurtri par la guerre (1/4)
06:16:01: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_v720.m3u8
06:16:01: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_aud_VF.m3u8
06:16:02: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_st_VF-FRA.m3u8
06:16:02: INFO - downloader Start download Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z file size: 859693999
06:16:02: INFO - downloader URL: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_v720.mp4
06:16:02: INFO - downloader Start download audio file size: 51089303
06:16:03: INFO - tools Convert vtt to srt
06:23:08: INFO - artetv File /home/serge/.Qarte/temp/081554-001-Avideo.mp4 downloaded
06:23:08: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_v720.m3u8
06:23:08: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_aud_VF.m3u8
06:23:08: INFO - downloader Get m3u8 file: 
   https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_st_VF-FRA.m3u8
06:23:08: INFO - downloader Start download Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z file size: 859693999
06:23:08: INFO - downloader URL: https://arte-cmafhls.akamaized.net/am/cmaf/081000/081500/081554-001-A/220811061450/medias/081554-001-A_v720.mp4
06:23:08: INFO - downloader Start download audio file size: 51089303
06:23:09: INFO - downloader Merging finished, file: /home/serge/.Qarte/temp/081554-001-Afinal.mkv
06:23:09: INFO - downloader set path for: Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z
06:23:09: INFO - downloader File renamed: Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z.mkv
06:23:09: INFO - artetv Merging finished: /home/serge/Vidéos/Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z.mkv
06:23:09: INFO - artetv Summary saved
06:23:09: INFO - tools Convert vtt to srt
06:30:23: INFO - artetv File /home/serge/.Qarte/temp/081554-001-Avideo.mp4 downloaded
06:30:25: INFO - downloader Merging finished, file: /home/serge/.Qarte/temp/081554-001-Afinal.mkv
06:30:25: INFO - downloader set path for: Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z
06:30:35: INFO - downloader File renamed: Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z.mkv
06:30:35: INFO - artetv Merging finished: /home/serge/Vidéos/Afghanistan, pays meurtri par la guerre (1-4)_2022-08-13_23-12-02Z.mkv
06:30:35: INFO - artetv Summary saved

06:32:44: INFO - core Call settings dialog box
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 22861, resource id: 9946564, major code: 40 (TranslateCoords), minor code: 0
06:33:16: INFO - core Call About dialog box
06:33:50: INFO - core Prepare to exit
06:33:50: INFO - config Save user config
06:33:50: INFO - config Configuration saved
