### ISSUE TITLE
why does youtube-dl only work with root rights

### ISSUE THREAD

**Issue by kosmosgit** [ytdl-org/youtube-dl#28336]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

when I start youtube-dl without sudo the following message appears
ERROR: requested format not available
but when I run youtube-dl with sudo the video is downloaded, but then my config file is ignored

Here i have two different versions, why?

youtube-dl --version
2021.03.03

dpkg -s youtube-dl
Version: 2019.01.17-1.1
Config-Version: 2019.01.17-1.1
Package: youtube-dl
Status: deinstall ok config-files
Priority: optional
Section: web
Installed-Size: 5481
Maintainer: Rogério Brito <rbrito@ime.usp.br>
Architecture: all
Depends: python3-pkg-resources, python3:any
Recommends: aria2 | wget | curl, ca-certificates, ffmpeg | libav-tools, mpv | mplayer, phantomjs, python3-pyxattr, rtmpdump

**Comment by rautamiekka** [comment]
Have you missed how the versions are over 2y apart ?

**Comment by kosmosgit** [comment]
no that's exactly what I find suspect, how can I update that?
sudo youtube-dl -U only updates the first. The secand version remains the same

**Comment by rautamiekka** [comment]
The older is thanks to the Debian/Ubuntu packager being a fucking lazy ass (who's unaffiliated with this GitHub repo I'm sure), which means you must never install youtube-dl from the stock Debian/Ubuntu repos. It's a diff story for the other distros and -types.

The one you run with `sudo` is installed somewhere on your machine, and the `root` user most likely doesn't have your user's `${PATH}`, so it's using the APT-installed one.

Since both installations should use the same config, you can just run
```bash
sudo apt remove youtube-dl
```
and find the other installation with
```bash
which youtube-dl
```
so you'll know where it is. Then use youtube-dl without `sudo`.

**Comment by kosmosgit** [comment]
Package »youtube-dl« is not installed, so it will not be removed either.

which youtube-dl an sudo which youtube-dl message booth the same path =/usr/local/bin/youtube-dl

I suspect that python does not have enough rights and therefore a call with sudo is necessary

**Comment by rautamiekka** [comment]
Package not installed ? Now that's weird. I can't find how to uninstall it without finding the DEB.

If Python is lagging rights, then at worst the whole distro installation could be fucked cuz this shouldn't, and hasn't to me, happen. Ubuntu comes stock with some Python 3 version, so, unless the distro is an in-dev one, your system's been modified in wrong ways.
