### ISSUE TITLE
Convert format to other formats after download

### ISSUE THREAD

**Issue by 10Meisterbaelle** [ytdl-org/youtube-dl#28365]
## Checklist

- [ X ] I'm reporting a feature request
- [ X ] I've verified that I'm running youtube-dl version **2021.03.03**
- [ X ] I've searched the bugtracker for similar feature requests including closed ones

## Description

It would be nice if there would be a -c option that can convert formats to other formats automatically after downloading so you can get a 4K mp4 file instead of webm.

**Comment by CHJ85** [comment]
That would be a massive downgrade in terms of image quality and not to mention increase in filesize, unless you encode the video using x265.
Still seems like a dumb idea though, because webm is an open source format and therefore better supported by various different video players.
But if you want to do this, just use ffmpeg.
"ffmpeg -i input.webm -c:a copy -c:v libx265 -b:v 500k -x265-params pass=1 -an -f mp4 NUL"
With these settings on a 4k video you shouldn't notice much of a difference, especially because youtube's compression screws up the quality to begin with.

**Comment by s104346** [comment]
youtube-dl already supports this with `--recode-video`, I think:
```
    --recode-video FORMAT                Encode the video to another format if
                                         necessary (currently supported:
                                         mp4|flv|ogg|webm|mkv|avi)
```

**Comment by 10Meisterbaelle** [comment]
> youtube-dl already supports this with --recode-video, I think
Thanks, I will try that
