### ISSUE TITLE
Pluralsite download is broken: HTTP Error 403

### ISSUE THREAD

**Issue by BernardoB95** [ytdl-org/youtube-dl#28384]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Bernardo\Aprendizaje Autonomo\Pluralsight>youtube-dl
[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-c', '--verbose',
 '--write-pages', '--no-warnings', '--console-title', '--batch-file=batch-file.t
xt', '--max-sleep-interval', '20', '--min-sleep-interval', '5', '-o', '%(playlis
t_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'
, '-f', 'bestvideo[height<=720]+bestaudio/best[height<=720]/worst']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['\ufeffhttps://app.pluralsight.com/library/courses/pyt
hon-design-patterns-building-more/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] python-design-patterns-building-more: Downloading JSON meta
data
[pluralsight:course] Saving request to python-design-patterns-building-more_http
s_-_app.pluralsight.com_player_api_graphql.dump
[download] Downloading playlist: Building More Python Design Patterns
[pluralsight:course] playlist Building More Python Design Patterns: Collected 54
 video ids (downloading 54 of them)
[download] Downloading video 1 of 54
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsi
k_\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsi
k_\build\youtube_dl\YoutubeDL.py", line 2275, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
```

## Description

Im trying to do a download with a config file on Pluralsight. Credentials are ok, yt-dl is up to date, however is returning a 403 error.

**Comment by BernardoB95** [comment]
Solved the issue... Passes Cloudflare's cookies as a parameter.
`--add-header __cf_bm:"value" --add-header __cfduid:"value"`

Considering that __cf_bm cookie might vary over time and give a 403 Forbiden HTTP Error. So, before using yt-dl, access your account and retrieve the values.

**Comment by MoroccanGeek** [comment]
@BernardoB95 I did what you've said and collected the __cf_bm and __cfduid values and add it to the command (values are not included below), but it does not work. Any idea why ?


`C:\Users\saber\Videos>youtube-dl --username my_username --password my_password https://www.pluralsight.com/courses/angular-services -o "/home/user/videos/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 60 --playlist-start 15 --add-header __cf_bm:"value" --add-header __cfduid:"value" --verbose


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.pluralsight.com/courses/angular-services', '-o', '/home/user/videos/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '60', '--playlist-start', '15', '--add-header', '__cf_bm:value', '--add-header', '__cfduid:value', '--verbose']
[debug] Adding header from command line option __cf_bm:value
[debug] Adding header from command line option __cfduid:value
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angular-services: Downloading JSON metadata
[download] Downloading playlist: Angular Services
[pluralsight:course] playlist Angular Services: Collected 39 video ids (downloading 25 of them)
[download] Downloading video 1 of 25
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by BernardoB95** [comment]
@MoroccanGeek It did work for me, but only once. I don't know if it is a cloudflare problem or maybe some security feature of the site you are trying to access.

The only tips I can give are, once you log in to your account, make sure that the cookies are the same as the ones in your file, otherwise, replace them for the new ones.

I will reopen this issue, so it can be solved.


> @BernardoB95 I did what you've said and collected the __cf_bm and __cfduid values and add it to the command (values are not included below), but it does not work. Any idea why ?
> 
> `C:\Users\saber\Videos>youtube-dl --username my_username --password my_password https://www.pluralsight.com/courses/angular-services -o "/home/user/videos/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 60 --playlist-start 15 --add-header __cf_bm:"value" --add-header __cfduid:"value" --verbose
> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.pluralsight.com/courses/angular-services', '-o', '/home/user/videos/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '60', '--playlist-start', '15', '--add-header', '__cf_bm:value', '--add-header', '__cfduid:value', '--verbose']
> [debug] Adding header from command line option __cf_bm:value
> [debug] Adding header from command line option __cfduid:value
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2021.04.01
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: none
> [debug] Proxy map: {}
> [pluralsight:course] angular-services: Downloading JSON metadata
> [download] Downloading playlist: Angular Services
> [pluralsight:course] playlist Angular Services: Collected 39 video ids (downloading 25 of them)
> [download] Downloading video 1 of 25
> [pluralsight] Downloading login page
> [pluralsight] Logging in
> ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
> File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
> File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
> File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
> File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
> File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by dalcarobo** [comment]
I just follow this steps and was able to download a full course: https://www.quora.com/Tutorials-How-can-I-download-PluralSight-training-videos/answer/Ahmad-Ismail-42?ch=10&share=734732f5&srid=T4z6

If youtube-dl creates a cookies.txt, erase and add the cookies.txt downloaded from browser.

My command:
`youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" -u "xxxxxxxxx" -p "xxxxxxxxxx"`

**Comment by serezlan** [comment]
Tried suggestion in quora forum above and it worked for the first video of the playlist. And got 403 afterward.
Any other suggestions?

**Comment by serezlan** [comment]
just wanna add that the error message is different than before. Now I got:

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include

Thx

**Comment by YoshQ** [comment]
Also getting the "HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug" with all of the above parameters.

**Comment by dirkf** [comment]
Unfortunately this error persists: see #29776.
