### ISSUE TITLE
svtplay - Download broken

### ISSUE THREAD

**Issue by msoellin** [ytdl-org/youtube-dl#28480]
**--Checklist**

- [ y] I'm reporting a broken site support
- [ y] I've verified that I'm running youtube-dl version **2021.03.14**
- [ y] I've checked that all provided URLs are alive and playable in a browser
- [ y] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ y]I've searched the bugtracker for similar issues including closed ones

**## Verbose log**

$ youtube-dl --verbose https://www.svtplay.se/video/30428164/the-tunnel-hamnden/the-tunnel-hamnden-sasong-3-avsnitt-3?modalId=KqWL64Z
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.svtplay.se/video/30428164/the-tunnel-hamnden/the-tunnel-hamnden-sasong-3-avsnitt-3?modalId=KqWL64Z']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-44-generic-x86_64-with-Ubuntu-20.10-groovy
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.77.244.41 (SE) as X-Forwarded-For.
[SVTPlay] 30428164: Downloading webpage
[SVTPlay] 8p3qA2z: Downloading JSON metadata
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading MPD manifest
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[SVTPlay] 8p3qA2z: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://svt-vod-10h.akamaized.net/d0/se/20210305/049b5dad-7bc9-46f7-a322-dddc5e56c760/dash-avc.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F049b5dad-7bc9-46f7-a322-dddc5e56c760%2Fdash-avc.mpd'
[dashsegments] Total fragments: 732
[download] Destination: Avsnitt 1-8p3qA2z.fdashhbbtv-0.mp4
[download] 100% of 1.01GiB in 04:42
[debug] Invoking downloader on u'https://svt-vod-10h.akamaized.net/d0/se/20210305/049b5dad-7bc9-46f7-a322-dddc5e56c760/dash-avc.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F049b5dad-7bc9-46f7-a322-dddc5e56c760%2Fdash-avc.mpd'
[dashsegments] Total fragments: 732
[download] Destination: Avsnitt 1-8p3qA2z.fdashhbbtv-5.m4a
[download] 100% of 64.86MiB in 02:07
[ffmpeg] Merging formats into "Avsnitt 1-8p3qA2z.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Avsnitt 1-8p3qA2z.fdashhbbtv-0.mp4' -i 'file:Avsnitt 1-8p3qA2z.fdashhbbtv-5.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Avsnitt 1-8p3qA2z.temp.mp4'
Deleting original file Avsnitt 1-8p3qA2z.fdashhbbtv-0.mp4 (pass -k to keep)
Deleting original file Avsnitt 1-8p3qA2z.fdashhbbtv-5.m4a (pass -k to keep)

```
# Description
SVT Play site has changed recently causing download to malfunction:
when multiple episodes are available in same season download will now only provide episode 1 even when requesting a different episode. Se log - request is for episode 3, download fetched is episode 1. This worked until a few days ago and malfunction is the same disregarding series.
/msoellin

**Comment by SwiftingSpeed** [comment]
I have noticed something similar when downloading from a series main page, full series. The result is quite often a completely different series. Here is an example of a children's show called "hej jycke", notice the parts in bold, it tries to download "Sanningen om skönhetsingreppen" instead.

> youtube-dl --verbose -s https://www.svtplay.se/hej-jycke
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', '-s', 'https://www.svtplay.se/hej-jycke']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.03.14
> [debug] Python version 3.7.3 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.8
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
> [debug] Proxy map: {}
> [debug] Using fake IP 78.78.38.124 (SE) as X-Forwarded-For.
> [SVTSeries] hej-jycke: Downloading series page
> [download] Downloading playlist: **Sanningen om skönhetsingreppen**
> [SVTSeries] playlist **Sanningen om skönhetsingreppen**: Collected 2 video ids (downloading 2 of them)
> [download] Downloading video 1 of 2
> [debug] Using fake IP 78.64.182.92 (SE) as X-Forwarded-For.
> [SVTPlay] edPpvM5: Downloading JSON metadata
> [SVTPlay] edPpvM5: Downloading MPD manifest
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [SVTPlay] edPpvM5: Downloading m3u8 information
> [debug] Default format spec: bestvideo+bestaudio/best
> [download] Downloading video 2 of 2
> [SVTPlay] KZmwvbZ: Downloading JSON metadata
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [SVTPlay] KZmwvbZ: Downloading MPD manifest
> [SVTPlay] KZmwvbZ: Downloading m3u8 information
> [debug] Default format spec: bestvideo+bestaudio/best
> [download] Finished downloading playlist: **Sanningen om skönhetsingreppen**

I'm not sure the problem is actually with youtube-dl but quite possibly in svtplay because when I try the same api url that youtube-dl requests (used --print-traffic option to get it), in my web browser I also get wrong results back. When refreshing multiple times the correct show eventually gets returned. This is the api url for the show "hej-jycke": https://api.svt.se/contento/graphql?query={%20%20listablesBySlug(slugs:%20[%22hej-jycke%22])%20{%20%20%20%20associatedContent(include:%20[productionPeriod,%20season])%20{%20%20%20%20%20%20items%20{%20%20%20%20%20%20%20%20item%20{%20%20%20%20%20%20%20%20%20%20...%20on%20Episode%20{%20%20%20%20%20%20%20%20%20%20%20%20videoSvtId%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20%20%20}%20%20%20%20%20%20id%20%20%20%20%20%20name%20%20%20%20}%20%20%20%20id%20%20%20%20longDescription%20%20%20%20name%20%20%20%20shortDescription%20%20}}

It seams like more often I get the result from a previous request back than a random show. Try alternating between the show above and the one msoellin tried (the-tunnel-hamnden): https://api.svt.se/contento/graphql?query={%20%20listablesBySlug(slugs:%20[%22the-tunnel-hamnden%22])%20{%20%20%20%20associatedContent(include:%20[productionPeriod,%20season])%20{%20%20%20%20%20%20items%20{%20%20%20%20%20%20%20%20item%20{%20%20%20%20%20%20%20%20%20%20...%20on%20Episode%20{%20%20%20%20%20%20%20%20%20%20%20%20videoSvtId%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20%20%20}%20%20%20%20%20%20id%20%20%20%20%20%20name%20%20%20%20}%20%20%20%20id%20%20%20%20longDescription%20%20%20%20name%20%20%20%20shortDescription%20%20}}

**Comment by Adriyst** [comment]
+1. It seemingly still works on some parts of svtplay, like [https://www.svtplay.se/video/30194896/rapport/rapport-17-mars-18-00-2?modalId=KyV7wnX](https://www.svtplay.se/video/30194896/rapport/rapport-17-mars-18-00-2?modalId=KyV7wnX), but not on others, like [https://www.svtplay.se/video/30194872/rapport/rapport-17-mars-12-00-1?modalId=8rJEVQg]( https://www.svtplay.se/video/30194872/rapport/rapport-17-mars-12-00-1?modalId=8rJEVQg)

**Comment by msoellin** [comment]
Two things - if it was the site that had this malfunction then I would guess it would show in normal browser use too - but it doesn't. Site works fine. And I also noticed that if you find a place where it works as it should and then try a couple of times with with different files on same series and then go back to the one that worked initially, then it faults!
Question - is there a playlist mechanism in YTDL so that you can order a specific episode in the playlist (and if you don't you get either the default episode (= no 1) - or all episodes (RAIPlay works like that and it seems that SVT Local News works like that)??
/msoellin
