### ISSUE TITLE
How do I tell Youtube-dl that I want it to download in the highest resolution available?

### ISSUE THREAD

**Issue by instaloadererror** [ytdl-org/youtube-dl#28597]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am not very knowledgeable about coding or anything computer related so I apologize if I am missing something obvious. Youtube-dl is not automatically downloading the highest resolution of the videos that are available. The videos I am trying to download are available in 1080p (and can be downloaded in that resolution with other downloaders), but will only download in 720p with Youtube-dl (and sometimes even lower resolution).

I am using a .bat file to use Youtube-dl. The text in that .bat file is copied below. I tried using the "-f" command that was recommended in the faq, but that just caused everything to fail completely. 

youtube-dl.exe -i --download-archive downloaded.txt -f best --add-metadata --embed-subs --embed-thumbnail --all-subs -o "Downloads\%%(uploader)s\%%(upload_date)s-%%(title)s-%%(id)s.%%(ext)s" -a VideosToDownload.txt

**Comment by remitamine** [comment]
install ffmpeg.

**Comment by rautamiekka** [comment]
Well, if you only take the res into acc, you won't get the best one, instead ytdl uses other means to decide on the best, which seems to cause a mismatch every so often.

But apart from that, ytdl defaults to asking the website for the separate best vid and best audio, otherwise it'll take the best pre-existing combination. You already told it to get the best combination, which is actually undesirable in the case of YT since if the vid has a high enough res (dunno what the criteria for audio is) it'll be split into separate vid and audio (I suspect they separate them in all cases).

^ So, take out the `-f best` flag. If you need to be more specific in the case of some content you can. **But remember to designate the folder of FFmpeg so you can use the `bestvideo+bestaudio` !**

Remember to read the readme.

**Examples:**

Audio only, or the best combination: `--format "bestaudio/best"`

Best vid+audio, going from 720p down to 240p, then to 1080p, then to whatever other res is available, then to the best combination, if such options aren't available:
```
--format "bestvideo[height=720]+bestaudio/bestvideo[height=480]+bestaudio/bestvideo[height=360]+bestaudio/bestvideo[height=240]+bestaudio+bestaudio/bestvideo+bestaudio/best"
```

The above {c,s}ould be optimized into:
```
--format "(bestvideo[height=720]/bestvideo[height=480]/bestvideo[height=360]/bestvideo[height=240]/bestvideo)+bestaudio/best"
```
