### ISSUE TITLE
How do I get youtube-dl to find python?

### ISSUE THREAD

**Issue by jomyer** [ytdl-org/youtube-dl#28654]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've  searched the bugtracker for similar questions including closed ones

## Question

How do I get youtube-dl to find python? 

I used the install method:

 $ sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl , and

 $ sudo chmod a+rx /usr/local/bin/youtube-dl

---

Running youtube-dl results:

 $ sudo youtube-dl -U
/usr/bin/env: ‘python’: No such file or directory

---

python installation:

 $ whereis python
python: /usr/bin/python3.8 /usr/lib/python3.9 /usr/lib/python2.7 /usr/lib/python3.8 /etc/python3.8 /usr/local/lib/python3.8 /usr/include/python3.8

---

I am running Ubuntu-MATE on Raspberry Pi 4B:

**Comment by rautamiekka** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28640#issuecomment-812774031

**Comment by MahfuzurRahmanMoon** [comment]
You can also create a symbolic link of python3 in the directory /usr/bin.

Run this command: sudo ln -s python3 /usr/bin/python

**Comment by rautamiekka** [comment]
> You can also create a symbolic link of python3 in the directory /usr/bin.
> 
> Run this command: sudo ln -s python3 /usr/bin/python

The basic idea's good, but the command itself won't work quite like that (as it is, the command would fail cuz `python3` is given as the source to symlink to (which likely doesn't exist), and even if it wouldn't it would fail cuz `/usr/bin/python`, which is given as the symlink's name, already exists. TLDR: the params are reversed. Also, you'd only be able to use the command from the current folder you're in):
1) `cd "$(dirname -- "$(which python)")"`
2) `sudo ln -vs python python3`

^ That enters the folder of the pre-existing Python, and correctly creates the symlink into the same folder as the original binary to make the address resolving faster; unless it was changed recently, absolute path to the source is resolved by following that given path regardless of the symlink existing in the same folder. That can be avoided by following the steps given above, or (on Debian-types) install the `symlinks` package to convert the absolute symlink to relative.

**Comment by MichaIng** [comment]
@rautamiekka 
I think you mixed up the issue: The `python3` executable does exist, but is not picked by `/usr/bin/env python`, which requires the `python` executable to exist. So @MahfuzurRahmanMoon's command is absolutely correct to create a symbolic link at `/usr/bin/python` which points to the existing `python3` executable in the same directory (and hence does not require a full path, regardless from where this command is called, hence no need to enter any directory).

The problem is, that usually `python` calls Python 2, which is often still installed but deprecated. So we want `youtube-dl` to use Python 3, which requires usually `/usr/bin/env python3` as shebang. Creating a symlink is a workaround but prevents e.g. Python 2 package installs, when required for some reason.

**Comment by rautamiekka** [comment]
> @rautamiekka
> So @MahfuzurRahmanMoon's command is absolutely correct to create a symbolic link at `/usr/bin/python` which points to the existing `python3` executable in the same directory (and hence does not require a full path, regardless from where this command is called, hence no need to enter any directory).

_Touche_. By `ln`'s own manpage this shouldn't happen, but it does for some reason. I guess the target and the symlink both existing in `PATH` has some kinda undocumented (AFAIK) behavior, or priority.

**Comment by MichaIng** [comment]
> By `ln`'s own manpage this shouldn't happen

It all happens as expected, or which statement of the manpage do you mean? Also `PATH` does not play any role in this regards, `ln` does not use it at all and the symlink's target path is always relative to the symlink location, not to the working directory. However, doesn't matter, I just wanted to shortcut other users workaround search by clarifying that
```sh
sudo ln -s python3 /usr/bin/python
```
is a very valid workaround 🙂.

**Comment by boltronics** [comment]
It's now getting common to see distros ship `python3` but not `python`, such as Debian and Ubuntu - which makes sense since 2.7 is EOL. It would be nice if youtube-dl was updated to look for `python3` so users didn't need to create a symlink, which also possibly confuses other applications that may specifically look for Python 2.7.

**Comment by rautamiekka** [comment]
That just ain't gonna happen, is what I say with confidence.

**Comment by boltronics** [comment]
Ever, in the lifetime of the project? If not, what criteria needs to be met to make the switch?

**Comment by boltronics** [comment]
In the meantime, it would also be nice if the `INSTALLATION` section of the `README.md` file pointed this step out, so people didn't have to search for a bug report.

**Comment by rautamiekka** [comment]
Well I'm sure 'ever' doesn't apply, I just mean upgrade to 3 has been here before (and yet again I can't find it cuz the titles are just about anything that doesn't come to my mind) and it was along the lines of some specific high-importance distros still holding onto 2.7 as the default, and I think most (all ?) of them don't have 3 installed alongside 2 by default, either.

^ Think it was like RHEL/CentOS or Arch being the culprits, the latter I think was 1 of the main devs' primary OS no less. And I recall someone saying some OS, think it was a Raspberry Pi, can't even compile Py3, which probly is also a heavy reason in the decision.

So ... There's [yt-dlp](https://github.com/yt-dlp/yt-dlp), an active direct fork, which is strictly Py3.

**Comment by boltronics** [comment]
Nice, thanks for the info. Could be - I haven't ran RHEL or CentOS in many years so have no idea about those.

Raspbian is based on Debian which has Python 3, and even MicroPython runs Python 3... but I'm sure there's probably some distro out there that doesn't have Python 3 support. It would be good to have a record of it for those of us who want to keep watch.

Thanks for the yt-dlp link - I'd never heard of it!

**Comment by MichaIng** [comment]
> RHEL/CentOS or Arch 

Arch has Python 3 natively for years, of course: https://archlinux.org/packages/?name=python
It's a rolling release distro, expect it to have new versions natively available as one of the first. Python 2 can still be installed, but the native support for additional modules is limited compared to Python 3.

RHEL and CentOS in latest versions natively support Python 3 as well (`yum install python3`), on older versions it can be quite comfortably installed via EPEL or [IUS](https://ius.io/) repositories.

Raspberry Pi can run and compile Python 3, not sure where the false opposite assumption is coming from. Same as on Debian, Ubuntu and Arch, on latest Raspberry Pi OS Bullseye natively available Python 3 modules are very limited.

> I think was 1 of the main devs' primary OS no less

If this was still true, then it would be nice to get a ping from that main dev and we will show how to easily install Python 3 nowadays 😎. All these worries about where it would be a problem to install Python 3 reads like an at least 3 years old guide for RHEL 6/7 resp. CentOS 5/6, or much older in case of every other distro. At least since Python 2 became officially EOL, efforts by distros or communities have been done make it available even on older versions, so that is really not at all an issue anymore.

Even if someone would for some reason run an ancient distro version and denied to use a non-native (but available easy) way to install Python 3, `youtube-dl` with the shebang change would still run perfectly fine by creating the alias or symlink or manually change the shebang, just like now all others are forced to do.

The question is whether you want to support a possibly existing minority of people riding a zombie (encouraging everyone else to use a fork instead... 🤔), or whether you want to support the majority of people who run newer OS versions or managed to install Python 3 on their older OS, which will be sooner or later all of them.

**Comment by rautamiekka** [comment]
Make no mistake, I'm also all for upgrading to newest 3; I might be the one most concerned with newest versions in every app.

I wouldn't be suggesting replacements if it wasn't necessary. Strictly high loyalty, y'see.

**Comment by MichaIng** [comment]
Ah yes, sorry I addressed the wrong person 😅. But good to have the facts here. Thanks for linking the fork btw, looks indeed very actively developed, with to give a try :+1:.
