### ISSUE TITLE
HTTP Error 403: Forbidden (PluralSight)

### ISSUE THREAD

**Issue by rrFK** [ytdl-org/youtube-dl#28762]
## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--all-subs', 'https://app.pluralsight.com/library/courses/getting-started-with-asynchronous-programming-dotnet', '-o', '~/video/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '10', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] getting-started-with-asynchronous-programming-dotnet: Downloading JSON metadata
[download] Downloading playlist: Getting Started with Asynchronous Programming in .NET
[pluralsight:course] playlist Getting Started with Asynchronous Programming in .NET: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] 9f83403b-fd20-4362-8809-6933628efa15-0: Downloading JSON metadata
[pluralsight] 9f83403b-fd20-4362-8809-6933628efa15-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 9f83403b-fd20-4362-8809-6933628efa15-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 9f83403b-fd20-4362-8809-6933628efa15-0: Waiting for 5 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I want to download a video from PluralSight.
I have a subscription and my account is not blocked.

**Comment by der-gabe** [comment]
I had the same problem and found out, through some googlin', that the issue is probably PluralSight throwing up a [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA). Not much `youtube-dl` or the PluralSight extractor can do about that...

HOWEVER, I was able to get around this problem by using the `--cookies` option (instead of username and password) with a cookies file I exported from Firefox with the [https://addons.mozilla.org/de/firefox/addon/cookies-txt/)(cookies.txt) Add-On, while logged in to PluralSight.

**Comment by rrFK** [comment]
Hi Gabriel,
thank you for
 your help.
I have exchanged the two parameters username and password for the parameter cookies and specified the file name of the cookie file. The cookie.txt file is in the same directory as the youtube-dl file. 
Unfortunately I still get the same error message: HTTP Error 403: Forbidden

Attached is the file with the error message.
[Error-Message.txt](https://github.com/ytdl-org/youtube-dl/files/6320705/Error-Message.txt)

Can you please see what else I need to change to make it work?
Thank you!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
The same here, 403 error.

**Comment by der-gabe** [comment]
@rrFK The only thing that springs to my mind is that in your last comment you write *cookie.txt* (singular) as the name of the cookie file, whereas in the attached text file you pass the option `--cookies cookies.txt` (plural)… is it possible that the filenames don't match?

Other than that, have you checked that you can play the course in your browser and are you running those `youtube-dl` commands on the same machine? I ask, because I think I've read somewhere that there may be georestrictions in place... if that should be the problem, then a VPM or access to a server in another geo might help.

Otherwise, I'm running out of ideas. I'm not a dev, just a regular old user... and even that only for a couple of days.
