### ISSUE TITLE
Newbie question: How to remove python3.5 and activate python3.9 (both seem to be installed and collide...)?

### ISSUE THREAD

**Issue by EmmW** [ytdl-org/youtube-dl#28766]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Hi, I seem to have managed to get multiple installations of python in my Mac OS 10.14.6 folder hierarchy and would very much appreciate if someone could help me sort this out...

1) When I write "python --version" in Terminal I get back "Python 2.7.17"

2) When I write "python3 --version" I get back "Python 3.5.1"

3) When I write "python3.9 --version" I get back "Python 3.9.4"

4) When I write "which python" I get back "/usr/local/bin/python"

5) When I write "which python3" I get back "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3"

6) When I write "which python3.9" I get back "/usr/local/bin/python3.9"

7) When I write "brew upgrade python" I get back "python 3.9.4 already installed"

8) When I write "sudo pip install --upgrade python" I get back the following error message:
"DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: The directory '/Users/mark/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

How do I completely remove python3.5 from my system and make sure that all necessary pointers are directed to the location where python3.9 now resides..?

Many thanks in advance for help in straightening this out! :-)

/Mark

**Comment by kikuyan** [comment]
This is not the right place asking about python installation. Use [Apple Support Communities](https://discussions.apple.com), Reddit, Stack Exchange or somewhere else.

**Comment by rautamiekka** [comment]
I'll chime in just for a little bit and leave it at that:

Generally you don't wanna replace the factory-installed default Python cuz if the system makes any use of that installation, you're highly likely to break those scripts (and maybe the OS if those scripts are vital) since they're coded/ported to that version, which means it'll work with that version at minimum, but might not when you upgrade it.

You'll need to create a shell `alias` (or whatever Zsh calls it; `alias` is a Bash name) after you install a system-wide PIP for Python (or [Miniconda](https://repo.anaconda.com/miniconda/); recommended) and a venv ("environment" for *conda) where you install the wanted Python version, like so:
```bash
alias youtube-dl='/path/to/python /path/to/youtube-dl '
```
Notice the trailing space !

I'll have to agree with @kikuyan above, you'll need to talk to a dedicated support place like those he recommended. I won't help with it more here.

**Comment by EmmW** [comment]
Thanks Rautamiekka for trying to help (though I'm afraid your advice is a bit above my skill level). I'll see if I can find somewhere else then where I can get some help with my seemingly dubious python installation for youtube-dl.
/Mark
