### ISSUE TITLE
[sibnet] Add extractor

### ISSUE THREAD

**Issue by KarolS** [ytdl-org/youtube-dl#2879]
As in the title. Both normal links (`http://video\.sibnet\.ru/(\w/)*video\d+-.*`) and embeds (`http://video\.sibnet\.ru/shell\.swf\?videoid=\d+`) would be nice.

Example URLs: 
- http://video.sibnet.ru/day/20140511/video1457787-Narushaya_zapretyi/
- http://video.sibnet.ru/video1457787-Narushaya_zapretyi/
- http://video.sibnet.ru/video1457787/
- http://video.sibnet.ru/video1457787
- http://video.sibnet.ru/shell.swf?videoid=1457787

all linking to the same video, the direct file URL is http://video.sibnet.ru/v/ec33490bf361cab6248d8f19bd304ea8/1457787.mp4

From what I looked, doesn't look terribly complicated; the direct URL for the video file is in the page source.

EDIT: found a script to do so: http://forum.sibnet.ru/index.php?s=172fda4f5ae0c7298b339511528ea566&showtopic=510072&view=findpost&p=12500112

**Comment by TRox1972** [comment]
Generic extractors currently works for the provided URLs with the exception of http://video.sibnet.ru/shell.swf?videoid=1457787

**Comment by arisboch** [comment]
The generic extractor stopped working, it just downloads a junk .php file. Could you take a look at it?

**Comment by arisboch** [comment]
@dstftw The problem is that this request is too old, because of that at not at the top of the list but closer to the back and because of that, it's rather unlikely for anyone to deal with it (just look at the support request #7403, the copyright problem was dealt with and still no-one wants to add support for that site (unless there's a reason for the lack of support of that no-one's wrote in the comment section of these issue requests)). And since "bumping" doesn't work, even with new developments, the issue will stay on the back pages no-one's bothered to look at (and #14316 wasn't even a duplicate, since according to the previous commenter, the generic extractor **were** able to download videos from sibnet, so this issue should've been closed).

**Comment by dstftw** [comment]
This does not make any difference. Issue requesting the same functionality is a duplicate. No duplicates are allowed.
