### ISSUE TITLE
youtube-dl not selecting best quality on pornhub

### ISSUE THREAD

**Issue by asdpolll2** [ytdl-org/youtube-dl#28927]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl 'https://www.pornhub.com/view_video.php?viewkey=ph5e8475a13b2b3' --verbose
[debug] System config: []
[debug] User config: ['--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: ['https://www.pornhub.com/view_video.php?viewkey=ph5e8475a13b2b3', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - macOS-11.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] ph5e8475a13b2b3: Downloading pc webpage
[PornHub] ph5e8475a13b2b3: Downloading JSON metadata
[PornHub] ph5e8475a13b2b3: Downloading m3u8 information
[PornHub] ph5e8475a13b2b3: Downloading m3u8 information
[PornHub] ph5e8475a13b2b3: Downloading m3u8 information
[PornHub] ph5e8475a13b2b3: Downloading m3u8 information
[PornHub] ph5e8475a13b2b3: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/202004/01/299115841/201220_0335_720P_4000K_299115841.mp4?validfrom=1619795329&validto=1619802529&rate=500k&burst=1400k&ipa=IPADDRESS&hash=6ytYFqrn1rXLs6xfP7yQUVZ5RTQ%3D'
[download] Destination: Hot Inked Purple Hair Punk Teen Gets Banged-ph5e8475a13b2b3.mp4
[download]   5.5% of 118.96MiB at 721.68KiB/s ETA 02:3
```

## Description

Even though 1080p versions are available for non members free, youtube-dl doesnt detect them at all even using 'youtube-dl --list-formats' only shows 720p as the best. Viewing the video in browser or dumping the json shows 1080p as an option

**Comment by asdpolll2** [comment]
looks like this issue is the same as this old one here https://github.com/ytdl-org/youtube-dl/issues/22749

**Comment by mthnprivate** [comment]
It seems like the problem is that PornHub tries to hide the actual download links. The download links used to be present on flashvars_<number>.mediaDefinitions, but they removed them from there.

Instead of that they added a link to the mediaDefinitions where the mediaDefinitions used to be. Not only that, they do not actually send the links when the page is loaded. They have some kind of script that builds the url from a list of fake and real variables. Man, I would love to see that code base, it must be a mess!

Unfortunately I was unable to piece together the correct URLs using only the raw page data. But I did manage to get something working. In https://github.com/mthnprivate/youtube-dl/commit/0827de72405235657ba0a610d1156efce2d98adb I added selenium as a dependency and used that to actually "load" the pages so the JavaScript would build the link to find the actual mediaDefinitions.

To get it working simply:
1. "pip install -U selenium" so it's available to be imported.
2. Clone the repository in which I provided this workaround.
3. Execute the the main script from the repository folder (e.g. "python .\youtube_dl\__main__.py -f best -ciw -o "%(title)s.%(ext)s" -v <url>").

Please note that my experience with Python is almost non-existent. Maybe someone with more experience can get this working with what's already in youtube-dl. But for now, at least this works.

**Comment by asdpolll2** [comment]
thanks @mthnprivate looks good!

@dstftw I notice you have a lot of fixes on the extractor in the past, looks like it can be fixed at some point? or not possible now they hide the files?

**Comment by asdpolll2** [comment]
Why has this been closed? The issue is not fixed as far as I can see
