### ISSUE TITLE
How do I recode only the audio?

### ISSUE THREAD

**Issue by gabrielluz-br** [ytdl-org/youtube-dl#28933]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hi. I'm trying to download the video and recode only the audio stream. I want only to copy the audio. I know that the --exec command won't let me use ffmpeg since I've seen that this is not possible as told by another user here.
How can I accomplish that? I just want to encode the audio to Opus, 64kbps.

**Comment by dirkf** [comment]
> the --exec command won't let me use ffmpeg
Really? Please post the reference you mention, as the `--exec` option should allow you to run any program that you could run in the context where you're running yt-dl.

**Comment by ne0zen** [comment]
`-x` will build audio at the highest quality possible on disc (possibly after downloading the video depending on the place you're pulling it from).  `youtube-dl --help` will show you the other flags it accepts.

**Comment by gabrielluz-br** [comment]
> I believe `-x` will stash an audio file at the highest quality possible on disc based on the source encoding (possibly after pulling down a video file depending on the source site). After that you can re-encode to your heart's content...

I've tried using -x but it will create a separate audio instead.

**Comment by episk** [comment]
> > I believe `-x` will stash an audio file at the highest quality possible on disc based on the source encoding (possibly after pulling down a video file depending on the source site). After that you can re-encode to your heart's content...
> 
> I've tried using -x but it will produce a separate audio file instead.

Haven't tested this specific config but I thought I'd take a stab at it anyway. First I guess you want to check if opus is available and download video and audio separate (usually best choice anyway):

You do this by defining video/audio preferences separately.
`-f bestvideo+bestaudio[acodec=opus]/bestaudio/best`

And then, I would assume:

`-x` to apply `--audio-format "opus"`,
`-k` lets you keep the video, but `--merge-output-format mp4`

and output

`-o "path/%(title).%(ext)s"`

should give you best possible video with opus. If not, maybe it'll help you find what detail I forgot. Doing it completely in post-processing, just use ffmpeg with `-v:copy` to ignore video and only make changes to the audio track. Hope this helps!

**Comment by dirkf** [comment]
I believe that what OP wanted was just the audio with no video, like this:
```
# youtube-dl -f 'bestaudio[acodec=opus]/bestaudio/best' -x --audio-format opus 'https://www.youtube.com/watch?v=ki7dYPv4uHc'
[youtube] ki7dYPv4uHc: Downloading webpage
[download] Destination: /media/drive1/Video/Train_Kept_On_Rollin.webm
[download] 100% of 3.18MiB in 00:03
[ffmpeg] Destination: /media/drive1/Video/Train_Kept_On_Rollin.opus
Deleting original file /media/drive1/Video/Train_Kept_On_Rollin.webm (pass -k to keep)
# ffprobe -hide_banner /media/drive1/Video/Train_Kept_On_Rollin.opus 
Input #0, ogg, from '/media/drive1/Video/Train_Kept_On_Rollin.opus':
  Duration: 00:03:24.27, start: 0.007500, bitrate: 128 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      LANGUAGE        : eng
      ENCODER         : Lavf58.20.100
# 
```
In case the best `opus` format should be low quality compared with some other available audio encoding, just use `-f 'bestaudio/best'`.

Parameters may need to be quoted differently for Windows `cmd`.

**Comment by gabrielluz-br** [comment]
> I believe that what OP wanted was just the audio with no video, like this:
> 
> ```
> # youtube-dl -f 'bestaudio[acodec=opus]/bestaudio/best' -x --audio-format opus 'https://www.youtube.com/watch?v=ki7dYPv4uHc'
> [youtube] ki7dYPv4uHc: Downloading webpage
> [download] Destination: /media/drive1/Video/Train_Kept_On_Rollin.webm
> [download] 100% of 3.18MiB in 00:03
> [ffmpeg] Destination: /media/drive1/Video/Train_Kept_On_Rollin.opus
> Deleting original file /media/drive1/Video/Train_Kept_On_Rollin.webm (pass -k to keep)
> # ffprobe -hide_banner /media/drive1/Video/Train_Kept_On_Rollin.opus 
> Input #0, ogg, from '/media/drive1/Video/Train_Kept_On_Rollin.opus':
>   Duration: 00:03:24.27, start: 0.007500, bitrate: 128 kb/s
>     Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
>     Metadata:
>       LANGUAGE        : eng
>       ENCODER         : Lavf58.20.100
> # 
> ```
> 
> In case the best `opus` format should be low quality compared with some other available audio encoding, just use `-f 'bestaudio/best'`.
> 
> Parameters may need to be quoted differently for Windows `cmd`.

No, Sir. I want both. I've tried using the merge output switch but it doesn't work.

**Comment by dirkf** [comment]
`--merge-output-format` only lets you select the container for the output, not the individual media codecs.

`--format` (`-f`) lets you select the codecs, but only from those advertised by the source site.

For your requirement, there are two cases:
* if the site offers the item with audio encoded as Opus and of sufficient quality, yt-dl can do the job itself;
* otherwise yt-dl has to be told to get the best audio and provided with a `--exec` command to convert the result to your desired format with Opus audio.

Specifying `-f (bestaudio+bestvideo/best)[abr>=64][acodec=opus]` should find the first case (or if you actually want to limit the quality of the audio at ~64Kbit/s, perhaps `...[abr>=60][abr<=68][acodec=opus]`).

One approach would be to have a command script that runs yt-dl with a `-f` option that would find case 1; if that fails run yt-dl again with the default `-f` option and a post-processing command like `ffmpeg -hide_banner -loglevel fatal -i {} -vcodec copy -acodec opus -aq 64K -strict -2 {}.webm' (`-strict -2` enables Opus encoding for ffmpeg v4).

Another would be to use yt-dl with `-f (bestaudio+bestvideo/best)[abr>=64][acodec=opus]/bestaudio+bestvideo/best` and in the `--exec`command check whether the audio needs to be re-encoded before doing so. The given format selection will have found 64K or better Opus audio if available, or whatever the best audio is otherwise; if the audio is Opus it's either 64K or better (in which case all OK) or the best audio available (in which case re-encoding to 64K would lose quality); if it's not, then it has to be re-encoded. This is a bit beyond the sort of one-line command that you would pass with `--exec` but you could make a script for your platform and call that. If a POSIX shell is available, this `maybe_reencode`:
```
#!/bin/sh
ffprobe -hide_banner -show_streams -select_streams a "$1" | grep -E '^codec_name=' | grep -q "opus" || 
    {   out="${1%.*}.tmp.${1##*.}"
        ffmpeg -hide_banner -loglevel fatal -y -i "$1" -vcodec copy -acodec opus -aq 64K -strict -2 "$out" &&
            mv -f "$out" "$1"
    }
```
fi

**Comment by gabrielluz-br** [comment]
I appreciate your guy's help. I know how to use ffmpeg and create bash scripts. I really wanted to do the whole process (e.g downloading the video and recoding the audio) with YouTube-dl. I'm closing this issue.
