### ISSUE TITLE
Facebook is generally broken

### ISSUE THREAD

**Issue by lucmp** [ytdl-org/youtube-dl#29204]
- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.05.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

```
$ youtube-dl -v 'https://fb.watch/5U22VqJyf9'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://fb.watch/5U22VqJyf9/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-3-amd64-x86_64-with-debian-9.4
[debug] exe versions: avconv 3.3.4, avprobe 3.3.4, ffmpeg 3.3.4, ffprobe 3.3.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 5U22VqJyf9: Requesting header
[redirect] Following redirect to https://web.facebook.com/watch/?v=1200825533700148
[facebook] 1200825533700148: Downloading webpage
[facebook] 1200825533700148: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 677, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 591, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
## Description

Facebook is generally broken. About half of the times I try to download a video from there, it fails. Both the post's base URL and the result from "Copy Link" fail. It began to happen about a week ago.

**Comment by tgkprog** [comment]
Yes another example

/usr/local/bin/youtube-dl -U
youtube-dl is up-to-date (2021.05.16)


/usr/local/bin/youtube-dl --verbose  https://m.facebook.com/story.php?story_fbid=4298741616854161&id=341163402640457


[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://m.facebook.com/story.php?story_fbid=4298741616854161']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[facebook] 4298741616854161: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


[1]+  Exit 1                  /usr/local/bin/youtube-dl --verbose https://m.facebook.com/story.php?story_fbid=4298741616854161

**Comment by D0LLYNH0** [comment]
@tgkprog, add the link in quotes and watch the magic happen...

**Comment by lucmp** [comment]
@tkgprog, your link works for me. I can download that video with yt-dl.

**Comment by Bartalos** [comment]
I can confirm this, Its not working for me either (Ubuntu 20.04)

 youtube-dl https://www.facebook.com/103885184808017/videos/298807061940874 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/103885184808017/videos/298807061940874', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-73-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[facebook] 298807061940874: Downloading webpage
[facebook] 298807061940874: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 677, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 591, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data;

**Comment by lucmp** [comment]
@Bartalos. Nazdar. Your link works for me. I can download it. This is really weird.

**Comment by tgkprog** [comment]
Might be file name issue on Ubuntu. Will try with quotes or alt file name

**Comment by dirkf** [comment]
The URL needs to be quoted '' in a POSIX shell because the embedded `&` is interpreted as a background execution instruction. So you wanted:
```
youtube-dl --verbose https://m.facebook.com/story.php?story_fbid=4298741616854161&id=341163402640457
```
but you got these two commands instead
```
youtube-dl --verbose https://m.facebook.com/story.php?story_fbid=4298741616854161 &
id=341163402640457
```
OP's URL fails for a different reason:
```
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

From other reports it seems that FB gives this error in some countries and the `Cannot parse data` in others.
