### ISSUE TITLE
Broken link for  Microsoft Visual C++ 2010 Redistributable Package (x86) link in README.md's link.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#29222]
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#the-exe-throws-an-error-due-to-missing-msvcr100dll says "The exe throws an error due to missing MSVCR100.dll

To run the exe you need to install first the Microsoft Visual C++ 2010 Redistributable Package (x86)."

However, its https://www.microsoft.com/en-US/download/details.aspx?id=5555 link is broken. I found it in https://www.microsoft.com/en-us/download/details.aspx?id=26999, but it doesn't mention Windows 10 (64-bit) so I am not sure if it is safe to install it into my brand new, updated 64-bit W10 Pro PC.

**Comment by antdude** [comment]
Thank you for the quick fix, dstftw! Do I assume it is OK to install and use in an updated, 64-bit W10 Pro?

**Comment by Vangelis66** [comment]
@antdude: 

https://docs.microsoft.com/en-US/troubleshoot/cpp/minimum-service-pack-levels#visual-c-2010-sp1-redistributable-package

BTW, M$ documentation is known to contain omissions/false info, etc... 😞 
However, since the official `youtube-dl.exe` binary is **32-bit**, make sure you download and install file **vcredist_x86.exe** (32-bit variant); you may optionally co-install **vcredist_x64.exe** if, in the future, you come across a 64-bit application built with VS2010...

**Comment by antdude** [comment]
Thank you, Vangelis66. I didn't want to break my new W10! :)
