### ISSUE TITLE
Issue outputting % character?

### ISSUE THREAD

**Issue by jriker1** [ytdl-org/youtube-dl#29231]
When exporting video and the filename has a percent symbol in it like 100% as below:

youtube-dl  --merge-output-format mkv --postprocessor-args "-strict experimental" -f "bestvideo+bestaudio/best" --embed-thumbnail --add-metadata https://www.youtube.com/watch?v=x3P2gi4QgyY -o "Is Universal Studios 100% Back To Normal MASSIVE Crowds &amp; Being Seated Next To Strangers On Rides!.mkv"

I get back:

ERROR: Error in output template: unsupported format character 'B' (0x42) at index 26 (encoding: 'cp1252')

Technically the percent symbol in a filename is valud, and having percent between double quotes saves like if you do mkdir % or mkdir "%" both create a folder named %, but on the above it errors out for some reason.

**Comment by dstftw** [comment]
`%` must be escaped in output template.

**Comment by rautamiekka** [comment]
If you only want the filename and the extension (which is a bad idea cuz if the name changes on YT you'll redownload the same again, wasting space, or alternatively you download another resolution, thus requiring having to go find the old (or even the new one) file to delete (assuming you don't try to DL the same vid again)), you should use this for the `-o`:
```
%(title)s.%(ext)s
```
I recommend this instead due to the points mentioned above:
```
%(title)s %(resolution)s #%(id)s#.%(ext)s
```

If you're on Window$ and using Command Prompt, put double quotes around the string; if you're using a Batch script along with Command Prompt, you need to use 2 percentage signs.

^ If you aren't using Window$' Command Prompt, use single quotes instead. No such problems with the percentage signs.
