### ISSUE TITLE
How is "best audio" determined?

### ISSUE THREAD

**Issue by donjoe0** [ytdl-org/youtube-dl#29376]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How does youtube-dl determine which audio file is "best"?

Based on the results I get with `-x` or `-f "bestaudio"` for [this video](https://www.youtube.com/watch?v=W6Ak2_TJ5zs) I'd say it's not the same method as YouTube itself uses and is incorrect: in both desktop and Android browsers I've tried, the web player for YouTube always serves format 251 (Opus) as the best audio, while youtube-dl seems to think format 140 (M4A) is the best for this particular file, and always downloads that one for `-x` or `-f "bestaudio"`, I guess because it's seeing a higher bitrate. But YouTube doesn't decide it like that, YouTube knows the technical differences between the codecs and knows Opus is technically superior and always prefers that one (if the bitrates are close enough, I guess they wouldn't prefer Opus if it had like half the bitrate vs. the M4A but anyway). And if you download both and open them in Audacity and set the views to Spectrogram you can immediately see a big reason to prefer the Opus: the M4A encoding cuts out all content above 16 kHz, while Opus preserves frequencies up to the limit of human hearing, 20 kHz.

So is youtube-dl ignoring codec performance differences and determining the M4A audio to "sound better" whenever it has even 1 kbps more than the Opus version?

**Comment by dirkf** [comment]
Basically, yes.

The formats are sorted using parameters acquired during extraction.
 
For audio-only, the normal sort order (method `_sort_formats()` of class `InfoExtractor`) uses, in order, and if available:
* `language_preference` (rarely set by extractors)
* `quality` (normally 0 for YT audio)
* `tbr` (total bit-rate)
* `filesize` (same as `tbr` apart from a factor, duration)
* `protocol` (HTTP/HTTPS preferred)
* `abr` (same as `tbr`)
* `ext` (`aac`<`mp3`<`m4a`<`webm`<`ogg`<`opus` if `--prefer-free-formats`; otherwise
`webm`<`opus`<`ogg`<`mp3`<`aac`<`m4a`).

Any particular extractor can customise the sort order. Someone who cared could add a `perceived_quality` parameter to formats in the YT extractor, calculated by some heuristic function of codec and bit-rate and change the sort-order to use that ahead of or instead of `tbr`.

You could use `-f 'bestaudio[acodec=opus]/bestaudio'` to prioritise opus generally, or just `-f 251/bestaudio`.

**Comment by donjoe0** [comment]
OK, thank you. Then I think I will report this as a bug, since "bestaudio" is not really the best audio - not decided on perceptual/psychoacoustic principles or on codec performance, and also not decided like YouTube itself decides it.

**Comment by donjoe0** [comment]
I don't remember where I got the information that Opus is better than AAC at equal bitrate, but SoundExpert's listener-reports based stats don't confirm any such thing in any bitrate category including the 110-140 kbps area where most YT videos seem to live these days: http://soundexpert.org/encoders-128-kbps

Opus seems worse than both MP3 and AAC at around 112 kbps, I guess it really is the correct choice to get the AAC stream as "bestaudio" whenever the bitrate is higher. It might be the correct choice even when bitrates are equal.

**Comment by dirkf** [comment]
https://wiki.hydrogenaud.io/index.php?title=Hydrogenaudio_Listening_Tests ?

The lesson of http://soundexpert.org/encoders seems to be that you should just go for 192kbit/s and then you won't be able to distinguish the encoder.

Sites (and users) may also qualify 'best' with other criteria than perceived audio quality, such as codec support.

**Comment by donjoe0** [comment]
> The lesson of http://soundexpert.org/encoders seems to be that you should just go for 192kbit/s and then you won't be able to distinguish the encoder.

No, what you seem to be talking about corresponds to SoundExpert's rating of 5 and it has to be the rating of 100% of users who have sent in results (i.e. the darkest bar on the shaded bars representation of the codec's rating should be at or above 5). This only starts happening around 256 kbps and not all codecs can do it that low, some of the Bluetooth codecs which use no psychoacoustic principles still need to go past 300-ish kbps to reach full transparency for presumably-all listeners.
