### ISSUE TITLE
ORF Radiothek has changed the URLs

### ISSUE THREAD

**Issue by jogitgl** [ytdl-org/youtube-dl#29394]
youtube-dl version 2021.06.06

ORF has changed the URLs for Radiothek.
I have tested the URLs in the file "orf.py.new" and the downloads are working now without problems.
But how these URLs can be changed in the official youtube-dl version?

**diff orf.py orf.py.new**
**191c191**
**<             'http://audioapi.orf.at/%s/api/json/current/broadcast/%s/%s'**
**---**
**>             'https://audioapi.orf.at/%s/api/json/current/broadcast/%s/%s'**
**228c228**
**<     _VALID_URL = r'https?://(?P<station>fm4)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>4\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>fm4)/(?P<date>[0-9]+)/(?P<show>4\w+)'**
**252c252**
**<     _VALID_URL = r'https?://(?P<station>noe)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>noe)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**265c265**
**<     _VALID_URL = r'https?://(?P<station>wien)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>wie)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**278c278**
**<     _VALID_URL = r'https?://(?P<station>burgenland)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>bgl)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**291c291**
**<     _VALID_URL = r'https?://(?P<station>ooe)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>ooe)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**304c304**
**<     _VALID_URL = r'https?://(?P<station>steiermark)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>stm)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**317c317**
**<     _VALID_URL = r'https?://(?P<station>kaernten)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>ktn)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**330c330**
**<     _VALID_URL = r'https?://(?P<station>salzburg)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>sbg)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**343c343**
**<     _VALID_URL = r'https?://(?P<station>tirol)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>tir)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**356c356**
**<     _VALID_URL = r'https?://(?P<station>vorarlberg)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>vbg)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**369c369**
**<     _VALID_URL = r'https?://(?P<station>oe3)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>oe3)/(?P<date>[0-9]+)/(?P<show>\w+)'**
**382c382**
**<     _VALID_URL = r'https?://(?P<station>oe1)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'**
**---**
**>     _VALID_URL = r'https?://radiothek\.orf\.at/(?P<station>oe1)/(?P<date>[0-9]+)/(?P<show>\w+)'**

**Comment by jkirk** [comment]
Actually the _station_ URLs still work fine, but you are right: the _radiothek_ URLs are not supported (I am working on it).

For example, this _station_ URL (currently) works: https://oe1.orf.at/player/20210723/645522 this _radiothek_ URL does not: https://radiothek.orf.at/oe1/20210723/645522 (both URLs provide the same mp3 file).

So your patch would break the ability to download the _station_ URLs (although I was not able to apply your patch, because of missing white spaces. You should use [fenced code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to paste your code).

But you inspired me to look at an older issue (#26043) where we already talked about the _radiothek_ URLs and now try to implement the extractor.

You also asked:
> But how these URLs can be changed in the official youtube-dl version?

You might want to read the [GitHub Docs](https://docs.github.com/en) first, but basically you [fork and clone](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the project, make changes and [submit a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by jkirk** [comment]
Thanks @dirkf for the clean up!

This triggered me to take another look into this issue.
I've tested an ORF OE1 (station) URL with `youtube-dl "https://oe1.orf.at/player/20210723/645522"` (with youtube-dl 2021.12.17, I haven't tested the latest version) . This still works.

ORF Radiothek does not exist anymore. It seems it has been superseded by ORF Sound: https://sound.orf.at/.

I think this issue can be closed; I will close my PR: https://github.com/ytdl-org/youtube-dl/pull/29679.

**Comment by dirkf** [comment]
Is https://oe1.orf.at/player/20210723/645522 an actual URL that can be found from sound.orf.at or any other orf.at site?

Currently I'm just finding `sound.orf.at/radio/{station}/sendung/{id}` which may also have a final `/{slug}`. However I see that the player URL is still valid (with no redirect) and playable, so I'll have to make sure it still gets extracted.

There are also `/collection/...` URLs where `/collection/{id}` brings up a playlist page and `/collection/{collection_id}/{item_id}` is one item in the playlist. Such an item may be an `upload` or `podcast-episode`, or it may be a `broadcast`, `broadcastitem` or `program` associated with a `station`, each with its own API.

I'll close the issue when an new ORF extractor module gets merged.

**Comment by dirkf** [comment]
Please test #32802 and report there.
