### ISSUE TITLE
Why hasn't there been a recent Windows build since 2021-06-06 ?

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#29710]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by rgiuffre** [comment]
Is anyone going to make a recent Windows build?  I would do it, but I don't know how.
Thanks!

**Comment by rautamiekka** [comment]
There's no new release of the software in other than source code form. You can easily run the pure source code if you've installed Python, anyways.

Dunno what happened to the devs, probly just a burnout (at worst: loss of interest), which is perfectly understandable.

**Comment by 89z** [comment]
Do you need a downloader for youtube.com? or something else? If for YouTube, other projects are available that are up to date.

**Comment by rgiuffre** [comment]
youtube-dl is the only one I really trust. I know about yt-dlp, youtube-dlc, and a few others, but Windows Security keeps deleting/quarantining the others. It just seems weird that after the whole legal battle taking down the youtube-dl github because of copyright laws, that the regular contributors have now just -- stopped --. I use youtube-dl daily, and I would GLADLY compile Windows executables from source, if I knew how. I have Python 3,9, and I could run the source directly from python, but I don't like doing it that way. Can someone post a message with detailed instructions on how to compile the source code into a 32/64-bit Windows executable? If the devs won't do it, I'll do it myself.  Thanks!

**Comment by 89z** [comment]
If youre interested, I have an alternative tool in Go here:

https://github.com/89z/mech/releases

Or you can build yourself:

https://github.com/89z/mech/tree/master/cmd/youtube

**Comment by nicolaasjan** [comment]
@rgiuffre
> I know about yt-dlp, youtube-dlc, and a few others, but Windows Security keeps deleting/quarantining the others.

Probably because of the integrated `pycryptodome` module, which is erroneously flagged as malware.
Yt-dlp is perfectly safe.
The Linux version of it, that hasn't got the Python modules built in, is flagged by [0 antivirus engines](https://www.virustotal.com/gui/file/9bb1a4897a8c7a9b10c1d751d0402f1adaa3592669c840fb7160ae540a579876/detection).

> I would GLADLY compile Windows executables from source, if I knew how. I have Python 3,9, and I could run the source directly from python, but I don't like doing it that way. Can someone post a message with detailed instructions on how to compile the source code into a 32/64-bit Windows executable? If the devs won't do it, I'll do it myself. Thanks!


- Open cmd as admin and run:
     `python.exe -m pip install pyinstaller` (Python must be in your PATH).
- Download the youtube-dl source code: https://github.com/ytdl-org/youtube-dl/archive/master.zip
- Extract to the folder `youtube-dl-master`.
- Open a command prompt in the folder `youtube-dl-master` and run:
     `pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl`
-  `youtube-dl.exe` is built and can be found in the `dist` subdirectory.

If your Python is 64bit, then youtube-dl will be 64bit as well. :)

**Comment by simteraplications** [comment]
it's extremely anoying for people like me who use youtube dl integrated in a program because we always have to push a new release when youtube dl breaks. A commonly occuring problem these days is that the age restriction guard breaks which makes a downloader worthless on such videos. I have already made custom builds but it is harder to get those over to users.

**Comment by 89z** [comment]
@simteraplications you only have yourself to blame, if you keep using YouTube-DL. Other packages are available that are up to date

**Comment by rgiuffre** [comment]
THANK YOU!

**Comment by rgiuffre** [comment]
I don't think it's because youtube-dl "breaks".  I think the websites are constantly changing their tactics to prevent people who use software like youtube-dl to download videos.  I am so frustrated with DRM... I can easily view videos on MS-Edge, but in no way, shape or form, can I download them in ANY of these "downloaders".

**Comment by nicolaasjan** [comment]
> THANK YOU!

Concerning virus detections, read this:
[yt-dlp is detected as a virus](https://github.com/yt-dlp/yt-dlp/issues/25).
Especially [this](https://github.com/yt-dlp/yt-dlp/issues/25#issuecomment-832544683).

FWIW, I compiled yt-dlp myself yesterday on Windows 10 with Python 3.9 and VirusTotal had [only 1 detection](https://www.virustotal.com/gui/file/8d1c1839195001ed4d5babfe86048fa3a8ec0ca2a00fa81e695a48d90bf1550b/detection).
(btw, the compilation procedure is [somewhat different](https://github.com/yt-dlp/yt-dlp#compile)).

On the other hand, the official yt-dlp [release](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.08.02) (built with Python 3.8) of it gave: [6 security vendors flagged this file as malicious](https://www.virustotal.com/gui/file/be95dceb29eb7c80e69a68d17e5575765978b3b89355a747ce5277202b7517f3/detection).

This is a Windows only problem, because the Unix version doesn't have the Python stuff built in (uses system Python).
