### ISSUE TITLE
Rename existing file by checking id within filename when video title changes rather downloading again

### ISSUE THREAD

**Issue by nudgegoonies** [ytdl-org/youtube-dl#29806]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Context:
I regulary use youtube-dl to mirror all videos of a specific youtube user by running "youtube-dl https://www.youtube.com/c/$USERNAME/videos" who often renames video titles to unify them. The id does not change. This results in downloading lots of duplicates that fill the folder.

Idea:
Add an option to rename local files containing the id. Check current directory for *.$ID.$FILEFORMAT file and rename it when the title differs. This would also help with --restrict-filenames.

**Comment by dirkf** [comment]
This sounds like a situation for which the `--download-archive` option was created.

As there isn't a general way to get from the ID of a previously downloaded file to the file itself, nor vice versa (because of the `-o` option), you'd still have to create some sort of scripting solution if you wanted to rename the previously downloaded files to match the user's current whim.

**Comment by rautamiekka** [comment]
The idea would work if the filename format is saved as the default (mine is completely diff: `"_websites_/com/youtube/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s"`), then dupes can be found.

You're on the correct path with the ID idea, which is why my format's the mentioned one.

(Knowing YT changes things and the resolution and bitrate aren't a reliable measure, I doubt there's any reliable ways to avoid skipping a better-quality (or same quality at lower filesize) later.)

**Comment by dirkf** [comment]
This proposal isn't going to be implemented as far as I'm concerned. Please raise a new issue if `--download-archive` doesn't work.
