### ISSUE TITLE
Is youtube-dl dead?

### ISSUE THREAD

**Issue by KBDCALLS** [ytdl-org/youtube-dl#29872]
Is youtube-dl dead ?

**Comment by nicolaasjan** [comment]
Related:
https://github.com/ytdl-org/youtube-dl/issues/29753

**Comment by fastily** [comment]
> Is youtube-dl dead ?

Unfortunately it would appear so.  The (actively maintained) spiritual successor is [yt-dlp](https://github.com/yt-dlp/yt-dlp)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I'm really starting to worry about if @dstftw is alive.

**Comment by Rekrullurker** [comment]
Unfortunately, I have an old system and yt-dlp doesn't work for me. And also unfortunately, I happen to be in the 0.00000000000000000000000000001% of users here who doesn't know to compile the source code myself to work on my system, so that leaves me out. :(

**Comment by nicolaasjan** [comment]
> Unfortunately, I have an old system and yt-dlp doesn't work for me. And also unfortunately, I happen to be in the 0.00000000000000000000000000001% of users here who doesn't know to compile the source code myself to work on my system, so that leaves me out. :(

`yt-dlp_x86.exe` should work from Windows Vista upwards.
See [this line](https://github.com/yt-dlp/yt-dlp/blob/8026e5015274f3899f5db2d43eaaecdfc7d94ffd/.github/workflows/build.yml#L142) in the  `build.yml` file.
If you use Windows XP you're out of luck.

**Comment by Rekrullurker** [comment]
Yes, I have an OLD system.

You know I find really amazing? Windows XP was supposedly the dominant operating system for about a decade even though it's apparently not powerful enough to run any software at all. Even command line programs need the awesome power of Vista and above to function.

How did the computer world survive for an entire decade with an operating system that nobody can write software for? I mean, since all these indispensable features that programs absolutely need to function, were only introduced with Vista, I don't understand how XP could have survived, considering that it lacked the ability to run any software.

**Comment by rautamiekka** [comment]
ytdl, like most Python apps, is coded so that you don't need to compile to use (hell, the compilation ain't so much a compilation as it's checking the code and making a ZIP), you can just use it like so:
1) download the repo into a folder.
2) run Python on the `youtube_dl` folder you see in the repo root:
```batch
python YTDLREPO\youtube_dl --verbose URL
```
You'll need a WinXP-supported Python >=2.6.x.

**Comment by Vangelis66** [comment]
@nicolaasjan wrote: 

> yt-dlp_x86.exe should work from Windows **Vista** upwards.
> (redacted)
> If you use **Windows XP** you're out of luck.

FTR, last XP-compatible release for `yt-dlp` is [2021.06.09](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.06.09) 😸 

@rautamiekka wrote: 

> while the last XP-supported was [3.4.3](https://www.python.org/downloads/release/python-343/)

...Well, yes, **3.4.x** is the **last** CPython3 to support WinXP, but the PSF **do offer** binary installers for the last "feature-update" release **3.4.4**, which can install and run fine under **XP SP3**: 

https://www.python.org/downloads/release/python-344/

Last ever 3.4.x release was ("security-only" release) **3.4.10**, for which a third party 32-bit installer [is available](http://matejhorvat.si/en/windows/python/index.htm)... 

OT discussion: 

@Rekrullurker wrote: 

> Windows XP was supposedly the dominant operating system for about a decade even though it's apparently not powerful enough to run any software at all. Even command line programs need the awesome power of Vista and above to function.
> 
> How did the computer world survive for an entire decade with an operating system that nobody can write software for? I mean, since all these indispensable features that programs absolutely need to function, were only introduced with Vista, I don't understand how XP could have survived, considering that it lacked the ability to run any software.

Since I also engage in retro-computing, I can empathise. 👍 ... Some perspective: 

When the vendor (Microsoft) end-of-live's (EOL) a Window OS (End of Extended Support), this fact alone gives the majority of coders the perfect reason/excuse to also drop support for that OS in their project(s); the main reason given to users is "security" related, but that is not the whole story, of course...

As users of EOL'ed  WinOSes inevitably decline in numbers, the coders lose incentive to continue supporting them, due to reduced "traffic/userbase"; sometimes, they only have to do very little to continue that support, but even then they decide to forego old WinOS support altogether...

Other times (and, as I understand it, this is the most frequent occurrence), they have to drop EOL'd OS support to focus better on developing for the OSes the majority of their users happen to be on; later and supported WinOSes come with improved libs/support for updated versions of coding languages and newer toolchains/compilers can better optimise compiled code for the current generation of OSes most use; this is especially true in the case of Microsoft derived compilers (e.g. **Visual Studio** - CPython uses that...), which, by vendor's decision, best support only the latest Windows versions... 

Also, many dev-teams are comprised of just a few active maintainers, keeping old WinOS support for long is just an overhead/development "headache" they simply can't afford...

Of course, I'm not talking here about the **big players** in the web, _they_ always want you to toss your older - but still working - H/W into a landfill (contributing more to environmental pollution) and fork out serious money (they always assume you got lots of it... ) out of your pocket to buy the latest and greatest H/W that can run the latest and greatest version of Apple's/Microsoft's etc. OS...

Returning **on-topic**, I don't think the fact `youtube-dl.exe` currently happens to **still** support **Windows XP SP3** is a conscientious decision, more like a "by necessity" one... 😜 
The Python module (**py2exe**) the official team use(d) to compile the **Windows 32-bit executable** breaks/fails in Python versions > **3.4.x**, so they had to "freeze" the python interpreter inside the binary to v3.4.4 (which, as stated above, is the last to support XP... ).

Best regards 😄

**Comment by pirate486743186** [comment]
@Rekrullurker

> Yes, I have an OLD system.
> 
>... Windows XP was supposedly the dominant operating system for about a decade...

May i suggest you switch to Linux? I'm using a Windows XP era 32bit laptop
At that level of old, Linux is the superior choice.
lol, Windows 11 want a computer from 2017 maximum, in practice even less then that.

I recommend Debian 11 32 bit version with nonfree components.
For the desktop, MATE or xfce or LXDE or LXQT
https://wiki.debian.org/
https://cdimage.debian.org/images/unofficial/non-free/images-including-firmware/

I'm assuming, since you are on this site, you'll be able to figure out what to do.

**Comment by rusty-snake** [comment]
This issues can be closed IMHO, #30568.
