### ISSUE TITLE
How to get ffmpeg output when youtube-dl uses it as downloader?

### ISSUE THREAD

**Issue by abvalyn** [ytdl-org/youtube-dl#29888]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

TL;DR Is there a way to see ffmpeg output when youtube-dl uses it as downloader?

Longer:

It was available for some time (e.g. in release 2021.04.07 for pornhub-m3u8 videos and then logic was changed and output was hidden by this [commit](https://github.com/ytdl-org/youtube-dl/commit/545d6cb9d06a8bf32bcd24463c0fd25e650bb2c7). The example of such an output might be found [here](https://github.com/ytdl-org/youtube-dl/issues/28698)).

It shows useful warnings/errors (like "HTTP error 429 Too Many Requests" and "HTTP error 403 Forbidden", etc.) which might be ignored by youtube-dl itself. Youtube-dl might show successful download when some peaces of video are actually not downloaded. I'd like to get at least ffmpeg logs to avoid such situations.

**Comment by dirkf** [comment]
Try `--verbose`/`-v`.

If that's too much, use`--external-downloader-args '-v 32'`, or 24 or 16 instead of 32 for still less.

If that's not enough, use`--external-downloader-args '-v 48'`.

Only the ffmpeg authors can explain why their program that does a lot of multiplication elsewhere was unable to turn numbers like 1, 2, 3, 4, ... into 8, 16, 24, 32, ... (though there are text alternatives).

**Comment by abvalyn** [comment]
Thanks for your reply. 

I investigated a little more. It looks like last version of youtube-dl with `--verbose` flag actually shows HTTP-errors if they lead to fragment fail and hide them if e.g. 6 out of 10 attempts are failed.
