### ISSUE TITLE
Yt-Dl instant crash

### ISSUE THREAD

**Issue by ChronosNoob** [ytdl-org/youtube-dl#29988]
Im very sorry if im missing sosmething super obvious but whenever i try to type or paste a url into yt-dl it crashes. I have linked a video and a screenshot of what it says.
I really hope someone here can help.
Thanks in Advance.
https://user-images.githubusercontent.com/83444922/133908347-643fb450-daed-4392-9969-0fa2380e92d9.mp4
![image](https://user-images.githubusercontent.com/83444922/133908441-29536598-389d-49df-9f74-1af94450a933.png)

**Comment by kikuyan** [comment]
From [README.md#BUGS](https://github.com/ytdl-org/youtube-dl#bugs):
Please include the full output of youtube-dl when run with -v, i.e. add -v flag to your command line, ...
Do not post screenshots of verbose logs; only plain text is acceptable.

**Comment by dirkf** [comment]
From the Fine Manual:
>[youtube-dl is a command-line program to download videos from YouTube.com and a few more sites. ](https://github.com/ytdl-org/youtube-dl#users-content-description)

You need to [open](https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/) a [command line window](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands) and then type a yt-dl command at the prompt, like so:
```
youtube-dl --help
```

```
youtube-dl "url-of-page-with-video"
```
Instead of `youtube-dl`, put the path name of your copy of the program. You ought to rename it from `...\Downloads\youtube-dl (1).exe` to `...\Downloads\youtube-dl.exe` first.
