### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by dileepar** [ytdl-org/youtube-dl#30035]
Hi,

I'm getting the below error when trying to download a video. 
![Inkedyt-error](https://user-images.githubusercontent.com/5918533/135547899-00f17200-6e71-4f90-baff-837d004ae878.jpg)

Is it just for me or a known issue?

**Comment by dirkf** [comment]
The file `cookies.txt` should be a UTF-8 text file, but it isn't.

Maybe you can open it in a text editor and save it as UTF-8, or modify whatever procedure you use to create the file?

**Comment by dileepar** [comment]
> The file `cookies.txt` should be a UTF-8 text file, but it isn't.
> 
> Maybe you can open it in a text editor and save it as UTF-8, or modify whatever procedure you use to create the file?

I think it's already in utf8. I use convert-cookies.js suggested in the original post to convert cookies into Netscape cookies format

**Comment by dirkf** [comment]
You might think so, but the yt-dl code is saying that the file can't be decoded as UTF-8:
```
        with io.open(filename, encoding='utf-8') as f:
            for line in f:  # my comment: failing line utils.py:2832
                try:
                    cf.write(prepare_line(line))
                except compat_cookiejar.LoadError as e:
                    write_string(
                        'WARNING: skipping cookie file entry due to %s: %r\n'
                        % (e, line), sys.stderr)
                    continue
```
It can't be that your file is [UTF-8 with a BOM](https://www.linuxtut.com/en/60d32006d13512ffeaff/), rather than plain UTF-8, since the `utf_8` decoder knows about BOMs, even if `utf_8_sig` (which strips any BOM) would appear to have been a better choice.

Is it perhaps UTF-16?
