### ISSUE TITLE
[QUESTION] OAuth2 support

### ISSUE THREAD

**Issue by ArcadeArchie** [ytdl-org/youtube-dl#30057]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,
im currently working on an App wrapper for youtube-dl and i was wondering if OAuth2 Accestokens are supported for user authtication. 
So the End-User doesnt have to re-ender credentials and 2FA codes for authentication everytime the wrapper is used

**Comment by dirkf** [comment]
A pedant might point out that OAuth Bearer tokens provide [authorisation rather than authentication](https://www.oauth.com/oauth2-servers/signing-in-with-google/), since the whole point is that the user's identity is verified by the OAuth server when the token is issued and the resource being accessed doesn't necessarily get to know about it.

Any authorisation procedure is specific to the extractor for the site. All that yt-dl does is pass the details used for authorisation, which might be "username" and/or "password", or one or more cookies, or an `Authorization` header, to the extractor. Several existing extractors do manipulate OAuth data internally.

Regarding YouTube in particular, #5936 suggests that OAuth2 wasn't helpful at that time (2015).

See also #11176 and more generally review https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue++OAuth2.

It seems that there are potential difficulties for anything more than sending a recently minted access token as the value of `--password` and raising `ExtractorError` if refresh is required. If refresh tokens are supported (we could pass the token as the value of `--user`), a new access token might be acquired automatically; presumably any newly acquired token would have to be stashed somewhere or otherwise passed back to the user for future use.

If OAuth2 support was being added to an extractor, it would be useful to do so such that the generic aspects could be used by other extractors.

**Comment by 89z** [comment]
> A pedant might point out that OAuth Bearer tokens provide [authorisation rather than authentication](https://www.oauth.com/oauth2-servers/signing-in-with-google/), since the whole point is that the user's identity is verified by the OAuth server when the token is issued and the resource being accessed doesn't necessarily get to know about it.

Yet again, @dirkf adding pointless and unhelpful comments. If youre talking abou the YouTube extractor, I have implemented OAuth support in my package as well as tool:

~~~
youtube [flags] [video ID]
  -a int
        audio itag (-1 to skip)
  -c    OAuth construct request
  -e    use embedded player
  -i    info only
  -r    OAuth token refresh
  -v int
        video itag (-1 to skip)
  -x    OAuth token exchange
~~~

https://github.com/89z/mech

**Comment by ArcadeArchie** [comment]
@89z i wasnt looking for an extra tool to do the OAuth code flow for me, what i wanted to know and which @dirkf mostly answered is if OAuth Accesstokens can be used as credentials instead of the user having to enter their Credentials to authenticate. 

As mentioned in #5936 using a workaround with the ```--add-header``` option by adding it as the Authenticaion Header might work.

So for now i'll close this issue and try to see if the workaround works for me and thanks to @dirkf for the info.
