### ISSUE TITLE
Choosing Audio Quality causing not download video from youtube

### ISSUE THREAD

**Issue by Max-Enrik** [ytdl-org/youtube-dl#30074]
I tried to find an answer in `Issues` section, unfortunately I didn't find useful answer.

Choosing audio quality causing not to download videos. I was using `ytdl-format=bestvideo[height<=?1080]+bestaudio/best` since video didn't downloaded and I removed that code from `mpv.conf` file. And everything is fine so far. But I'd like to choose 1080p with that code. This problem doesn't come from Video Quality after I removed that line of code I still watch video with > 1080p. So I think the issue does come from Audio Quality.

Any ideas?

**Comment by dirkf** [comment]
This format selection option 
```bestvideo[height=1080]+bestaudio/best[height=1080]/bestvideo+bestaudio/best```
should give you a 1080 video if it exists and the default selection otherwise.

If neither that nor further study of the [Manual](https://github.com/ytdl-org/youtube-dl#user-content-format-selection) resolves your question, please provide logs for "`youtube-dl -v -F `\<your url>" and for "`youtube-dl -v --get-format -f `\<your format selection> \<your url>" with the various format selection options that you've tried.

**Comment by Max-Enrik** [comment]
Look like I made it with your help, I really highly appreciate that.
```
C:\mpv>youtube-dl.exe youtube-dl -v -F "https://www.youtube.com/watch?v=jenVMnOi2uA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['youtube-dl', '-v', '-F', 'https://www.youtube.com/watch?v=jenVMnOi2uA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Proxy map: {}
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 2390, in _real_extract
youtube_dl.utils.ExtractorError: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
```

**Comment by dirkf** [comment]
You've put the command twice: leave one out!
`youtube-dl.exe `<strike>youtube-dl</strike>` -v -F "https://www.youtube.com/watch?v=jenVMnOi2uA`

**Comment by Max-Enrik** [comment]
Here you go.
```
C:\mpv>youtube-dl.exe -v -F "https://www.youtube.com/watch?v=yOhGkZ4U4lI"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=yOhGkZ4U4lI']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] yOhGkZ4U4lI: Downloading webpage
[info] Available formats for yOhGkZ4U4lI:
format code  extension  resolution note
249          webm       audio only tiny   49k , webm_dash container, opus @ 49k (48000Hz), 1.90MiB
250          webm       audio only tiny   56k , webm_dash container, opus @ 56k (48000Hz), 2.16MiB
251          webm       audio only tiny  103k , webm_dash container, opus @103k (48000Hz), 3.93MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 4.93MiB
278          webm       256x144    144p   19k , webm_dash container, vp9@  19k, 30fps, video only, 762.53KiB
160          mp4        256x144    144p   34k , mp4_dash container, avc1.4d400c@  34k, 30fps, video only, 1.31MiB
242          webm       426x240    240p   28k , webm_dash container, vp9@  28k, 30fps, video only, 1.07MiB
133          mp4        426x240    240p   70k , mp4_dash container, avc1.4d4015@  70k, 30fps, video only, 2.68MiB
134          mp4        640x360    360p   49k , mp4_dash container, avc1.4d401e@  49k, 30fps, video only, 1.90MiB
243          webm       640x360    360p   52k , webm_dash container, vp9@  52k, 30fps, video only, 1.99MiB
244          webm       854x480    480p   81k , webm_dash container, vp9@  81k, 30fps, video only, 3.12MiB
135          mp4        854x480    480p   84k , mp4_dash container, avc1.4d401f@  84k, 30fps, video only, 3.21MiB
136          mp4        1280x720   720p  158k , mp4_dash container, avc1.4d401f@ 158k, 30fps, video only, 6.03MiB
247          webm       1280x720   720p  162k , webm_dash container, vp9@ 162k, 30fps, video only, 6.19MiB
298          mp4        1280x720   720p60  170k , mp4_dash container, avc1.4d4020@ 170k, 60fps, video only, 6.49MiB
302          webm       1280x720   720p60  185k , webm_dash container, vp9@ 185k, 60fps, video only, 7.07MiB
303          webm       1920x1080  1080p60  313k , webm_dash container, vp9@ 313k, 60fps, video only, 11.92MiB
299          mp4        1920x1080  1080p60  322k , mp4_dash container, avc1.64002a@ 322k, 60fps, video only, 12.28MiB
18           mp4        640x360    360p  139k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 5.33MiB
22           mp4        1280x720   720p  287k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

**Comment by NintendoManiac64** [comment]
Forgive my ignorance on youtube-dl's current behavior, but historically its "best" arguments only cared about bitrate without any regard for the codec.

I mention this because, if it sees AAC audio at 128kbps and Opus audio at 127kbps, it'd pick the AAC every single time despite Opus being a superior codec (that is, it provides better quality per bit).  The same goes for video - if youtube-dl found AVC at 5001kbps and VP9 at 5000kbps and even AV1 at 4999kbps, it'd pick AVC every time despite the VP9 being higher quality at that bitrate and _especially_ the AV1 being higher quality.

I say all of this to point that that, 99.99999999% of the time, format 251 will be the best audio quality as it is Opus at the highest bitrate that they encode it at.  Furthermore, a lot of YouTube's AAC encodes actually have some sort of cut-off at around 16kHz which is not present in their Opus encodes.  Lastly, 99.99% of all digitally-recorded video is natively recorded with audio that has a sampling rate at 48kHz which is what Opus uses, but YouTube's AAC encodes use 44.1kHz instead.

I wish something could be said the same about video, but the bitrates are much too variable.  For example, on the following video, the 1080p AVC encode has about twice the bitrate of the 1080p VP9 encode which should be more than enough to make the AVC encode higher quality:
https://youtube.com/watch?v=pAJrXicfWsM

Yet on the following video, the 1080p VP9 encode only has around a 4% lower bitrate than the 1080p AVC encode, therefore the VP9 encode should actually be higher quality since that shouldn't be enough bitrate for AVC to overtake VP9:
https://youtube.com/watch?v=L1v3ZmfV_hw

**Comment by dirkf** [comment]
> Forgive my ignorance on youtube-dl's current behavior, but historically its "best" arguments only cared about bitrate without any regard for the codec.
> ...
While this isn't on topic for OP's question (which, as above, may be more to do with mpv's integration), I would suggest that a 4% or less difference in bit-rates between H.264/AAC and VP9/Opus is not something that a person with a life should care about.

Legacy (as in, firmware that came with the box) media player non-support for VP9/Opus is a more realistic concern when selecting formats.
