### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by yoones** [ytdl-org/youtube-dl#30129]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yoones:~$ whereis youtube-dl
youtube-dl: /usr/local/bin/youtube-dl
yoones:~$ youtube-dl
/usr/bin/env: ‘python’: No such file or directory
```

## Description

OS: Debian 11.1

I have the following binaries installed:
- python2.7
- python3
- python3.9

The shebang of youtube-dl (`#!/usr/bin/env python`) does not work in this context since there is no executable file called `python`.

**Suggested solution:**

Have a shell script that acts as a launcher. This script could for instance embed a list of known python interpreters (python, python2.7, python3, ...) and use the first of the list that is present on the host.

**Comment by Almaz** [comment]
For me it worked like this: `sudo ln /usr/bin/python3 /usr/local/bin/python`.

**Comment by nudgegoonies** [comment]
Adjusting the shebang of youtube-dl to #!/usr/bin/env python3 works too.

**Comment by yoones** [comment]
> Adjusting the shebang of youtube-dl to #!/usr/bin/env python3 works too.

Yes but changing the shebang manually only lasts until the next update of youtube-dl.

**Comment by nudgegoonies** [comment]
Yes, but everything else is a workaround and not a fix. I have explicit not installed the python-is-python3 debian package to be able to find every shebang that ist wrong.

**Comment by dirkf** [comment]
If you installed the package they wouldn't be wrong, would they? And you can always uninstall it if you want none of your Python scripts to run, which is much more straightforward than managing a whole lot of manually patched scripts.

I take the position implied by the name of the package. If your script needs Python 2 put that in the shebang; otherwise just ask for Python. Let's hope that we don't have to go through all this again with some future Python 4.

**Comment by nudgegoonies** [comment]
Every new major Python X version should be no trouble as long all scripts use pythonX in the shebang and as long no one depends on a default python executable to be a specific major version which will definitely increase in the future ;-)

**Comment by jehoshua7** [comment]
Have just installed youtube-dl as per the instruction on Kubuntu 20.04.3 , and got the error message. If I do a `locate -i python` , there are many pages. Does anyone know where the python executable is on Kubuntu please ? I can see /etc/python2.7/ , /etc/python3/ , and /etc/python3.8/ paths but they do not have the library,etc

**Comment by dirkf** [comment]
Don't the original suggestions [here](https://github.com/ytdl-org/youtube-dl/issues/30129#issuecomment-946748616) help?

**Comment by jehoshua7** [comment]
It seems the Kubuntu configuration setup has nothing in /usr/local/bin though.

`ls -al /usr/bin/pyth*`

> lrwxrwxrwx 1 root root       9 Dec 28  2020 /usr/bin/python3 -> python3.8
-rwxr-xr-x 1 root root 5490488 Nov 27 07:14 /usr/bin/python3.8
lrwxrwxrwx 1 root root      33 Nov 27 07:14 /usr/bin/python3.8-config -> x86_64-linux-gnu-python3.8-config
lrwxrwxrwx 1 root root      16 Mar 13  2020 /usr/bin/python3-config -> python3.8-config

`ls -al /usr/local/bin/`

> total 51172
drwxr-xr-x  2 root root     4096 Jan 15 18:17 .
drwxr-xr-x 10 root root     4096 Aug  1  2020 ..
-rwxr-xr-x  1 root root      529 Jun  5  2021 bundle
-rwxr-xr-x  1 root root      531 Jun  5  2021 bundler
-rwxr-xr-x  1 root root 50540544 Sep  4 20:16 hugo
-rwxr-xr-x  1 root root  1837828 Jan 15 18:17 youtube-dl

**Comment by dirkf** [comment]
So either of the proposed solutions should work, assuming that Kubuntu 20.04 still has _python-is-python3_.

The proposal with the `ln` command is making a link in the `/usr/local/bin/` directory, which is normally ahead of the main system directories in the `PATH`, so that typing `python` causes `python3`, which is actually `python3.8`, to run.

**Comment by jehoshua7** [comment]
Thanks for your help @dirkf . The `ln` did nothing ,but the package `python-is-python3' did the trick.

**Comment by pablodz** [comment]
3.10 python3 uprgade on ubuntu 22 is the erro

**Comment by CesarDevesa** [comment]
Ubuntu 22.04

`sudo ln /usr/bin/python3 /usr/local/bin/python`
`sudo apt install python-is-python3`

 @pablodz, It Works for me!

**Comment by dirkf** [comment]
[Here](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1449990989) is a script that can be used in POSIX shell, adapting as necessary, to modify the shebang of single file self-extracting yt-dl program, and possibly any other script.

**Comment by byoso** [comment]
**Linux solution**
So the dev team for some reason doesn't want to use `#! /usr/bin/env python3` and prefers to ask the users to modify their system with python-is-python3. I wont argue with that, but as I don't want to do this, I show you a simple alternative solution on linux. Just add this script in your ~/bin directory (because it is in the PATH and without sudo, if you don't run an ubuntu fork os, add this directory to the PATH within the .bashrc) and use it to launch the app instead of using directly `youtube-dl`:

**myyoutube-dl** (make it executable)
```python
#! /usr/bin/env python3

import sys
import os

args = sys.argv[1:]

params = ""
for arg in args:
    params += f" {arg}"

os.system(f"python3 /usr/local/bin/youtube-dl{params}")

```

**Comment by dirkf** [comment]
Why on earth would you do that rather than just making a `python` link on your `PATH` that points to your preferred Python?

`~/bin` may be in your `PATH` but that isn't necessarily or widely so.

[some reason](https://github.com/ytdl-org/youtube-dl/issues/30129#issuecomment-1006067708).

**Comment by nudgegoonies** [comment]
Python 2 and 3 are incompatible major versions. With the introduction of Python 4 we will have the situation again that we need two different Python versions installed at the same time. A Python 3 program will not run on Python 2 and Python 4. So why rely on a default python that could be **any** major version rather than setting the **required** major version in the shebang which automatically selects the correct version?

**Comment by dirkf** [comment]
Youtube-dl is a Python program, not a Python2 or Python3 program. When Python2 was more of a thing, and when yt-dl was created, Python2 **was** Python. My personal memory of Pythons doesn't go back to Python 1.x, but I gather that regular small changes in language behaviour were typical between 1.x and early 2.x versions, without a big fork as happened with 2->3.

As Python3 became more widespread, compatibility shims were added to yt-dl so that the code now uses a subset of Python3, avoiding incompatible syntax (eg `f'{expression}'`) and with certain incompatible library calls hidden under aliases that invoke a shim suitable for the actual Python version.

Without speaking for [Debian](https://packages.debian.org/source/bullseye/what-is-python), I believe that this was their plan:
* remove the `python` executable (alias) to flush out programs that don't mention 2 or 3
* switch all packages that use Python to say one or the other explicitly
* allow users to provide a default for other Python programs by installing one of the mutually incompatible _python-is-python3_ or _python-is-python2_ (while it lasts).

In this framework, if you as a user or system admin have Python programs that care about the Python version but just ask for `python`, you should decide where the majority lies, install the appropriate _python-is-..._ package for those programs, and fix the others. yt-dl won't care whether you give it 2.7 or 3.9 (eg, but especially as I run those): it's just caught in the cross-fire.

This is just papering over the underlying problem that the Python language was forked incompatibly, like a toy language, but at least GvR did it more or less himself: JavaScript needs an entire standards committee.

**Comment by byoso** [comment]
Ok, thank you for making this point more clear. If I understand, the team wants to keep the app compatible with both 2 and 3. I will try to think about that, maybe it is possible to keep compatibility with both 2 and 3 another way.

**Comment by superbonaci** [comment]
macOS 14.5 does not have any python*, only python3.

**Comment by dirkf** [comment]
With such macOS, or if Debian abandons the package mentioned, either
* install using `-m pip` with a Python that is available, or 
* create a symlink to some Python executable on your system, like the above `python3`.

**Comment by superbonaci** [comment]
Does the `-m pip` install the latest nightly and keeps it updated? Because the stable version 2021.12.17 is broken for certain videos.

**Comment by superbonaci** [comment]
Why do you have to call directly python? They already made a mess renaming all `python2` links to `python` for compatibility, then `python3` to `python2` or `python`, and now they want to revert the changes.

I can't make a `python` symlink to `python3` system wide because can break something. python 1 and 2 are end of life this is why macOS does not include them anymore.

Could you offer 3 different nightlies where each one calls a different python? So brew.sh can download the best one for each system and not just call "python" for everybody. For example:

https://github.com/ytdl-org/ytdl-nightly/releases/tag/2024.06.21_python1
https://github.com/ytdl-org/ytdl-nightly/releases/tag/2024.06.21_python2
https://github.com/ytdl-org/ytdl-nightly/releases/tag/2024.06.21_python3

All files inside:
https://github.com/ytdl-org/ytdl-nightly/releases/download/2024.06.21_python3/youtube-dl
https://github.com/ytdl-org/ytdl-nightly/releases/download/2024.06.21_python3/youtube-dl.exe

**Comment by dirkf** [comment]
If you don't have a `python` executable now, symlinking your Python3 as `python` shouldn't affect anything (though there are weird code tricks that could be affected). A paranoid user could put the `python` link in a directory that's only added to `PATH` in the user's shell session, or only when needed, etc.

Other than the offered solutions, do the equivalent of `alias youtube-dl="python3 wherever/youtube-dl"` in your shell. You can also install the latest master using Homebrew (read their docs for the details that I have now forgotten). Or build the program yourself, or ask Homebrew (or similar) to package the release.

**Comment by superbonaci** [comment]
Why you just don't follow my recommendation? python and python2 are end-of-life.

**Comment by dirkf** [comment]
Apparently there is a known bilingual hack that we should use: https://github.com/ytdl-org/youtube-dl/pull/33292#issuecomment-5343908927.
