### ISSUE TITLE
cannot proceed because MSVCR100.dll was not found

### ISSUE THREAD

**Issue by noormazlina** [ytdl-org/youtube-dl#30143]
![image](https://user-images.githubusercontent.com/43901085/138559696-e868dd97-2392-4a54-b52b-cb3cec0bc45d.png)

**Comment by FixV** [comment]
They also don't have the file in the Visual Studio 2015, 2017, 2019, and 2022 x86 version.

Maybe download the Visual Studio 2010 (VC++ 10.0) SP1 (no longer supported) x86 version
then after download the Visual Studio 2015, 2017, 2019, and 2022 x86 version.

**Comment by FixV** [comment]
> You need to install the 32-bit Microsoft Visual C++ package which is needed to run yt-dl.
> 
> https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160
> 
> Note you need the 32 bit version (x86) since youtube-dl is a 32-bit application. you can install both the 32 & 64 bit versions if you like,.

They also don't have the file in the Visual Studio 2015, 2017, 2019, and 2022 x86 version.

Maybe download the Visual Studio 2010 (VC++ 10.0) SP1 (no longer supported) x86 version
then after download the Visual Studio 2015, 2017, 2019, and 2022 x86 version.

**Comment by Vangelis66** [comment]
... This is yet another **duplicate** of at least **20** other issues (both open+closed): 

https://github.com/ytdl-org/youtube-dl/issues?q=redistributable

The **officially** released `yt-dl` Windows executable is built upon CPython **3.4.4** x86, and it's _that_ version of CPython that is compiled with **VS2010**, thus the dependency on `msvcr100.dll`; the link contained in the `README.md` (referenced [already](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#the-exe-throws-an-error-due-to-missing-msvcr100dll) in this thread) is **still valid**, and pertains to the **last** ever update of the 32-bit 2010 redistributable, "**Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update**": 

https://www.microsoft.com/en-us/download/details.aspx?id=26999 => 

`https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe`

If you only want to run official `youtube-dl.exe` but fail to do so due to that **specific** missing dependency, download and install **only** the above file (v10.0.40219.325) ...
