### ISSUE TITLE
youtube-dl error concerning udemy courses download

### ISSUE THREAD

**Issue by Asbed** [ytdl-org/youtube-dl#30223]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by rohitm95** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.udemy.com/course/nodejs-the-complete-guide/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

> ## Checklist
> * [ ]  I'm reporting a broken site support issue
> * [x]  I've verified that I'm running youtube-dl version **2021.06.06**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [ ]  I've searched the bugtracker for similar bug reports including closed ones
> * [ ]  I've read bugs section in FAQ
> 
> ## Verbose log
> ```
> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.udemy.com/course/nodejs-the-complete-guide/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
> ```
> 
> ## Description
> WRITE DESCRIPTION HERE

**Comment by rohitm95** [comment]
> ## Checklist
> * [ ]  I'm reporting a broken site support issue
> * [x]  I've verified that I'm running youtube-dl version **2021.06.06**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [ ]  I've searched the bugtracker for similar bug reports including closed ones
> * [ ]  I've read bugs section in FAQ
> 
> ## Verbose log
> ```
> [debug] System config: []
>[debug] User config: []
>[debug] Custom config: []
>[debug] Command-line args: ['https://www.udemy.com/course/nodejs-the-complete-guide/', '--verbose']
>[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
>[debug] youtube-dl version 2021.06.06
>[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
>[debug] exe versions: none
>[debug] Proxy map: {}
>[udemy:course] course: Downloading webpage
>ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  >File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  >File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  >File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  >File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  >File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  >File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  >File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
> ```
> 
> ## Description
> WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
See also #29705.
