### ISSUE TITLE
[Better error messages or better notifications] [Addendum: This applies to the situation where youtube-dl faces an ".unknown_video", which also ends up in the created local file, as its trailing suffix part.]

### ISSUE THREAD

**Issue by rubyFeedback** [ytdl-org/youtube-dl#30241]
(I did not fill in the template because the template is not applicable IMO. I'll provide useful information nonetheless in this issue request.)

Today I used youtube-dl on a website; I don't want to give the URL since it is a bit embarassing :D but you can imagine perhaps. But this is not the reason I started the issue specifically.

Instead, I got this:

    youtube-dl some-random-video-on-some-website

[xyz] 12345: Downloading webpage
[xyz] 12345: Downloading m3u8 information
ydl [download] Destination: xyz 

And then:

[download] 100% of 1.39KiB in 00:01

So obviously youtube-dl only downloaded a small part. I don't know if
this is a defence mechanism by the remote website or not. Youtube-dl
does not tell me much about it right now.

Is there perhaps a way to show more information to the end user?

Evidently 1.39KiB when you expected some 100 MB video instead
means that something failed. But from the messages above I 
really don't know what could have failed. What I would thus
suggest is for youtube-dl to provide a bit more information.

IF some error happened then youtube-dl could report this; or if
the real video was not found, perhaps youtube-dl could tell me
too. Right now I don't know what is causing only a 1kb download
rather than the video, so it would be nice if youtube-dl could
inform me about what is going on.

(You may reason that there are smaller files and thus also
other legitimate uses for youtube-dl in this regard. This is
ok, but in my particular case here, my use case was to download
a larger video, e. g. 50MB or 100MB, and this did not work
yet youtube-dl did not tell me about any problem or anything
like that. So I'd like to have better information here.)

**Comment by 89z** [comment]
If you want help with the actual problem, run this command and comment back here with the output:

~~~
echo URL | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by rubyFeedback** [comment]
Hello there 89z,

Unfortunately Go isn't in use on my local system. I am fine just using youtube-dl
as such. IMO it may be better to e. g. just confine youtube-dl to python but that's
not my call to make obviously.

There is one thing I actually forgot to add, which is that the JSON data that is
downloaded ends up with a trailing ".unknown_video" string. So I assume 
youtube-dl can not really identify the video. I am quite certain that these are
mp4 videos though, so probably something in the parsing isn't working
 properly. (To further add: the same website worked fine some months
ago, so I assume that they must have changed something in the last
months. Either way I still think that youtube-dl as such should provide more
information in this case. I modified the title a bit.)

**Comment by 89z** [comment]
You dont need Go, just download the prebuilt version:

https://github.com/FiloSottile/age/releases/tag/v1.0.0

**Comment by dirkf** [comment]
If a known or detectable error had occurred, you would have been told about it. So the likelihood is that the site extractor is silently failing to find the target media correctly, and your new post above seems to confirm this. It has been known for a site to include a comment block in the site HTML that happens to be matched by the yt-dl extractor instead of the real target; or maybe the extractor code is just wrong for your URL, or for the site in general after a site update. To debug this, you need to share the URL, or to become a debugger yourself, for which there is guidance in the Manual.

In the latter case, if you had checked out the 2021-06-06 version and changed directory into the checked-out root (`youtube-dl`), you could insert `import pdb; pdb.set_trace()` at the start of the `_real_extract()` method of the `xyz` extractor and then run `python -m youtube_dl ...` where `...` are the options you gave to the failing `youtube-dl` command; then you could track the extraction script in the Python debugger.

Also: what actually was the small file? A prefix of the target media, a video thumbnail of the target, some unwanted media (a trailer?), a playlist, or a text or HTML file with error-related information?

`unknown_video` is a default value returned by the yt-dl utility function `determine_ext()` that tries to propose the file extension for a given URL.

**Comment by dirkf** [comment]
Probably the manifest listed DRM formats that yt-dl rejected, leaving just some ancillary stream (storyboards, eg) whose type yt-dl did not recognise.
