### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Railkimi** [ytdl-org/youtube-dl#30447]
ERROR: [youtube] 7wHJ3M8_XSE: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.youtube.com'. (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.youtube.com'. (_ssl.c:1131)"))) (caused by URLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.youtube.com'. (_ssl.c:1131)")))

**Comment by dirkf** [comment]
Something is intercepting your web connection so that the host at the other end of your supposedly secure link to YT is not YT, but some firewall/proxy/MITM attacker that does not have a valid cert for YT. That's why we have SSL/TLS. What happens in the browser? What are your proxy settings? And possibly, where are you?

**Comment by kikuyan** [comment]
If you're using **yt-dlp** like #30446, do not make an issue report here. Even if it would be the same troubleshooting.
