### ISSUE TITLE
Questions about the function progress_hooks and ffmpeg merge video

### ISSUE THREAD

**Issue by iferencz** [ytdl-org/youtube-dl#30444]
## Checklist
- [√] I'm asking a question
- [√] I've looked through the README and FAQ for similar questions
- [√] I've searched the bugtracker for similar questions including closed ones

## Question
This is my code, I am downloading a video, and download the file through the hook function `progress_hook` to check the download progress. But I have a question. You can check the download status of the file by judging `progress_hook_info["status"]`, but how to judge whether the downloaded or finished file is a video or audio?
In addition, the video format I specified is `bestvideo+bestaudio/best`, which involves the merging of video and audio. How can I judge the completion of the merging of video and audio? Thank you so much.

code
```
import youtube_dl


def download():
    ydl_opts = {
        "format": "bestvideo+bestaudio/best",
        "merge_output_format": "mp4",  # todo How do I know if the merging of video and audio is complete?
        "ffmpeg_location": "ffmpeg",
        "prefer_ffmpeg": True,
        "outtmpl": "%(id)s.%(ext)s",
        "noplaylist": True,
        "progress_hooks": [progress_hook],
        "quiet": True,
        "cachedir": False,
        # "verbose": True
    }

    ydl = youtube_dl.YoutubeDL(ydl_opts)
    ydl.download(["https://www.youtube.com/watch?v=SrcLs1LXKRQ"])


def progress_hook(progress_hook_info):
    if progress_hook_info["status"] == "downloading":
        video_download_percentage = progress_hook_info["_percent_str"].lstrip().replace("%", "")
        print(" progress " + video_download_percentage)
        # todo How to judge whether the file being downloaded is video or audio?

    elif progress_hook_info["status"] == "finished":
        print(progress_hook_info)
        # todo How to judge whether the downloaded file is video or audio?


if __name__ == '__main__':
    download()
```

output
```
 progress 0.0
 ...
 progress 100.0
{'downloaded_bytes': 34426681, 'total_bytes': 34426681, 'filename': 'SrcLs1LXKRQ.f299.mp4', 'status': 'finished', 'elapsed': 709.4927663803101, '_total_bytes_str': '32.83MiB', '_elapsed_str': '11:49'}
 progress 0.1
 ...
 progress 100.0
{'downloaded_bytes': 913650, 'total_bytes': 913650, 'filename': 'SrcLs1LXKRQ.f251.webm', 'status': 'finished', 'elapsed': 31.162306308746338, '_total_bytes_str': '892.24KiB', '_elapsed_str': '00:31'}
```

**Comment by dirkf** [comment]
No doubt you can identify what sort of download completed by looking at the `filename` in the `dict` passed to the hook, or call `extract_info()` (in a `try:` block) instead of `download()` to have access to the entire returned `info_dict`.

I don't believe that there is any progress monitoring of the postprocessing phase, just as downloading progress wouldn't be monitored with an external downloader. The progress monitoring depends on the monitored action calling the specified progress hooks, which won't happen with an external process (eg, in `downloader/http.py`, `_hook_progress()` is called at key points). So the postprocessing phase is only known to be complete when it returns successfully.

You could probably implement a progress monitoring function for each external command that could be called, by hooking and parsing the output passed back to yt-dl, provided that the command is run with options that cause it to report progress to stdout or stderr. If the command has no progress output, a possible technique is to run a separate thread with a progress monitoring function (eg, checking the length of the output file).

**Comment by iferencz** [comment]
@dirkf Thank you very much, this inspired me to change the source code and manually add hooks.
