### ISSUE TITLE
what does the -l argument do and why is it not in --help

### ISSUE THREAD

**Issue by mohsentux** [ytdl-org/youtube-dl#30502]
I use `youtube-dl` with `aria2c` with `-c -j 16 -x 16 -s 16 -k 1M` and sometimes if I don't use the `-l argument` `aria2c` is unable to download the youtube video.
`-l` is not listed in `--help`. what does it do?

**Comment by dirkf** [comment]
Example, please.

However we can take a guess as to what's happening.

`-l`/`--literal` and `-t`/`--title` are obsolete (hence no help) ways of saying `--output '%(title)s-%(id)s.%(ext)s'` (POSIX quotes: Windows '' -> ""). They are deprecated because this has been the default for ages.

By putting `-l` you are resetting whatever output template was previously specified, and which led to an invalid filename (probably regardless of `--external-downloader aria2c`), to the default, which didn't.
