### ISSUE TITLE
telegram video upload problem

### ISSUE THREAD

**Issue by WhoR3born** [ytdl-org/youtube-dl#30555]
hi,
download working perfect for pornhub but when i try to upload it to telegram, video uploaded as file. Is this about video codec or something else?

**Comment by dirkf** [comment]
So yt-dl provided you with a playable video? This is whatever video the site offered, possibly repackaged in your selected container format.

You seem to have a Telegram problem, which you should take up there.

**Comment by WhoR3born** [comment]
I download video manuel then upload it to telegram. This way is working.

**Comment by WhoR3born** [comment]
You are right btw. This is not problem of yt-dl just i wonder is there any addional settings for fix this issue.

**Comment by dirkf** [comment]
If the problem is that TG won't accept your video file, then yt-dl isn't going to help. Maybe _ffmpeg_ would be more use.

But you would have to provide a lot more details of your problem to be sure, and the answer is still likely to be that you need to sort out your use of TG, of which I personally have almost no knowledge.
