### ISSUE TITLE
Don't download audio, if video already has audio stream in it

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#30553]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

OK, so I'm always using params like this:
 _-f http-764+bestaudio[ext!=webm]/best_ 
or 
_-f http-764,bestaudio[ext!=webm]/best_

It works fine and ffmpeg merges those. 

But sometimes, it's an overkill since in many cases video format already has an audio stream... 
Is there some trick in syntax to check, if selected video format already has audio? and skip bestaudio, if it does.

Or the only way to do this is to edit some .py file?
@dirkf  Sorry to bother you with this, but you seem to be the most active member here. Maybe you can advise?

**Comment by dirkf** [comment]
In a format selection:
* `/` separates alternative format selections in priority order;
* `+` separates a video and an audio format that should be merged;
* `,` separates format selections, both of which should be downloaded.

So if you say `x+bestaudio/best` you should get format x and what yt-dl considers the best audio-only format, or if there aren't any, the best combined format, if any.

With `http-764+bestaudio[ext!=webm]/best`, yt-dl will pick `http-764` and the best audio-only format and merge them if there is a matching format of each type, or otherwise the best combined format. If `http-764` is actually a combined format, I expect that you will get its video stream merged with the best audio stream; you could try `http-764[acodec!=none]/http-764+bestaudio[ext!=webm]/best` to avoid merging, not that I've tried this.

With `http-764,bestaudio[ext!=webm]/best`, you should get at most two downloads, one being the `http-764` stream if present and one being either the best audio-only stream if there are any, or the best combined format. I guess this isn't what you want.

**Comment by someziggyman** [comment]
You're very kind! thanks for the explanations. 
Your suggestion for http-764[acodec!=none] works!

Test case:
youtube-dl -f "http-2176[acodec!=none]/http-2176+bestaudio[ext!=webm]/best" --ffmpeg-location ./myffmpegLocation https://twitter.com/BobbyMarks42/status/1485702058292518915

Is there like and OR operator in this syntax? my goal is to make it work like this:
if http-2176[acodec!=none] exists then download just this format. 
if it does not, then download http-2176 and bestaudio separately. 

Need it for some of my use cases. thought using ( ) this will do the trick, but youtube-dl attempts to download two video formats:
http-2176[acodec!=none]/(http-2176,bestaudio[ext!=webm]/best)

I must have overcomplicated things, but hope the logic is clear.

**Comment by dirkf** [comment]
`,` means unmerged downloads.

Use `+` as described before to merge, and append `/bestvideo+bestaudio` to cover any case where the page only offers separate downloads that don't match your preferred `http-2176+bestaudio[ext!=webm]` (or put it before `/best`, as you like).

**Comment by dirkf** [comment]
I hope that's all clear now. Reopen if not.
