### ISSUE TITLE
[Hotstar] Firefox Wont play in M3u8

### ISSUE THREAD

**Issue by kishan167** [ytdl-org/youtube-dl#30589]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi there

few weeks i use to get M3u8 Url to download by changing User agent but now i tired with Firefox 96.0.3 (64-bit) i cant get M3u8 anymore only getting MPD URL, i tired different user agent also. how can i get Stream to play in M3u8?

 Link to the Stream
https://www.hotstar.com/in/tv/bigg-boss-ultimate/1260080018/day-2-in-the-house/1260081457

you need Proxy to bypass Geo-Restriction

**Comment by 89z** [comment]
Please provide a proxy.

**Comment by dirkf** [comment]
It looks as if you meant to raise a [broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) for Hotstar. Please provide the information requested in that template: in particular, a verbose log showing what happens when you issue your yt-dl command, perhaps with/without a specific user agent.

Also you could try an iOS UA, [like this](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-1026177294).
