### ISSUE TITLE
youtube-dl doesnt respect index parameter in the URL

### ISSUE THREAD

**Issue by darvin** [ytdl-org/youtube-dl#30611]
```
youtube-dl https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=1
youtube-dl https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=54
youtube-dl https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=33
```

all result in the same file being downloaded

**Comment by darvin** [comment]
but curiously enough 

```
youtube-dl https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA
```

results in different file being downloaded

**Comment by dirkf** [comment]
All the URLs that are quoted above result in yt-dl retrieving the playlist, unless playlist options are used. For example:
```
$ youtube-dl --get-id 'https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=33'
cy4CJ4F-epA
rR8Six9qpcA
pcYrTCGKyrU
gBMkbAM1qiA
...
```
You might see a different first video being retrieved depending on which playlist items were previously downloaded.

Also, although the `index=...` URL parameter is clearly known to the site (it doesn't get stripped, and the site may change it), different `index` values didn't seem to make any difference to the display in the browser.

Apparently `index` is correctly being ignored by the extractor, but I am no YT expert since I generally use this program, or perhaps Invidious, to access YT content owing to the unusable bloat (etc) of the site itself.

**Comment by dirkf** [comment]
yt-dl is behaving as expected: the `index` URL parameter is not (or no longer) significant; playlist options have to be used to force selection of the focussed item or any specific item or subset of items.
