### ISSUE TITLE
Parallel downloading

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [ytdl-org/youtube-dl#30638]
Another program, jdownloader, enables parallel downloading, not just of separate files but also of the same file. That increases speed sometimes by up to 40 times.
I want parallel downloading in youtube-dl aswell.

**Comment by Lee-Carre** [comment]
#duplicate

See [Parallel youtube-dl](/ytdl-org/youtube-dl/projects/1).

You could always run multiple instances of youtube-dl.

**Comment by ErfolgreichCharismatisch** [comment]
Your link does not work.
I could run multiple instances for separate files but not for the same, right?

**Comment by Lee-Carre** [comment]
Correct. Though, see also #6319.

**Comment by dirkf** [comment]
Use yt-dlp, or use _aria2c_ as an external downloader.

Also, consider whether you actually need the increased download speed since you may be denying bandwidth to other site users and provoking sites to implement more stringent barriers; therefore causing more work for maintainers of programs like this, or even rendering them impractical to maintain.

**Comment by Lee-Carre** [comment]
> consider whether you actually need the increased download [rate]

I've often thought this. But, then, I cut my teeth on dial-up (and a heavily saturated (read: unusable at lunch) T1 line at school).

Media can only be watched at a limited rate. So, what's really gained by downloading 10+ times greater than the playback rate (other than seeing big numbers)?

Smarter strategy helps a lot. Avoid putting yourself in a position where you're having to wait for youtube-dl.
* download the next video while watching the previous
* download during off-peak hours (overnight); then it can take much longer at a lower rate (because you're asleep); this is an example of being a good network citizen
* if wanting to watch a series (especially a playlist), then set `--limit-rate` to something sensible which is maybe 20% above the playback bitrate; start watching the first video while the others download. The next will be ready by the time you've finished the first
* use scripting to automate (e.g. loop-on-failure) fetching, if failure-avoidance is why you're supervising fetches. Use the system scheduler (`cron`) to trigger the script to start youtube-dl at off-peak hours, so your files await you come the morning
* install more storage capacity, to have a larger cache of local videos
* use separate hosts for fetching versus watching; this would avoid playback performance issues (e.g. when ffmpeg is running)

More broadly;
* I'd rather have 1 video which is 100% fetched, rather than 10 which are each 10%. At least I can watch one whole video, then.
* often, I want videos downloaded in a particular order
* sequential processing is simpler & more robust
* work on something else, while media are being fetched; multi-tasking
* don't download high-resolution formats unless you really need them; often 240p & the lowest bitrate audio is just fine for most cases. Sure, music & game play-throughs are different, but you don't need 9720p & lossless audio for a video of someone speaking to camera. When there's less data to download, it'll finish quicker, without needing ridiculous capacity.
* prefer hosting (‘platforms’) which use WebTorrents or other distributed systems

Being savvy about it can save you money; you don't need such a high tariff with your ISP. I got by just fine on 2Mbps (and was watching 720p, for some things).

> you may be denying bandwidth to other site users and provoking sites to implement more stringent barriers

I've also had that suspicion.

Besides network capacity, the likes of latency & jitter will also (likely) be affected (until anti-bufferbloat AQM is ubiquitous), which risks disrupting those watching streams.

Data-centre grade connectivity isn't cheap (compared to domestic).

**Comment by dirkf** [comment]
>aria2c turns out to download with 16 parallel threads alledgedly but only accomplish 150 KB/s instead of 6 MB/s.

If the site is YT and you aren't using the fixed, as yet unreleased, YT extractor (or yt-dlp), _aria2c_ will get the throttled media URLs. Probably the resources of Google are up to the job of throttling all instances of the same download URL going to the same IP address as one, rather than individually.
