### ISSUE TITLE
ignore keywords when download channel

### ISSUE THREAD

**Issue by afterdelight** [ytdl-org/youtube-dl#30648]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Is it possible to ignore videos with certain keywords such as 'cat' and 'dog' in title when downlaoding youtube channel?

**Comment by dirkf** [comment]
See the description of `--reject-title` and `--match-title` in the [Fine Manual](https://github.com/ytdl-org/youtube-dl#user-content-video-selection).

Reading the 'Video Selection' section of the manual is likely to be good idea if you have a question about video selection.

For your example, you'll probably need to use a regular expression as the parameter of the option. If you now feel that you [have two problems](https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/), refer to the [Python documentation](https://docs.python.org/2/library/re.html). You might want something like `--reject-title '(cat|dog)s?'`, ie skip any video with title containing either 'cat' or 'dog', or either of those followed by 's'  (in a Windows _cmd_ session, use "double-quotes" around the parameter instead of '' in the example).

**Comment by afterdelight** [comment]
Thanks! That part must be skipped by my eyes lol. Can the reject word list loaded from .txt file tho?

**Comment by dirkf** [comment]
I don't believe so. Bear in mind that it's not a list, just a pattern. If you have a list of words (bad1, bad2, bad3, ...) you need to make an alternative pattern `bad1|bad2|bad3|...` from them. Also bear in mind that I've never use these options myself, so my advice is based on the manual and the source code.

One solution could be to copy your default configuration file (if any) and add the required `--reject-title ...`  option to the new configuration file. Then use `--config-location new_config_file` as a command-line option instead of `--reject-title`. Using external utilities you could automate the conversion of a reject word list to a pattern and inserting that as the value of the `--reject_title` option in a prepared configuration file template.

If you are running yt-dl, you probably have a Python installation (some people use a Windows version with its own dedicated Python) which would give you one way of doing this. In UNIX-like systems with a POSIX shell, you could use the shell and utilities; in fact you could even just make the pattern on the command-line like this: `--reject-title "$(printf '%s|' $(cat reject_word_list.txt) | head -c -1)"`. Windows PowerShell also has the necessary capabilities (somewhere). For Windows _cmd_, you can study [here](https://ss64.com/nt/syntax.html).

**Comment by Lee-Carre** [comment]
> Can the reject word list loaded from .txt file tho?

Aside from Dirk's fine suggestion of using a command-line tool-chain, you could
1. enumerate the channel's videos into a file (in a format suitable for using as input for `--batch-file`; the `jq` tool may be helpful to augment youtube-dl's own output)
2. perform whatever processing on said file (e.g. to exclude matches, comment them out (add a `#` at the start of the line) — this part, using the right tools, could be done using a list of patterns
3. run youtube-dl with it pointed to (via `--batch-file` mentioned earlier) your filtered file of entries

This approach has the advantage of caching the list of videos, so that rerunning, with different filtering, is easy & quick. No need for youtube-dl to refetch the list each time.

**Comment by dirkf** [comment]
https://stedolan.github.io/jq/
