### ISSUE TITLE
Just tried this again today, it remains unsupported.

### ISSUE THREAD

**Issue by luctrudel** [ytdl-org/youtube-dl#30668]
Just tried to download https://cpac.ca/episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6 but it gives me

 youtube-dl https://cpac.ca/episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6
[generic] episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6: Downloading webpage
[generic] episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6: Extracting information
ERROR: Unsupported URL: https://cpac.ca/episode?id=bc48d49a-b1ed-4817-afd5-6757a9f23cb6

Just tried this again today, it remains unsupported.

_Originally posted by @MagicFab in https://github.com/ytdl-org/youtube-dl/issues/18148#issuecomment-620870213_

**Comment by dirkf** [comment]
Apparently the author of the 2018 PR wasn't interested in responding to the maintainer's review.

Probably the site is using a completely different structure and URL format now. The generic extractor can't be used because the media links are not in the non-JS page seen by yt-dl and similarly the ld+json tactic from PR #18265 is no use.

Single video:
https://www.cpac.ca/episode?id=fc7edcae-4660-47e1-ba61-5b7f29a9db0f

Search page:
https://www.cpac.ca/search?programId=51

Playlist page??

For the episode page, one can extract the GUID from the URL as `episode_id`. Then fetch f'https://www.cpac.ca/api/1/services/contentModel.json?url=/site/website/episode/index.xml&crafterSite=cpacca&id={episode_id}'. In the returned JSON, the `.page` object contains useful metadata and `.page.details` contains media links.
