### ISSUE TITLE
DRM Widevine L3 decryption key parameters can be placed into youtube-dl ?

### ISSUE THREAD

**Issue by rajhlinux** [ytdl-org/youtube-dl#30770]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I have decryption keys for Udemy website, I would like to know if I can download Udemy content using the decryption keys I have.

I have paid subscription videos which I would like to download that is DRM protected.

Udemy.com utilizes, L3 Widevine DRM protocol. Wondering if it is possible to download Udemy videos using this open source git.

If so, how do I place the syntax parameters?

Thank You.

**Comment by maherz1229** [comment]
Are you crazy? What you are asking for is illegal even if you have the decryption keys. 
You know that this is PUBLIC. Do you think they will support it specially it's DRM related?

**Comment by dirkf** [comment]
yt-dl can't help with this.

If you would like to download encrypted media, say to test your hard disk, [yt-dlp](https://github.com/yt-dlp/yt-dlp) has the `--allow-unplayable-formats` option that enables that, if the yt-dlp Udemy extractor supports it.

**Comment by 89z** [comment]
I feel like this conversation was shut down prematurely.

Yes, I can understand YouTube-DL doesnt want to engage in piracy, or openly break US law. I don't think anyone here is suggesting we do that. Tools are currently available [1] that allow people to decrypt Widevine and similar encryption methods, assuming people have the keys.

This is perfectly legal. You could create a video today using your phone, then encrypt it yourself using Widevine. then you could decrypt the same video, using your own keys that you created. None of this is against the law. This is similar to file sharing, in that its not against any law to file share something you created or own. If people choose to use a tool to break the law, that's their choice. But we should not shut down a conversation, because the possibility exists that someone could misuse a tool.

Similar to how YouTube-DL calls FFmpeg, YouTube-DL could call `mp4decrypt`, or even implement its own decryption, if user supplies the keys. Personally, I'm not sure how you can say using FFmpeg with encrypted HLS is OK (which YouTube-DL currently does), but any conversation about other encryption methods is shut down. Encryption is not going away, so while I am not arguing for openly breaking the law, I think we should be discussing handling encryption more, as its not unreasonable to think of a future where most sites (including YouTube) are using it.


1. https://bento4.com/documentation/mp4decrypt

**Comment by dirkf** [comment]
It can be argued that
* material offered for you to view or hear is yours to remember;
* those who lack eidetic memory should not be prevented from using technical means to aid their memory
* so-called effective technical mechanisms that claim to protect content are a legal fiction, or the content could never be accessed.

yt-dl avoids such controversy generally by reproducing what is presented to a browser. Although it might be possible to connect yt-dl to the browser's (eg) WideVine EME, that looks like a research project.

Meanwhile yt-dl and yt-dlp have completely functional mechanisms (more extensive in the latter case) for post-processing the downloaded media, or just piping the output to a further processing stage. For the moment that is where the user should cast any magic spell to make the download usable; some people may wish to make an archive of unplayable content in case it may become playable in future. So I would be open to back-porting `--allow-unplayable-formats` and modifying relevant extractors to avoid skipping DRM formats under that option.
