### ISSUE TITLE
[Youtube] Unable to recognize tab page

### ISSUE THREAD

**Issue by highdesertnm** [ytdl-org/youtube-dl#30813]
```
youtube-dl --verbose https://www.youtube.com/shorts/yWaA6Z-Lohc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/shorts/yWaA6Z-Lohc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.15-76051515-generic-x86_64-with-Pop-20.04-focal
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

baj@pop-os:~/Videos$ 
```

**Comment by 89z** [comment]
Release:

~~~
PS D:\Desktop> pip install youtube-dl
PS D:\Desktop> youtube-dl.exe yWaA6Z-Lohc
[youtube] yWaA6Z-Lohc: Downloading webpage
[download] Destination: Scare prank on dad in dark hallway-yWaA6Z-Lohc.f136.mp4
[download]  13.0% of 973.28KiB at 78.86KiB/s ETA 00:10
~~~

or master:

~~~
PS D:\Desktop> pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
PS D:\Desktop> youtube-dl.exe https://www.youtube.com/shorts/yWaA6Z-Lohc
[youtube] yWaA6Z-Lohc: Downloading webpage
[download] Destination: Scare prank on dad in dark hallway-yWaA6Z-Lohc.f136.mp4
[download] 100% of 973.28KiB in 00:00
~~~

**Comment by dirkf** [comment]
```ShellSession
$ python -m youtube_dl -v -F 'https://www.youtube.com/shorts/yWaA6Z-Lohc'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/shorts/yWaA6Z-Lohc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 12ca5f6a4
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] yWaA6Z-Lohc: Downloading webpage
[debug] [youtube] Decrypted nsig _AN_H9S6XFk0uxv4l => SnI5wyl5HvBwlw
[debug] [youtube] Decrypted nsig wH7Gs8GnmRHLk8nyN => 49Kav_LBVGYa2w
[info] Available formats for yWaA6Z-Lohc:
format code  extension  resolution note
249          webm       audio only tiny   43k , webm_dash container, opus @ 43k (48000Hz), 295.16KiB
250          webm       audio only tiny   45k , webm_dash container, opus @ 45k (48000Hz), 309.72KiB
251          webm       audio only tiny   83k , webm_dash container, opus @ 83k (48000Hz), 569.37KiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 884.02KiB
160          mp4        82x144     144p   17k , mp4_dash container, avc1.4d400b@  17k, 30fps, video only, 118.26KiB
278          webm       82x144     144p   18k , webm_dash container, vp9@  18k, 30fps, video only, 124.78KiB
242          webm       136x240    144p   24k , webm_dash container, vp9@  24k, 30fps, video only, 164.61KiB
133          mp4        136x240    144p   32k , mp4_dash container, avc1.4d400c@  32k, 30fps, video only, 218.78KiB
243          webm       202x360    240p   34k , webm_dash container, vp9@  34k, 30fps, video only, 236.03KiB
244          webm       270x480    240p   48k , webm_dash container, vp9@  48k, 30fps, video only, 328.21KiB
134          mp4        202x360    240p   52k , mp4_dash container, avc1.4d400d@  52k, 30fps, video only, 360.28KiB
135          mp4        270x480    240p   80k , mp4_dash container, avc1.4d4015@  80k, 30fps, video only, 548.53KiB
247          webm       406x720    360p   76k , webm_dash container, vp9@  76k, 30fps, video only, 520.46KiB
136          mp4        406x720    360p  142k , mp4_dash container, avc1.64001e@ 142k, 30fps, video only, 973.28KiB
18           mp4        270x480    240p  397k , avc1.42001E, 30fps, mp4a.40.2 (48000Hz), 2.65MiB
22           mp4        406x720    360p  453k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$
```

To explain the results above:
* in the 'Release' example [above](https://github.com/ytdl-org/youtube-dl/issues/30813#issuecomment-1086899750), the video ID was manually extracted from the URL, but the download speed was throttled.
* the git master, as above and [here](https://github.com/ytdl-org/youtube-dl/issues/30813#issuecomment-1086899750), includes a fix to support `/shorts/` YT URLs and  a fix to make downloads run at full speed.

All of this would have been apparent by [searching the tracker](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+tab+page).

**Comment by 89z** [comment]
@dirkf sorry for the following off topic comment, but I figure you might be interested. I think you have wondered why I delete some comments, the answer is because some people on this forum are shitheads:

https://github.com/ytdl-org/youtube-dl/issues/30737#issuecomment-1072956095

so whenever I make a comment, if its a normal technical argument, then I usually leave it. But if its any comment that might be disagreeable, then I usually remove it. When I was younger, people were able to have disagreements, as people don't always see eye to eye. However in this day, some people use any disagreement as an opportunity to dig through a persons entire online history. 

In my mind, this is childish and completely unacceptable behavior. If someone was found to be pulling information from third party websites, for the purpose of doxxing or shaming someone, I would instantly ban them. That is toxic behavior. I am not afraid to disagree with people. Sometimes I do get heated, but I like to think I usually start from a technical point of view, while the person I linked to, has a habit of generally posting off topic shitty comments. You can take whatever action you want (or no action), but I wanted to give some light on my point of view.

**Comment by dirkf** [comment]
Generally, I adhere to maxims like ["Publish and be damned"](https://www.eyemagazine.com/feature/article/publish-and-be-damned), ["Tell the truth and shame the devil"](https://idiomorigins.org/origin/tell-the-truth-and-shame-the-devil). In the end, trolls and fools abound, as well as apparently intelligent people who are just wrong, and it isn't worth getting worked up over. Also, the software world is not short of people with the [social skills of a thermonuclear device](https://devblogs.microsoft.com/oldnewthing/tag/the-social-skills-of-a-thermonuclear-device) and one should develop a thick skin.

When trying to convey a particularly disputatious point, I would try to phrase the comment in some way that I would be happy to let stand. I recommend this especially since deleted GH comments **are** recoverable and people who might have appreciated your deleted comment will just be confused when another commenter innocently refers to it.
