### ISSUE TITLE
 youtube-dl.exe only opens a comand promt for a second

### ISSUE THREAD

**Issue by Hotlynx16** [ytdl-org/youtube-dl#30871]
## Checklist

- [ x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE Sorry I am a nube at this but when I double click on  youtube-dl.exe it opens up a command prompt for just a second and then goes away. Running windows 10 latest version. Tried as an administrator,no go. What could I be doing wrong? I installed the [Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package (x86) also, no help. I tried running it in compatability mode and ran it as windows 8 and no change.

**Comment by Xtendera** [comment]
You need to pass in the video URL as an argument.
EG:
youtube-dl.exe "https://www.youtube.com/watch?v=aqz-KE-bpKQ"

**Comment by dirkf** [comment]
Open a terminal, aka command prompt, window. Then run the command from the prompt. Don't just double-click on the yt-dl program icon like Notepad.

https://ss64.com/nt/syntax-cmd.html

**Comment by Hotlynx16** [comment]
Thanks for the replies, already tried in a command prompt, see attached pic.
![ACMD](https://user-images.githubusercontent.com/103961298/163885270-f7cb564e-22a4-45af-afb6-587d8003e1ea.PNG)

**Comment by bolshoytoster** [comment]
@Hotlynx16 that's because you're in the wrong folder, you should either `cd` to where your `youtube-dl.exe` is or add it's location to your PATH.

It would help if you didn't run the command prompt as admin because then it would start you in your home folder, which is probably closer to where the `youtube-dl.exe` is.

**Comment by Hotlynx16** [comment]
Ok, I did have it in my download folder and tried moving it to my C: drive not in a folder, how about in my user folder??

**Comment by bolshoytoster** [comment]
@Hotlynx16 if you open a non-admin command prompt then move the `youtube-dl.exe` to your user folder you should be able to execute it.

**Comment by Hotlynx16** [comment]
Thanks, It seems to be working now!!

**Comment by Hotlynx16** [comment]
Well I don't know now, it is taking 8 hrs to download a 1.6 gb file, is that normal? I have 200Mbps download!

**Comment by dirkf** [comment]
It is expected, unless you install the latest development version (git master). YT throttles the download speed unless we respond to a challenge in the media link parameters.

Short solution:
* uninstall the yt-dl that you have
* install [Python](https://www.python.org/downloads/windows/)
* [run](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) `python -m pip install "https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip"`
* you may then be able to run a `youtube-dl` command or if not use `python -m youtube_dl` instead.

Instead of `python`, you may need to say `python3`.

**Comment by Lee-Carre** [comment]
@Hotlynx16

Since much of this isn't about `youtube-dl` per se, but using a CLI shell in general, then might I recommend reading [Introduction to the Command Line](//archive.flossmanuals.net/command-line/), which will explain a whole lot of context for you (along with usage suggestions, and recipes).

When used skillfully, a CLI is much more powerful than a GUI (scripting & automation for the win).

---

Separately (meta, @ contributors); perhaps a pointer to such a guide needs to be included in the readme, since this seems to be a common stumbling block for unfamiliar newbies (I recall several duplicate tickets).

I've been thinking of overhauling the documentation (e.g. separating the manual from the readme (while leaving a pointer, of course), so I may submit a PR when I have the time to tackle it properly.

**Comment by bolshoytoster** [comment]
@Lee-Carre I could probably make a basic GUI for less experienced users using something like tkinter.

**Comment by garoto** [comment]
Plenty of youtube-dl GUIs around already.

**Comment by dirkf** [comment]
OP's problem was solved.
