### ISSUE TITLE
allow dashes in date and more

### ISSUE THREAD

**Issue by Aphexus** [ytdl-org/youtube-dl#30882]
yt-dlp allows one to modify the upload date using %(upload_date>%Y-%m-%d)s 
but youtube-dl only allows %(upload_date)s 

e.g., 2022-01-01 vs 20220101

I use these interchangeably because sometimes yt-dlp doesn't properly convert some files so I have to use youtube-dl. I use it in automation so having the date format mismatch is unpleasant.  yt-dlp allows for more configuration along these longs across the board. Maybe could copy and paste the code from it?

**Comment by dirkf** [comment]
But if you stuck to `%(upload_date)s` it would work for both ...

**Comment by Aphexus** [comment]
> But if you stuck to `%(upload_date)s` it would work for both ...

But if the code was updated to be more congruent to reality it would work for both too.

**Comment by 89z** [comment]
I don't really care for OPs tone, but it seems they are right. According to RFC 3339 [1], the dashes are required:

~~~
2006-01-02T15:04:05Z07:00
~~~

1. https://datatracker.ietf.org/doc/html/rfc3339

**Comment by pukkandan** [comment]
> According to RFC 3339 [1], the dashes are required:

youtube-dl has never claimed `upload_date` to be RFC 3339 compliant. What it does claim is that it will be in `YYYYMMDD` format. It would be a compatibility nightmare to change this.

It would technically be possible to create a new field for this, but then the same has to be done for `release_date`, and maybe even `timestamp`/`release_timestamp`. This is not to even mention the problem that people will keep asking for other formats

**Comment by 89z** [comment]
> youtube-dl has never claimed `upload_date` to be RFC 3339 compliant. What it does claim is that it will be in `YYYYMMDD` format. It would be a compatibility nightmare to change this.

Instead of choosing a standardized format, YouTube-DL choose some random format. The format has some good properties, in that its less bytes, and still sortable. Regardless OP has a case here. RFC 3339 should be, if not the default format, one of the possible formats.

> It would technically be possible to create a new field for this, but then the same has to be done for `release_date`, and maybe even `timestamp`/`release_timestamp`.

Nothing "has to be done", ever. Thing only need to be done when people decide they are important to do. For OP, the only thing they care about is `upload_date`. The YouTube-DL maintainer, can make their own decision as to how far down the rabbit hole they want to go.

> This is not to even mention the problem that people will keep asking for other formats

Straw man. We are not talking about some random format (which ironically is whats being used now). We are talking about a format that has existed since the 1980s, arguably the most common date format in existence.

**Comment by dirkf** [comment]
The reason for the existing format is doubtless that YT sends the value like that. yt-dl carried it over to all supported sites.

If a change were to be made it would be in the direction originally suggested by OP, and not by changing the structure to `'-'.join([x[:4], x[4:6], x[6:]])`, because of the "compatibility nightmare". But not in the immediate, or even foreseeable, future.

An `upload_date_with_dashes` metadata item, while simple to implement, wouldn't solve OP's problem (and would also be a bad idea).

**Comment by Aphexus** [comment]
> I don't really care for OPs tone, but it seems they are right. According to RFC 3339 [1], the dashes are required:
> 

My tone? You haven't seen nothing yet! There is nothing in my tone in my OP. But it's ok for someone to reply to me and tell me I should just suck it up and deal with the inadequacy just cause and I by me replying and saying no I have tone? Go fuck off asshole.... how do you like that tone? Oh sure, you'll be protected for the sociopath you are but that's ok. [Yes, you are a sociopath. You chose to attack me with "I don't like your tone" BS knowing that is offensive because it is antagonizing. You could have just ignored it if you thought it was offensive rather than being antagonistic. The only difference is I make it explicit and put you in your place and know I will be punished for it because I'll be damned if I let you lunatics get away with your BS... of course you will but at least it wasn't a walk in the park]

**Comment by Aphexus** [comment]
> The reason for the existing format is doubtless that YT sends the value like that. yt-dl carried it over to all supported sites.
> 
> If a change were to be made it would be in the direction originally suggested by OP, and not by changing the structure to `'-'.join([x[:4], x[4:6], x[6:]])`, because of the "compatibility nightmare". But not in the immediate, or even foreseeable, future.
> 
> An `upload_date_with_dashes` metadata item, while simple to implement, wouldn't solve OP's problem (and would also be a bad idea).

No one is asking for the format to be forced upon people. The entire point is that yt-dl lets one configure the output. There is no way to configure it with youtube-dl. Why force people to choose one or the other? Why not give them the option? It's a few lines of code and surely there will be more than one person that will find it useful. It's moronic(yes, it is... at the very least it is authoritative) to claim that "YOU HAVE TO DO IT MY WAY" when everyone can be made happy and the best of both worlds can be achieved with only a few lines of code. It's not like one has to spend 3 years writing a million lines of code to allow make it happen and I'm not asking for it to override current behavior.

**Comment by 89z** [comment]
@Aphexus

> Go fuck off asshole.... how do you like that tone? Oh sure, you'll be protected for the sociopath you are but that's ok.

Hoo boy. I was the one person defending you in this thread. While I agreed with your underlying proposal, you presented in a rude fashion. This isn't a deal-breaker per se, but since you aren't a maintainer, its probably a good idea to be nice to the people that you want to change something.

However its become very clear that you aren't interested to do that. Good luck to you.
