### ISSUE TITLE
How to auto resume after error?

### ISSUE THREAD

**Issue by mataski** [ytdl-org/youtube-dl#31027]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How to auto resume after an error like `ERROR: unable to download video data: Remote end closed connection without response`

Auto resume/retry until it's finished at 100%?

```
[download]  27.7% of ~2.14GiB at  1.09MiB/s ETA 21:36 (frag 969/3507)[download] Got server HTTP error: Downloaded 572509 bytes, expected 674168 bytes. Retrying (attempt 1 of 10) ...

[download]  43.1% of ~2.13GiB at  1.16MiB/s ETA 16:53 (frag 1510/3507)ERROR: unable to download video data: Remote end closed connection without response
```

![image](https://user-images.githubusercontent.com/62036912/173547810-aff9b045-0091-451c-a7ba-2600a9619cb9.png)

Other error that stops download and doesn't resume

`ERROR: unable to download video data: <urlopen error [Errno 0] Error>`

Real life situation, leave file download over night and find it aborted and incomplete.

Current solution: Resuming it manually works. Over and over until it's finished at 100%.

**Comment by dirkf** [comment]
You seem to have a bad network environment, perhaps some censorship firewall?

You could use a command script that runs yt-dl to download the target until it succeeds, with some delay between attempts. How you do that will depend on your system.

**Comment by mataski** [comment]
What command indicates that target succeeded at 100%? (Windows batch)

**Comment by rautamiekka** [comment]
Since by its very design ytdl (and by extension, ytdlp) doesn't return process codes (and changing to that is a massive rewrite), I can think of just 2 abstract ways:

1) A parent script (Bash, PowerShell, not Command Prompt/Batch) runs ytdl, receives its verbose output, looks for specific substrings indicating errors, sends a termination signal, and relaunches ytdl.

1) _(Admittedly I dunno much about this one, so it might not work this way)_ A parent Python script uses ytdl as a module, receives its thrown errors, terminates ytdl, and relaunches ytdl.

**Comment by mataski** [comment]
This `IF %ERRORLEVEL% NEQ 0` seem to work. Thank you.
