### ISSUE TITLE
youtube-dl cant find python if only python3 on system

### ISSUE THREAD

**Issue by SaeedBaig** [ytdl-org/youtube-dl#31107]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v https://youtu.be/dAywaOWz8Tc
/usr/bin/env: ‘python’: No such file or directory
$ which python3
/usr/bin/python3
$ which python
$ # no output
```

Some other system info if relevant (since `-v` doesn't work in this case):
- OS: Kubuntu 22.04 LTS
- Python version: Python 3.10.4 (default)

## Description

`youtube-dl` can't seem to find Python on systems that only have python3 by default, like Ubuntu 22.04 (i.e. only a defined 'python3', no 'python' alias). When you try to use it, it simply says `/usr/bin/env: ‘python’: No such file or directory` (details in verbose log output above).

I used [the workaround](https://askubuntu.com/a/1242145/902655) of simply passing youtube-dl to python3 (`python3 $(which youtube-dl) <URL>`), and all youtube-dl functions work fine then. But this is an ugly workaround and I hope there's a more elegant solution.

Idk what that solution is... I don't want to `alias python='python3'` in case I need to install python2 in the future and the alias breaks stuff. But I also don't want to install python2 just for youtube-dl since it works fine using python3; it just can't find it by default (the readme says youtube-dl requires _"Python interpreter, version 2.6, 2.7, or 3.2+"_; so users shouldn't have to install a Python2 if they already have a Python3.2+).

I imagine the best solution would be for youtube-dl to check if `python3` exists if `python` can't be found.

**Comment by dirkf** [comment]
What the instructions didn't expect was that nutjobs would build systems with Python 3, no Python 2 and `python` not aliased to `python3`.

If this problem is with the `youtube-dl` package from Kubuntu 22.04, raise the issue there.

Otherwise, in Debian/Ubuntu (etc), [install package (that ought to have been included in the original installation) _python-is-python3_](https://github.com/ytdl-org/youtube-dl/issues/27219#issuecomment-808536161). Should you want to install Python 2 at any point, you could tweak the shebangs of whatever code you want to run under it, or change the `PATH` under which you run it, or uninstall _python-is-python3_.

Or [installing using `python3 -m pip`](https://github.com/ytdl-org/youtube-dl/issues/30995#issuecomment-1145013361) should also work, and give you an improved version as well: let us know.

**Comment by SaeedBaig** [comment]
I decided to `alias youtube-dl="python3 $(which youtube-dl) "` in my .bash_aliases, which is an elegant-enough solution for me.
(the youtube-dl I downloaded was via the manual curl-chmod method, not via apt or pip (I'd rather avoid snaps, and I'd rather not deal with pip)).

But anyways, I'm just glad to see from your linked issue that this bug is known about. I'll leave the issue open if anyone has anything to add, but my problem's basically solved - you can close it if you like.

**Comment by rautamiekka** [comment]
No, not a bug, it's on purpose.

**Comment by dirkf** [comment]
As the problem exists it needs to be acknowledged in the documentation, but before committing the changes it would be good to know if, eg, installing with `python3 -m pip` solves the problem.

Also the distro packages should fix their packaging, if necessary, which I'll raise when the next release is imminent.

**Comment by capeguy63** [comment]
Anyone knows how to fix this for Windows? Thanks!

**Comment by rautamiekka** [comment]
> Anyone knows how to fix this for Windows? Thanks!

What's there to fix ?

**Comment by capeguy63** [comment]
youtube-dl cannot find python in my system. It is looking for python3 instead of just python. Is there a way to fix this in Windows? Or is it a separate issue?

**Comment by rautamiekka** [comment]
On Window$ it doesn't work like that, so you need to show proof.

**Comment by dirkf** [comment]
Rather, open a [new bug report](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=4_bug_report.md&title=) and complete the template.

**Comment by dzodzo666** [comment]
cd /usr/bin
ln -s python3 python

i wonder why would anyone ever again need to use python2 except for some testing and development

**Comment by wesley7891** [comment]
That's it, Thank you

**Comment by Rudxain** [comment]
I had this issue since I uninstalled Py2. Turns out the symlink was pointing to Py2 all along, and it (the symlink) somehow got removed from my system (I don't remember if it was `apt` or `rm` that removed the residual files), leaving only Py3 without an alias pointing to it. I used this as a solution
```sh
cd /usr/bin
ln -s python3 python
```

But IDK if it's "safe". I've read that `python` is expected to be V2 by most programs. Will this cause any problems in the future?

**Comment by dzodzo666** [comment]
Greetings, if you're unsure you might break something, you can use designed commands that do very much the same but in officially recommended manner but if something expects python2 it better be converted to python3 anytime soon

for Debian and clones: https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
for RHEL and clones: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_configuring-the-unversioned-python_configuring-basic-system-settings

**Comment by dirkf** [comment]
yt-dl is a program that can run on Python 2 or Python 3 interchangeably, without the use of dependencies like _six_ or _2to3_. The guidance in these links is not entirely helpful for yt-dl.

yt-dl in Unix-like environments relies on a `#!/usr/bin/env python` line, which finds the first `python` executable in the `PATH`. Since Python 3.5+ may work better, we want yt-dl to run under those if available, but whatever configuration is used should not cause other Python2-specific programs, which don't dynamically adapt to the version in use, to do so.

One solution that works is bundling a Python version in the yt-dl download. This is the typical type of yt-dl installation for Windows. However this approach requires a Python version that runs on all OS versions that yt-dl users are running and the bundling package to be supported and able to target those versions: neither of these is straightforward.

Another is installing with `-m pip` using your preferred Python (that supports _pip_, problematic in some legacy versions whose SSL setup doesn't match PyPi's CD's requirements). But then platforms with no Python installed by default pose a hurdle for less technical yt-dl users.

**Comment by rautamiekka** [comment]
I don't see how bundling an universal Python (even if only considering x86) would be possible, much less without adding another 100% to the size for Py for every OS.

^ Hell, even converting Py from C to Rust wouldn't be a good option. Maybe Jython, but ytdl would have more things to consider due to the diffs between CPython and Jython on the technical level.

The simplest I know would be to release separate ytdl binaries "targeting" Py 2 or 3 that only differ by the shebang, since ytdl will run on both no problem.

**Comment by Rudxain** [comment]
( Replying to @dzodzo666 )
> you can use designed commands that do very much the same but in officially recommended manner

Thank you for the links and the info

> if something expects python2 it better be converted to python3 anytime soon

I hope so!

( Replying to @dirkf ) 
> Python version that runs on all OS versions

That would very likely require a fat binary, but with extra bloat (because the entire interpreter is bundled)

**Comment by liOnux-fr** [comment]
Why not update the documentation about this issue ? For example by installing the python-is-python3 package (Debian/Ubuntu)

**Comment by the-moog** [comment]
`sudo apt install python-is-python3`

**Comment by dirkf** [comment]
Packagers should and do adapt the yt-dl installation to match the default Python installation on the target platform.

A problem can arise when the target platform doesn't have a Python by default (Windows, recent macOS) and the packagers forget that any recent Python installed on their platform will probably call itself `python3`.

Otherwise the self-extracting POSIX single file build requires one of the tweaks from this issue or from https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1449990989.
