### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Halltech176** [ytdl-org/youtube-dl#31134]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

```
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Xmetalfanx** [comment]
More info would be needed in the template format to help with this issue

**Comment by mrmelwynm** [comment]
Not sure if this is what you mean by verbose log, but this is the command line and the result i got.

C:\youtube-dl http://fdown.net/downloader.php?id===ANw1mL0lmbp9CZuV3LvlGZ1F2LkBXbfNzNzMTNyQzMy8Cdy9yMvMzMvcjNvgzMvMHduVmdl9idj9SYpRWZt9Cdl5mLkVmepFWbhtWYuQ2boNXYk9yL6MHc0RHa
[generic] downloader: Requesting header
WARNING: Could not send HEAD request to http://fdown.net/downloader.php?id===ANw1mL0lmbp9CZuV3LvlGZ1F2LkBXbfNzNzMTNyQzMy8Cdy9yMvMzMvcjNvgzMvMHduVmdl9idj9SYpRWZt9Cdl5mLkVmepFWbhtWYuQ2boNXYk9yL6MHc0RHa: HTTP Error 403: Forbidden
[generic] downloader: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mrmelwynm** [comment]
I've ensured I have the latest version of youtube-dl.

**Comment by 89z** [comment]
@mrmelwynm you're in the wrong place.

**Comment by suntong** [comment]
More info on this issue:

```
youtube-dl -f best --continue --ignore-errors 'https://www.youtube.com/watch?v=fgh0sqGacnU'
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] fgh0sqGacnU: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by 89z** [comment]
@suntong this isn't, and never was a valid issue. If you have a similar problem, you should post a new issue, while ensuring to fully complete the issue template.

**Comment by dirkf** [comment]
If OP wants an extractor for fdown.net, post a site support request.
