### ISSUE TITLE
Limit youtube-dl channel scraping to first 10 videos

### ISSUE THREAD

**Issue by ExploiTR** [ytdl-org/youtube-dl#31209]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## I want to limit the amount of videos youtube-dl finds when scraping a channel

I've used  `extract_info(channel_url, download=False)` to extract first 10 videos from a random channel with 1000 videos, and it tries to extract info for all 1000 videos. I want only the first 10 or 5 videos, or maybe the only most recent one. I can't find a way to do so without it trying to scrape the whole 1000 video list which will be very time consuming.

(channel_url is formatted like this : https://www.youtube.com/c/channel_name/videos?)

**Comment by dirkf** [comment]
How about `--playlist-end 10`?

I only put a question-mark there because this option is [clearly documented in the Manual](https://github.com/ytdl-org/youtube-dl#user-content-video-selection) and anyone who had bothered to look up such options would have read about and tried it.

**Comment by ExploiTR** [comment]
Does that work if it's still not a playlist? Okay I'll try that.

**Comment by ExploiTR** [comment]
No it's not working, it's still doing this : 

```
[download] Downloading video 22 of 1040
[youtube] PAoVVpGPgho: Downloading webpage
```

**Comment by ExploiTR** [comment]
No it's not working, it's still doing this : 

```
[download] Downloading video 22 of 1040
[youtube] ABCD1234: Downloading webpage
```

**Comment by ExploiTR** [comment]
I also tried `--flat-playlist` and `--max-downloads`. It seems to crawl everything then do the operations.

**Comment by dirkf** [comment]
Full verbose log, please. Like this:
```ShellSession
$ python -m youtube_dl -v --flat-playlist --playlist-start 9 --playlist-end 11 'https://www.youtube.com/channel/UCKfVa3S1e4PHvxWcwyMMg8w/videos'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--flat-playlist', u'--playlist-start', u'9', u'--playlist-end', u'11', u'https://www.youtube.com/channel/UCKfVa3S1e4PHvxWcwyMMg8w/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 4050e10a4
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube:tab] UCKfVa3S1e4PHvxWcwyMMg8w: Downloading webpage
[download] Downloading playlist: lex will - Videos
[youtube:tab] playlist lex will - Videos: Downloading 3 videos
[download] Downloading video 1 of 3
[download] Downloading video 2 of 3
[download] Downloading video 3 of 3
[download] Finished downloading playlist: lex will - Videos
$
```

**Comment by ExploiTR** [comment]
Okay so I figured out I was passing the arguments like cmd-line args but actually needed to pass the in-code params, so I looked into the cli spec at options.py and below snippet worked. Thanks for the help!

```
params = {
    'verbose': True,
    'outtmpl': '%(id)s.%(ext)s',
    'extract_flat': True,
    'playliststart': 1,
    'playlistend': 1
}
ydl = youtube_dl.YoutubeDL(params)
```

**Comment by ayoubelmhamdi** [comment]
I am also, I have this `bug` with some `channel` and others not happened.
- channel have this bug
  - [1](https://www.youtube.com/c/%D8%B3%D9%8A%D9%84%D9%81%D9%8A%D8%B3%D8%A8%D9%88%D8%B1%D8%AA)
  - [2](https://www.youtube.com/c/MamdouhNasrAllahMadfa3)
- channel does not have this bug
    - [3](https://www.youtube.com/channel/UCBkVNEpuMB-xwO8ElZgi3iA)
   
the main problem, in bugs channel (1 and 2)  is the delimiter is powered by 2:
```
--playlist-end  2  -->     4 items
--playlist-end  3  -->     9 items
--playlist-end  10 -->   100 items
```

**Comment by dirkf** [comment]
Channel 1 (https://www.youtube.com/c/%D8%B3%D9%8A%D9%84%D9%81%D9%8A%D8%B3%D8%A8%D9%88%D8%B1%D8%AA) has 4 items, each of which is a playlist (Uploads, قصة الجمعة - سيلفي سبورت, توب 5 الرياضة, Popular uploads). "Uploads" and "Popular uploads" look like different sorts of the same data but have different cardinality.

Channel 2 (https://www.youtube.com/c/MamdouhNasrAllahMadfa3) has 3 items, each of which is a playlist (Uploads, Popular uploads, مجنونة يا كورة) containing items of `_type` `url`.
* [Uploads](https://www.youtube.com/c/MamdouhNasrAllahMadfa3/videos?view=0&sort=dd&shelf_id=0) has 2584 items
* [Popular uploads](https://www.youtube.com/c/MamdouhNasrAllahMadfa3/videos?view=0&sort=p&shelf_id=0) has 999 items.
* [Arabic text that formats badly](https://www.youtube.com/playlist?list=PL9CX-8B6ssKAR2qyCozDnuKR9ysSQwb-A) has 46 items.

Fetching each playlist with `--playlist_end 2` gives 2 items. Fetching the channel with `--playlist_end 2` gives **4** items, which are the 2 items from the first 2 playlists.
```shellsession
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/c/MamdouhNasrAllahMadfa3/videos?view=0&sort=dd&shelf_id=0' 
aDfzyvwYIpg
rZiBN72thP0
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/c/MamdouhNasrAllahMadfa3/videos?view=0&sort=p&shelf_id=0' 
ZdDBg8MjQbE
9vzjoiNF_XQ
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/playlist?list=PL9CX-8B6ssKAR2qyCozDnuKR9ysSQwb-A' 
Cw0J7KjdMQk
3Sn4ZcxZpf8
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/c/MamdouhNasrAllahMadfa3'
aDfzyvwYIpg
rZiBN72thP0
ZdDBg8MjQbE
9vzjoiNF_XQ
$
```
Channel 3 (https://www.youtube.com/channel/UCBkVNEpuMB-xwO8ElZgi3iA) has 1 item, which is a playlist (Uploads). The playlist has 216 items, all of `_type` `url`. Fetching the playlist with `--playlist_end 2` gives 2 items, as does fetching the channel.
```shellsession
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/channel/UCBkVNEpuMB-xwO8ElZgi3iA' 
yJyHLBAK0Gw
lcjyv8InjYM
$ python -m youtube_dl --playlist-end 2 --get-id 'https://www.youtube.com/channel/UCBkVNEpuMB-xwO8ElZgi3iA/videos?view=0&sort=dd&shelf_id=0' 
yJyHLBAK0Gw
lcjyv8InjYM
$
```
What's apparently happening is that the `--playlist-end ...` option is being applied to the top-level playlist and then to each nested playlist. So, provided that enough playlists and items are available at each of m levels*, `--playlist-end n` will produce n**m items. Indeed, with the above example, we get 3**2 = 9 items:
```
$ python -m youtube_dl --playlist-end 3 --get-id 'https://www.youtube.com/c/MamdouhNasrAllahMadfa3' 
aDfzyvwYIpg
rZiBN72thP0
85vnL6mlLJc
ZdDBg8MjQbE
9vzjoiNF_XQ
OLZaf0xr3nc
Cw0J7KjdMQk
3Sn4ZcxZpf8
HZOfv6RfW8Q
$
```
There is a semantic problem with these `--playlist-...` options. The manual description assumes that the options are being used with one or more separate playlists, none having a nested playlist.

When fetching videos from a channel, use the "Uploads" playlist together with your desired `--playlist-...` option(s). Otherwise `--playlist-end ...` can reduce the number of items returned, but not always to the value you specified.

* In a maximally nested playlist where levels 1..m-1 are playlists with at least n items and all items at level m are media items.

**Comment by ayoubelmhamdi** [comment]
So, the best solution is to specify the playlist that we should be got it, 
like:
![teej1](https://user-images.githubusercontent.com/34358145/194888266-71ce5927-7ffc-42e0-82c9-855dd65cb2ca.png)
```
https://www.youtube.com/watch?v=eL9iEiJTcDw&list=UUd3dNckv1Za2coSaHGHl5aA
```
**TO BE**
```
youtube_dl .........  --playlist-end 10 'https://www.youtube.com/playlist?list=UUd3dNckv1Za2coSaHGHl5aA'
```

**Comment by dirkf** [comment]
So, if you want to scrape 10 different videos from a YT channel like https://www.youtube.com/c/MamdouhNasrAllahMadfa3, use its Uploads link https://www.youtube.com/c/MamdouhNasrAllahMadfa3/videos?view=0&sort=dd&shelf_id=0 instead with `--playlist-end 10`.

If you want every video from the channel, use the channel URL itself and other links (possibly with videos not included in the Uploads list?) will be analysed recursively.

**Comment by ayoubelmhamdi** [comment]
@dirkf that is what I need, I will give it a try, thanks

**Comment by alien999999999** [comment]
as i tested this yesterday, it seems like the uploads link (for which the items below are a combination of previous streams and videos), but when you click that link, you actually go to videos (without previous streams) :-( ; but i do see random changes almost weekly at this point and it seems each change breaks other stuff... yt is not doing so great...
