### ISSUE TITLE
Simulation Delay and Upkeep

### ISSUE THREAD

**Issue by Neehier** [ytdl-org/youtube-dl#31232]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to simulate multiple Youtube livestreams to extract frames from these during set intervals. I have gotten the application to work, but raise the following questions to determine its longevity.

- When simulating a livestream off Youtube using the `simulate` option, what is the lifetime of this simulated URL? 
- How long is the delay between the simulated stream and the original stream?
- What happens to a simulated URL if the original livestream off Youtube comes to an end?

**Comment by dirkf** [comment]
As to points 1 and 2, `--simulate` just avoids downloading or writing to disk. In the nature of a livestream I expect that if you gather a download link with `--get-url`, you'll get the livestream at its current point rather than from when you gathered the URL, but people who have actually tried this will know better.

At some point the live stream may morph into a plain stream. There may be a gap while YT switches in the final streams across its servers and CDNs.

Maybe you should explain what you're trying to achieve?

**Comment by dirkf** [comment]
I'll close this now, but feel free to post any further observations from your project that might be relevant to yt-dl devs and users.
