### ISSUE TITLE
Video Not Playing in the  apk Build

### ISSUE THREAD

**Issue by FrancisArul** [ytdl-org/youtube-dl#31246]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I am trying to make a video player for Google cardboard for that I have downloaded the youtubedl package from the unity assests store and used it in the project. The problem is, video gets played when I was running the application in the unity editor, but when I took a apk build and tested in a device the video was not playing. I'm using the YTDLVideoPlayer_UI prefab. Also I Need to change the url at runtime. Is there any solution for these two above mentioned problems.

Thanks in advance...

**Comment by 89z** [comment]
YouTube-DL doesn't offer any APK build. So if you found one, you need to get help for it somewhere else.

**Comment by dirkf** [comment]
I'd have closed this already but we don't often get a query about such an exotic environment. If I understand correctly, "Cardboard" is a discontinued Google VR platform and Unity is a game engine with a Cardboard plug-in. I want my [Silent 700](http://www.computinghistory.org.uk/det/14411/TI-Silent-700-ASR-Data-Terminal/) back.

OP may by all means supply full details of the problem in case some reader is able to help, but (especially if the query concerns a paid package incorporating yt-dl) the package supplier must be responsible for support.

I'm interested to know if OP came here because the packager failed to change the bug report message or just by searching for "youtube-dl".
