### ISSUE TITLE
Use `.mkv` for VP9, and use `.mp4` for AVC

### ISSUE THREAD

**Issue by thariq-nugrohotomo** [ytdl-org/youtube-dl#31294]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Sometimes the video that I want to download is using AVC codec, but sometimes it's using VP9 codec.

For AVC, youtube-dl will output a `.mp4` file. But for VP9, the output is a `.webm` file.

How can I use youtube-dl to output `.mkv` file, "**only**" when the video is in VP9 format?

| video codec | expected container |
| ------------- | --------------- |
| AVC             | `.mp4`             |
| VP9             | `.mkv`              |

Thanks.

**Comment by dirkf** [comment]
I don't know of an automatic solution that does what you want using just yt-dl. Generally, the idea is that yt-dl gives you whatever playable file it can make from the media selected from the specified page.

However, a webm container is basically mkv.

Is it enough to rename any output .webm as .mkv in a script run by `--exec ...`? Otherwise, use `ffmpeg -i input -c copy output` in the script instead `mv`/`rename`.

Or you could ask for mkv always, or only when you expect a webm/VP9 result, with `--recode-video mkv`. Use `--postprocessor-args "-c copy"` to avoid actual re-encoding of any streams.

**Comment by rautamiekka** [comment]
What's the point of this request anyway, OP ?

**Comment by dirkf** [comment]
>would --merge-output-format mkv work ??

I believe OP wanted to leave mp4 mergers alone and just force webm to mkv.

Although it might now be allowed to merge VP9+Opus into mp4 some players like OPs won't know what to do with that combination.
