### ISSUE TITLE
Plugin location in Debian

### ISSUE THREAD

**Issue by emresaracoglu** [ytdl-org/youtube-dl#31300]
Hello,

I am using youtube-dl on my Debian 10 server and trying to find its location to add a new plugin. Where are the plugins located?

Thank you.

**Comment by rautamiekka** [comment]
What "plugins" ? How did you install ytdl ?

**Comment by rautamiekka** [comment]
How did you install ytdl ?

**Comment by emresaracoglu** [comment]
I followed these steps;

```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by dirkf** [comment]
In that case the extractor modules are inside the self-extracting executable that you downloaded. You may be able to use an archive tool to investigate.

For adding a new extractor:
1. Install a Python3 if necessary (say, 3.9).
2. Also install Python 2.7 if necessary so that you can check compatibility (2.6 as well for completists, but we haven't had a 2.6 bug report in my recollection).
3. Follow the [instructions in the Manual](https://github.com/ytdl-org/youtube-dl#user-content-adding-support-for-a-new-site).

You don't need any of the dependent tools [listed above in the Developer Instructions](https://github.com/ytdl-org/youtube-dl#user-content-developer-instructions), except possibly _nosetests_ if you need to reproduce the testing that (currently) runs in the CI workflow.

**Comment by dirkf** [comment]
@emresaracoglu ?

**Comment by emresaracoglu** [comment]
Hello,

**Thank you for your answer.** Frankly, I didn't check this page because I thought I didn't get a response from you for this issue. I guess I must have overlooked the email. I will try to delete it completely from the server soon and try to follow your steps.

cc @dirkf

**Comment by dirkf** [comment]
Let us know how you get on.
