### ISSUE TITLE
ffprobe: undefined symbol: vaSyncBuffer

### ISSUE THREAD

**Issue by SchErich** [ytdl-org/youtube-dl#31353]
doesn't work under Ubuntu 22.10
ERROR: WARNING: unable to obtain file audio codec with ffprobe
ffprobe: symbol lookup error: /lib/x86_64-linux-gnu/libavcodec.so.59: undefined symbol: vaSyncBuffer
Seems, that libavcodec59 is not compatible with actual  youtube-dl -version 2021.12.17

**Comment by dirkf** [comment]
The problem is with your installation of _ffmpeg_. yt-dl doesn't link to any _ffmpeg_ libraries, but just runs programs from the package.

**Comment by SchErich** [comment]
thank's dirkf. Any solution available?

**Comment by dirkf** [comment]
Use your distro support channels. Off the top of my head, I would force reinstall _ffmpeg_, possibly after disabling any PPAs that offer different versions of it. Something very like your issue was seen [here](https://bugs.launchpad.net/savos/+bug/1991440); unfortunately, the resolution was to reinstall the OS.
