### ISSUE TITLE
Problem playing two youtube live videos on separate TV's using a Raspberry pi 4

### ISSUE THREAD

**Issue by rijotech** [ytdl-org/youtube-dl#31375]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm facing a problem playing two live youtube videos simultaneously on separate TV's from a Raspberry pi 4 2GB, via VLC youtube-dl.
I created a web interface to control what to show on each TV when I press the live video I want to watch, now for some reason when I select two specific channels it works fine but if I select different ones the audio continues playing but the  videos freeze.

From PHP this is what I'm executing to watch on HDMI 1
`DISPLAY=:0 sudo -u pi cvlc --alsa-audio-device default --no-one-instance youtube-dl -g -U -4 --hls-prefer-ffmpeg --http-chunk-size 100M --buffer-size 32K --ignore-config --ignore-errors --skip-download --geo-bypass  https://www.youtube.com/watch?v=w_Ma8oQLmSM`

And for HDMI 2
`DISPLAY=:0 sudo -u pi cvlc --qt-fullscreen-screennumber=1 --alsa-audio-device hw:1,0 --no-one-instance youtube-dl -g -U -4 --hls-prefer-ffmpeg --http-chunk-size 100M --buffer-size 32K --ignore-config --ignore-errors https://www.youtube.com/watch?v=knJAmiXVqOg`

If I play those two channels everything works fine but when I play others simultaneously it freezes I don't know what to do to fix this I have tried lot of stuff but I can't find a solution, I'm open to  any ideas on how to fix this.

https://user-images.githubusercontent.com/17016357/203422723-b8cd2f99-ea8b-4a45-8919-ed406c014c8e.mp4

Thanks in advance!

**Comment by dirkf** [comment]
Does this solution ensure that each yt-dl is running in a separate directory?

What is the load on the Pi when running the command?

yt-dl can run on a 128MB 2x400MHz MIPS32 SoC, so it shouldn't be the limiting factor in your Pi, but VLC is a heavyweight program.

For a live relay, you'll need the git master code with the (latest) unthrottling fix.

**Comment by rijotech** [comment]
> Does this solution ensure that each yt-dl is running in a separate directory?
> 
> What is the load on the Pi when running the command?
> 
> yt-dl can run on a 128MB 2x400MHz MIPS32 SoC, so it shouldn't be the limiting factor in your Pi, but VLC is a heavyweight program.
> 
> For a live relay, you'll need the git master code with the (latest) unthrottling fix.

Check the video you can see the load when running the command on the pi, CPU usage and memory is normal. 
I updated youtube-dl to the latest 2021.12.17.
And yes I tried running from different directories but not luck.
What is crazy is the fact that if I play those two YouTube channels it works fine but if I start with different ones it freezes.

**Comment by dirkf** [comment]
```
DISPLAY=:0 sudo -u pi cvlc --alsa-audio-device default --no-one-instance youtube-dl -g -U -4 --hls-prefer-ffmpeg --http-chunk-size 100M --buffer-size 32K --ignore-config --ignore-errors --skip-download --geo-bypass https://www.youtube.com/watch?v=w_Ma8oQLmSM
```
Go [here](https://helpmanual.io/help/cvlc/) to read about _cvlc_ command options (apart from `--no-one-instance` which [this](https://unix.stackexchange.com/a/75422) confirms is, or was, relevant). The stream is expected to like some sort of URL but you've just stuck a yt-dl command there, unless you lost some backquotes when pasting. You need it to be a POSIX shell substitution, like `"$(youtube-dl options... URL)"`, or a pipe: `youtube-dl -o - other_options... URL | cvlc -` (maybe `stream:///dev/stdin` rather than `-`). If the original ever works, _cvlc_ must be silently swallowing the "URL" `youtube-dl` and all its unexpected options and just using the YT URL.

Regarding the yt-dl command

* `-U` - no, don't even think of updating the program while another instance could be running
* these options are all irrelevant since you said `-g`, so no download
 * `--hls-prefer-mpeg`
 * `--http-chunk-size`
 * `--buffer-size`
 * `--ignore-errors`
 * `--skip-download`
* `--geo-bypass` isn't applicable for YouTube as the extractor disables XFF (presumably because it's not effective for YT).

Fortunately, the VLC package [includes its own subset of yt-dl](https://askubuntu.com/questions/796575/how-to-force-command-line-vlc-to-stream-youtube-videos-of-specific-quality) so you could try (and in fact you probably are) skipping the yt-dl command entirely and just letting it do its own extraction.

Since the GUI of VLC is so atrocious, I cleave to _mpv_, especially after the maintainer of the yt-dl hook was sniffy about letting yt-dl use a fragment of the hook code despite VLC happily relying on yt-dl itself.

**Comment by rijotech** [comment]
Thanks for your responses, I think I found a way, I'm  testing different methods and the [youtube.lua script](https://code.videolan.org/videolan/vlc/-/issues/27529) is dead It wont work anymore, only youtube-dl works fine.
I'm running both instances of VLC + two separate youtube live videos with a few tweaks my only problem now is to kill each individual process via the web interface meaning kill the process on the TV on the right without affecting the process on the TV on the left. and since Pid cannot be assign i'm a bit lost.

**Comment by dirkf** [comment]
VLC's ytdl-hook is fixed again if you replace youtube.lua with the new version linked from the issue for 3.0.19. I've no idea how it was working up to last week: yt-dl hasn't been using the tactic that they replaced for ages.
