### ISSUE TITLE
Add download date to the archive

### ISSUE THREAD

**Issue by m3thm4th** [ytdl-org/youtube-dl#31407]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

When using the `--download-archive` option add the date of download in ISO8601 format in the same line

**Comment by dirkf** [comment]
That's not what the download archive is for. yt-dl assumes that each line of the archive uniquely represents a downloaded item. If the download date were included it would no longer represent the item, but the instance of downloading, which would be useless for de-duplicating, since we can't magically modify all existing yt-dl and yt-dl fork implementations.

You could instead record the download date in filesystem (title, or extended attributes if supported) or media container metadata. Or you could record your own download date index using `--exec ...`. Solutions like these have the advantage of not causing difficulty for anyone else.

But if enough other people were to consider this a useful feature (especially to the point of producing a PR), a couple of possible approaches come to mind.

Within the current scheme we could invent a special extractor (say, `_YTDLDATAIE`) whose ID would be interpreted by new versions of the software, such that each archive entry would use 2 lines:
```
<extractor key> <video id>
_YTDLDATA <extractor key> <video id> <additional data>
```
Arguably, the text format of the existing archive index is inefficient and limiting. The current code requires a linear search of the archive file for each download check, which would only be aggravated by doubling the number of entries. There is no guarantee that the archive index includes at most one entry per `(extractor_key, video_id)`, except that the code is meant not to add multiple entries: if an index were to become corrupt duplicate entries would be retained forever.

The archive index could be upgraded to a (say) SQLite3 database, perhaps with a final pass to create an archive database in the current format if it has been updated. Then, new code could look for the SQLite3 archive (let's assume its name is rigidly derived from the `--download-archive ...` name, say by appending `.sqlite`), falling back to the text file. The schema of such a database could be extended with further columns like `download_date` without affecting code that only knows of `extractor_key` and `video id`, or only knows of the current archive format.

@pukkandan - any views?

**Comment by pukkandan** [comment]
This has been brought up to me multiple times as well, and my answer is same as yours - https://github.com/yt-dlp/yt-dlp/issues/1762#issuecomment-976441715

A more complicated schema for archive would be possible, and quite easy tbh as long as the lines still start with `ie_key id`. But, I haven't seen any compelling reason to implement one. These requests are generally coming from a misunderstanding of what the option is meant to be.

Some users just want the archive to be more "human readable" and contain the metadata that they want - not actually preform de-duplication with this new data. This can be achieved using or `--exec echo` (or `--print-to-file` in yt-dlp) and is not related to archive in any way

> The archive index could be upgraded to a (say) SQLite3 database, perhaps with a final pass to create an archive database in the current format if it has been updated. Then, new code could look for the SQLite3 archive (let's assume its name is rigidly derived from the --download-archive ... name, say by appending .sqlite), falling back to the text file. The schema of such a database could be extended with further columns like download_date without affecting code that only knows of extractor_key and video id, or only knows of the current archive format.

Using an sqlite DB would be possible, but again, the actual de-duplication can only be done with id and extractor. It doesn't make sense to use other fields for that purpose. One merit I can see in such a feature is that it would make a single store of info-json + archive. If this is something people want, I wouldn't be opposed to it. But I don't think OP's use-case will be satisfied by this

**Comment by pukkandan** [comment]
> Arguably, the text format of the existing archive index is inefficient and limiting. The current code requires a linear search of the archive file for each download check, which would only be aggravated by doubling the number of entries.

This can be overcome by loading the archive to memory at program start (like yt-dlc/p does). In theory, this isn't quite correct when multiple ytdl instances are reading from the same archive; but I've never seen anyone complaining about this. Alternatively, if it is not something you are willing to compromise on, the file's `mtime` could be used to reload archive as necessary

**Comment by dirkf** [comment]
Thanks, that's useful. As OP closed the issue we can let the record stand in case there is a sudden demand from people with gigantic download archives.
