### ISSUE TITLE
Remove link to malicious extension in README.md

### ISSUE THREAD

**Issue by iwalfy** [ytdl-org/youtube-dl#31465]
[Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) extension it is a malicious extension which must be reported and removed from README.
It sends the following data of every request in your browser to https://ck.getcookiestxt.com/getcookie
```
{  
  "timestamp": "<TSTAMP>",  
  "e": "<UUID Identifying your Device",  
  "f": "<USERAGENT>",  
  "b": "<FULL URL>,  
  "locale": "<LOCALE_CODE - your Language Settings>",  
  "platform": "<PLATTFORM - MAC/Win/Linux...>"  
}
```

**Comment by dirkf** [comment]
More of the story is at https://old.reddit.com/r/youtubedl/comments/10ar7o7/if_youve_been_using_the_get_cookiestxt_chrome/.

The developer has responded in the Chrome crippleware store that the behaviour will be made optional. Let's see before changing the text. The privacy policy for the Edge version claims that the extension doesn't collect your data and someone who cared could post an issue in [its repo](https://github.com/ian-bateman/GetCookies.txt/issues).

For users of the extension who are are probably using Chrome, this can't really make things worse. But I suppose it might also run on Vivaldi, etc.

**Comment by dirkf** [comment]
Also strange, a relevant HackerNews page listed by G has gone.

**Comment by Leseratte10** [comment]
"Will be made optional" sounds like "We'll give the user the ability to opt-out", I don't really like that statement. That would mean that nearly everyone would still be tracked as nobody expects to have to opt-out of something like this. 

Also, I'm not sure what you mean with "For users using Chrome this can't make things worse" - you mean just because I consent to Google tracking me I also consent to a random extension developer tracking me?

That plugin added tracking that sends A) a unique browser UUID and B) the exact URL of every single visited website to the developer's website. That's not something that's required for that extension to function and it's not something that should be expected from a simple cookie dumper. 

In my opinion this plugin should be removed everywhere (including the store) for a behaviour like that, and I'm fairly sure that behaviour like that violates the Chrome Store policies. And it also shouldn't get any advertisements anywhere like in the README.

Is there any alternative extension that could be promoted instead?

**Comment by dirkf** [comment]
You sow the Chrome, you reap the "Get cookies.txt", the Manifest V3, etc. I'm only familiar with extensions for other platforms.

There is another extension that appeared when the "Get cookies.txt" extension was pulled, but its supposed source repo is invalid. Some tools exist that aren't extensions. Or a skilled user can use the browser Dev Tools.

Or Firefox.

**Comment by Leseratte10** [comment]
> You sow the Chrome, you reap the "Get cookies.txt", the Manifest V3, etc. 

Not sure what this has to do with Chrome. Malicious developers adding malicious tracking code to their extensions can also happen on Firefox or any other browser, can it?

**Comment by dirkf** [comment]
No, it's the monoculture. FF extensions would work with Chrome otherwise.

Possibly the old cookies.txt extension which is no longer in the Chrome store but is available in various other places and still seems to be functional according to one of the Reddit contributors would be a candidate, until Chrome breaks the extension APIs again.

**Comment by rautamiekka** [comment]
Pretty sure this doesn't count as malicious, but still, point in that this shouldn't be allowed.

**Comment by nicolaasjan** [comment]
> Can youtube-dl merge back the feature from yt-dlp that allows it to read the necessary cookies directly from a browser so users no longer need the cookie file?

👍️
This would be the way forward.

**Comment by dirkf** [comment]
There's already a PR for this https://github.com/ytdl-org/youtube-dl/pull/29201, which became the yt-dlp proposal https://github.com/yt-dlp/yt-dlp/pull/488.

I haven't reached #29201 in my oldest-first trawl of unmerged PRs. It seemed like a maintenance and dependency hell when I originally saw it. But as it's now been well exercised in yt-dlp, someone could take this and update it with the yt-dlp fixes. It's acceptable for it to fail gracefully on missing dependencies, say for Py 2.6.

**Comment by Sophira** [comment]
Hiya. I'm the person who posted the initial Reddit link that was [posted in the second comment of this issue](https://github.com/ytdl-org/youtube-dl/issues/31465#issuecomment-1382828055).

Unfortunately, I've just re-checked the extension and found that it now actively sends all your cookies to the developer, as well. I've made another Reddit post at https://old.reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively/ about this.

Since it's been almost two months and it's now actively sending data that can be used to compromise accounts, I'd say the developer is probably not interested in removing this misfeature, and I would also recommend that the link in the README is removed.

**Comment by pukkandan** [comment]
Off topic:

> I haven't reached #29201 in my oldest-first trawl of unmerged PRs.

Just a friendly suggestion from my own experience as a maintainer. I suggest going through them newest first (or recently updated first). I agree this is unfair to the authors of the older PRs, but newer PRs are more likely to be still relevant and have less conflicts. I think such a change in approach would help speed up development. Considering the huge backlog you have inherited, I can't even imagine how daunting it is to go through them oldest-first - you have my respect for even attempting it!

**Comment by dirkf** [comment]
My oldest-first trawl, actually from mid-2020, isn't the only one, and luckily most of those are obsolete, having been accepted into dl[cp]!
