### ISSUE TITLE
app's ffmpeg api for meta-data merging is very slow

### ISSUE THREAD

**Issue by LovelyBloom** [ytdl-org/youtube-dl#31470]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
I've included adding meta-data to my downloaded files and for a 15 min file it takes minutes and for a 4 hour and 30 min it took 40 minutes and it was only one of the files on the playlist. what do expect me to do. buy 1000 gallon of coffee to sip while it finishes fixing all my downloads. you can't put the blame on me for using an HDD which is a top of the line Barracuda pro 7200 instead of the best samsung nvme cpu raid0 pciex4 ssd. this issue needs to be prioritized. especially prioritized over site compatibility. we're talking about the software's api's dignified execution and quality of code.

**Comment by dirkf** [comment]
Let's see your verbose log with timings. Perhaps you have selected options that require re-encoding some 5GB file.

Generally, if there is a problem with _ffmpeg_ or some other auxiliary tool, it should be raised in the tool's support system, though it may also be useful to raise it here in case the issue is with how yt-dl uses the tool, or there might be a work-around that avoids the need to change the tool.
