### ISSUE TITLE
Youtube-dl is fried; do I update to yt-dlp?

### ISSUE THREAD

**Issue by MintKakapo** [ytdl-org/youtube-dl#31535]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Yo, I tried downloading a video today and noticed everything's busted. I have the same issues as threads #31534, #31533, #31532, #31531 & #31530 , which leads me to ask this; should I download yt-dlp due to the change of management requesting it (refer to #30568 as well as [here in #31530](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433324977)), or will there be an internal patch to vanilla youtube-dl? Just asking this for anyone else who doesn't frequent this page, wondering why everything broke out of the blue.

## Edits

1.) Punctuation and added another thread that talks about this
2.) Added this fancy header

**Comment by elgonzo** [comment]
> should I download yt-dlp

Sorry for responding with a counter question, but what actually stops you from downloading and trying yt-dlp? That said, perhaps wait a day or a few before doing that (because: https://github.com/yt-dlp/yt-dlp/issues/6253#issuecomment-1433520595)

**Comment by Grub4K** [comment]
`youtube-dl` failed due to occasional inclusion of `@user` in some data by YouTube, which did not match a regex and caused the program to fail, since it was mistakenly marked as required. Predicting changes in the website is challenging, buttTypically these should not be required and therefore avoid program failure.

If you don't have specific requirements by all means do try `yt-dlp`, it has many [new features](https://github.com/yt-dlp/yt-dlp#new-features). Both repositories are still getting worked on, though `youtube-dl` has not seen a regular release *yet*. At time of writing this, **yt-dlp has *not* seen a release solving this problem either** though.

Ultimately it is up to you to pick and choose the application you like the most. There are [changes in the default behavior](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior), possibly making it a worse fit. Some people are also constrained by the additional requirements that yt-dlp poses, however for the regular end user those are mostly not noticeable.

**Comment by dirkf** [comment]
If your environment supports it, yt-dlp will be fine for you. You can enable various compatibility options if you want it to act as a yt-dl clone, or otherwise use the native command syntax, which is still similar to yt-dl.

Comparing the two programs:
* yt-dlp's core processing is more sophisticated, supporting more complicated download functionality
* extractors are generally easy to port either way: sometimes the yt-dlp extractor will be newer, sometimes not
* yt-dlp has more dependencies, but yt-dl is more likely to run if you have an older environment.

Or you can use the yt-dl git master by installing it with _pip_ from your Python installation (probably 2.7 is the minimum version for which this works, and you need a _pip_ version that is new enough to install from GitHub but old enough to run in 2.7).

Or you can find an unofficial nightly build in a fork of yt-dl, or make your own fork and build the program.

Or you can wait for an official release with the latest changes.

If you are still using yt-dl 2021.12.17, you have a lot more issues than just the `uploader_id`.

**Comment by MintKakapo** [comment]
> If you are still using yt-dl 2021.12.17, you have a lot more issues than just the `uploader_id`.

0_0 oh no. That doesn't bode well.

**Comment by dirkf** [comment]
Just to look at some fixes and enhancements for the YT extractor:
```
commit 58988c1421b88875a33015b08e4d2ada43021e09
    [YouTube] Bypass age-gating for certain restricted videos
commit 6d829d811932b24be4d3cc8b6c1e0d46c2b1566c
    [YouTube] Fix not finding videos listed under a channel's "shorts" subpage. 
commit 811c480f7b6c25ca510a033e6365d00174135392
    [YouTube] Support JSON3 subtitle format
commit 0c0876f790c78c38ececbc920073e8b6cf01e9c7
    [youtube:search] Add tests
commit 78ce962f4fe020994c216dd2671546fbe58a5c67
    [youtube] Support channel search
commit 34c06b16f5eb814308392b68dce07bbff62bc406
    Support Youtube Shorts URL format
commit af9e72507ea38e5ab3fa2751ed09ec88021260cb (and more recent updates)
    Implement n-param descrambling using JSInterp
```
On the other hand the [`uploader_id` issue seems to have gone away by itself](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433869627).

The age-gate fix also adds (or restores) extraction of several unrelated metadata items (view/like count, track/album/etc).

**Comment by bkraul** [comment]
Thanks for this. `yt-dlp` patched the issue. Switched.

**Comment by colhountech** [comment]
It's the new `@chanelname` parameter

Fixed here --> https://github.com/yt-dlp/yt-dlp/issues/6247

If you want  a quick fix for now, just need to add this new parameter option:`/|(?=@))`

in  .local/lib/python3.8/site-packages/youtube_dl/extractor

Change this:
```
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
```
to this 
```
 'uploader_id': self._search_regex(r'/(?:channel/|user/|(?=@))([^/?&#]+)', owner_profile_url, 'uploader id', default=None),
```

and wait for a new update soon. :-)

**Comment by MintKakapo** [comment]
Lots of interesting developments happening :0 Thanks for keeping me posted guys; really appreciate it :)

**Comment by MintKakapo** [comment]
Closing this thread and referring to #31530 for further developments. Thanks for your insight on this issue, guys! :)

**Comment by Tyrewt** [comment]
> > If you are still using yt-dl 2021.12.17, you have a lot more issues than just the `uploader_id`.
> 
> 0_0 oh no. That doesn't bode well.

An explanation would have been nice too, as youtube-dl 2021.12.17 is literally the current stable release.

**Comment by HighCommander4** [comment]
> If you are still using yt-dl 2021.12.17, you have more issues than just the `uploader_id`.

This is an aside, but, wow, is that ever true!

I've been using 2021.12.17 and my YouTube download speeds have been rate-limited to like ~60kB/s, and I assumed that was a server-side limitation that I couldn't do anything about -- but nope, after upgrading to the master branch, downloads are lightning faster.

I am kind of curious what is standing in the way of promoting the version on the master branch to an official release.

**Comment by dirkf** [comment]
#31585

**Comment by Tectract** [comment]
Ooof, this one just hit me.

ERROR: Unable to extract uploader id; 

youtube-dl -U yields:

youtube-dl is up-to-date (2021.12.17)

Yeesh. This is admittedly an old system, that I use mainly for media as a "mythbox". I tried to update to yt-dlp but it requires a higher version of python 3, so it's becoming a boondoggle to get it working again now...

Is there a quick fix somehow? Can't I tell it to ignore uploader ID via a command-line option or something?

**Comment by dirkf** [comment]
[Could we maybe get like, a hotfix?](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by 01bradmiller** [comment]
I have gone round and round with yt-dl & youtube_dl trying to download subtitles, keep getting this:
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bkraul** [comment]
Yep, swapped to `yt-dlp` via `pip`, never looked back. As a matter of fact, downloads were never as fast with `youtube-dl` .

**Comment by dirkf** [comment]
@01bradmiller, #30839 (known issues).

**Comment by Dominic-Mayers** [comment]
I see above comments referring to a 2021.12.17 version of yt-dl, In Dec 2024, Youtube-dl is still well supported in https://github.com/ytdl-org/youtube-dl .  With python, zip, git and Gnu make already installed, the simplest way I found to avoid problems was to clone the youtube-dl repository using git and create my own build with `make `and `sudo make install` at the root of the repository.  I had issues such as missing certificates with builds that were already created.

**Comment by dirkf** [comment]
There's little point in installing _yt-dl_/_yt-dlp_ from a distro repository, because the WWW target changes too quickly. But _ffmpeg_, etc, sure.

Just use the nightly build release here, or stable or nightly build of _yt-dlp_ for extra capabilities on Py3.9+.
