### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by scarrijo** [ytdl-org/youtube-dl#31547]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

I have the latest version of youtube-dl, but I am receiveing this error. 
Z:\Temp\youtube-dl  https://www.youtube.com/watch?v=Tt_nqLvuR2A&t=43s
[youtube] Tt_nqLvuR2A: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
't' is not recognized as an internal or external command,
operable program or batch file.

Z:\Temp\>youtube-dl.exe -U
youtube-dl is up-to-date (2021.12.17)

**Comment by gkfirst8** [comment]
Same here

**Comment by azibi69** [comment]
also same here:

pieter@aspire:~$ dlp -v https://youtu.be/5_w5WJUvy50 
[debug] System config: []
[debug] User config: ['--no-warnings', '--ignore-errors', '--restrict-filenames', '--no-overwrites', '--limit-rate', '1M', '--default-search', 'ytsearch', '--output', '/media/pieter/Data/youtube/%(uploader)s/%(upload_date)s-%(title)s-%(uploader)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--no-playlist', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '128K', '-v', 'https://youtu.be/5_w5WJUvy50']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-31-generic-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1
[debug] Proxy map: {}
[youtube] 5_w5WJUvy50: Downloading webpage
[youtube] Downloading just video 5_w5WJUvy50 because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pieter/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pieter/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pieter/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/pieter/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/pieter/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

pieter@aspire:~$

**Comment by dirkf** [comment]
You didn't complete the issue template which would have identified that the problem is known and already addressed.

**Comment by JohnTRL** [comment]
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`

**Comment by scarrijo** [comment]
*I am sorry bothering you again, but changing this file didn't work for
me. *


[image: image.png]




*Sergio Luiz Carrijo*

E-mail:   ***@***.***

**Comment by dirkf** [comment]
> ... changing this file didn't work for me.

Follow #31530 for supported solutions.
