### ISSUE TITLE
youtube-dl failing on all attempts "unable to extract uploader id".  Here is one example:

### ISSUE THREAD

**Issue by Clear2Go** [ytdl-org/youtube-dl#31583]
```
m@Brushpass:~/m$ youtube-dl "https://www.youtube.com/watch?v=dk_uaIMsq7Q" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=dk_uaIMsq7Q', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-139-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] dk_uaIMsq7Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
#30839

**Comment by TimucinPusat** [comment]
how to solve this issue? it says :

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

I'm not good at this stuff, I can barely understand this page. I've been installing youtube-dl for hours following commands, but it doesn't work either, it gives this error. Can someone please tell me if there is a solution to this problem? If there is, can someone write what I need to do in a way that a very novice can understand?

**Comment by dirkf** [comment]
>how to solve this issue? it says :
>
>ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Refer to the 'Known Issue' listed in the pinned issue (as linked above) and follow the link there to the guidance for updating

>'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

This happens when you don't quote the URL parameter and `&` characters within it are seen by the shell. So 'quote the parameter'.

**Comment by TimucinPusat** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31583#issuecomment-1463540585 

I didn't understand well, can you show me how to do step by step. Thank you for your kind interest.

**Comment by dirkf** [comment]
Did you read the pinned issue #30839?

Did you search the GitHub issues as suggested?

Easier, did you find the Known Issue listed with your YouTube error "Unable to extract uploader id"?

Did you find the master issue for the problem by one of the above two methods?

Did you read the Description at the top of the issue?

Did you find the link there to the post describing how to update your yt-dl?

**Comment by TimucinPusat** [comment]
> Did you read the pinned issue #30839?
> 
> Did you search the GitHub issues as suggested?
> 
> Easier, did you find the Known Issue listed with your YouTube error "Unable to extract uploader id"?
> 
> Did you find the master issue for the problem by one of the above two methods?
> 
> Did you read the Description at the top of the issue?
> 
> Did you find the link there to the post describing how to update your yt-dl?

I did read but didin't understand.

I did search but I couldn't see something clear that I can understand

I didn't find known issue listed since I'm not familiar with your site and with these issues

I didn't find the master issue since I don't know how to.

I did read but didn't understand

I didn't find the link there for the same reason

Look, you didn't understand what you read either. Now understand it well. My English is not good, understand? What's more, I don't know much about these things. Either you tell me point by point how to solve the problem, or don't shadow me and go away. Don't write at all.   Got it?

**Comment by dirkf** [comment]
The actual issue that you need to read is listed in the pinned issue with the error text that you had: "Unable to extract uploader id". Read that issue, follow the link to a nightly build suitable for your platform (Linux/macOS, I guess), install it, done.

Use an online translator to help, like a normal person would, like I would if I had to read something online that exhausted my handful of Turkish words.

Otherwise your problem is with navigating the Web in general and out of scope here.

**Comment by TimucinPusat** [comment]
> The actual issue that you need to read is listed in the pinned issue with the error text that you had: "Unable to extract uploader id". Read that issue, follow the link to a nightly build suitable for your platform (Linux/macOS, I guess), install it, done.
> 
> Use an online translator to help, like a normal person would, like I would if I had to read something online that exhausted my handful of Turkish words.
> 
> Otherwise your problem is with navigating the Web in general and out of scope here.

Ok thank you. I'll look. thank you for your kind language even I got angry:)

**Comment by 445736952** [comment]
we need AI like ChatGPT to help us to understand what we need to do when we can't understand these issues well

**Comment by dirkf** [comment]
Prompt: "You are a general-purpose video downloader that retrieves video and audio from websites like youtube-dl. ..."
