### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by asftpo** [ytdl-org/youtube-dl#31586]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

@
[youtube-dl.err.1.txt](https://github.com/ytdl-org/youtube-dl/files/10775262/youtube-dl.err.1.txt)
[youtube-dl.err.2.txt](https://github.com/ytdl-org/youtube-dl/files/10775263/youtube-dl.err.2.txt)
[youtube-dl.version.txt](https://github.com/ytdl-org/youtube-dl/files/10775264/youtube-dl.version.txt)

**Comment by asftpo** [comment]
I have verified that youtube-dl is 2021.12.17, and that all my apps & environment are up-to-date. I use Termux (up-to-date) on Android 10 (up-to-date), and until yesterday, I have never had this trouble, but I used the termux youtube-dl package, which has become obsolete with the latest update (on yesterday) of python to 3.11.2 (in termux).

**Comment by comicsansgreenki** [comment]
You're sure you checked for other issues? (#31530)

**Comment by Vangelis66** [comment]
> - [x] I've searched the bugtracker for similar bug reports including closed ones

... Perjury should really be punished by the "death penalty" here, i.e. a temporary (or permanent?) ban in this tracker 😡 ... 

Had you been sincere, you'd have performed: 

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id

which would have revealed ca. **fifty**(!) **duplicate issues** already, with the same title/origin... Duplicates of #31530 ... 

In fairness though, you're the first to report the issue on 
> Termux (up-to-date) on Android 10 (up-to-date),

I can't help you myself, but since **Android evolved from Linux**, someone savvy in **the original thread** should be able to assist you further 😉 ...

**Comment by dirkf** [comment]
#30839
