### ISSUE TITLE
I've seen this

### ISSUE THREAD

**Issue by MonkberryMedium** [ytdl-org/youtube-dl#31613]
peter@desktop:~/Desktop$ [youtube] NAj8suae3WY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
q
When I tried to download this
youtube-dl https://www.youtube.com/watch?v=NAj8suae3WY&list=OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE&index=6

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by MonkberryMedium** [comment]
It would seem that these particular videos are being blocked.
youtube-dl https://www.youtube.com/watch?v=NAj8suae3WY&list=OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE&index=6

**Comment by dirkf** [comment]
No.

> [ ] I've searched the bugtracker for similar bug reports including closed ones

Why not?

#30839

**Comment by MonkberryMedium** [comment]
yes. I'm apparently having a problem. The "no" answer is not helpful.

**Comment by MonkberryMedium** [comment]
peter@desktop:~/Desktop$ youtube-dl https://www.youtube.com/watch?v=NAj8suae3WY&list=OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE&index=6
[1] 5718
[2] 5719
peter@desktop:~/Desktop$ [youtube] NAj8suae3WY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Did you not read the linked issue, that you were asked to read before creating this issue, or the other one?

**Comment by MonkberryMedium** [comment]
I did NOT read the issue. It was NOT clear to me what the issue was. If it is clear to you, please divulge. Thanks, Peter

**Comment by dirkf** [comment]
[THIS LINKED ISSUE](https://github.com/ytdl-org/youtube-dl/issues/30839)!

**Comment by MonkberryMedium** [comment]
Yes, of course I saw that and it did NOT fix the download problem

**Comment by MonkberryMedium** [comment]
also, just a suggestion, why not try downloading the video in question yourself and then tell me how it went?

**Comment by dirkf** [comment]
What should I have written that would have caused you
1. to perform the suggested search (which would have listed a recent issue with more comments than almost any in the tracker, and which covers your problem)?
2. to study the list of known fixed issues (including the one that you have)?

I'm asking seriously. Help us improve!

**Comment by MonkberryMedium** [comment]
As has been suggested, I believe the simplest way to see what I'm experiencing, is to try it yourself. I've tried with youtube-dl installed via apt and pip and also on different newest operating systems (via vm). Please try this yourself. If this works for you, then I'll know it must be my setup here.

youtube-dl https://www.youtube.com/watch?v=NAj8suae3WY&list=OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE&index=6

**Comment by dirkf** [comment]
Your problem is this error, no?
```
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Follow the [steps](https://github.com/ytdl-org/youtube-dl/issues/31613#issuecomment-1436208261) in the issue pinned at the top of the issue tracker page, and linked here several times, to discover solutions for your problem, which is well known and fully understood. Then, if you like, answer my last question.

**Comment by MonkberryMedium** [comment]
From your question, I can tell that language might be an issue as well. As far as the web site (and your help on it goes), I think it sucks. It is very confusing to a first time user that does NOT wish to become a programmer or git person. The solution that I found for this is relative to a windows install (yt-dlp) and I am running Linux (and have been for about 35 years). I've found that when you receive missleading advice or run around advice, the person sending you that probably does not understand the question, no less have an answer to the query. I could easily just view the video and extract the audio via audacity but I became curious as to why this was happening. I realize that I did not ask the question in detail but I also felt that it was enough detail to get the point across, however, as we both know (no?) assuming can and usually will lead to mixed results. I'm not trying to be harsh with this answer, moreover honest. From a user standpoint, this web site could use a lot of work. This may not be a user web site but it does not appear to be helpful. Just me .02. Thank you for the help. Peter

**Comment by dirkf** [comment]
The reason for your problem and its resolution were obvious to start with since hundreds of other people had already seen the same problem. The pinned issue had been revised to help people find the known solution. No-one is being paid to answer questions here: whenever someone ignores an existing solution it detracts from time that could be spent on improvements to the program; say, making a new official release.

I still don't understand what it was about the self-help steps you were asked to follow that was so challenging. If you don't like what you were asked here you certainly won't want to try getting a doctor's appointment in Britain.

**Comment by Vangelis66** [comment]
> It is very confusing to **a first time user** that does NOT wish to **become a programmer or git person**.
> ...
> and I am **running Linux** (and have been **for about 35 years**).

... As a **Windows** user exclusively 😉 , I can't help reading a 'contradiction' in the above statements... Haven't you ever installed programs **from source/via git** in your decades-long experience with Linux? 

Please understand that this repo is being currently managed by **only ONE** active coder/maintainer (**dirkf**); dealing with close to **100 duplicate submitted issues** ALL about **the very same root cause** (but under varying running environments = Python versions/OSes) isn't for the fainthearted and is, most certainly, extremely time consuming (often times also nerve wrecking...). 

All potential issue submitters are asked is to follow a certain procedure, clearly and eloquently outlined, baring cases for which the reader has very poor command of the English language (where machine translation can still help).

> From a user standpoint, this web site could use a lot of work.
> This may not be a user web site but it does not appear to be helpful

Well, will you offer yourself (in your spare time) as **a proficient Linux expert** and help triage Unix-related issues here? 
The "web site" (actually, a GitHub open source code repository, with an enabled issues tracker) will surely get better by extra "volunteer" work, don't you think?

> why not try downloading the video in question yourself 
> and then tell me how it went?
```shell
yt-dl -f worst "https://www.youtube.com/watch?v=NAj8suae3WY&list=OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE&index=6"

[youtube:tab] Downloading playlist OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE - add --no-playlist to just download video NAj8suae3WY
[youtube:tab] OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE: Downloading webpage
[youtube:tab] OLAK5uy_l9OrpmSmct3cOnJo78yKRrocch_3OIcOE: Downloading webpage
[download] Downloading playlist: The Kick Inside
[youtube:tab] playlist The Kick Inside: Downloading 13 videos
[download] Downloading video 1 of 13
[youtube] UPxi6EmWp-o: Downloading webpage
[download] Destination: Moving (2018 Remaster)-UPxi6EmWp-o.mp4
[download] 100% of 3.71MiB in 00:04
[download] Downloading video 2 of 13
[youtube] ArhssokTFuk: Downloading webpage
[download] Destination: The Saxophone Song (2018 Remaster)-ArhssokTFuk.mp4
[download] 100% of 4.80MiB in 00:04
[download] Downloading video 3 of 13
[youtube] uY-Z8Lte8WU: Downloading webpage

ERROR: Interrupted by user
Terminate batch job (Y/N)?
```
... Windows here... But I **did** comb through #31530 to "fix" my setup...
