### ISSUE TITLE
ERROR : Unable to extract uploader id

### ISSUE THREAD

**Issue by andresitompul** [ytdl-org/youtube-dl#31746]
iam trying to use version 2021.12.17 and run
youtube-dl and the url i wanted.

i get this error, do you have a fix for this ?

Thanks

**Comment by qmarty-ccc** [comment]
Same here:

qmarty@jupiter:/tmp$ python3 -m pip install --upgrade youtube-dl
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: youtube-dl in /usr/lib/python3/dist-packages (2021.12.17)

qmarty@jupiter:/tmp$ youtube-dl --verbose 'https://youtu.be/GmvB0VGD89w'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/GmvB0VGD89w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] GmvB0VGD89w: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by shomedas** [comment]
I am also getting the same error while trying to download any youtube video. I just installed the latest verion of yt-dl from git. 

$ youtube-dl -citw https://www.youtube.com/watch?v=tq2hI-pQwUY
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[youtube] tq2hI-pQwUY: Downloading webpage
ERROR: **Unable to extract uploader id**; please report this issue on https://yt-dl.org/bug .

With verbose on:

$ youtube-dl --verbose https://www.youtube.com/watch?v=tq2hI-pQwUY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=tq2hI-pQwUY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-5.4.0-139-generic-x86_64-with-glibc2.27
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tq2hI-pQwUY: Downloading webpage
ERROR: **Unable to extract uploader id**; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ciscfs** [comment]
Ditto for me:

% youtube-dl --verbose --no-playlist -f m4a 'https://www.youtube.com/watch?v=JFyuOEovTOE'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--no-playlist', u'-f', u'm4a', u'https://www.youtube.com/watch?v=JFyuOEovTOE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube] JFyuOEovTOE: Downloading webpage
[youtube] Downloading just video JFyuOEovTOE because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Exit 1

**Comment by nicolaasjan** [comment]
[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839).

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by ciscfs** [comment]
Good to hear that it has been fixed in the master code, but that does not help us until youtube-dl is actually updated from the broken 2021.12.17. I’m not familiar with yt-dlp, should I be?

Regards, Chris

**Comment by nicolaasjan** [comment]
> Good to hear that it has been fixed in the master code, but that does not help us until youtube-dl is actually updated from the broken 2021.12.17.

In the meantime, you could try the unofficial daily build from [here](https://github.com/ytdl-patched/youtube-dl/releases/latest).

> I’m not familiar with yt-dlp, should I be?

It's highly recommended, so just give it a try.
It has [more features](https://github.com/yt-dlp/yt-dlp#new-features) as well.

Note however, that both youtube-dl and yt-dlp suffer from yet another [YouTube throttling issue](https://github.com/yt-dlp/yt-dlp/issues/6400)...

**Comment by dirkf** [comment]
#30839.

**Comment by dirkf** [comment]
>Note however, that both youtube-dl and yt-dlp suffer from yet another YouTube throttling issue...

Both now fixed.
