### ISSUE TITLE
YouTube-DL Patched: YouTube is back to downloading at molasses speed

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#31753]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I apologize if I'm breaking a rule posting this here, but the bug tracker for the patched version demands that I test with YT-DLP. I can't test with YT-DLP, because I have a very old system and can't run YT-DLP. Which is why I'm using the patched version of YouTube-DL rather than that program If I could run YT-DLP, I'd probably be using that instead.

I don't want to start any fights, I just want to make sure that the appropriate people are aware of the fact that for the last 3-4 days now, downloading YouTube videos with the patched version of YouTube-DL has become painfully slow. It's now as slow as the official build was, back when it still worked on YouTube.

There are no errors, it just downloads VERY slowly. Other sites still work fine.

**Comment by AdalbertoLacruz** [comment]
Using --external-downloader aria2c I get a speed increase from 50K to 250K. Very slow but better.

**Comment by dirkf** [comment]
Try the current git master, or a nightly built from it. Two throttling issues were fixed in the last two commits.

**Comment by nicolaasjan** [comment]
> I can't test with YT-DLP, because I have a very old system and can't run YT-DLP. Which is why I'm using the patched version of YouTube-DL rather than that program If I could run YT-DLP, I'd probably be using that instead.

What OS do you have?

If it's Linux with an unsupported Python (≤ 3.6), then you can use the Linux standalone binary.
`https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux`

**Comment by Rekrullurker** [comment]
>Using --external-downloader aria2c I get a speed increase from 50K to 250K. Very slow but better.

Yes, I've been doing that myself. However I use a script to send the download link to a Windows GUI download manager because none of the command line downloaders I've ever been able to run has worked worth a damn. Internet Download Manager will make up to 16 connections per download, which gives me up to 1MB/s download speed. Pretty good, but not as fast as YouTube-DL's native download speed (when not throttled).

>Try the current git master, or a nightly built from it. Two throttling issues were fixed in the last two commits.

The only nightly build I know of is the patched version, and that hasn't had the latest fixes yet. I'm pretty clueless when it comes to Github. I saw YouTube-DL mentioned on the net, a Google search lead me to its page, and then the Support link lead me here. A message in one of the threads lead me to the patched version after suffering through with the last official build for almost a year. 

>What OS do you have?

This will probably open me up to ridicule, but I have a very old system that still has Windows XP on it.

Yes, I know it's not supported and is considered obsolete. but it's what I have. I don't have the money to buy a new system. At the moment, it's a struggle just to pay my bills and put food on the table. Although my current system could probably run Win7, I don't really want to wipe something that (mostly) works and start over from scratch without something to fall back on if I run into problems.

I hope to be able to cobble together a better system from junk ones I've found in the trash, but so far I haven't been able to do that. And even when I have a newer one, none of the available OS choices are all that appealing to me. Developers are already dropping support for Win7/8. I don't like the forced updates in Win10/11. And I know nothing about Linux, plus none of the scripts I've written in Windows Batch would work without being re-written from scratch. I would have to learn an entirely new scripting language, and some of my scripts are fairly long and complex. I'm a big fan of using the Choice command to make menu-driven scripts with multiple options and functions.

So for the time being, I'm limping along with an outdated system that can't run most new software. I have to make do with the few projects that will still work for me. I'm very selective about what software I download and I run *EVERYTHING* through VirusTotal, even if it comes from this site.

**Comment by dirkf** [comment]
Follow the steps suggested in #31530 to update your yt-dl.

Check out _wine_ to maintain compatibility with your batch scripts under Linux:
```
df@Spiridion:~$ uname -a
Linux Spiridion 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:00 UTC 2021 i686 i686 i686 GNU/Linux
$ ls -l yout*
-rwxrwxr-x 1 df df 1837828 Dec 16  2021 youtube-dl
lrwxrwxrwx 1 df df      19 Aug 27  2022 youtube-dl.exe -> /usr/bin/youtube-dl
$ wine cmd
Wine CMD Version 5.1.2600 (1.6.2)

Z:\home\df>dir yout*.*
Volume in drive Z has no label.
Volume Serial Number is 0000-0000

Directory of Z:\home\df

16/12/2021     19:01     1,837,828  youtube-dl
09/01/2022     20:55           332  youtube-dl.exe
       2 files                1,838,160 bytes
       0 directories         57,905,152 bytes free


Z:\home\df>
```

**Comment by Vangelis66** [comment]
@Rekrullurker 

The latest "daily/nightly" build from below: 
https://github.com/ytdl-patched/youtube-dl/tags
i.e. [2023.03.04.1919](https://github.com/ytdl-patched/youtube-dl/releases/tag/2023.03.04.1919) has the **two youtube-throttling fixes** mentioned above incorporated... 
If you have already downloaded a previous build, these come with **internal updating enabled**, so, alternatively, you could just issue (cmd prompt): 

`youtube-dl -vU` and you'll be updated to latest (working) build (and so on in the future) ...

NB: The YT throttling issues are fixed if you use `youtube-dl` **itself** to fetch; if your scripts simply use **it** to get the download URLs and then pass them along to a different downloading tool/app, throttling may persist (e.g. see [here](https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1454288724)) ...

OT
You don't have to apologise for using the OS of your choice 😄 ; vendor support isn't the top priority here, since `youtube-dl` strives to continue supporting **both** py2.7.18/py3.4.4 (EoS for **XP**) ... 

If you want, you can join the **MSFN Forums**, where large and "healthy", non-judgemental, communities exist, consisting of members who are still (via choice/necessity, etc.) on **WinOSes not supported anymore by Microsoft**; once there, you may find that `yt-dlp` has also been backported to XP, at least until **py3.8** support has been removed by downstream...
/OT

Best regards

**Comment by nicolaasjan** [comment]
(OT)
XP backport is done by me.
See [this thread](https://msfn.org/board/topic/184368-who-here-has-a-youtube-dl-compile-for-winxp/); sign in and you'll find a downloadlink in my signature.

It has a few false positives on VirusTotal, but that's because I use the official PyInstaller and not [the one yt-dlp uses](https://yt-dlp.github.io/Pyinstaller-Builds/x86_64/pyinstaller-5.8.0-py3-none-any.whl), which doesn't leave traces that could be confused with malware)
See also [this issue](https://github.com/yt-dlp/yt-dlp/issues/25).

**Comment by fbhradec** [comment]
I'm getting the same issue and a really old arch linux install (haven't updated it in 6 months!). 
Using  `--external-downloader aria2c` got me up to 256Kb/sec, which is much better than 64kb/sec! Thanks for the tip! 

Running the latest `master` from `git`, with `python 3.9.1`.

**Comment by dirkf** [comment]
If you really have the latest yt-dl master, please show your verbose log (using the native downloaders) with this behaviour. It ran at many MB/s on the CI test host.

**Comment by dirkf** [comment]
This seems to be working now in the git master version.
