### ISSUE TITLE
ERROR: Unable to extract uploader id !! Urgend !!

### ISSUE THREAD

**Issue by ChristianErdtmann** [ytdl-org/youtube-dl#31871]
I try the following:
       # Create pafy object for the video
        video_url = f'https://www.youtube.com/watch?v={video_id}'
        video = pafy.new(video_url)

        # Get the best available audio and video streams
        best_audio = video.getbestaudio()
        best_video = video.getbestvideo()

        # Download the audio and video streams
        best_audio.download()
        best_video.download()

The Video ID is: HNjW0C1rvmc 

Console Output:
New video found: HNjW0C1rvmc (2023-03-16T08:23:05Z)
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error downloading the video: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

can you please solve this problem. Tried it with different channels and alltimes the same error.

**Comment by dirkf** [comment]
I'm going to assume hopefully that you eventually, by studying #30839 or otherwise, found #31530 and applied one of the recommended solutions. If not, that was what you should have done.

_pafy_ belongs to another project and really you should raise your problem there, but as #30839 says, if you can reproduce the error with a plain youtube-dl command, post the verbose log in a new issue, or in #31872 (I'll reopen it if so).
