### ISSUE TITLE
Is there a regex for all the supported sites? (No)

### ISSUE THREAD

**Issue by Wamy-Dev** [ytdl-org/youtube-dl#31991]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I was wondering if there is a regex with all the websites supported by youtube-dl? I couldn't find anything in the documentation or in the issues here. If there is not, I think we should make one. This way it is a lot easier for us developers to use all the sites rather than just defining specifically what sites we want to use. Now, I do realize that this regex may not be very performant due to its size but maybe just a list of regex for each site would be sufficient. Whenever a new site is submitted, we should require a regex to be written for it.

**Comment by october262** [comment]
see here - https://ytdl-org.github.io/youtube-dl/supportedsites.html
note that not all sites in this list might not work.

**Comment by Wamy-Dev** [comment]
I understand that there is a list of the sites, but I am looking for a regex for each one.

**Comment by dirkf** [comment]
What would you possibly do with such a gigantic pattern even if it could be created?

Look in the `extractors` directory, count the `.py` files, then imagine that many of those contain several IE classes, each with a URL pattern. Moreover, since the regexes usually contain a `(?P<id>...)` sub-pattern, a simple-minded idea of importing all the IE classes and joining any regexes with `|` is doomed.

In any case, there is not necessarily a URL pattern for every supported site. yt-dl calls the `InfoExtractor.suitable()` class method for each IE class to find an IE class that supports a given URL. The default for this is to match the class's `_VALID_URL`, but it could, say, download the page content for the URL and test that instead. The yt-dl module doesn't expose how it decides that a particular IE should handle a particular URL, though there is a reasonable use case where you can say "only try this specified IE, and give up if it isn't suitable".

I think you need to explain what you're trying to do, because the question implies that you don't quite understand how yt-dl works. The FAQ section BUGS gives advice on formulating a question for an issue in terms of your actual problem rather some subsidiary problem that results from an assumption about the best way to solve the original problem.

**Comment by Wamy-Dev** [comment]
Okay, yeah a massive pattern would not be to what I need. Like I said before a list of all the regex per site would be nice. 

I am using youtubedl over nodejs and it would be a nice to have thing. I have to match urls to be able to use youtubedl to make sure it would work as youtubedl is not the only function I have built into this url matcher. It's not a big deal, I just think it would be a good thing to require for every site.

**Comment by dirkf** [comment]
Try using yt-dl on the URL, using either CLI or a Python wrapper calling into the `youtube_dl` module; if it fails, use one of your other tactics.

You could extract a list of URL patterns for working IE classes using a Python wrapper, but you wouldn't be able to use them easily in JS because the RE syntax is subtly different. Matching the URL (or more generally, passing the `suitable()` method) still doesn't guarantee that yt-dl will succeed in processing the media at the given URL.

**Comment by dirkf** [comment]
Closing as answered, but please open a new issue if required after considering the response.
