### ISSUE TITLE
This program doesn't work on Mac for me

### ISSUE THREAD

**Issue by jadenquinn** [ytdl-org/youtube-dl#32132]
I know this is probably a VERY dumb issue, I don't usually use CLI programs so I'm still kinda new to this, but I install youtube-dl, it's in the bin folder or whatever like it should be so I can just run it anywhere, so I just type "youtube-dl https://www.youtube.com/watch?v=PIuAFrLeXfY" and that didn't work, so I tried "youtube-dl URL https://www.youtube.com/watch?v=PIuAFrLeXfY", and that gave me the same error, I'm probably missing some kind of library, but I have both Python 2.7 and 3 installed on my system (for compatibility, if you can believe it), so I have literally no clue what I'm doing wrong. Every article and even the MD for this repository says to do EXACTLY WHAT I DID, so yea.

Here's the error:

jaden@UltraYummyBlade ~ % youtube-dl https://www.youtube.com/watch?v=PIuAFrLeXfY
zsh: no matches found: https://www.youtube.com/watch?v=PIuAFrLeXfY

Here's the other thing I tried:

jaden@UltraYummyBlade ~ % youtube-dl URL  https://www.youtube.com/watch?v=PIuAFrLeXfY
zsh: no matches found: https://www.youtube.com/watch?v=PIuAFrLeXfY

Help..? Pweeze?

**Comment by dirkf** [comment]
In _zsh_ `?` is a special character. Enclose the URL in single quotes: `'URL'`.

>Every article and even the MD for this repository says ...

to quote the URL if it might contain special characters, using the quoting convention for your shell. `&` is special in a POSIX-conformant shell. `=` is special in Windows _cmd_. Basically, always quote the URL so that you know that isn't going to be the problem when something doesn't work.
