### ISSUE TITLE
Download youtube video from direct URL

### ISSUE THREAD

**Issue by anonwins** [ytdl-org/youtube-dl#32239]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello. Is there a way to download a youtube video from a direct URL? Let's say I saved the url using --get-url and I want to download it without re-extracting the info. This is to save time. Thanks.

**Comment by dirkf** [comment]
If you have an extracted media URL, you may be able to download it directly using _curl_, _wget_, etc, or just your browser. If that doesn't work, the media URL needs additional parameters (or has expired) and you have to repeat the extraction and download within yt-dl.

Instead of saving the URL alone, you could save the info as a JSON file that can be passed to yt-dl so that it goes straight to downloading without re-extracting the original page: however that doesn't help if the extracted media URL(s) in the JSON file have expired.

**Comment by anonwins** [comment]
Actually yes I did use curl, but youtube throttles the connection speed. So I used yt-dlp and set --http-chunk-size 10M and just fed the direct url to it. it works and bypasses the throttling. i don't know if youtube-dl will do the same though.

**Comment by dirkf** [comment]
That's an example of what I described as "additional parameters". I expect yt-dl to work in the same way: yt-dl master incorporates the recent anti-throttling measures from yt-dlp.

It's always safer to let the program do its work, or otherwise assume responsibility for your desired behaviour by embedding the yt-dl module in y9our own Python program.

**Comment by Khmys** [comment]
Hitilafu:  [0;31mERROR: [0m Unable to extract  [0;34muploader id [0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the verbose flag and include its complete output.
