### ISSUE TITLE
make youtube_dl return 1 formad with bestvideo as formad  setting

### ISSUE THREAD

**Issue by thedtvn** [ytdl-org/youtube-dl#32320]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

can I make youtube_dl return 1 formad with `bestaudio/best` as format it can save a lot of load time
```py
with youtube_dl.YoutubeDL({'format': 'bestaudio/best', "quiet": True, 'noplaylist': True}) as ydl:
      info = ydl.extract_info(pageurl, ie_key="Youtube", download=False)
      print(len(info["formats"])) # 1 
```

**Comment by dirkf** [comment]
It does return one format, no? The available formats have to be processed to identify either the `bestaudio`, or the `best` combined format if no audio-only formats are available.

Otherwise you may hope that a certain site always has a format with a certain `format_id`, but yt-dl still has to extract the details of that format (media link, etc).

**Comment by thedtvn** [comment]
> It does return one format, no? The available formats have to be processed to identify either the `bestaudio`, or the `best` combined format if no audio-only formats are available.
> 
> 
> 
> Otherwise you may hope that a certain site always has a format with a certain `format_id`, but yt-dl still has to extract the details of that format (media link, etc).

can we add number formad return ?

**Comment by dirkf** [comment]
You'll have to explain more clearly what it is that you think ought to happen and isn't now. Example commands with verbose logs are likely to be helpful.

**Comment by dirkf** [comment]
If a single format has been selected and found, the data items for the selected format are already copied into the top level of the `info` dict. So you can just ignore the `formats` key, or even `del info['formats'].

Asking for just the resulting format wouldn't make the program faster because it has to process all the available formats before selecting the one (if any) that matches the (possibly implicit) format selection option.

If the selected format has separate video and audio formats, the details are in `info[`requested_formats`] instead.

**Comment by thedtvn** [comment]
> If a single format has been selected and found, the data items for the selected format are already copied into the top level of the `info` dict. So you can just ignore the `formats` key, or even `del info['formats'].
> 
> 
> 
> Asking for just the resulting format wouldn't make the program faster because it has to process all the available formats before selecting the one (if any) that matches the (possibly implicit) format selection option.
> 
> 
> 
> If the selected format has separate video and audio formats, the details are in `info[`requested_formats`] instead.
> 
> 
> 
> 

thank
