### ISSUE TITLE
Why does YouTube-DL keep getting throttled by YouTube?

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#32355]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Since the official YouTube-DL hasn't been updated in a year and half, I've been using the patched version. I don't use YT-DLP because I have an OLD computer and can NOT run it. The program will NOT execute on my system. At this time, it is a literal impossibility for me to use YT-DLP. This is why I use the patched version of YouTube-DL.

Can someone please explain to me in semi-technical terms why the patched versions get throttled by YouTube every other week or so? 

It will be working fine, then one day I'll try to download a video, it throws up an error, says downloading might be throttled and sure enough, it downloads at a snail's pace. A couple days go by, with me downloading the newest release each night and usually after a couple of them, the issue goes away and it starts downloading videos at full speed again. It works for a week or two, then the same thing happens again. Sometimes it gives me an error and sometimes it just downloads very slowly.

Obviously I know something is changing that causes the throttling, what I'd like to know is what, and why YouTube-DL can't cope with it.

I have Opera 36.0.2130.80, which is 6-7 years old at this point, installed on this (OLD) computer, and it still views YouTube videos just fine.

So how is it that a browser that is over half a decade old can cope with whatever changes YouTube is making, but a current program that's updated nightly, breaks every couple of weeks?

I'm not trying to be a jerk here, I'd honestly like to understand why it's so hard for YouTube-DL to handle YouTube's changes.

**Comment by dirkf** [comment]
Your oldish Opera has a reasonably capable JavaScript interpreter, although it probably barfs a lot on modern websites. YT doesn't seem to use the latest JS syntax, presumably because it would then fail to show ads on old mobile phone browsers that aren't updatable.

There is no third-party JS interpreter that can be reliably integrated or distributed with yt-dl (because of platform dependencies, functionality and licensing issues).

Therefore yt-dl has a JSInterp module that understands just enough JS to run the signature and n-sig processing. When, every so often, YT sends a new player with different JS code, it may use some syntax that we didn't support, or it may expose a bug in what the yt-dl JS module was supposed to support. You can study the relevant issues and commits to see examples of both cases. The [test script](https://github.com/ytdl-org/youtube-dl/blob/master/test/test_jsinterp.py) may also be enlightening.

JavaScript was invented in a week by Brendan Eich at Netscape and combines what he was asked for (a scripting language that looks like Java) with what he wanted (Scheme, a then-fashionable Lisp dialect popularised in a [classic MIT textbook (PDF)](https://web.mit.edu/6.001/6.037/sicp.pdf)). If only he'd been allowed to use a plain Lisp, we'd all have been much better off.

**Comment by Rekrullurker** [comment]
Thank you for the explanation. You're also correct in that Opera has problems with a lot of web sites. In fact, even newer browsers that were back-ported to my old system, have problems on a lot of websites. Actually, that's probably the biggest problem I face in using an outdated system/OS.

I want something newer/faster, but don't have any spare money at the moment. I also don't particularly like my OS choices. I don't like the fact that Win10/11 gives MS carte blanche to change the OS as it sees fit, and I know nothing about Linux. Plus some of the programs and scripts that I use daily won't work in Linux.

**Comment by dirkf** [comment]
Sites like msfn.org may be relevant.

**Comment by Rekrullurker** [comment]
Just in case it wasn't clear, YouTube downloads are being throttled right now, and have been for the past couple weeks or so. I just tried today's release binary, but there's no change. 

I'm not complaining, I understand the problem of trying to keep a program like this compatible with all the sites it supports, and I'm grateful that it exists at all, I just wanted to make someone was aware that it was happening. I know I can assume that someone else has mentioned it, but just in case they haven't...

**Comment by dirkf** [comment]
No, show us the verbose log. If you're using the unofficial nightly build, it wasn't updating properly, but I set up an official one that does: see #31530.

**Comment by Rekrullurker** [comment]
Yes, I'm using the unofficial nightly build, AKA the "patched" version available here;

https://github.com/ytdl-patched/youtube-dl/releases

I tried reading the linked thread and got completely lost in the discussions about merges, pulls requests, fixes, yt-dlp, official versus unofficial builds etc. To be honest, Github somewhat confuses me. 

Here's where I'm coming from:

I have an old system that can run YouTuve-DL, but cannot run YT-DLP, which is why I stick to YouTube-DL. For a long time I was using the official version, updating the Window binary as needed. Then the official releases stopped coming and downloads from YouTube got throttled. I got pointed to the link above, I downloaded that version, downloads got fast again. When downloads would get throttled, I'd download the latest nightly build and downloads would usually get fast again. A couple weeks ago downloads started getting throttled. I've been manually downloading the nightly builds each day in the hope that the issue would be fixed.

It's not complaining about not being able to extract the uploader ID. Instead it says "Unable to extract Initial JS player n function alias".

I tried to attach a log file created with the verbose option, but Github doesn't like my outdated browser. So I'll post it below;

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=UGceYMpg5fM', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2023.07.09.1919 (single file build)
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-XP-5.1.2600-SP3 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg N-105053-gc417616-Reino
[debug] Proxy map: {}
[youtube] UGceYMpg5fM: Downloading webpage
[youtube] UGceYMpg5fM: Downloading player 1dda5629
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Wsa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\youtube.py", line 1672, in _n_descramble
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\youtube.py", line 1644, in _extract_n_function
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\youtube.py", line 1629, in _extract_n_function_name
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\common.py", line 1013, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Wsa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr5---sn-j5caxoxu-i2ol.googlevideo.com/videoplayback?expire=1688967855&ei=T0arZJm8Csaj_9EP09-vgAI&ip=67.84.74.123&id=o-AKgrGCuc3DXIqD3yFAi3HlXU8xVKmy1ChcBYCMJV5moN&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=Vs&mm=31%2C29&mn=sn-j5caxoxu-i2ol%2Csn-ab5sznzs&ms=au%2Crdu&mv=m&mvi=5&pl=22&initcwndbps=1537500&spc=Ul2Sqzix3F0TSVvR_vQJjoP7HMgkDdR7hZvBwmWxBQ&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Ri-8O61n9t_zaJRVmrW_fzYO&gir=yes&clen=148007962&dur=753.040&lmt=1688925458337322&mt=1688945830&fvip=4&keepalive=yes&fexp=24007246%2C24363392&c=WEB&txp=5535434&n=O5oeuLYijyVvcpjw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJ7nld763wv965-_S-slTSKhqpP8eU9g3nv4t6it56SQCIHIsDtR8CHHkgE4J742OuewmeXtTI5letPOjsaqSwtDI&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMF98q_RNY6TascI_hpGFGeYxXT9f0EEyxcs7au0AR2LAiAc7NjmMSdaZynahYUW8-8zJRcZHoYYGRYEdF76XI_U9g%3D%3D'
[dashsegments] Total fragments: 15
[download] Destination: 10 Awful Plot Twists That Completely Ruined Great Movies-UGceYMpg5fM.f137.mp4

[download]   0.0% of ~150.00MiB at  3.76KiB/s ETA 11:19:59
[download]   0.0% of ~150.00MiB at 11.29KiB/s ETA 03:46:39
ERROR: Interrupted by user

**Comment by dirkf** [comment]
In the text where you were directed to that repo, there is now a link to our new nightly build repo. Use that. See also #31585.

The fix needed for this player hasn't propagated to the unofficial nightly build despite the build date. The page extracts OK with master.

**Comment by Vangelis66** [comment]
> I have an old system that can run YouTube-DL, but cannot run YT-DLP, which is why I stick to YouTube-DL.

> Sites like msfn.org may be relevant

@Rekrullurker , **dirkf** is very right! 👍 If you do subscribe there, you'll find a welcoming and non-judging community of users of older Windows systems (Win2k, WinXP, WinVista, Win7, etc.), and a whole new world will be opened to you with regards to browser options compatible with the modern, **JS-bloated**, monster of a web 😠 ...

There's no need to use the out-dated **Opera 36** today - **roytam1**'s browsers (New Moon **28**, Serpent **52**, Serpent **55**) and the **360EE mods** based on **Chromium 86** are the way to go...

Also, @nicolaasjan provides (via links in his **MSFN signature**) constantly updated `youtube-dl.exe` win32 binaries (XP-compatible) and, what's more, he even provides XP SP3 compatible (SSE2 instruction set required) `yt-dlp.exe` builds; these use a community produced **CPython 3.8** (soon **3.9**) iterations compatible with XP SP3/Vista SP2; this isn't a plug to switch to `yt-dlp`, just a FYI as to your available options under WinXP 😄 ...
`End-of-Life` (EoL) is a term invented by the OS vendor, when it should have been `End-of-Support` (EoS); the OS doesn't have to stop "living" just because MS (and their partners) won't support it...
