### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by guidoenr** [ytdl-org/youtube-dl#32378]
Hey Guys, how is it going?

Today i tried to use your software in the simplest way possible:

```bash
youtube-dl https://www.youtube.com/watch?v=Doiij_7QxM4
```

And i got this error message:
```bash
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
└─$ youtube-dl --version
2021.12.17
```

**Comment by Kir4R00t** [comment]
I'm making a discord bot right now I got same error while trying to use this

**Comment by GreatestFool** [comment]
@dirkf Considering how many other issues which have less information than this that stay open, and the fact that this package, which is named after the service it's grabbing from, is currently failing at its primary purpose, I'd say it's somewhat important to verify if this is a one-off issue or not _before_ being irresponsible and simply closing it immediately. Please just re-open this issue thread and save yourself the trouble of more issue threads being made instead of just working in this one.

Regardless, here is the very same error that you would likely be able to get yourself if you would've tried:
```
youtube-dl --verbose 'https://www.youtube.com/watch?v=qY03H-RRW-o'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=qY03H-RRW-o']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-6.3.9-arch1-1-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] qY03H-RRW-o: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The error may have something to do with YouTube's change to using at-symbols.

**Comment by guidoenr** [comment]
Hey guys. 

Exactly, that is the same error. Sorry for not passing you the output with the --verbose flag.

So, this is due to a Youtube new change. Nothing to do.

thanks :)

**Comment by Vangelis66** [comment]
People filling issues in this tracker should have first heeded pinned issued #30839 : 

![30839](https://github.com/ytdl-org/youtube-dl/assets/9669492/cdacdd52-9008-4014-81ec-1cdbd17c366f)

Inside that, there is a detailed guide one should follow to make sure the issue one is about to file isn't a redundant duplicate one, and towards the end there's also a list of `KNOWN ISSUES`, fixed already in the `master` branch code... Guess what's the first one there 😜 ...

> I'd say it's somewhat important to verify if this is a one-off issue or not **before being irresponsible** and simply closing it immediately.

... And who's acting irresponsibly here? Certainly not the repo maintainer... OP didn't even make the simple effort to follow the pinned issue's directions (e.g., where's the `New issue` template in the first post?) ... 

Everything has been made very clear beforehand: 

> If you raise an issue without using the chooser, or **if you ignore or misuse the chosen template**, your issue is likely **either to be a duplicate of an issue that is already being handled**, or to lack sufficient supporting information to solve the problem. **Maintainers may close such issues without prejudice.**

> Nothing to do.

Wrong, again 😠 ... Since this is a dupe of #31530 (from as early as **Feb 16th 2023** !), one should "do" the offered solutions [here](https://github.com/ytdl-org/youtube-dl/issues/31530#Description) and [here](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611) ...

**Comment by dirkf** [comment]
Somehow my post that reminded OP of the pinned issue went missing ...
