### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by elektropepega** [ytdl-org/youtube-dl#32460]
2023-07-20 17:18:57 INFO     discord.voice_client Connecting to voice...
2023-07-20 17:18:57 INFO     discord.voice_client Starting voice handshake... (connection attempt 1)
2023-07-20 17:18:57 INFO     discord.voice_client Voice handshake complete. Endpoint found frankfurt8068.discord.media
[youtube] u0BhX3tCzAY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !

**Comment by dirkf** [comment]
Clearly. Have you actually read the pinned/linked issue?

**Where this problem is listed**

**Comment by Espionage724** [comment]
> Clearly. Have you actually read the pinned/linked issue?
> 
> **Where this problem is listed**

You are hindering people needlessly, why are you a contributor? I haven't used youtube-dl in years, and wanted to just a minute ago. I got this same error. I came to GitHub, searched "uploader id", and this was the first issue listed. And instead of a straight answer, you pull some roundabout shenagains that I'd expect from a toddler. Come on.

https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by ness001** [comment]
> 

Love your words

**Comment by dirkf** [comment]
You get the support you pay for. No-one is helped by opening duplicate issues for known problems. If you have a problem, your contribution to making support possible is to follow the reporting procedure, and that applies to [snarky commenters](https://github.com/ytdl-org/youtube-dl/issues/32460#issuecomment-1644487971) as well. TBH this issue should have been closed as spam, and any response at all went beyond that.

OP was clearly asked to review the pinned issue before opening a new issue, and again after doing so, but **clearly had not** since it covers several points relevant to the problem, none of which were reflected in the creation of the issue:
* how to ensure that one's issue uses the correct template
* the need to complete that template
* how to report an issue when yt-dl is being invoked by another program
* how to find an existing issue mired in idiotic duplicates
* most importantly in this case, the actual problem and a link to the master issue for it, which obviates the previous points.

Anyone can fork the project and support their fork if they disagree with the support policy here, but others who have done so have a [still stricter policy](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=triage%2Csite-bug&projects=&template=1_broken_site.yml).

>DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
>Fill all fields even if you think it is irrelevant for the issue
>[ ] I understand that I will be blocked if I intentionally remove or skip any mandatory* field *
