### ISSUE TITLE
match filter for percentage watched / watch progress

### ISSUE THREAD

**Issue by ohsix** [ytdl-org/youtube-dl#32519]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I've got some large playlists on youtube that I've incidentally watched large portions of by chance. finding videos in the playlist that haven't been watched yet is time consuming. if the match filter could check the video playback state (never played, percentage played over/under x), it would be trivial

with --playlist-random & --max-downloads I could quickly work through them without getting the playback indicator on youtube too far out of whack

thank you for your time

**Comment by dirkf** [comment]
Generally, including for YT, yt-dl doesn't currently extract any "amount watched" data. You can mark a video as "watched" when yt-dl` is given login data, but even excluding "watched" videos requires the use of `--download-archive ...` since the corresponding site data isn't extracted (#24467).

The required data may be available in some form: someone would have to research this. Then we would have to decide whether to add support for the necessary metadata to the yt-dl framework. Finally support for that would have to be added to the YT extractor.

**Comment by dirkf** [comment]
If someone offers a plausible PR to implement this request, or even suggests a researched design that could be implemented, the issue can be reactivated. Meanwhile, no.
