### ISSUE TITLE
How do you use thing thing on Linux?

### ISSUE THREAD

**Issue by cristi-neagu** [ytdl-org/youtube-dl#32551]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How are you suppose to use this thing on Linux? All I get is:
```
  File "/usr/local/bin/youtube-dl", line 2
    PK
SyntaxError: source code cannot contain null bytes
```

I modified the command given in the readme (for obvious reasons). First I got the latest release on here, then I got the nightly build. Modified the shebang to point to the correct Python (it wants python3, not just python), and both the latest release and the nightly build behave exactly the same. What am I missing here?

Thanks.

**Comment by dirkf** [comment]
You have probably corrupted the download when you changed the shebang. yt-dl is a Python program. It expects to be run with `python`.

Check that the unmodified program runs with `python3 youtube-dl --version`.

If that works, either
* find a way to have a program called `python` in your `PATH` (eg symlink manually or with a package called `python-is-python3` if available), or
* edit the shebang correctly (an example script is hidden somewhere in #31530), or
* install the program in a different way, such as using _pip_ (again, see #31530).

**Comment by cristi-neagu** [comment]
Thank you for the response @dirkf. Yep, that was it. Looks like I corrupted the file. I did try to run it with python3, but it was already corrupted so was giving the same response. Thanks.

**Comment by AverseABFun** [comment]
I'm glad it was fixed, but I noticed that that looks oddly like the signature of a ZIP file. It's too late now, but something got screwed up and you were trying to run a ZIP file?

**Comment by cristi-neagu** [comment]
No, I was running the right file, I just wasn't running it right.

**Comment by AverseABFun** [comment]
What do you mean?

**Comment by dirkf** [comment]
The zipfile signature is expected. [Python knows how to execute a zip file](https://docs.python.org/2/using/cmdline.html#command-line).

>When invoking Python, you may specify any of these options:
>
>python [-bBdEiOQsRStuUvVWxX3?] [-c command | -m module-name | script | - ] [args]
> 
> ...
>    When called with a file name argument or with a file as standard input, it reads and executes a script from that file.
>...
>\<script>
>
>    Execute the Python code contained in script, which must be a filesystem path (absolute or relative) referring to either a Python file, a directory containing a __main__.py file, or a zipfile containing a __main__.py file.
>
>    If this option is given, the first element of sys.argv will be the script name as given on the command line.
>...
>    If the script name refers to a directory or zipfile, the script name is added to the start of sys.path and the __main__.py file in that location is executed as the __main__ module.
>...

A file consisting of a Unix shebang (eg, `#!/usr/bin/python`) line followed by a zipfile as above, and marked as executable, is executed in a Unix-style OS [like this](https://stackoverflow.com/questions/3009192/how-does-the-shebang-work): the `exec()` (or similar) system call reads the shebang and runs the Python program (interpreter) specified there with the name of the file as its argument; since [a valid zipfile can have arbitrary data preceding the zipfile signature (`PK...`)](https://en.wikipedia.org/wiki/ZIP_%28file_format%29#Combination_with_other_file_formats), the shebang line is ignored by Python when executing the zipfile.

Windows has (or used to have) some support for shebang, or magic number, file type identification in the registry schema underlying Explorer and the `ShellExecute()` API, which is a higher level than Unix `exec()` (corresponding to `CreateProcess()`). But I don't recall the details, or whether it was actually used. For Windows, we have to use different bundling techniques to make a single yt-dl program file.

**Comment by AverseABFun** [comment]
Ohh, sorry. Unfamiliar with that. Ignore me XD
