### ISSUE TITLE
Getting error while getting facebook video data

### ISSUE THREAD

**Issue by vinit2510** [ytdl-org/youtube-dl#32587]
## Checklist

- [X] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I want to fetch Facebook video data, but I have been getting this error for 1 month.

ERROR:
Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

CODE:
ydl = youtube_dl.YoutubeDL()
result = ydl.extract_info(url, download=False)

**Comment by dirkf** [comment]
This text is in the error message for **a reason**:
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

Also, you have opened a question instead of a bug report. You appear to have ignored pinned issue #30839 whose title includes `THIS MEANS YOU!` for **a reason**. Review this issue.

If you study your verbose output, you will probably find, following the guidance there, that your problem is an existing issue. Otherwise, open a full bug report according to #30839.
