### ISSUE TITLE
Youtube-dl Showing Errors

### ISSUE THREAD

**Issue by Ermiasmarino** [ytdl-org/youtube-dl#32636]
## Checklist

- [ ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I installed youtube-dl on my Mac using curl, but I am getting the following errors whenever I try to interact with it on the Terminal: 

/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

I tried to search for the solution online but I couldn't find it. This is the closest I got. Help.

**Comment by dirkf** [comment]
1. Review #30839.
2. Make sure to install the nightly version rather than the 2021.12 release.
3. Note #32499 which affects downloads from YouTube for the moment, or use _yt-dlp_.
4. Make sure that you have made the downloaded file executable (use `chmod` as in the installation instructions).
5. Make sure that you have a `python` command on your `PATH`, eg by symlinking (as admin)`/usr/local/bin/python` to your `python3`, or run the program as `python3 /usr/local/bin/youtube-dl ...` (this will also work if your problem is 4 above).
6. Remember that modern MacOS versions run the _zsh_ shell in Terminal, where `?` as well as `&` are special characters: always 'quote' URLs passed to yt-dl.

**Comment by Rushilwiz** [comment]
Yeah, look at [the website](https://yt-dl.org) you're downloading from, looks like they just got sued.
