### ISSUE TITLE
Error when download video, "Unable to extract uploader id"

### ISSUE THREAD

**Issue by Sepehr0Day** [ytdl-org/youtube-dl#32719]
My code :
```python
import youtube_dl

video_url = "https://www.youtube.com/watch?v=w9Fcgdlw-Nc"

desired_format = 'mp4'

ydl_opts = {
    'format': desired_format,
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([video_url])

```

Error :
```text
PS C:\Users\sepeh\Desktop\Bot> & "C:/Program Files/Python39/python.exe" c:/Users/sepeh/Desktop/Bot/main.py
[youtube] w9Fcgdlw-Nc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sepeh\Desktop\Bot\main.py", line 12, in <module>
    ydl.download([video_url])
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\sepeh\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS C:\Users\sepeh\Desktop\Bot> 
```

Thanks in advance🙏

**Comment by dirkf** [comment]
#30839 links to your solution.

What part of

>READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!

was hard to understand? How can it be made more obvious?

**Comment by d3vpunk** [comment]
logged in just to to downvote because the tone of @dirkf

**Comment by dirkf** [comment]
@d3vpunk especially, and also @antemasqued, @mat926, @JonnyKong, @danieltanfh95:
>... How can it be made more obvious?

This was not just a vexed reaction to a user who hadn't been able to make use of what appeared to be well sign-posted help, but also a serious question. If available help can be made more obvious, everyone benefits (as explained in the link "Why is all this important for the project?" from #30839 itself).

I'd like to have learned why OP wasn't able to find the help so as to improve it, since it surely can't just have been laziness or stupidity. Maybe people stabbing at tiny handheld screens can't see the tracker page fully? That also applies to @uilianries, @harveenchadha, @mscheper, who "like"d OP but presumably had the same trouble since none of them pointed out where to find the explanation and solution of the problem.

**Comment by danieltanfh95** [comment]
Unfortunately it is not immediately clear what exactly is wrong with this post. Falsely linking to the general post about how to post issues doesn't help.

It would be great if say, there's an order list of items to do while posting an issue and quoting the direct item that the poster did not perform. 

In this case I suspect it's a case of `Don't raise a new issue if an existing issue matches your problem.`. However the problem is likely because the suggested solution (which is very hard to look for, under hidden comments and SO comments), is to use another fork.

**Comment by dirkf** [comment]
The *actual error message* that was reported is listed in the [pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839) as a *known issue* that is fixed in the nightly build (which is linked).

That's why I asked OP to read the pinned issue, and why I wanted to understand what prevents people from doing so. OP showed no sign of having followed the pinned issue by completing the relevant issue template: doing so would have led to the master issue where the same solution is recommended. The pinned issue tries to help people follow the template that was established years ago, because there are ways of opening issues that don't present the issue template. 

While some details of [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html) may be a bit dated, or not my personal style, the idea that someone who wants free help with free software should prepare properly before actually asking for help seems quite fair; at a minimum that should mean following the process of the party offering the help.

**Comment by antemasqued** [comment]
> @d3vpunk especially, and also @antemasqued, @mat926, @JonnyKong, @danieltanfh95:
> 
> > ... How can it be made more obvious?
> 
> This was not just a vexed reaction to a user who hadn't been able to make use of what appeared to be well sign-posted help, but also a serious question. If available help can be made more obvious, everyone benefits (as explained in the link "Why is all this important for the project?" from #30839 itself).
> 
> I'd like to have learned why OP wasn't able to find the help so as to improve it, since it surely can't just have been laziness or stupidity. Maybe people stabbing at tiny handheld screens can't see the tracker page fully? That also applies to @uilianries, @harveenchadha, @mscheper, who "like"d OP but presumably had the same trouble since none of them pointed out where to find the explanation and solution of the problem.

The fact that you're @-ing people who reacted to your post makes me understand further how poor your attitude is towards questions. It's honestly a bad reflection the project, and worse for yourself as it paints you as a grifter. I'm not saying this to insult you, but rather to help you, @dirkf, as you seem to lack the self awareness for this kind of reflection. While I was searching for the same answer as OP I came across some of your other replies to other users. I suspect you might think of yourself as some tortured, high intelligence, low respected maintainer. You're just out here in the trenches you know? Doing the hard work. Might be true, but see my first point.

Everyone think's they're Linus and no one wants to admit they're actually just Stallman.

Cheers.

**Comment by dirkf** [comment]
Happy to be either or, fortunately for yt-dl contributors who don't want to be flamed either à la Torvalds or à la Stallman, neither.

> While I was searching for the same answer as OP ...

Did that not work, and, if not, why?
* did you read the pinned issue and find the **Known Issue**, or had that not yet been added?
* did you read the pinned issue and follow the searching advice?
* did you not see the pinned issue at all?

This is the sort of thing I wanted to find out.

Anyone who bothered to log in to post a reaction should expect to be asked about that reaction: especially dv3punk, who wrote to say so, then deleted the comment. Normally posting reactions in a closed duplicate issue is a waste of time, but that comment alerted me. Instead, if you think the issue is not a duplicate or should be reopened for other reasons, please say so, or open a replacement issue if the context of the issue (yt-dl version, site structure) has changed sufficiently; otherwise it's dropping pebbles down a well.

OTOH, anyone with the attitude that it's acceptable to snipe without contributing to the project, whether by making a PR or just by following the project's issue workflow, arguably deserves to be excluded. See "... someone who wants free help with free software ..." above.

In a related project the maintainer makes you check a box that says "I understand that I will be banned [if I fail to complete the issue template]".

**Comment by d3vpunk** [comment]
@dirkf i found it a little rude.

to deescalate: thx for the work you invest in the project
