### ISSUE TITLE
Android UserLAnd support

### ISSUE THREAD

**Issue by Marty-coder-dev** [ytdl-org/youtube-dl#32711]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Absolutely nothing

## Description

I've tried installing on android but after installation on each of the subsystems it never actually downloaded ANYTHING.
Please review this.

**Comment by dirkf** [comment]
How did you try to install it?

#30839 tells you how to search.
#30860 gives example commands for an Android installation.

In principle:
* you need a package (or packages) that gives you a command shell in a terminal "window" with a supported Python;
* then follow the instructions for a Unix-like (POSIX) installation;
* use the [nightly build](https://github.com/ytdl-org/youtube-dl/issues/32595#issuecomment-1762630843) rather than the 2021.12.17 release - you would have to modify the final `pip` command in the above example to do that.

If you try to run the POSIX self-extracting build and no supported Python on your `PATH` is named `python`, you will need to make a link to a supported Python (maybe called `python3`) with that name in the `PATH`.

Having done any of this, you should have some terminal text to paste in the issue to illustrate any problem that occurs.

**Comment by dirkf** [comment]
@Marty-coder-dev ?

**Comment by Marty-coder-dev** [comment]
Well, after trying all that, this still doesn't work, but it might be the problem that I've modified it. The modification makes it slightly bigger on the screen and the input is autocorrected once it tries to execute the command with an error and it doesn't show the autocorrected things, I could add the special commands, that might be the problem.

**Comment by Marty-coder-dev** [comment]
If that's the problem, I'll try to add the special command.

**Comment by Marty-coder-dev** [comment]
If that's the problem, I'll try to add the special command. And, I might just open my own repository for the mods I've made.

**Comment by dirkf** [comment]
Anything that clarifies how you are using the program would help. For the moment I'm going to assume that you have a problem like this mentioned in #30839, and so close the issue (you are the support channel for your own code):
>If your problem occurred when running another package that invokes youtube-dl, try to reproduce the problem with a youtube-dl ... command, or report it through the support channel for the other package; similarly **if the problem occurred when running your own code**.
