### ISSUE TITLE
Urgent Videos Download Please Add Before 10 Days Link Expiry

### ISSUE THREAD

**Issue by speedily** [ytdl-org/youtube-dl#32835]
SOLVED

**Comment by dirkf** [comment]
Someone would have to be willing to help and you would have to share your account details with that person. Since that is a long shot, instead, consider these options in order:
* use the option to Save Video if available in your (or a better) browser
* use the browser's dev tools to find the request sent by the browser to fetch the video and generate the corresponding _curl_ command that you can adapt to try downloading the video
* point your best video camera at the screen while playing the video full-screen on a well-sized monitor; possibly record the audio separately on the machine or from its `line out` socket.
