### ISSUE TITLE
Is there a way to select a specific quality for the download?

### ISSUE THREAD

**Issue by marvyn7** [ytdl-org/youtube-dl#32911]
So, I got the app running and used it yesterday, it works fine, but the problem is that when downloading the best quality (with ffmeg in the same paste), the 4k result is just something my phone cant run. Is there a way to select the quality to, lets say, 720p instead?

I am downloading by doing the basic of writing yt-dlp and them the url, is there any extra command I must imput?

**Comment by tansy** [comment]
Sure: `youtube-dl --help` is your friend.

<details>
<summary></summary>

`--format`
</details>

**Comment by bashonly** [comment]
> I am downloading by doing the basic of writing **yt-dlp**

maybe you're posting on the [wrong issue tracker](https://github.com/yt-dlp/yt-dlp/issues)?

**Comment by marvyn7** [comment]
> > I am downloading by doing the basic of writing **yt-dlp**
> 
> maybe you're posting on the [wrong issue tracker](https://github.com/yt-dlp/yt-dlp/issues)?

never mind, found the way on reddit.

**Comment by dirkf** [comment]
Also, **#30839**.

But RTFM is the answer wherever you post. Then, if something is unclear, raise an issue asking about **the program's own documentation** so that the doc can be improved. What some random posts on Reddit, YT, etc, could be anywhere from correct through unreliable or misleading to completely wrong, but it's not practical to correct such things.
