### ISSUE TITLE
Windows installation dont work

### ISSUE THREAD

**Issue by Reegzy** [ytdl-org/youtube-dl#32939]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Reegzy** [comment]
![7qdEAIeONo](https://github.com/user-attachments/assets/3c301253-7b2d-4063-aecc-2ecbc1d2faed)

**Comment by salty-catpuccino** [comment]
Hello, I wanted to also include that this issue is happening with Linux builds with the bin/youtube-dl contents having the HTML that @Reegzy provided above.

**Comment by dirkf** [comment]
The image is a black rectangle for me. Always post diagnostics as text and do actually **WRITE DESCRIPTION HERE** as asked.

>[x] I've verified that I'm running youtube-dl version 2021.12.17

Review #30839 **as asked** to see why this is expected to fail and how to find and use a version that is more likely to work (but still fails at #32905).

**Comment by salty-catpuccino** [comment]
That is interesting that the image is not loading for you. 
I can however provide exactly what is contained in it, it happens to be the same error users see if they navigate to the initial download location from the installation instructions. [This link](https://yt-dl.org/downloads/latest/youtube-dl) Shows the following HTML (This is what is pictured above):
```
<h1>Access denied</h1>

<p>
  Due to a <a href="[https://openjur.de/u/2466945.html](view-source:https://openjur.de/u/2466945.html)" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="[https://openjur.de/u/2466945.html](view-source:https://openjur.de/u/2466945.html)" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>
```

This also is the same text that linux users get when examining the bin file (Presumably because the download goes to that link which only has this HTML available to download) So when trying to execute, at least from a Linux perspective, all we see is the Header tag for Access Denied.

**Comment by dirkf** [comment]
So in fact you didn't get to running 2021.12.17, but the resolution of your duplicate issue is clearly explained here
>Review #30839 as asked ...
