### ISSUE TITLE
Sign in to confirm you're not a bot error!

### ISSUE THREAD

**Issue by quantum-glitch** [ytdl-org/youtube-dl#32933]
Your issue reporting guide is unnecessarily lengthy & complex just for one to report a simple bug, so i worded it like this, close it if you wish, at least it will be visible and you will be aware of the issue if not already.

Whenever i try to DL a playlist or any YT video using the latest nightly build it fails with an error message saying "sign in to confirm your not a bot" can this be fixed?

**Comment by dirkf** [comment]
By following the minimally complex procedure you would have found #32920. Please review that issue to understand why that issue is closed, and why this one will also be closed, unless it is updated with the required completed issue template.

**Comment by webloginwu** [comment]
**I tried** 

youtube-dl -u "youtubeloginname" -p "youtubeloginpassword" url

**but got below error**
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
**version**
youtube-dl --version
2021.12.17

My solution comes from:
https://askubuntu.com/questions/776122/how-to-resolve-sign-in-error-when-using-youtube-dl-for-downloading-my-personal

**Comment by dirkf** [comment]
Continued in #32960.

**Comment by dirkf** [comment]
@webloginwu, use a cookie-file exported from your logged-in browser session (see FAQ) rather than the command-line authentication options, which no longer work with YT: the AskUbuntu answer has not been valid for several years, though it may have been in 2016.

And **review #30839** to find out about the nightly release which might have a chance of working if your IP has not been banned.
