### ISSUE TITLE
YouTube suggestion: provide option to skip requests if file with video ID exists

### ISSUE THREAD

**Issue by narinishi** [ytdl-org/youtube-dl#32977]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

When downloading multiple videos, multiple requests are made before checking the file exists.
It would be helpful to have a command line option that would pre-emptively check for a video file with corresponding video ID in the filename. 
The option should have a name that implies potentially unwanted behavior, as it would not be possible to check the existing file matched the duration (or intended quality) of the desired video.

**Comment by dirkf** [comment]
Whether "the file exists" depends on the output template and the metadata extracted from the site, so the program can't make the decision until it's about to download to the file.

`--download-archive ...` shortcuts this, since it changes the "file exists" test to "`{ie_key}:{video_id}` in archive index". This should meet your needs, though you would have to generate an archive index matching your existing files.

**Comment by narinishi** [comment]
Fair enough.  I found it easy to generate a suitable file for `--download-archive`
