### ISSUE TITLE
Add  a --dns-resolver option

### ISSUE THREAD

**Issue by TheGr33k** [ytdl-org/youtube-dl#4726]
It would be nice to have a feature that allows you to state the  nameserver you want youtube-dl to  use to resolve domain name.Some common example include OpenDNS , Google Public dns etc....

Regards

**Comment by Kaligule** [comment]
I think you should be able to achive the same effect by using ```nslookup``` and a ```|```.

**Comment by TheGr33k** [comment]
@Kaligule Could you please show an example ?

Even then we won't be able to know for sure what dns server youtube-dl sees

Feel free to correct me if i am wrong

**Comment by phihag** [comment]
The main problem is not that we cannot hook up a custom resolver class, but that we need to actually implement (a simple subset of) DNS. Unless someone contributes the necessary code (basically a pure Python implementation of [`gethostbyaddr`](https://docs.python.org/dev/library/socket.html#socket.gethostbyaddr)), this issue will not be resolved.

**Comment by yan12125** [comment]
For those who are interested in it: I have a proof-of-concept branch at https://github.com/yan12125/youtube-dl/tree/custom-dns, which uses the [ISC licensed](https://github.com/rthalley/dnspython/blob/master/LICENSE) dnspython.

**Comment by calestyo** [comment]
Is this option still considered for inclusion?

I think I might suffer from the same issue described here #13734, that is, when downloading videos (in fragments) over a very fast connections, I get quite soon blocked.
Happens with the DNS server of my ISP (which is the biggest one in Germany) as well as e.g. Google’s `dns.google` (though these seem to be far less aggressive).

`yt-dlp`'s download freezes (and sometime it shows even nameserver timeouts) as do any other connection which make new DNS resolution... OTOH, while `yt-dlp` is stuck, `scp`ing a `truncate --size 1TB image` file from my server to my local `/dev/null` (where no further DNS queries are involved) continues with ~19 MB/s ... kinda proves that it's not the transmission itself but really only the name resolution.

I think most browsers do have their own DNS caching (at least Firefox) and despite this IMO being broken by design it's probably the reason why the problem never shows up there.

**Comment by dirkf** [comment]
Also, you can cache locally, and often in your modem/router. There should never be an excessive load of DNS lookups going out of your local network.

This is a network configuration issue that yt-dl isn't going to solve unless there's a much more compelling case. And even if it hasn't yet been rejected downstream.
