### ISSUE TITLE
Improve the format selection logic and syntax

### ISSUE THREAD

**Issue by haasn** [ytdl-org/youtube-dl#5242]
This is a combination of three similar feature requests, all aimed at improving the ability to specify the particular format(s) chosen by youtube-dl.
1. I want an operator that says “choose the better of the two”. For a motivating use case, non-DASH formats are better than (equivalent) DASH formats when used in mpv (eg. allows seeking and accurate duration information) as well as standalone (they can be streamed instantly, rather than needing to wait for both components to finish downloading before remuxing them). The syntax I imagine could be something like this: `best|bestvideo+bestaudio`. It would pick the one with highest overall quality, preferring the leftmost if they're identical. (Ideally there should also be some slight tolerance for considering formats “equal”)
2. I want to be able to set my heuristics for audio and video tracks independently. The way I imagine this working is by being able to “group” together a format selection using parentheses, like this: `(bestvideo[tbr<13000][height>720]/bestvideo[tbr<13000][fps>30])+(bestaudio[ext=webm]/bestaudio)`
3. The “quality” assessment should be multiplied by a format-specific weight, since eg. 128 kbps Opus is definitely better than 128 kbps MP3, and eg. 21 Mbps VP9 ought to be better than 22 Mbps AVC. This should probably be user-configurable, and would coincidentally allow me to easily “prefer free formats” by giving them (significantly) higher weights than corresponding non-free formats.

**Comment by jaimeMF** [comment]
Grouping with parentheses will be supported in the next version, open a new issue if you find any problem.

**Comment by realnc** [comment]
Thanks!

Just an idea: It might be more elegant to support `/` in more places. Example:

`bestvideo[ext=webm/mp4/*]`

Would mean: prefer webm, if not available then mp4, if also not available, then use whatever is there.

**Comment by keybounce** [comment]
Yes, please, a way to say "Take the 480p mp4 if it exists, 480p dash second choice", while still fetching audio.

As referenced in that other thread, I was doing:
```-f "best[height<=480]/bestvideo[height<=480]+bestaudio"```
because I wanted 480, ideally already "put together" without having to recode/re-assemble. I had already learned the hard way the need to have best video + best audio (downloaded too many silent movies without the pairing).

Switching to
```-f "bestvideo[height<=480]+bestaudio/best[height<=480]"```
will work, but I can see it forcing dual downloads and recombines more often than it will need to.

EDIT: Re-reading that first post -- Is that why sometimes I can watch a video while it's downloading, and sometimes I have to wait for it to finish before I can start? (I've stopped trying to watch while downloading).
