### ISSUE TITLE
Support for Instagram photos

### ISSUE THREAD

**Issue by EnginePod** [ytdl-org/youtube-dl#9337]
I'll skip the formality as there already is support for Instagram videos, but not photos.
Here is an example photo: https://www.instagram.com/p/BEvqLm5mcSK/?tagged=test

**Comment by dstftw** [comment]
Photos is out of scope of youtube-dl.

**Comment by EnginePod** [comment]
Why?  While it downloads Instagram videos it can download photos as well.
I can't see why Instagram wouldn't be eligible as an exception.

**Comment by yan12125** [comment]
Unlike other websites, right-click on images of instagram does not give a save-to option. There's no easy way to get the image without HTML or network sniffing knowledge. Maybe the policy can be changed.

**Comment by dstftw** [comment]
Supporting static images will also introduce semantic clash with thumbnails.

**Comment by yan12125** [comment]
For static pictures, ```thumbnail``` and ```url``` can be the same one.

**Comment by dstftw** [comment]
So in general you are suggesting duplicating `formats` and `thumbnails`?

**Comment by yan12125** [comment]
Yeah. ```url``` points to the interested file, and for static pictures, ```thumbnail``` can be the target itself.

**Comment by Hrxn** [comment]
You still can do this:
`document.querySelector("[id^='pImage']").getAttribute("src");`

(Run against Instagram post page, i.e. https://www.instagram.com/p/XXXXXXXXXXX/)

:smile: 

Their source is an awful mess of nested div elements infused with React garbage, boy that is ugly..

But I think that RipMe still works with Instagram:
https://github.com/4pr0n/ripme

(Java based program)

**Comment by EnginePod** [comment]
That line works perfectly in the console, but it would be useful to have support for it in youtube-dl so all solution would be gathered in one place.

**Comment by Hrxn** [comment]
Hmm, you can still automate this further. The post IDs are inside some JSON on the profile page, they can be extracted, then you can construct the URLs to the single post pages, fetch the HTML documents from each post page, and then query again.

:smile: 

I just tested some images there, and maybe it is just me, but the picture quality is horrible. Total potato quality. I guess you never notice this when browsing Instagram normally (Web or Mobile), because the user agent always scales down the images and displays them this way...

**Comment by EnginePod** [comment]
All that needs to be done is to get value of content for the meta image <meta property="og:image" content="">.

This contains the URL to the highest quality version of the image.
Once the value is retrieved it can be set as both the thumbnail and the URL for the output.

**Comment by TRox1972** [comment]
Any progress on if this will be implemented or not?

**Comment by yan12125** [comment]
There's currently no consensus on whether youtube-dl should support non-audio/video files or not. It's a change to the essence of youtube-dl, so I guess it's better to get a common conclusion among developers before moving on. My personal idea is that supporting static pictures on existing websites is OK, for example Facebook, Tumblr and Instagram, but not adding new website with static pictures only.

**Comment by TRox1972** [comment]
@yan12125 I agree. Would this be a big change, requiring much new/changed code?

**Comment by yan12125** [comment]
Nope. Just a single line for Instagram.

**Comment by CiscoPress** [comment]
I use Jdownloader for Image download on Social Networks. Most Social Networks make it a pain to download full resolution image and the implementation changes very often. Lots of Pic Hunters have troubles to download a good quality image. Mostly they distribute/share low resolution pics.

I would love if the best open source tool supports images.

**Comment by Hrxn** [comment]
So there are different resolutions, or formats, in youtube-dl parlance, to deal with.
Is this documented somewhere, for Instagram, for example? I am not so sure anymore if getting the image from the page source is really enough. The API might return something different..

**Comment by yan12125** [comment]
@Hxrn Sorry not getting it. What does it mean by "The API might return something different.."?

**Comment by Hrxn** [comment]
https://www.instagram.com/developer/

Like this
'https://api.instagram.com/v1/users/self/media/recent?access_token=.............&count=40'

I am currently testing this, will see if I get another image,

Because I don't know if anyone else noticed, but the image quality on Instagram seems horrible. You don't realize this normally, when using it on mobile, because the images get scaled downed and the mobile displays have a higher resolution (dpi).
I've looked at a lot of different Instagrams yesterday, and this really seems to be their quality..

**Comment by yan12125** [comment]
I see. Usually youtube-dl tries to parse the web page instead using APIs. Parsing user pages should be possible.

**Comment by TRox1972** [comment]
On user pages it is possible to get different image resolutions the same way that we do it now for videos.

**Comment by Hrxn** [comment]
> On user pages it is possible to get different image resolutions [...]
Can you please elaborate? I don't see what you mean right now.

API access looks like a dead end. Apparently, all registered API clients run in some sandbox mode in default, which limits the access to what is otherwise considered public data on Instagram. Full access is only available for 'production' clients, which have to get through a review process first, it seems.
Only god knows why...

Whatever, I doubt that this would've helped with the crappy image quality of Instagram ;)

**Comment by TRox1972** [comment]
@Hrxn `/<user>/media` gives some info about the images/videos on the users Instagram, among which is resolutions. Though as you say, they don't seem to be very high quality:
```
format code          extension  resolution note
low_resolution       jpg        150x150
thumbnail            jpg        320x320
standard_resolution  jpg        640x640    (best)
```

**Comment by Hrxn** [comment]
Oh, okay. Guess I misunderstood. With 'user pages', I thought you maybe meant the normal web URL, i.e. `instagram.com/<user>`.

I feared that I've failed to see some kind of menu button or something ;)

Okay, but `<user>/media` is an API endpoint, so I guess the sandbox problem still applies. Or could you do this successfully for another `<user>`, just some random Instagram account?

My initial plan was to try to find if the original upload would still be available somewhere. Because Instagram keeps that, AFAIK. At least I heard that somewhere.

I don't know about their format list, but there is some more I suspect. One Instagram post I chose for my test is a JPEG with 1080 x 1349, for example.

But quality is still not that good. Ridiculous, if compared to Flickr or 500px, for example.

**Comment by TRox1972** [comment]
> Or could you do this successfully for another <user>, just some random Instagram account?

The method works for all users I've tested so far (not many). It is also the current method we use in the Instagram extractor only for videos. But because it is an API endpoint, as you mentioned, Instagram may treat us differently.

The best way would be to mimic the browser: Using the `<user>/media` method for a picture yielded the resolutions mentioned above, but looking at the page source 1080x809 resolution is available, which is not in itself very good quality but, compared to the other resolutions, it's significant.

**Comment by EnginePod** [comment]
From pages that I've checked the photo with the highest quality is the one in the `<meta>` tag (or `<meta property="og:image" content="[HIGH QUALITY URL HERE]">` to be more specific) and this line is available in the source code straight from the beginning so no browser emulation or API needed.

But if you're trying to get all the photos of a user then it'll be a more complicated task.
The `/<user>/media` page returns some images, but it doesn't provide the highest quality.

I came to this conclusion by comparing the highest quality version of a photo from `/<user/media` and comparing it with the `<meta>` version that I was talking about earlier.

There is however one solution to getting the highest quality version of the photo, but it's a bit annoying.
The `/<user>/media` returns the photo IDs of user's images so it'd be possible to get all of those IDs, downloading their sources by visiting `/p/<photo_ID>/` and downloading `<meta>` photo URL that has the highest quality.

**Comment by TRox1972** [comment]
> The /<user>/media returns the photo IDs of user's images so it'd be possible to get all of those IDs, downloading their sources by visiting /p/<photo_ID>/ and downloading <meta> photo URL that has the highest quality.

If InstagramIE extracts the high-quality image from `/p/<photo_id>`, then InstagramUserIE could collect all the `photo_id`s an parse them to InstagramIE.

**Comment by EnginePod** [comment]
I think that would be a clean and well functioning solution.

**Comment by Hrxn** [comment]
> The method works for all users I've tested so far (not many). It is also the current method we use in the Instagram extractor only for videos. [...]

The current method?
But the Instagram information extractor `extractor/instagram.py` doesn't use the API.

With API access I meant something like this:
`https://api.instagram.com/v1/users/{user-id}/media/recent/?access_token=ACCESS-TOKEN`
https://www.instagram.com/developer/endpoints/users/#get_users_media_recent

Oh, wait. I think I get what you mean. Sorry for the misunderstanding. The extractor uses `http://instagram.com/<user-id>/media`, which returns the normal profile page as some JSON, basically. There we only have the formats you listed above, like `standard_resolution`. The URLs for these formats could actually be rewritten, yielding us a better picture, but as long as we have to guess the parameters, we won't get something better than what is already in the markup, I assume.

So, `<meta property="og:image" content="[URL  HERE]">` looks indeed like the best option right now.
To be sure, I've checked the `<div>` where the actual image is on a couple of postings, but the URL here is exactly the same as in the `og:image` meta element, and so is the image, unsurprisingly.

**Comment by yan12125** [comment]
youtube-dl will **NEVER** use any API that requires a key. Please discuss API usages privately but not here.

**Comment by Hrxn** [comment]
This was never my intention. I'm aware that's not feasible, in addition, not even possible. I said that earlier.

The point was only to find out if Instagram stores higher res images at all, or rather the original resolution, i.e. the uploaded file. Because cell phone cameras may be crap, but they're not that bad as what Instagram is serving as pictures.

**Comment by TRox1972** [comment]
Should there be a vote between you developers whether or not youtube-dl will support static images?

**Comment by yan12125** [comment]
I guess we can have a simple vote: Click +1 on @EnginePod's original post if you like this idea, and -1 if you don't.

**Comment by TRox1972** [comment]
It has been some time now. Any development on the issue?

**Comment by yan12125** [comment]
There are not so many +1's. Maybe people don't know this debate on expanding youtube-dl's coverage.

**Comment by TRox1972** [comment]
Is anyone against implementing this? If not, why not implement it?

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl/issues/9337#issuecomment-215442034

**Comment by Tratoschek** [comment]
Don't know if I should make a new issue for this, but I already found a comment about Tumblr in https://github.com/rg3/youtube-dl/issues/9337#issuecomment-223351245.

For so, extracting (best) images from Tumblr is also not straight forward. Take e.g. http://programmerryangosling.tumblr.com/post/76642406919. This site links directly to the image, but not in the best quality. To get the best quality you also have to parse http://programmerryangosling.tumblr.com/image/76642406919 (and the browser shows the image only with enabled js).

**Comment by Hrxn** [comment]
?

Tumblr?

But this issue is about Instagram?

**Comment by EnginePod** [comment]
@Tratoschek, this was about Instagram, but the `og:image` method seems to work well here too [see https://github.com/rg3/youtube-dl/issues/9337#issuecomment-225213571].

In other words, you just need to view the source for the page with the specific post and extract `og:image`.
For the post you linked to: http://68.media.tumblr.com/77b54f57528c86f6c05ec55d1ce948f1/tumblr_n0zx7rXYk71r8lg7to1_1280.jpg

**Comment by Tratoschek** [comment]
@Hrxn I know, but this issue has evolved to the central "Support images in youtube-dl"-issue.
@EnginePod Thank you, you're right, haven't seen this.

To the generic discussion here. What I get so far, the current facts are:
- Photos are out of scope ([source](https://github.com/rg3/youtube-dl/issues/9337#issuecomment-215442034))
- Technically no problem
- Other techniques of youtube-dl not meaningful with pictures, e.g. conversion, good picture title ([source](https://github.com/rg3/youtube-dl/issues/2157#issuecomment-32796488))

Maybe some of this can be solved with some rules, what a "good" picture site is, to suggest some:
- The main content of the site has to be an (only one) image.
- Only this image would be downloaded (if different qualities are available, youtube-dl can list them).
- The generic extractor never does anything special for images (just ignore them).

(This rules would include sites such as instagram, tumblr, imgur, ...)
Because the website is dedicated to the image, it is likely the image has a meaningful title. FFmpeg supports conversion of images (if this is wanted). The then extended scope of youtube-dl is clearly defined and partly similar to the current (extract the - one - video out of the site).

**Comment by EnginePod** [comment]
"The main content of the site has to be an (only one) image."
I agree with you on many points, especially this one.

As you sort of mentioned, it would be easy to implement by just adding the image as a format, example:
`format: image, ext: jpg, url: http://68.media.tumblr.com/77b54f57528c86f6c05ec55d1ce948f1/tumblr_n0zx7rXYk71r8lg7to1_1280.jpg` and setting `thumbnail` to either the image URL or leaving it at null.

To keep images and videos separated on sites that provide both (like FB, IG, etc.) you would have the image support only as a fallback.  So if there was no video on the page then it'd fallback to extracting the image (unless there's a 404).

The problem doesn't seem to be the technical implementation, but rather that photos shouldn't be supported by youtube-dl (see @dstftw's reply) even though it'd make life easier for everyone.

**Comment by fletom** [comment]
+1 for Twitter and Instagram photo downloads. especially with gifs nowadays the distinction is somewhat baseless

youtube-dl doesn't just work on YouTube anymore, and it doesn't have to just work for video either

**Comment by yan12125** [comment]
With 14 +1 votes, I consider this a valid request. Implementation still require discussions.

**Comment by dardo82** [comment]
I'd like this feature, how can I help?

**Comment by haasn** [comment]
I realize this is an old issue with a lot of historical discussion on the topic already, so adding my own flavor of "+1" probably isn't going to do much good.

Nonetheless, as a long-time user of youtube-dl I'd like to emphasize just how *usable* the internet is with youtube-dl existing. Without youtube-dl I would basically be unable to use any video site currently in existence - and it's simply staggering the amount of logic youtube-dl has for nearly every media hoster in use, to the point where youtube-dl even supports crap like dropbox - as long as what's pointed to by it is a video file.

In fact, if somebody sends me, say, a dropbox link that *isn't* a video file, I'm unable to open it. This restriction has always seemed sort of artificial to me. `youtube-dl` clearly has logic for downloading things from dropbox - why should this wonderfully useful logic have a built-in check that prevents it from operating if the link you got sent doesn't have the right file type? It's this weird disconnect between what the code supports and what the tool allows it to do that has always sort of bothered me.

By limiting the scope of youtube-dl you're essentially saying that we need to create a second tool that replicates all of the site-specific logic that youtube-dl has but with the intention of allowing non-videos from being downloaded as well. This seems sort of silly to me. Massive amounts of work clearly go into youtube-dl and it seems to me it would be much easier and more logical to extend youtube-dl than it would be to recreate it from scratch.

Add to this the fact that images are sort of a gray area in between videos and general files and it makes my opinion even stronger that youtube-dl should be able to handle them, since images are just more media files. It doesn't matter whether the tool at the other end (e.g. mpv) is opening one type of media file or another, it will still open. Now, normally I don't really care much about the image use case because browsers are normally able to display images. But then you have complete garbage like imgur which these days simply doesn't display anything at all, and I find myself wishing youtube-dl could help me every single time it happens. At some point I may try ripping out the imgur-specific logic from youtube-dl and wrapping it into my own command line tool to grab them, simply so I can *view* imgur links again. But it still seems like it would be a waste for youtube-dl not to add support directly.

Anyway, since I don't commit to youtube-dl my words are cheap so take them for what they are. Just a frustrated user who's tired of having to ask people to re-upload imgur links to other websites simply so he can view them..

**Comment by dardo82** [comment]
@haasn try https://github.com/RipMeApp/ripme/

**Comment by Hrxn** [comment]
Interesting, on GitHub alone we seem to have:
- instaloader/instaloader
- althonos/InstaLooter
- rarcega/instagram-scraper

Or did you mean some other program called *instaloader*?

**Comment by spiralofhope** [comment]
I tested [instagram-scraper](https://github.com/rarcega/instagram-scraper) under Windows Subsystem for Linux, Debian, 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 GNU/Linux

``` bash
sudo apt-get install python-dev build-essential
sudo apt-get install python-pip
pip install --upgrade pip
python -m pip uninstall pip

# I had problems using it from its git repo, so I used Debian's

pip install instagram-scraper
pip install instagram-scraper --upgrade
```

Example use:

``` bash
instagram-scraper  <username>
# So for https://www.instagram.com/therock/ it would be:
instagram-scraper therock
```

Any future notes notes I write will go [on my notes page for instagram-scraper](https://blog.spiralofhope.com/?p=41291).
